### ISSUE TITLE
geom_point happily colorizes unfilled_shapes on main plot but shows only black on legend

### ISSUE THREAD

**Issue by jrbrearley** [has2k1/plotnine#100]
Showing colors on a graph but not on the legend is inconsistent. My preference would be to show the colors on the legend as well as the main plot. I suppose black everywhere would also be a answer.

Here is the short script to demonstrate the issue:
```python
import pandas, plotnine
from plotnine.data import diamonds
# NB: shapes used by geom_point are defined in plotnine/scales/scale_shape.py
g0 = plotnine.ggplot(plotnine.aes(x='carat', y='price', fill='color'), data=diamonds)
g1 = g0 + plotnine.geom_point(shape=1) # Legend all black
print(g1)
g2 = g0 + plotnine.geom_point(shape='s') # Legend correctly colorized
print(g2)
````

I did try adding parameters 'color=fill' 'color=color' & fill='color' to try and get the legend colorized, but no luck

**Comment by has2k1** [comment]
This is an MPL issue.

**Comment by jrbrearley** [comment]
I patched my local copy of matplotlib/axes/_axes.py with your 3 line fix. Now all the plots using unfilled_shapes are totally black. Is this what you intended?

**Comment by has2k1** [comment]
> Is this what you intended?

That is strictly correct behaviour. The question is; whether, for convenience, to make exception? The is already a [similar one](https://github.com/has2k1/plotnine/blob/cde6d84cf841d49933b5522bfdd18de3a46ce77b/plotnine/geoms/geom_point.py#L52) in place.
