### ISSUE TITLE
how to hide <ggplot: (174776257614)> below the pic

### ISSUE THREAD

**Issue by gaorongchao** [has2k1/plotnine#103]
I Want to know how to hidden the <ggplot: (174776257614)> below the pic 

![1514440130 1](https://user-images.githubusercontent.com/3361790/34401408-e7c6f29a-ebd5-11e7-8a49-1e741bb97f8d.png)

**Comment by has2k1** [comment]
The only way to hide it is to manually call the draw method and have the last statement of the notebook cell be None. e.g

```python
p = (ggplot(mtcars)
     + aes('wt', 'mpg')
     + geom_point())
p.draw()
None
```

**Comment by gaorongchao** [comment]
Great,It worked!
Thank you very much.
