### ISSUE TITLE
Mean + errorbar causes ValueError: Buffer dtype mismatch 

### ISSUE THREAD

**Issue by HenrikEckermann** [has2k1/plotnine#104]
Hey Hassan,

I ran into an error and I wonder if the plot is affected or not (since I get the output but also several error lines. I cannot figure out what is wrong here. Can you explain to me what is the problem or whether I made a mistake? Here is the [gist](https://gist.github.com/HenrikEckermann/1d334a44f61349ac71f0e235b3443a69#file-gistfile1-txt)

I use plotnine a lot. Thanks for all the effort!

**Comment by has2k1** [comment]
You can safely [ignore](https://github.com/pandas-dev/pandas/pull/18252) the errors.
