### ISSUE TITLE
Axis texts overlap in facet_wrap

### ISSUE THREAD

**Issue by gokceneraslan** [has2k1/plotnine#106]
When I use violin plot with facet_wrap and free_y scale, axis labels overlap with the next plot:

![image](https://user-images.githubusercontent.com/1140359/34919790-a560a202-f936-11e7-81c1-4385dd837b7d.png)

I'm using plotnine 0.3 from pip.

**Comment by gokceneraslan** [comment]
With `scales='fixed'` it renders fine:

![image](https://user-images.githubusercontent.com/1140359/34919811-dcc67c58-f936-11e7-9a16-75d53fd5e3bf.png)

**Comment by has2k1** [comment]
This a known issue. It is a consequence of not having good layout manager, related to #46. The solution is to use [subplots_adjust](https://plotnine.readthedocs.io/en/stable/generated/plotnine.themes.themeable.subplots_adjust.html).

**Comment by gokceneraslan** [comment]
Is it going to be fixed if MPL 2.2 is released with `constrained_layout` thing?

**Comment by has2k1** [comment]
It depends on if `constrained_layout` is stable when released. MPL 2.2 is scheduled for the end of the month, `constrained_layout` will probably not make it in there.

Without a good layout manager is it hard to extend the package to do more interesting stuff.

**Comment by TyberiusPrime** [comment]
For other people trying to figure this out:
```p += p9.theme(subplots_adjust={'wspace':0.15})``` is what you need to toy with.

**Comment by TyberiusPrime** [comment]
And I can also report that right now adding constrained_layout=True to the plt.figure call in ggplot._create_figure does not fix the layout.
