### ISSUE TITLE
Could not plot in a for loop in jupyter-qtconsole

### ISSUE THREAD

**Issue by hw449** [has2k1/plotnine#107]
I found that when I called ggplot function in a for loop in jupyter-qtconsole, no images appeared. Images can only appear when I draw them one by one. Could you please help me solve this problem? Thank you very much.

**Comment by has2k1** [comment]
Can post some minimal code to demonstrate the problem.
￼

**Comment by hw449** [comment]
For example:

from plotnine import *
import pandas as pd
df1=pd.DataFrame({'x':[4,5,6] ,'y':[1,2,3]})
df2=pd.DataFrame({'x':[14,15,16] ,'y':[11,12,13]})
for df in [df1,df2]:
    print df
for df in [df1,df2]:
    ggplot(df)+geom_point(aes(x='x',y='y'))

**Comment by hw449** [comment]
For example:
from plotnine import *
import pandas as pd
df1=pd.DataFrame({'x':[4,5,6] ,'y':[1,2,3]})
df2=pd.DataFrame({'x':[14,15,16] ,'y':[11,12,13]})
for df in [df1,df2]:
      print df
for df in [df1,df2]:
      ggplot(df)+geom_point(aes(x='x',y='y'))

**Comment by hw449** [comment]
Indentation lost after clicking 'comment'

**Comment by has2k1** [comment]
You have to print the plot you construct (the same reason you did so for the dataframes!).

```python
for df in [df1,df2]:
    p = ggplot(df) + geom_point(aes(x='x', y='y'))
    print(p)
```
