### ISSUE TITLE
Problems using `scale_size_manual`

### ISSUE THREAD

**Issue by r-barnes** [has2k1/plotnine#108]
I'm trying to use plotnine to build a plot with points sized based on their a classification 1-4.

In the MWE below, I've constructed a test dataset that matches mine.

    from plotnine import *
    import pandas as pd
    import numpy as np

    a = pd.DataFrame(data={'a':4*list(range(4)), 'x':np.random.random(16), 'y':np.random.random(16)})

    ggplot(a, aes(x='x', y='y', size='a')) + geom_point() + scale_size_manual(values=(3,3,3,3))

However, when I run the code, I get the following message:

> TypeError: Continuous value supplied to discrete scale

Thinking that the problem was that the `a` column was non-categorical, I tried the following MWE:

    from plotnine import *
    import pandas as pd
    import numpy as np

    a = pd.DataFrame(data={'a':4*list(range(4)), 'x':np.random.random(16), 'y':np.random.random(16)})

    a['a'] = a['a'].astype('category')

    ggplot(a, aes(x='x', y='y', size='a')) + geom_point() + scale_size_manual(values=(3,3,3,3))

However, this gives the error message:

> ValueError: cannot convert float NaN to integer

In R's ggplot, the following

    library(ggplot2)
    a = data.frame(a=rep(1:4,4), x=runif(16), y=runif(16))
    ggplot(a, aes(x=x, y=y, size=a)) + geom_point() + scale_size_manual(values=c(3,3,3,3))

gives the familiar message

> Error: Continuous value supplied to discrete scale

Introducing a factor solves the issue:

    library(ggplot2)
    a   = data.frame(a=rep(1:4,4), x=runif(16), y=runif(16))
    a$a = factor(a$a)
    ggplot(a, aes(x=x, y=y, size=a)) + geom_point() + scale_size_manual(values=c(3,3,3,3))

**Comment by has2k1** [comment]
Though it is not perfect, you can avoid it with

```python
... + scale_size_manual(values=(3,3,3,3), na_value=-1)
```

At it's core, the is an issue of numpy not having a good way to deal with missing values.

```python
import numpy as np

a = np.array([1, 2, 3])
a[[False, False, False]] = np.nan
```

**Comment by r-barnes** [comment]
Awesome, thanks!
