### ISSUE TITLE
Add Tutorial Link To Kaggle

### ISSUE THREAD

**Issue by chris1610** [has2k1/plotnine#109]
I noticed that Kaggle now has a section on plotnine in their new free online courses - https://www.kaggle.com/learn/overview

Here's the section on plotnine - https://www.kaggle.com/residentmario/grammer-of-graphics-with-plotnine-optional/

I'd recommend adding it to your tutorial links.

**Comment by has2k1** [comment]
It is a good tutorial. Thanks the notice.
