### ISSUE TITLE
How to expand the plot dimensions to fit legend?

### ISSUE THREAD

**Issue by ksw9** [has2k1/plotnine#113]
Hi -
Thank you for a fantastic module! I'm having a bit of trouble converting some of my code from R to python. I'm plotting a facet plot with a legend and am having trouble expanding the margins to fit the entire legend. I tried plot_margin but run into an error. Do you have suggestions? Thank you!
(ggplot(results_sens, aes('filter', 'value', fill = 'pipeline')) +\
  geom_col(position = "dodge") +\
  scale_fill_discrete(name="Mapper/Caller") +\
  ylab("Sensitivity") + \
  xlab("Filter") + \
  facet_wrap('~variable') + \
  theme(plot_margin={'t': 5, 'r': 5}))

I get the error:  can't invoke "event" command:  application has been destroyed
    while executing
"event generate $w <<ThemeChanged>>"
    (procedure "ttk::ThemeChanged" line 6)
    invoked from within
"ttk::ThemeChanged"

**Comment by has2k1** [comment]
Use `suplots_adjust` to make space for the legend. For example,

```python
+ theme(subplots_adjust={'right': 0.85})
```

**Comment by ksw9** [comment]
Thank you!
One more question that I couldn't figure out on the GitHub threads - is there a function similar to R's plot_grid to combine multiple plots and use a single legend?

**Comment by has2k1** [comment]
No there isn't one.

**Comment by timothyfraser** [comment]
Fun fact - looks like the method is to use patchworklib with plotnine now.

**Comment by has2k1** [comment]
@timothyfraser, this was resolved. plotnine now has a layout manager and the legend should automatically fit unless if any of its dimensions are longer than those of the figure or there about.
