### ISSUE TITLE
scale_x_log10 gives non-sensical error

### ISSUE THREAD

**Issue by Make42** [has2k1/plotnine#114]
The code

```
scale_x_log10(breaks=list(np.unique(result_df.inv_cutoff)),
              labels=list(np.around(np.unique(result_df.inv_cutoff), 3).astype(str)),
              minor_breaks=[])
```

results in the error

> plotnine.exceptions.PlotnineError: 'Breaks and labels are different lengths'

which makes no sense to me.

**Comment by has2k1** [comment]
Are you sure?

```python
len(list(np.unique(result_df.inv_cutoff))) == len(list(np.around(np.unique(result_df.inv_cutoff), 3).astype(str)))
```

It would be more helpful if you submit a minimal reproducible example.

**Comment by Make42** [comment]
Yes, this checks out. My code works with using `scale_x_continuous` instead of `scale_x_log10`. I suspect it might be, because there is a `0` on the x-axis. What is your suggestion?

```
result_df = pd.DataFrame({'inv_cutoff': [0,0.01,0.1,1,10], 'my_y': [1,2,3,4,5]})
ggplot(aes(x='inv_cutoff', y='my_y'), data=result_df) + \
        geom_line() + \
        scale_x_log10(breaks=list(np.unique(result_df.inv_cutoff)),
                           labels=list(np.around(np.unique(result_df.inv_cutoff), 2).astype(str)),
                           minor_breaks=[])
```

**Comment by has2k1** [comment]
The issue is having a `0` (or any other value outside the limits) in the breaks. The solution is a better error message from plotnine.
