### ISSUE TITLE
Misleading documentation / bug for scale_x_continuous's breaks

### ISSUE THREAD

**Issue by Make42** [has2k1/plotnine#115]
The documentation of http://plotnine.readthedocs.io/en/stable/generated/plotnine.scales.scale_x_continuous.html states that "breaks (array_like or callable, optional)" so I expect that numpy arrays are ok. Turns out they are not:

> plotnine/scales/scale.py", line 575, in get_breaks
>
> ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

When I use lists that works.

**Comment by has2k1** [comment]
I think this bug was fixed. Try the master branch.

**Comment by Make42** [comment]
Well, I am using the pip install variant - could push a new version to pip then?
