### ISSUE TITLE
scale_{x,y}_reverse doesn’t work with discrete values

### ISSUE THREAD

**Issue by flying-sheep** [has2k1/plotnine#116]
So categorical axes can’t be reversed

**Comment by flying-sheep** [comment]
That’s an implementation detail.

The name promises to reverse the order in which the data points are arranged on the x/y axis.

It would be cool if it’d do that also with categorical axes by reversing the order of the categories.

**Comment by has2k1** [comment]
On 15/02/18, Philipp A. wrote:
> That’s an implementation detail.
> 
> The name promises to reverse the order in which the data points are arranged on the x/y axis.
> 
> It would be cool if it’d do that also with categorical axes by reversing the order of the categories.
> 

The documentation says that it is a continuous scale. And, I think
ggplot treats it the same.

*Categorical scales are not transformed*.

**Comment by flying-sheep** [comment]
I ported some code from ggplot to plotnine. The only unportable thing was that `+ scale_y_reverse()` stopped working.

**Comment by has2k1** [comment]
I do not know how you got reverse a discrete scale in ggplot2, but it should not work. Here is a minimal example that fails as expected.

```R
library(ggplot2)
df <- data.frame(x=c(1, 2, 3 ,4), y=c('a', 'b', 'c', 'd'))
ggplot(df) + aes(x=x, y=y) + geom_point() + scale_y_reverse()
```

In fact, `scale_y_reverse` is a [continuous scale](http://ggplot2.tidyverse.org/reference/scale_continuous.html).
