### ISSUE TITLE
Unclear argument requirements in plotnine/stats/binning.py

### ISSUE THREAD

**Issue by chrisjcameron** [has2k1/plotnine#117]
In `geom_histogram` the `breaks` argument is documented as _array-like_ which seems to mean "numpy array like in that it supports vector arithmetic and element wise multiplication". This means that simple specifications with python native data types, like `[x-.5 for x in range(10)]` are not supported unless one wraps the whole thing in an `np.array()`

Perhaps the function could cast the input sequence to the expected np.array data type or the line
`bin_x = (breaks[:-1] + breaks[1:]) * 0.5` could be made more general.

Assuming:

```
import itertools as itr
breaks = [x-.5 for x in range(10)]
```

Then:

```
a, b = itr.tee(breaks)
next(b)
bin_x = [(i+j)*.5 for i,j in zip(a,b)]
```

**Comment by chrisjcameron** [comment]
(Or the docs can be more explicit!)

**Comment by has2k1** [comment]
In the scientific python ecosystem, [array-like](https://docs.scipy.org/doc/numpy/glossary.html#term-array-like) includes lists.

**Comment by chrisjcameron** [comment]
Then we are in agreement that the function _should_ accept python lists and tulples, which makes it all the more surprising that both of these cause exceptions. 

Re-read above for the `bin_x` line in `binning.py` that performs operations **not** supported by all array-like data structures. Note that this code works fine with an `np.array` argument.

**Comment by chrisjcameron** [comment]
Unable to reproduce with plotnine 0.3.0 installed via conda. Closing.
