### ISSUE TITLE
Possible to hide legend?

### ISSUE THREAD

**Issue by jdanbrown** [has2k1/plotnine#119]
R ggplot supports `theme(legend.position = "none")`, but plotnine doesn't appear to recognize `'none'` in `theme(legend_position='none')`.
- http://ggplot2.tidyverse.org/reference/theme.html

Is there another way to do this, or is this a feature that would need to be added?

**Comment by jon-c-silva** [comment]
A workaround for this in the meantime is to set `guide=False`  in `scale_*` functions

**Comment by jdanbrown** [comment]
Thanks, confirmed! Leaving this issue open as is.

```py
(ggplot(mpg)
    + geom_point(aes(x='displ', y='hwy', color='class'))
)
```

<img width="707" alt="ggplot-mpg-n-g-74a681d8" src="https://user-images.githubusercontent.com/627486/36949781-d488e71a-1fa1-11e8-9d01-146348532243.png">

```py
(ggplot(mpg)
    + geom_point(aes(x='displ', y='hwy', color='class'))
    + scale_color_discrete(guide=False)
)
```

<img width="604" alt="ggplot-mpg-n-g-a4cf8359" src="https://user-images.githubusercontent.com/627486/36949780-d20b2ac0-1fa1-11e8-8bd3-280b2ae467da.png">

**Comment by jdanbrown** [comment]
Thanks!

**Comment by gaw89** [comment]
For anyone else looking at this in the future, I was also able to hide the legend by adding `show_legend=False` in my call to the `geom`.

    (ggplot(mpg)
    + geom_point(aes(x='displ', y='hwy', color='class', show_legend=False))
    )

**Comment by grahamjeffries** [comment]
This bug was fixed subsequent to this discussion. `theme(legend_position='none')` works as intended.

**Comment by Et9797** [comment]
> This bug was fixed subsequent to this discussion. `theme(legend_position='none')` works as intended.

Thank you - make sure it is 'none' without the capital ('None' does not work).

**Comment by PabloCanovas** [comment]
> For anyone else looking at this in the future, I was also able to hide the legend by adding `show_legend=False` in my call to the `geom`.
> 
> ```
> (ggplot(mpg)
> + geom_point(aes(x='displ', y='hwy', color='class', show_legend=False))
> )
> ```

This works BUT make sure you use 'show_legend = False' **outside** the aes() call!

**Comment by jwhendy** [comment]
Note from the future, it seems to be `guide=None` now. I had old code with `guide=False` which upon rerunning yields:
```
PlotnineError: 'Unknown guide: False'
```
