### ISSUE TITLE
scale_continuous options to position axes on top/right

### ISSUE THREAD

**Issue by dhimmel** [has2k1/plotnine#121]
ggplot2 2.2 [now](https://stackoverflow.com/a/40927909/4651668) supports positioning the x-axis and y-axis. From the `scale_continuous` [docs](http://ggplot2.tidyverse.org/reference/scale_continuous.html): 

> position: The position of the axis. "left" or "right" for vertical scales, "top" or "bottom" for horizontal scales

This doesn't appear to be a feature as of plotnine v0.3.0.

**Comment by has2k1** [comment]
This is come when there is a better layout support, belongs with #46.
