### ISSUE TITLE
Right censoring data

### ISSUE THREAD

**Issue by stillmatic** [has2k1/plotnine#126]
With a given plot, I want to right-censor my data similar to how [scale_continuous](http://ggplot2.tidyverse.org/reference/scale_continuous.html) in ggplot2 works, with `oob=squish`. I see in the plotnine documentation that `oob=np.nan` is the default, which replicates the ggplot2 default of `oob=censor`. I have tried a couple lambda functions to do this but am unsure of the shape  /format of the input (or expected output) data.

How might one do this in plotnine?

**Comment by has2k1** [comment]
Is [squish_infinite](https://mizani.readthedocs.io/en/stable/bounds.html#mizani.bounds.squish_infinite) what you are looking for?

**Comment by stillmatic** [comment]
Thanks, that's close -- that has the proper squishing behavior but looks to only trigger for infinite values. I want to squish anything larger than a certain value to that value, e.g. `lambda x: min(x, 50)` would censor any items to 50.

Here's a small R example:
```
library(ggplot2)
library(scales)
dat <- data.frame(x=factor(1:10), y=1:10)
ggplot(dat, aes(x=x, y=y)) + geom_bar(stat='identity') + scale_y_continuous(limits = c(3,7), oob = squish)
```

If such a feature doesn't exist, I'm happy to make a PR for it. I'm guessing the code for `squish_infinite` should not be hard to modify for this use case.

**Comment by has2k1** [comment]
Okay, I have seen the squish function. I guess I missed porting it since I had not really used it. Please do submit a PR at [mizani](https://github.com/has2k1/mizani).
