### ISSUE TITLE
Reorder geom_bar based on values

### ISSUE THREAD

**Issue by swayson** [has2k1/plotnine#13]
What is the way in which to achieve the reordering of the bars according to its values.

Example
```
df = pd.DataFrame([('a', 1), ('b', 20), ('c', 5)], columns=['category', 'value'])
ggplot(df, aes('category', 'value')) + geom_bar(stat='identity')
```
Bars are ordered A, B, C. Instead I want this reordered on the values, thus B, C, A.

Here is a thread on how this is achieved in R, but my question is how this can be done in plotnine
https://stackoverflow.com/questions/33613385/sort-bar-chart-by-sum-of-values-in-ggplot

Is there an equivalent reorder function?

**Comment by has2k1** [comment]
```python
ggplot(df, aes('category', 'sorted(value)')) + geom_bar(stat='identity')
```
