### ISSUE TITLE
What font families are supported?

### ISSUE THREAD

**Issue by bevankoopman** [has2k1/plotnine#130]
I understand that font family can set set within `theme` but what are support values for font family? Perhaps these can be added to docs and API docs? Thanks.

**Comment by has2k1** [comment]
See https://matplotlib.org/api/text_api.html#matplotlib.text.Text.set_family. I have added it to the documentation.

**Comment by bevankoopman** [comment]
Awesome. Thanks for the quick reply. 

Also, it's great to have plotting library that both _python_ and _grammar of graphics_ so thanks for that, too!
