### ISSUE TITLE
Add helper to create a pdf document with a plot per page

### ISSUE THREAD

**Issue by khaeru** [has2k1/plotnine#133]
This is a request for an enhancement. I find myself writing a lot of code like this:
```python
from matplotlib.backends.backend_pdf import PdfPages
import matplotlib.pyplot as plt
import plotnine as p9

# (data loading code)

with PdfPages('output.pdf') as pdf:
    for label, group_data in data.groupby('foo'):
        plot = p9.ggplot(group_data) \
            + p9.geom_point()
            # (further geoms and plotnine stuff)
        fig = plot.draw()
        pdf.save(fig)
        plt.close(fig)  # save memory
```
and find myself wishing to do something like:
```python
plot = p9.ggplot(data) \
    + p9.facet_page('foo') \
    + p9.geom_point()
    # (further geoms and plotnine stuff)
plot.save('output.pdf')
```

At least three problems I can imagine:
- Only the PDF backend in matplotlib supports multiple-page files, and plotnine doesn't know until told to draw/save whether the user will be using PDF. If they are not, I guess, they would need to supply a callback like the `labels` argument to some scales that would generate the (base)name of multiple files; or the `filename` argument to `save()` would need to be a format string like `output-{foo}.png`; or something like that.
- “That's an abuse of the grammar of graphics; you should find a better way to plot your data.” This is true, but I find myself doing this while figuring out *how* I want to design more carefully-constructed plots.
- “This is too similar to `plotnine.Animation`,” though I think it's fairly distinct, just as the multi-page PDF and animation features of matplotlib seem to be distinct and target different use-cases.

A very brief skim suggests the existing faceting code seems more oriented at producing layouts on a single page, but with a few words of direction on how this should work I'd be happy to take a stab at it over the upcoming months.

**Comment by has2k1** [comment]
I think `facet_page()` is not the best way to add such functionality. If the objective is to have multiple plots plotted to different pages of a pdf document, then it is better to use a helper method e.g. 

```python
def draw_to_pdf_pages(iterable_of_ggplots, *args, **kwargs):
    ...


plots = (
    ggplot(df) + geom_point() + facet_wrap('a ~ b') + labs(title=label)
    for label, df in data.groupby('foo')
)

draw_to_pdf_pages(plots, filename='output.pdf')
```

Such an approach allows the pages to have more disparate plots and it avoids some the problems you listed.

**Comment by khaeru** [comment]
Thanks for the response!

After another look at the code, `ggsave()` could be overloaded to do this by changing the first argument from `plot` to `plot_or_plots`:
- `plot_or_plots` is an instance of `ggplot`→ same one-liner as currently; preserves the current semantics of `ggsave`.
- `plot_or_plots` is iterable **and**:
  - `args` and `kwargs` indicate the output should be in PDF → save one plot per page, calling `plt.close()` along the way to keep memory use down.
  - some other format indicated → `ValueError`



And then I'd add an example or two to the documentation showing how it could be used: one with your flexible iterable-of-plots; one using a generator to yield the plots (as I currently do in my own code).

Would that be okay, or would you prefer a separate method? Please let me know and I'll get started on a PR.

**Comment by has2k1** [comment]
I prefer a separate method, e.g `save_as_pdf_pages`. Do you have a better name?

**Comment by khaeru** [comment]
Sure, can use this name. Should it go in `ggplot.py`, another file or a new file?

**Comment by has2k1** [comment]
Yes can go in `ggplot.py`.
