### ISSUE TITLE
Changing limits in scale_y_continuous errors out:

### ISSUE THREAD

**Issue by mcpeterson** [has2k1/plotnine#135]
qplot('currency', 'gini', data=df, geom="bar", stat="identity") +\
  scale_y_continuous(range=(0.8, 1)) +\
  theme(axis_text_x=element_text(rotation=45))

it looks like range is trying to call "train" on the object.

From a wee df I can provide I think, returns this error:
error here --> self.range.train(x)
AttributeError: 'tuple' object has no attribute 'train'

**Comment by has2k1** [comment]
Use `scale_y_continuous(limits=(0.8, 1))`. The documentation of the `range` parameter is outdated and misleading.
