### ISSUE TITLE
How to add legend labels for fitted distributions using stat_function?

### ISSUE THREAD

**Issue by BlackArbsCEO** [has2k1/plotnine#141]
For example how to add a custom legend to a plot like below:
```
import plotnine as pn
from plotnine.data import economics

loc, scale = economics['pce'].mean(), economics['pce'].std()
(pn.ggplot(economics[['pce','date']], pn.aes(x='pce'))
 +pn.geom_density()
 +pn.stat_function(color='red', fun=stats.norm.pdf, args=dict(loc=loc,scale=scale))
 +pn.stat_function(color='blue', fun=stats.laplace.pdf, args=dict(loc=loc,scale=scale)))
```
![plotnine-fitted-distributions-screenshot-localhost-8888-2018 05 29-14-26-58](https://user-images.githubusercontent.com/7452471/40683691-78c7f738-634c-11e8-9f9d-fa134b52ad83.png)

Also how do I suppress the output of the `stat_density, stat_function, stat_function` in the image?

**Comment by has2k1** [comment]
> how to add a custom legend to a plot like below:

You cannot do so. If you want to get a legend, put the computed data in a dataframe and use `aes` mapping. The legend the is generated for mapped columns *only*.

> Also how do I suppress the output of the stat_density, stat_function, stat_function in the image?

You are likely using modified version of plotnine!
