### ISSUE TITLE
future warnings related to plotnine itself and pandas-0.23.0

### ISSUE THREAD

**Issue by stonebig** [has2k1/plotnine#144]
example code below.

the first warning `plotnine\utils.py:281` seems caused per plotnine own code, isn't it ?
````
from plotnine import ggplot, aes, geom_blank, geom_point, stat_smooth, facet_wrap, theme_bw
from plotnine.data import mtcars
ggplot(mtcars, aes(x='hp', y='wt', color='mpg')) + geom_point() +\
facet_wrap("~cyl") + theme_bw()
````

![image](https://user-images.githubusercontent.com/4312421/40877306-1c87272e-667f-11e8-804c-0adb30e7b94f.png)

**Comment by has2k1** [comment]
This was fixed in master. It will be released soon.

**Comment by stonebig** [comment]
please define "soon"

**Comment by has2k1** [comment]
@stonebig, Yesterday.
