### ISSUE TITLE
Reverse factor?

### ISSUE THREAD

**Issue by jdanbrown** [has2k1/plotnine#145]
I really like the idea of the `factor = pd.Categorical` shorthand provided for aesthetics:
- https://github.com/has2k1/plotnine/blob/9e52a25/plotnine/layer.py#L299

But every time I want to reverse the order of a `factor(x)` I end up doing what feels like a lot of work. So two questions:
1. Do you know of good, lightweight translations of the R idioms into python/plotnine?
   - `factor(x, levels = rev(levels(x))))` ([example](https://stackoverflow.com/a/8713598/397334))
   - `scale_x_discrete(limits = rev(levels(x)))` ([example](https://stackoverflow.com/a/34271060/397334))
2. If not, do you think it'd make sense to add a nonstandard `rev_factor` to accommodate this (I think common) use case?

**Comment by has2k1** [comment]
I do not know if these count as light weight

```python
x = x.cat.set_categories(list(reversed(x.cat.categories)))
scale_x_discrete(limits=list(reversed(x.cat.categories)))
```

However if `x` is a categorical, then

```python
aes(x='x.cat.set_categories(list(reversed(x.cat.categories)))')
```
though it works, it looks ugly.

**Comment by jdanbrown** [comment]
Yeah, those seem mostly workable, even if not ideal.

The first one is close to the R idiom `scale_x_discrete(limits = rev(levels(x)))`, but it becomes awkward when you don't have a simple name for `df`, e.g. you've applied transformations in a pipeline style:
```py
(df
    .append(...)
    .merge(...)
    .pipe(ggplot, aes(x='x', ...))
    + geom_point()
    + scale_x_discrete(limits=list(reversed(???['x'].cat.categories)))
)
```

I think the second one might work well. It's similar to `factor(x, levels = rev(levels(x))))`, it only requires builtin pandas operations (I had overlooked `.set_categories`!), it isn't really that much more verbose or more complex than the R idiom, and except for the `xlab` it's isolated to one line in a pandas/plotnine pipeline:
```py
(mpg
    .pipe(ggplot, aes(
        x='manufacturer.cat.set_categories(list(reversed(manufacturer.cat.categories)))',
        y='hwy',
    ))
    + geom_point()
    + coord_flip()
    + xlab('manufacturer')
)
```

I'll try incorporating #2 into my workflow. Thanks!

(Maybe worth adding as an example to the docs?)

**Comment by has2k1** [comment]
`'manufacturer.cat.set_categories(list(reversed(manufacturer.cat.categories)))'` is really ugly, yet I do not want to add functions that are unique to Plotnine to the string evaluation API.
