### ISSUE TITLE
when the default scale could be either discrete or continuous

### ISSUE THREAD

**Issue by yasminlucero** [has2k1/plotnine#15]
I have a request to support a frequent use case. (Apologies if I have just missed the way to do this, I looked!) There exist cases where a column could reasonably map to either a discrete or a continuous scale, and I would like a user option to specify which one to use. 

A common example is a data column that is integer type (defaults to continuous scale), but actually only takes on a handful of values in practice (meaning it could be reasonably mapped to a discrete scale). There is not an exact number of distinct values that can differentiate whether or not the integer variable should be treated as discrete or continuous, it ultimately depends on the user's need. From what I can see, plotnine assigns the default scale based on the pandas data type in the data frame, and thus the only way to change the default behavior is to mutate the data frame itself before creating the plot object. Obviously, mutating the dataframe works fine as a workaround.  

Here is my example: 
```
import pandas as pd
import random
import plotnine

df = pd.DataFrame({'a': [random.uniform(0,1) for i in range(15)], 
                   'b': [random.uniform(0,1) for i in range(15)], 
                   'c': [random.randint(0,5) for i in range(15)]
})

ggplot(df, aes('a', 'b', color='c')) + geom_text(aes(label='c')) + geom_line(aes(group='c'))
```

FYI: in R::ggplot2 I would accomplish this by casting the variable to a factor in the aes: 
```
ggplot(df, aes(a, b, color=factor(c)) + ...
```

In case it isn't clear, the reason this matters to me is it impacts how I can manipulate the color scale. For example, in the case where the integer code is binary, the default behavior is to assign the colors purple and yellow (extremes of the 'viridis' color scale), that yellow is an unfortunately hard to see default, and changing it is harder than it seems like it needs to be.

**Comment by has2k1** [comment]
You can do the likewise in plotnine

```python
ggplot(df, aes('a', 'b', color='factor(c)')) + ...
```

which is the just a shortcut for

```python
ggplot(df, aes('a', 'b', color='pd.Categorical(c)')) + ...
```

**Comment by yasminlucero** [comment]
thank you
