### ISSUE TITLE
Issues with aesthetics

### ISSUE THREAD

**Issue by guilhermeleobas** [has2k1/plotnine#150]
Hi all,

By looking at the API reference for [geom_map](http://plotnine.readthedocs.io/en/dev/generated/plotnine.geoms.geom_map.html), I have the impression that I can set `size` inside `aes`:

```Python
(mg_map
 + geom_map (data = df, mapping = aes(fill = 'media_LC', size=0.5), draw = 'Point', stroke = 0)
 + scale_fill_cmap('Blues')
)
```

But changing `size` inside `aes` when plotting `Points` has no effect. Points ended up having the same size regardless of the value of `size. Below is the image produced with the code above. 

![image](https://user-images.githubusercontent.com/2712115/41263456-9be1d89e-6dbd-11e8-8697-9291a4850c1a.png)

Nevertheless, If I set `size` outside the aesthetics, everything works fine. Is this a bug with aesthetics or I am missing something?

Regards

**Comment by has2k1** [comment]
> If I set size outside the aesthetics, everything works fine. Is this a bug with aesthetics or I am missing something.

You are missing something. `aes()` provides a mapping of values and those values are scaled by the grammar system. If you specify a single scalar value, then a scale is of little use; there isn't any variation in the data.

Values outside `aes()` are for the manual specification. That is what you want. A rule of thumb is "if it is not data you are trying to understand, do not put it in aes".
