### ISSUE TITLE
How to force axis values to scientific notation

### ISSUE THREAD

**Issue by jonwenjen** [has2k1/plotnine#152]
In ggplot2 we can use "scale_y_continuous(labels = scales::scientific)" to show scientific notation.
How to show scientific notation in plotnine?

**Comment by has2k1** [comment]
Use the [scientific_format](http://mizani.readthedocs.io/en/stable/formatters.html#mizani.formatters.scientific_format) from the mizani package.

```python
from mizani.formatters import scientific_format

+ scale_y_continuous(labels=scientific_format(digits=2))
```
