### ISSUE TITLE
How to show shape by letters

### ISSUE THREAD

**Issue by jonwenjen** [has2k1/plotnine#153]
In ggplot2, we can use "scale_shape_manual(values=LETTERS[1:10])" to let shape by letters.
It's more clear to identify.
How we can do it in plotnine?

Thanks

**Comment by jonwenjen** [comment]
from plotnine import *
from plotnine.data import *
from plotnine.ggplot import *

mixed_shapes = (
    r'$\mathrm{A}$', 
    r'$\mathrm{B}$',  
    r'$\mathrm{C}$',  
    r'$\mathrm{D}$',  
    r'$\mathrm{E}$',  
    r'$\mathrm{F}$',  
    r'$\mathrm{G}$',  
)


(ggplot(mpg, aes('displ', 'hwy', shape='class', colour='class'))
 + geom_point(size=3)
 + scale_shape_manual(values=mixed_shapes)
)

**Comment by has2k1** [comment]
Created a [tutorial](https://github.com/has2k1/plotnine-examples/blob/master/plotnine_examples/tutorials/miscellaneous-using-letter-as-shapes.ipynb)
