### ISSUE TITLE
Deleting blank lines in faceted plot produced using geom_tile function

### ISSUE THREAD

**Issue by dputhier** [has2k1/plotnine#154]
Hi,
I don't know whether this is a question or issue. I have posted a question on *stackoverflow* regarding the usage of *facet_grid* with *geom_tile*. The code seems good to me as I'm using 'free_y' on scales. But maybe I'm missing something.
Best
  
https://tinyurl.com/ybskfbn7

**Comment by has2k1** [comment]
This is a bug that was fixed.

```
pip install git+https://github.com/has2k1/plotnine.git
```
