### ISSUE TITLE
Scale_y_log10 has no effect

### ISSUE THREAD

**Issue by Hoeze** [has2k1/plotnine#155]
Hi, I just plotted some data:
![grafik](https://user-images.githubusercontent.com/1200058/41648294-c550cbe2-7478-11e8-9e9f-2167178770f2.png)
And tried to log-scale the y-axis:
![grafik](https://user-images.githubusercontent.com/1200058/41648260-b334852a-7478-11e8-9b9b-121feab5fbf3.png)
log10 does not produce a visible effect here.
Are there other possible log bases, e.g. 2?

**Comment by has2k1** [comment]
I think the log scaling works fine, but the base you have chosen does not give you the effect you want. The data does not span a magnitude of 10. Try another base e.g

```python
+ scale_y_continuous(trans='log2')

# OR
from mizani.transforms  import log_trans
t = log_trans(base=2)
+ scale_y_continuous(trans=t)
```
See [mizani.transforms](http://mizani.readthedocs.io/en/stable/transforms.html) for more transform functions.

**Comment by Hoeze** [comment]
Thank you, that was exactly what I was searching for!

**Comment by has2k1** [comment]
Reopened. I realised the documentation was lacking.
