### ISSUE TITLE
row ordering by categorie levels in geom_tile  

### ISSUE THREAD

**Issue by dputhier** [has2k1/plotnine#156]
Hi,
I'm trying to reorder the rows in a geom_tile diagram. From what I got from ggplot2, If rows correspond to a factor/category, the level order of the factor/category dictate the way rows are ordered. 
This means that in my example below, changing:

       # row ordering
       data.object = Categorical(data.object, categories=data.object.unique(), ordered=True)

into

       # Reverse order
       # data.object = Categorical(data.object, categories=data.object.unique()[::-1], ordered=True) 

Should reverse row ordering in the plot. Maybe there is another way to achieve this result.
Best

    from plotnine import (ggplot, aes, geom_tile, 
                            facet_grid, theme_bw, 
                            scale_fill_gradientn, 
                            theme,
                            element_blank,
                            element_rect)
    import plotnine
    import pandas as pd
    import io
    import requests
    from pandas import Categorical

    #------------------------------------------------------------------------
    # Load the data.frame
    #------------------------------------------------------------------------

    url = "https://raw.githubusercontent.com/dputhier/dp_examples/master/plotnine/df_example_2.txt"
    s= requests.get(url).content
    data = pd.read_csv(io.StringIO(s.decode('utf-8')), sep="\t", header=0)
    data = data.sort_values("cls")
    data.object = Categorical(data.object, categories=data.object.unique(), ordered=True)
    data.condition = Categorical(data.condition, categories=data.condition.unique(), ordered=True)
    data.cls = Categorical(data.cls, categories=data.cls.unique(), ordered=True)

    # Create a facetted diagram

    color_palette = "#d73027,#fc8d59,#fee090,#e0f3f8,#91bfdb,#253494"
    color_palette_list = color_palette.split(",")

    p = ggplot(data=data, mapping=aes('pos',
                                      'object')
                                      ) + geom_tile(aes(fill='value'))
    p += theme_bw()
    p += scale_fill_gradientn(colors=color_palette_list,
                              name="Signal", na_value="#222222")

    p += plotnine.labels.xlab('position')
    p += plotnine.labels.ylab("object")

    p += theme(panel_grid_major=element_blank(),
               panel_grid_minor=element_blank(),
               panel_border=element_rect(colour="black", size=1))

    p +=  plotnine.facet_grid("cls~condition ",
                              scales="free_y",
                              space="free")

    p.save(filename='plot_dp_1.pdf')

    #------------------------------------------------------------------------
    # Now let's reverse factor ordering of 'object' dimension
    #------------------------------------------------------------------------

    # HERE we expect to change row/object ordering by changing the categorie levels ordering  
    data.object = Categorical(data.object, categories=data.object.unique()[::-1], ordered=True)

    # Create a facetted diagram

    color_palette = "#d73027,#fc8d59,#fee090,#e0f3f8,#91bfdb,#253494"
    color_palette_list = color_palette.split(",")

    p = ggplot(data=data, mapping=aes('pos',
                                      'object')
                                      ) + geom_tile(aes(fill='value'))
    p += theme_bw()
    p += scale_fill_gradientn(colors=color_palette_list,
                              name="Signal", na_value="#222222")

    p += plotnine.labels.xlab('position')
    p += plotnine.labels.ylab("object")

    p += theme(panel_grid_major=element_blank(),
               panel_grid_minor=element_blank(),
               panel_border=element_rect(colour="black", size=1))

    p +=  plotnine.facet_grid("cls~condition ",
                              scales="free_y",
                              space="free")

    p.save(filename='plot_dp_2.pdf')

**Comment by has2k1** [comment]
You have a lot of code going, I cannot read it. But the ordering does take from the order of the categories, [see](https://plotnine.readthedocs.io/en/stable/tutorials/miscellaneous-order-plot-series.html).
