### ISSUE TITLE
Consume too much memory due to more than 20 figures

### ISSUE THREAD

**Issue by jonwenjen** [has2k1/plotnine#158]
When I continue draw few hundred figure, the memory will consume a lot by python.
How I can close figure every time like matplotlib (like fig.clf(), fig.close())?  

Thanks

**Error message:**
537: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  max_open_warning, RuntimeWarning)

**Code:**
from plotnine import *
from plotnine.data import *

for i in range(900):
   p= ggplot(mpg)+geom_qq(aes(sample='displ', colour='factor(cyl)'))
   fig=p.draw(return_ggplot=False)
   print(i)

**Comment by has2k1** [comment]
I think the problem is you are not printing the plot at the end of each loop. When a plot is printed, the figure associated with the previous plot is closed. You are letting them accumulate.

```python
from plotnine import *
from plotnine.data import *

for i in range(21):
    p = ggplot(mpg)+geom_qq(aes(sample='displ'))
    print(p)
    print(i)
```
