### ISSUE TITLE
Default limits for timestamp

### ISSUE THREAD

**Issue by apnewberry** [has2k1/plotnine#170]
If I define a series of timestamps that are very close to each other, the default axis limits don't seem to account for this, and the axis shows no visible difference between the points. I would want it to calculate the range of the points and provide a nice bound for the axis.

```
from datetime import datetime

import pandas as pd
import plotnine as p9
import matplotlib.pyplot as plt


df = pd.DataFrame({
    'ts': [datetime.now(), datetime.now(), datetime.now()],
    'temperature': [99.1, 200.4, 400.5],
})


(
    p9.ggplot(p9.aes(x='ts', y='temperature'), data=df)
    + p9.geom_point()
    + p9.theme(axis_text_x = p9.element_text(angle = 45, hjust = 1))
).save('out.png')
```

![image](https://user-images.githubusercontent.com/31109952/43359896-41c9e1ae-9260-11e8-9cde-6dc5ca7d457a.png)

**Comment by has2k1** [comment]
This is a [mizani](https://github.com/has2k1/mizani) issue that goes all the way to Matplotlib. Microsecond time intervals are not properly supported, you can get them to work for years before 1677, after that you run into issues.

The solution is to follow the note [at](https://matplotlib.org/api/dates_api.html#matplotlib.dates.MicrosecondLocator).

> If you want microsecond resolution time plots, it is strongly recommended to use floating point seconds, not datetime-like time representation.
