### ISSUE TITLE
geom_density_2d weird render using levels for filling

### ISSUE THREAD

**Issue by raphaelcampos** [has2k1/plotnine#174]
When I run the script bellow:
```python
(
    ggplot(df_merged, aes(x='x', y='y')) +
    stat_density_2d(aes(fill='..level..'), color=None, geom = "polygon", alpha = 1.0, levels = 15) +
    facet_grid('churn~.') 
)
```
I get the following result.

![image](https://user-images.githubusercontent.com/3073266/43915563-78b7d092-9be1-11e8-8392-f5a5882f51c6.png)

It seems that is being caused by the fact that the contour lines are being cut. Once, I change the script to increase the limits of x I can get a good plot.

```python
(
    ggplot(df_merged, aes(x='x', y='y')) +
    stat_density_2d(aes(fill='..level..'), color=None, geom = "polygon", alpha = 1.0, levels = 15) +
    facet_grid('churn~.') +
    xlim(-0.2, 1.2)
)
```

![image](https://user-images.githubusercontent.com/3073266/43915720-f6bdb218-9be1-11e8-9c74-ea2e64aabadd.png)

I am not sure whether or not this is an anomalous behavior;

**Comment by has2k1** [comment]
This is a known issue that has no resolution. The "weirdness" shows up when the data limits are not sufficient to contain most of at least one single level. The solution is to have the levels computed over a larger space, i.e. [extend the limits](https://github.com/has2k1/plotnine/issues/172#issuecomment-409518942).
