### ISSUE TITLE
Confusing wording on aes grouping in the docs

### ISSUE THREAD

**Issue by nk9** [has2k1/plotnine#180]
The docs on [`plotnine.aes()`](https://plotnine.readthedocs.io/en/stable/generated/plotnine.aes.html?highlight=group) run out of steam when they get to the "group" section:

>The group aesthetic
>
>group is a special aesthetic that the user can _map_ to. It is used to group the plotted items. If not specified, it is automatically computed and in most cases the computed groups are sufficient. However, there may be cases were it is handy to map to it.

How does one _map_ to something? I tried using map(), but didn't know what to use for the second argument. I tried a lambda, but that failed too:

    geom_boxplot(aes(group = lambda x: round(x)))

Error:

    plotnine.exceptions.PlotnineError: "Do not know how to deal with aesthetic 'group'"

Tracked down that error [in the code](https://github.com/has2k1/plotnine/blob/master/plotnine/layer.py#L338), but I still can't quite figure out how I'm supposed to use this. That method only seems to discuss types.

I'm hoping I can use it like `cut_interval()` and friends in ggplot2. I want all of my data on a given axis to be grouped into buckets like ((0,2], (2,4], (4,6], etc.).

Anyway, some more guidance in the docs would be really helpful here.

**Comment by has2k1** [comment]
Try 

```python
aes(group='np.round(x)')
```

In the terminology of the plotting grammar, to *map* means to assign column values (or a computation on column values) to an aesthetic. The `aes` function creates mappings and when these mappings are created, the data points are automatically put into groups to make the right plot. Sometimes this automatic grouping mechanism does not do what the user expects; so the user can override it by directly mapping to the group aesthetic. This is [example](https://plotnine.readthedocs.io/en/stable/tutorials/miscellaneous-automatic-grouping-insufficient.html).

**Comment by nk9** [comment]
That's helpful, thanks. I still feel like an example in the docs would be helpful. I didn't try passing a string before, although I see now that many of the other arguments take strings as well.
