### ISSUE TITLE
subplots_adjust ignores hspace, wspace

### ISSUE THREAD

**Issue by lzamparo** [has2k1/plotnine#185]
I'm trying to adjust layout of `facet_grid` via `theme(subplots_adjust={})` as suggested in #113, but whatever I pass as a dict gets ignored:

```
p = gg.ggplot(gg.aes(y='objective', x='value', fill='param'), df)
p = p + gg.geom_point(show_legend=False) 
p = p + gg.geom_density_2d(show_legend=False)
p = p + gg.facet_wrap('~ param', ncol=3, scales='free_x')
p = p + gg.theme(figure_size=(8,8))
p = p + gg.theme(subplots_adjust={'hspace': 0.2})
```
![spearmint_hyperparam_values](https://user-images.githubusercontent.com/1569186/44819746-fe63fd80-abbb-11e8-9211-1cd603296e1b.png)

```
p = gg.ggplot(gg.aes(y='objective', x='value', fill='param'), df)
p = p + gg.geom_point(show_legend=False) 
p = p + gg.geom_density_2d(show_legend=False)
p = p + gg.facet_wrap('~ param', ncol=3, scales='free_x')
p = p + gg.theme(figure_size=(8,8))
p = p + gg.theme(subplots_adjust={'wspace': 0.5,'hspace': 0.5})
```
![spearmint_hyperparam_values](https://user-images.githubusercontent.com/1569186/44819831-4be06a80-abbc-11e8-859f-cdc057ca687d.png)

As per the[ matplotlib docs](https://matplotlib.org/api/_as_gen/matplotlib.figure.SubplotParams.html) values to `subplots_adjust` are supposed to be fractions of the figure height / width.  Has anyone else seen this?

plotnine version: 0.4.0

**Comment by has2k1** [comment]
That is a bug.

```python
theme(panel_spacing_y=0.2)
```

**Comment by lzamparo** [comment]
A bug upstream in matplotlib?  Thanks for clarifying at any rate :)

**Comment by has2k1** [comment]
> A bug upstream in matplotlib?

No, it is in plotnine. ``panel_spacing_x` and `panel_spacing_y` always override `wspace` and `hspace` of the `subplot_adjust` parameters.
