### ISSUE TITLE
No x/y-coordinates shown in graph window

### ISSUE THREAD

**Issue by physici** [has2k1/plotnine#187]
Hi,

I just discovered that in the graph window created by plotnine the x/y-coordinates are not shown in the lower left corner.

Is this a bug?

Thanks,
Rainer

**Comment by has2k1** [comment]
What graph window? And what backend are you using?

**Comment by physici** [comment]
I am using spyder with the ipython-console and the Qt5Agg backend for matplotlib.

My settings force matplotlib to create a new window every time I call plt.figure(). Also plotnine creates a new plot window.  Graphs are not shown as inline.

I have marked the position of the coordinates, where plotnine only shows "x= y=" instead of the coordinates of the curser in the figure.
![grafik](https://user-images.githubusercontent.com/15417017/45148607-f6154f00-b1c7-11e8-836e-3f9ac547657a.png)
