### ISSUE TITLE
Add alpha for geom_smooth lines

### ISSUE THREAD

**Issue by votti** [has2k1/plotnine#19]
The 'alpha' transparency parameter seems to be currently ignored with 'geom_smooth'.

For 'geom_line' it seems to work as expected.

Example:
 ```python
from plotnine import *
import pandas as pd

pdat = pd.DataFrame({'x': range(10), 'y': range(10)})

p = (ggplot(pdat, aes(x='x', y='y'))+
    geom_smooth(alpha=0.1))
p.draw()


p = (ggplot(pdat, aes(x='x', y='y'))+
    geom_line(alpha=0.1))
p.draw()
 ```

**Comment by votti** [comment]
I just noticed, that this is also not possible in the R ggplot2, but this solution is recommended:
(https://stackoverflow.com/questions/19474552/adjust-transparency-alpha-of-stat-smooth-lines-not-just-transparency-of-confi)
 ```python
p = (ggplot(pdat, aes(x='x', y='y'))+
  geom_line(stat="smooth",method = "lm",
              alpha = 0.1))
p.draw()
 ```
..which works beatifull also in plotnine.
Thanks for the great implementation!

**Comment by has2k1** [comment]
It is by design. Also, unless you intend to use the result (figure) of the `draw()` method, it is better to do `print(p)`
