### ISSUE TITLE
How do I get stat_summary to work with mean?

### ISSUE THREAD

**Issue by gaurakshay** [has2k1/plotnine#190]
@has2k1 How do I get stat_summary to work with mean?

Using the following method in R, I am able to plot the mean for the dataset:

    ggplot(aes(x=TIME, y=TEMP), data = df)
    + geom_line(aes(group=RANK, color=RANK))
    + stat_summary(fun.y = "mean", geom = "line", color="red", size=1)
    + labs(title='Year 2011 days with maximum T >= 42 C, NRMN mesonet site', x='Central Daylight Time', 
    y='degree C', color='Hotness Rank')

![stat_summary_r](https://user-images.githubusercontent.com/17280428/45322133-f9347600-b50c-11e8-894d-0a26d9922e3f.png)

However in plotnine, using similar plot grammar :

    (
     ggplot(aes(x='TIME', y='TEMP'), data=df)
    + geom_line(aes(color='RANK', group='RANK'))
    + stat_summary(aes(group='RANK'), fun_y="mean", geom = "line", color="red", size=1)
    + labs(title='Year 2011 days with maximum T >= 42 C, NRMN mesonet site', x='Central Daylight Time', 
    y='degree C', color='Hotness Rank')
    )

This gives me:
`TypeError: 'mean' is not a callable object`

How do I get a line for average for the y values across the groups?

**Comment by gaurakshay** [comment]
Okay, I think I need to add somthing like np.mean to fix this. However, if I do this:

    ggplot(aes(x='TIME', y='TEMP'), data=df)
    + geom_line(aes(color='RANK', group='RANK'))
    + stat_summary(aes(group='RANK'), fun_y=np.mean, geom = "line", color="red", size=1)
    + labs(title='Year 2011 days with maximum T >= 42 C, NRMN mesonet site', x='Central Daylight Time', y='degree C', color='Hotness Rank')

I am getting all the lines as red:

![stat_summary_plotnine](https://user-images.githubusercontent.com/17280428/45323443-b2487f80-b510-11e8-88e4-c2c4957c0dda.png)

**Comment by has2k1** [comment]
You have `color='red'`
```

**Comment by gaurakshay** [comment]
Its my bad. I was passing a "group" aesthetic in the stat_summary function.
