### ISSUE TITLE
Cannot fill by column that contains Nan

### ISSUE THREAD

**Issue by svenski** [has2k1/plotnine#192]
I have included an example where I `fill` by a column that contains Nan (`np.nan`) and get an error.  The corresponding version in R shows the NA bar in grey, which is a nice feature.

```python
import pandas as pd
import numpy as np
from plotnine import *

df = pd.DataFrame({'a' : [1,2,3], 'b': ['a', 'b',np.nan]})
ggplot(df,aes('a')) + geom_bar(aes(fill='b'))
```

The error I get is: 
```
<SNIP>
/XXX/lib/python3.6/site-packages/plotnine/scales/scale.py in map(self, x, limits)
    284         else:
    285             pal = np.asarray(pal)
--> 286             pal_match = pal[match(x, limits)]
    287             pal_match[pd.isnull(pal_match)] = self.na_value
    288         return pal_match

IndexError: index 2 is out of bounds for axis 1 with size 2
```

I'm using python 3.6.6 and plotnine 0.3.0.

UPDATE: Actually the above was run with 0.3.0 but I reproduced it in a new conda environment with python 3.7 and plotnine 0.4.0.

**Comment by has2k1** [comment]
I cannot reproduce this bug, and I seem to recall fixing it. Try a fresh install.

**Comment by svenski** [comment]
I've tried both conda-forge version 0.4.0 and the github development version using pip with the same result, when using fresh conda environments. 

I've attached an environment.yml file which specifies the conda environment and dependencies. I set it up from scratch to test this. In order to reproduce the environment you can run `conda env create -f environment.yml` . The activate the environment and the above should be reproducible. 

[environment.yml.zip](https://github.com/has2k1/plotnine/files/2379297/environment.yml.zip)

**Comment by svenski** [comment]
The issue with the code above is that the `pal` array is of length two. The `match(x,limits)` returns `[1,2,-1]` which exceeds the index of `pal`. The `limits` variable starts with `np.nan` which is why the index is higher than expected. 

It's been fixed for a version just above where `pal` is a `dict` with a try catch block. 

 I couldn't get the tests to pass, I think due to not having the right fonts installed as all the differences were in text.  Also, I'm not certain on how the different parts hang together, so I'm not going to try to fix it, but this might help someone to fix it.

**Comment by has2k1** [comment]
I was unable to reproduce the crushing bug. However I realised that same example sometimes lead to a different and clearly wrong plot.

A lack of proper support for missing values in `numpy` and `pandas` has made this issue very hard to resolve, but I'll will push the solution soon.
