### ISSUE TITLE
Plotnine fails installing with pipenv

### ISSUE THREAD

**Issue by stefansimik** [has2k1/plotnine#195]
Hi, when I install plotnine with pipenv, installation fails

Used command:
----------------------------------------------------------------------------------------------
pipenv install plotnine

Error output:
----------------------------------------------------------------------------------------------
(risk_ml_models-nBjo5Jpn) C:\MYDATA\Projects\PABK\Programming\knoyd_pabk_code\risk_ml_models>pipenv install plotnine
Installing plotnine...
Collecting plotnine
  Using cached https://files.pythonhosted.org/packages/fe/49/7af942bc63277dfca6ad397415f4cff60789c56d173b1f7edf0bd30e27e0/plotnine-0.4.0-py2.py3-none-any.whl
Collecting patsy>=0.4.1 (from plotnine)
  Using cached https://files.pythonhosted.org/packages/5d/eb/92c4b45ca47a2dd1339c958636e083b50ffadb5162a599a1cbbe92f89832/patsy-0.5.0-py2.py3-none-any.whl
Collecting mizani>=0.4.5 (from plotnine)
  Using cached https://files.pythonhosted.org/packages/52/01/8a3b4c6e45749674a1e5241174b4b63cd6435125e124bec275f3e02c96ac/mizani-0.4.6-py2.py3-none-any.whl
Requirement already satisfied: numpy in c:\users\stesim\.virtualenvs\risk_ml_models-nbjo5jpn\lib\site-packages (from plotnine) (1.15.1)
Requirement already satisfied: matplotlib>=2.1.0 in c:\users\stesim\.virtualenvs\risk_ml_models-nbjo5jpn\lib\site-packages (from plotnine) (2.2.3)
Requirement already satisfied: six in c:\users\stesim\.virtualenvs\risk_ml_models-nbjo5jpn\lib\site-packages (from plotnine) (1.11.0)
Requirement already satisfied: pandas>=0.21.0 in c:\users\stesim\.virtualenvs\risk_ml_models-nbjo5jpn\lib\site-packages (from plotnine) (0.23.4)
Collecting geopandas>=0.3.0 (from plotnine)
  Using cached https://files.pythonhosted.org/packages/24/11/d77c157c16909bd77557d00798b05a5b6615ed60acb5900fbe6a65d35e93/geopandas-0.4.0-py2.py3-none-any.whl
Collecting descartes>=1.1.0 (from plotnine)
  Using cached https://files.pythonhosted.org/packages/e5/b6/1ed2eb03989ae574584664985367ba70cd9cf8b32ee8cad0e8aaeac819f3/descartes-1.1.0-py3-none-any.whl
Collecting statsmodels>=0.8.0 (from plotnine)
  Using cached https://files.pythonhosted.org/packages/77/2b/8ba61399b31f984c263b177c2e2547a34f0d4d972a24a51fc77c376079b0/statsmodels-0.9.0-cp36-cp36m-win_amd64.whl
Requirement already satisfied: scipy>=1.0.0 in c:\users\stesim\.virtualenvs\risk_ml_models-nbjo5jpn\lib\site-packages (from plotnine) (1.1.0)
Collecting palettable (from mizani>=0.4.5->plotnine)
  Using cached https://files.pythonhosted.org/packages/56/8a/84537c0354f0d1f03bf644b71bf8e0a50db9c1294181905721a5f3efbf66/palettable-3.1.1-py2.py3-none-any.whl
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\stesim\.virtualenvs\risk_ml_models-nbjo5jpn\lib\site-packages (from matplotlib>=2.1.0->plotnine) (1.0.1)
Requirement already satisfied: pytz in c:\users\stesim\.virtualenvs\risk_ml_models-nbjo5jpn\lib\site-packages (from matplotlib>=2.1.0->plotnine) (2018.5)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\stesim\.virtualenvs\risk_ml_models-nbjo5jpn\lib\site-packages (from matplotlib>=2.1.0->plotnine) (2.7.3)
Requirement already satisfied: cycler>=0.10 in c:\users\stesim\.virtualenvs\risk_ml_models-nbjo5jpn\lib\site-packages (from matplotlib>=2.1.0->plotnine) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\users\stesim\.virtualenvs\risk_ml_models-nbjo5jpn\lib\site-packages (from matplotlib>=2.1.0->plotnine) (2.2.1)
Collecting pyproj (from geopandas>=0.3.0->plotnine)
  Using cached https://files.pythonhosted.org/packages/29/72/5c1888c4948a0c7b736d10e0f0f69966e7c0874a660222ed0a2c2c6daa9f/pyproj-1.9.5.1.tar.gz
    Complete output from command python setup.py egg_info:
    using bundled proj4..
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\stesim\AppData\Local\Temp\pip-install-m6yqgp4m\pyproj\setup.py", line 72, in <module>
        objects = cc.compile(['nad2bin.c', 'src/pj_malloc.c'])
      File "c:\users\stesim\anaconda3\Lib\distutils\_msvccompiler.py", line 345, in compile
        self.initialize()
      File "c:\users\stesim\anaconda3\Lib\distutils\_msvccompiler.py", line 238, in initialize
        vc_env = _get_vc_env(plat_spec)
      File "c:\users\stesim\.virtualenvs\risk_ml_models-nbjo5jpn\lib\site-packages\setuptools\msvc.py", line 185, in msvc14_get_vc_env
        return EnvironmentInfo(plat_spec, vc_min_ver=14.0).return_env()
      File "c:\users\stesim\.virtualenvs\risk_ml_models-nbjo5jpn\lib\site-packages\setuptools\msvc.py", line 1228, in return_env
        self.OSIncludes,
      File "c:\users\stesim\.virtualenvs\risk_ml_models-nbjo5jpn\lib\site-packages\setuptools\msvc.py", line 963, in OSIncludes
        sdkver = self._sdk_subdir
      File "c:\users\stesim\.virtualenvs\risk_ml_models-nbjo5jpn\lib\site-packages\setuptools\msvc.py", line 1057, in _sdk_subdir
        ucrtver = self.si.WindowsSdkLastVersion
      File "c:\users\stesim\.virtualenvs\risk_ml_models-nbjo5jpn\lib\site-packages\setuptools\msvc.py", line 604, in WindowsSdkLastVersion
        self.WindowsSdkDir, 'lib'))
      File "c:\users\stesim\.virtualenvs\risk_ml_models-nbjo5jpn\lib\site-packages\setuptools\msvc.py", line 809, in _use_last_dir_name
        for dir_name in reversed(os.listdir(path))
    FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\PlatformSDK\\lib'

    ----------------------------------------

Error:  An error occurred while installing plotnine!
Command "python setup.py egg_info" failed with error code 1 in C:\Users\stesim\AppData\Local\Temp\pip-install-m6yqgp4m\pyproj\

System:
---------------------------------------
OS:        Win10 Home
Python:  3.6.4 Anaconda on win32

**Comment by has2k1** [comment]
This looks like an issue with `pyproj`. Based on [this](https://github.com/has2k1/plotnine/issues/178#issuecomment-420528771) recommendation, the `pyproj` will not be a requirement in the next version.

**Comment by jordangumm-progenity** [comment]
This appears to be resolved.
