### ISSUE TITLE
Alpha appears to be ignored if it's constant for all datapoints:

### ISSUE THREAD

**Issue by TyberiusPrime** [has2k1/plotnine#200]
(why does github treat no text and enter as a valid issue... sorry about that).

An alpha aes is ignored when all instances have the same value.
Observe:
```python
p = plotnine.ggplot()
p += plotnine.geom_rect(
    plotnine.aes(xmin='xmin',xmax='xmax',ymin='ymin',ymax='ymax',fill='fill',
                alpha='alpha'),
          data = pd.DataFrame({
              'xmin': [0,0],
              'xmax': [1,0.5],
              'ymin': [0,0],
              'ymax': [1,0.5],
              'fill': ['red', 'blue'],
              'alpha': [0.5, 0.51]
          }),)
p += plotnine.scale_fill_identity()
p
```
Produces this, as expected.
![image](https://user-images.githubusercontent.com/1257580/46079830-85df6500-c198-11e8-8864-030adee6d1e4.png)

But replacing that second alpha value with 0.5:
```python
p = plotnine.ggplot()
p += plotnine.geom_rect(
    plotnine.aes(xmin='xmin',xmax='xmax',ymin='ymin',ymax='ymax',fill='fill',
                alpha='alpha'),
          data = pd.DataFrame({
              'xmin': [0,0],
              'xmax': [1,0.5],
              'ymin': [0,0],
              'ymax': [1,0.5],
              'fill': ['red', 'blue'],
              'alpha': [0.5, 0.50]
          }),)
p += plotnine.scale_fill_identity()
p
```
![image](https://user-images.githubusercontent.com/1257580/46079858-9db6e900-c198-11e8-9666-6f1ee9333bcd.png)

I suspect this is also the underlying issue with #50  and #43 - arguably setting an aes to a scalar is something a user would expect - it's documented to work for x and y in the API.
But please note that this is a different case - we have a valid aes mapping that just happens to contain the same value for all instances and it's completely ignored :(.

**Comment by TyberiusPrime** [comment]
I understand why this is happening - the scale is treating a single alpha value as a discrete scale and creates a mapping that's just that_one_scalar->1.0, while it treats two floating point values as a continuous scale, which at least get's some transparency, but not the one the user wanted. 

scale_alpha_identity() has to be added for that.

**Comment by TyberiusPrime** [comment]
I believe there's already some magic around x/y axis and discrete/continuous/date axis to get 'decent' limits and breaks by default. 

Could the argument be made that the alpha axis should undergo similar magic be default?
For example  'all values floats between 0 and 1 -> identity, otherwise discrete/continuous with limits(0.1, 1) as before'?

**Comment by has2k1** [comment]
> I suspect this is also the underlying issue with #50 and #43 - arguably setting an aes to a scalar is something a user would expect - it's documented to work for x and y in the API.

Yes that is the issue. This specific is not about discrete or continuous distinctions.

> Could the argument be made that the alpha axis should undergo similar magic be default?
There is no magic. It is works for `x` and `y` (positional aesthetics) because the guide/legend for those aesthetics is the axis itself! And the axis can represent numbers in any range, no range of values is special.

For the alpha value, we cannot treat the [0, 1] range any different because that would change the meaning of what it means to map to a scale. If you have any specific values, put them outside the `aes()` call. If you think about it some more, it will make sense!

**Comment by TyberiusPrime** [comment]
Hassan, I have the deepest respect for your work on plotnine. It is a truly beautiful library.
May I suggest that "If you have any specific values, put them outside the aes() call."
would be better phrased as 'if you have specific values, use an identity mapping'.
This is the more general, and to my mind, more useful advice.


> Yes that is the issue. This specific is not about discrete or continuous distinctions.

Indeed, it is about sensible default mappings.

Having scale_alpha_continuous(range(0.1, 1)) as the default scale trips new users, as evidenced by multiple bug reports.

How about switching to scale_alpha_identity() by default.
It does not change 'the meaning of what it means to map to a scale'
and it will explode with a (semi-useful) error message if you pass in something that needs 
one of the 'true' mappings.

But separately from the issue of the default scale for alpha, why
does training scale_alpha_continuous((0.1,1)) on a single value
map to an alpha of 1, while a scale_x_continuous will put your 
value in the middle of the plot?

I'd have expected it to map to 0.5.

**Comment by TyberiusPrime** [comment]
I appreciate you being so welcoming and responsive.

So alpha uses rescale_pal by default.

rescale_pal's doc string states 'Useful for alpha, size, and continuous position.'
It's being used by alpha, size and stroke though. Could possibly benefit from an example 
about what happens if you only supply one value, just to be thorough. 
Would you like me to write a pull request to improve the doc?

> That may lead to less confusion in some cases but it represents a significant API change as it would be different from ggplot2.

Hey, if we wanted to do everything exactly the same as ggplot2, we could've been using an rpy2 wrapper (I  I've done so for years. And I rejoice at the opportunity to replace it's guts with plotnine!).
