### ISSUE TITLE
Default minor breaks on log scales are wonky

### ISSUE THREAD

**Issue by TyberiusPrime** [has2k1/plotnine#202]
The minor_breaks created by default on a scale_x/y_log10 are unintuitive.

Example:
```python
import pandas as pd
import plotnine
df = pd.DataFrame({"x": [0.1, 5]})
p = plotnine.ggplot(df, plotnine.aes('x','x'))
p += plotnine.geom_point()
p += plotnine.geom_point(data=pd.DataFrame({'x': 
    [ 0.082, 0.28, 0.46, 0.64, 0.82, 2.8, 4.6, 6.4, 5]
}), color='blue')
p += plotnine.geom_text(plotnine.aes(label='x'),
                    ha='left', nudge_x=.1)
p += plotnine.scale_y_log10()
p += plotnine.scale_x_log10()
p
```

![image](https://user-images.githubusercontent.com/1257580/46151105-569b2780-c26e-11e8-8812-b311dcc67d41.png)

Note the blue dots, and their values that I reverse engineered out of a geom's panel_params.

Not that ggplot does it much better, placing a single minor tick sometwhere around Pi.
![image](https://user-images.githubusercontent.com/1257580/46151763-c6f67880-c26f-11e8-95ab-920af005404b.png)

Either way, the default minor ticks are worthless if the viewer can not
figure out what values they actually have.
My suggestion would be to either: Do not have default minor ticks on log axis,
or default to proper log ticks for base 10 and nothing for other bases.

**Comment by has2k1** [comment]
The calculation of minor breaks in plotnine differs from ggplot2, and they make sense. They divide the space into equal parts, if the space (due to the choice of scale) is non-linear, it will be depicted in the minor breaks. It works like this for all scales.


```python
import pandas as pd
import numpy as np
from plotnine import *

df = pd.DataFrame({
    'x': [0.1, 5]
})

df_minor_breaks = pd.DataFrame({
   'x':  np.hstack((
       np.log10(np.logspace(0.1, 1, num=6)),
       np.log10(np.logspace(1, 10, num=6)))
   )
}) 


p = (ggplot(df, aes('x','x'))
     + geom_point()
     + geom_point(df_minor_breaks, color='blue')
     + geom_text(aes(label='x'), ha='left', nudge_x=.1)
     + scale_x_log10()
     + scale_y_log10()
    )

p
```
![minor_breaks](https://user-images.githubusercontent.com/780341/46200613-bf3fde00-c31a-11e8-8bd3-d366f2da440d.png)

**Comment by TyberiusPrime** [comment]
I agree in principle, 6 divisions (=4 in between) is appropriate for a linear scale.
But  np.log10(np.logspace(0.1, 1, num=10)) is more appropriate for a log10 scale.


```python
import pandas as pd
import numpy as np
from plotnine import *

df = pd.DataFrame({
    'x': [0.1, 5]
})
ten_per = np.hstack([np.log10(np.logspace(0.1, 1, num=10)),
np.log10(np.logspace(1, 10, num=10)),])

df_minor_breaks = pd.DataFrame({
   'x':  ten_per
}) 


p = (ggplot(df, aes('x','x'))
     + geom_point()
     + geom_point(df_minor_breaks, color='blue')
     + geom_text(aes(label='x'), ha='left', nudge_x=.1)
     + scale_x_log10(minor_breaks =np.log10(ten_per))
     + scale_y_log10(minor_breaks =np.log10(ten_per))
    )
p
```
![image](https://user-images.githubusercontent.com/1257580/46202228-8dc51380-c316-11e8-9186-1e9699ab6c65.png)

(Also can you explain why I have to give the minor_breaks in log10 units?)

**Comment by TyberiusPrime** [comment]
I've been thinking about this, and have found that the way the default breaks work on log plots create perfectly un-interpretable plots.

I mean look at this one (code below):
![image](https://user-images.githubusercontent.com/1257580/46213233-54050480-c338-11e8-8a98-d0f04c22dfe4.png)
and read the value of the right/upper dot from the axis.

I can't. I strongly suspect most people can't.

It's 5000 by the way:
```python
import pandas as pd
from plotnine import *

df = pd.DataFrame({
    'x': [0.1, 5000]
})

p = (ggplot(df, aes('x','x'))
     + geom_point()     
     + scale_x_continuous(trans='log10')
     + scale_y_continuous(trans='log10')
    )
p += labs(title="log_10")
p
```

And now how this plot *should* look like
![image](https://user-images.githubusercontent.com/1257580/46213693-911dc680-c339-11e8-9782-3eafd73ae76b.png)
using the following breaks and minor_breaks

```python
breaks = [0.1, 1, 10, 100, 1000]
minor_breaks = np.hstack((
    np.log10(np.log10(np.logspace(0.1, 1.0, 10))),
    np.log10(np.log10(np.logspace(1, 10, 10))),
    np.log10(np.log10(np.logspace(10, 100, 10))),
    (np.log10([100, 200, 300, 400, 500, 600, 700, 800, 1000])), # np.logspace starts exploding at these ranges
    (np.log10([1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 10000]))
))    
```

I don't think there's a valid reason to omit any '1-log unit' in a log10 plot like the current algorithm is doing.

Ok, you might be dealing with supernovae and have something going up to 10**30,
but those three people on the planet can set their breaks themselves.

Everybody else just needs a readable mapping, preferably by default.

**Comment by has2k1** [comment]
The algorithm for log breaks will be updated.

**Comment by has2k1** [comment]
>I  agree in principle, 6 divisions (=4 in between) is appropriate for a linear scale.
> But np.log10(np.logspace(0.1, 1, num=10)) is more appropriate for a log10 scale.

I have always been more bothered by the fact that it is not easy to change the number of `minor_breaks`.
It requires a refactoring.

>(Also can you explain why I have to give the minor_breaks in log10 units?

That is a bug.

**Comment by TyberiusPrime** [comment]
> > (Also can you explain why I have to give the minor_breaks in log10 units?
> 
> That is a bug.

Can we fix this first / quickly before we change the break algorithm / interface for minor breaks?

**Comment by TyberiusPrime** [comment]
> > I  agree in principle, 6 divisions (=4 in between) is appropriate for a linear scale.
> > But np.log10(np.logspace(0.1, 1, num=10)) is more appropriate for a log10 scale.
> 
> I have always been more bothered by the fact that it is not easy to change the number of `minor_breaks`.
> It requires a refactoring.

Yes, one would think that minor_breaks = <int> would be a useful way for the user to specify that number of minor breaks between major breaks.

I can patch get_minor_breaks to do that:
```python
    def get_minor_breaks(self, major, limits=None):
        """
        Return minor breaks
        """
        if major is None:
            return []

        if limits is None:
            limits = self.limits

        if callable(self.minor_breaks):
            breaks = self.minor_breaks(self.trans.inverse(limits))
            _major = set(major)
            minor = self.trans.transform(breaks)
            return [x for x in minor if x not in _major]

        if isinstance(self.minor_breaks, int):
            self.trans.minor_breaks.n = self.minor_breaks - 2 # could also
            return self.trans.minor_breaks(major, limits)
        elif not is_waive(self.minor_breaks):
            return self.minor_breaks

        return self.trans.minor_breaks(major, limits)
```

but it breaks encapsulation. 

Unfortunately, the setter for  trans does not pass any parameters to 'mizani.transforms.gettrans()
