### ISSUE TITLE
Points at 'infinity' can't be plotted

### ISSUE THREAD

**Issue by TyberiusPrime** [has2k1/plotnine#204]
One of the nicer hidden features of ggplot2 is that points with infinite value
are plotted 'half' at the border of a plot, like in this toy example:
![image](https://user-images.githubusercontent.com/1257580/46215481-c3c9be00-c33d-11e8-99b5-05fb1062e44b.png)

Currently, potnine drops infinite values. 
Silently, unlike points otherwise outside the limit.
Even if the oob-function does return them, they're not plotted.

It would be nice to have this functionality in plotnine, at least optionally.
Together with an oob function that replaces values outside of the limits
with +-inf this would be really cool.

**Comment by has2k1** [comment]
Related to #166. I have a commit that should address the issue for all geoms, just haven't tested it.

**Comment by has2k1** [comment]
The warning is not related to infinity in the data. It can be relevant information and should not be suppressed.

**Comment by TyberiusPrime** [comment]
No, it is related to a 0 in data that get's log-transformed.
But you need to pass in a 0 to get a point at the bottom/left side of the plot if you have a log-scale.
The scale transform 0 to -inf (and complains), while -inf get's turned into nan (and a complaint) and dropped.

I'd argue that if the 0 is being drawn at the bottom of a log plot - like a -inf value in a non-log plot - is a valid value and should not be warned about.

Or tell me another way to get my (background) rect to span the whole height in a plot with a log-y axis.

**Comment by has2k1** [comment]
It is a transformation issue, not a boundary of the plot issue. In this case the two just happen to coincide, so that warning preceded the infinity fix. For example in you square-root transform a negative value you should get a similar transformation issue warning.

I guess the warning message could be better, but we would have to fight with numpy to get that to happen.

**Comment by TyberiusPrime** [comment]
Ok, I'll do my alternating background plots as an annotation (= a data-less geom), that way I can simply use the y_range passed into geom.draw_group.

Is there a way for the geom to tell that the scale is continous?

**Comment by has2k1** [comment]
> Is there a way for the geom to tell that the scale is continous?

Not possible.
