### ISSUE TITLE
Non-aes x-value (and y?) treatment

### ISSUE THREAD

**Issue by TyberiusPrime** [has2k1/plotnine#207]
For *reasons* I wanted to create a jitter plot with a constant x-value,
which fails with an exception that "position_jitter requires the following missing aesthetics: x'" 
```g += p9.geom_point(aes(y='y_column'), x = 1.0, position=p9.position_jitter(0.5, False)```

Thinking about this this has uncovered some inconsistencies in the way mappings are handled in kwargs,
which for color etc are *not* mapped:
```df = pd.DataFrame({
    'datax': ['shu','shu','shu'],
    'y': [1,2,3]})
g = p9.ggplot(df)
g += p9.geom_point(aes(y='y', x='datax'), color='blue')
```
is valid while
```g += p9.geom_point(aes(y='y', x='datax'), color='not-a-color')```
will throw an (expected) exception.

So far, so understandable.

But with x-values, weird things happen. 
```g += p9.geom_point(aes(y='y', x='datax'), color='blue')``` => 
![image](https://user-images.githubusercontent.com/1257580/46741741-f2348b00-cca5-11e8-9dcc-9d1c30c0f8cc.png)

```g += p9.geom_point(aes(y='y'), x = 'constant')```
![image](https://user-images.githubusercontent.com/1257580/46741767-fd87b680-cca5-11e8-8a99-76f2ab99ff11.png)

or with a numeric value
```g += p9.geom_point(aes(y='y'), x = 5.0)```
![image](https://user-images.githubusercontent.com/1257580/46741799-0bd5d280-cca6-11e8-8dc4-205ee7444b01.png)

Note that 5.0 is simply outside the default limits, and  you can't add a scale with  appropriate limits to the last one, training will fail with an exception.
If you have points on the plot to train the axis though,
```
g += p9.geom_point(aes(y='y', x='y'), color='blue')
g += p9.geom_point(aes(y='y'), color='red', x=1.1)
```
this does get you an arguably correct plot:
![image](https://user-images.githubusercontent.com/1257580/46742012-7e46b280-cca6-11e8-8fda-1f1ab7f21482.png)
with **mapped** values (try with x='y*100' and x= 150).

But this only applies to numerical values, even on discrete scales:
```
g = p9.ggplot(df)
g += p9.geom_point(aes(y='y', x='datax'), color='blue')
g += p9.geom_point(aes(y='y'), color='green', x='shu') # shows nothing
g += p9.geom_point(aes(y='y'), color='red', x=1.1)
```
![image](https://user-images.githubusercontent.com/1257580/46742166-c6fe6b80-cca6-11e8-99c2-bb033b6ce642.png)

A long list of examples without much of a point, I guess - they just don't feel right.

I think at least ```g += p9.geom_point(aes(y='y'), color='green', x='shu')``` should throw an
exception. 

Being able to pass continuous numbers to a discrete scale - and have them
being interpreted as they are - is useful though, even if it's a bit inconsistent in that 
the euclidean scales always get their data mapped, while the others need literal values.

**Comment by has2k1** [comment]
In a weird way, what you are experiencing makes *some* sense. You are putting values on an axis that should have no scale. A good and sensible scale is created only if there is data mapped to it, by setting the `x` values outside `aes` there is no mapping, hence these

```python
g += p9.geom_point(aes(y='y'), x = 'constant')
g += p9.geom_point(aes(y='y'), x = 5.0)
```

produce plots with undemarcated x-axis. It shows that the axis has no scale. Remember the x-axis is the guide/legend for the x-aesthetic, and a guide only makes sense when there is a mapping.

Now, you can search the coordinate system to reveal the numerical placement of the values.

```python
+ p9.coord_cartesian(xlim=[-1, 1])  # 'constant' should be at 0
+ p9.coord_cartesian(xlim=[4, 6])   # 5.0 should be at 5
```

 But this is just poking around the internals and I would not depend on it to always be predictable.

**Comment by TyberiusPrime** [comment]
Yes, I don't want to  argue  that it's wrong or that we should change anything,
just that we need to improve documentation on this.

It's an fairly overloaded API we inherited from R - Hadley recently had to introduce a new operator called quasiquotation to get around some limits of R expressions in this very context.
It does make the most common use case very brief though.

Let's count the number of ways the user can currently pass in data to be plotted:

Let's start with  aes() - it takes "expression | array_like | scalar"
Where expression might be a column from the plot's data frame (1), or from the geom's dataframe (2), or a variable in the outside scope (3), a 'expression' like "x*5" or "np.log10(x)" (4). Note that (2) overrides (1), but you can mix in (3) to either, and having a column named 'x*5' means that the expression is not evaluated, but the column used instead. The expression may use everything in the scope where the geom is being called, following normal python scoping rules.

Also note that when using (3), you have to keep in mind the type of the variable - x*5 will explode if x is a list and the dataframe does not have len(x) * 5 values.

The array_like may be either a numpy array/pandas series (5) or a list (6), either of length of the dataframe (7) or of length 1 (8). It may contain values that get mapped, so ```color=['a','a','b','b']``` is ok,
so is color=['a'].

Scalars may be numerical (9), in which case they get mapped just like an array_like or any expression.
It may be a string (10), but it must be wrapped in additional quotes (otherwise it will be treated as an expression). So ```color='"a"'``` is ok, but color="a" will probably fail. 

Aesthetics may also refer to a stat-derived value, which may be referred to 
as either (e.g.)  'stat(count)' (11) or '..count..' (12).

You may also pass constant aesthetics outside of the aes() argument as keyword argument to a geom (13). In this case they will be set to a literal value, e.g. color='red'.
For the x and y axis this means that they values get placed in the right place with regard to the limits,
but if your axis is transformed, you must apply the transformation to your constant value yourself (@has2k1  is this a bug similar to the minor breaks?). 
(Side note: If you want to use literal values in an array or scalar inside an aes(), you need to set a literal scale)


Did I miss anything?


Further nothes
  * The outside-variable variant (3) still needs at least on empty dataframe for the plotting to work, this is arguably a bug.

**Comment by has2k1** [comment]
> ... you must apply the transformation to your constant value yourself (@has2k1 is this a bug similar to the minor breaks?

That is not a bug.

**Comment by TyberiusPrime** [comment]
I believe there are two conceptually missing 'pass-in-data' variants:

a) mapped array-like data (all the same length, inside aes()) and a do-not-use-any-dataframe data-value
b) unmapped array-like data and a do-not-use-any-dataframe data-value (replacing annotate)
(and of course, a combination of both and with 'single value literals').
