### ISSUE TITLE
Plotting stat_summary with seperate aes

### ISSUE THREAD

**Issue by TyberiusPrime** [has2k1/plotnine#208]
Let's say I want to plot the minimum of a column.
I'd have expected the following to work
```python
(p9.ggplot(pd.DataFrame({
    'x': ['A','A','B','B', 'A'],
    'y': [4,5,6,7,8]})) + 
p9.geom_point(p9.aes(x='x',y='stat(ymin)'),stat=p9.stat_summary(mapping=aes(x='z', y='y'))))
```
but I end up with
```python
PlotnineError: 'stat_summary requires the following missing aesthetics: y'
```

What am I doing wrong?

**Comment by has2k1** [comment]
You cannot have separate `aes` with the same mappings, it is ambiguous. For you specific example, you should change the function that acts on the `y` aesthetic. i.e

```python
df = pd.DataFrame({
    'x': ['A','A','B','B', 'A'],
    'y': [4,5,6,7,8]
})

(p9.ggplot(df)
 + p9.geom_point(p9.aes('x', 'y'), stat=p9.stat_summary(fun_y=np.min))
)
```

**Comment by TyberiusPrime** [comment]
Hm... I always found stats to be one of the less-well-defined parts of the ggplot2-grammar
(or possibly, I just don't grok them). 

I'd like to think of stats as grouping-aware data transformations that also replace a geom's data and manipulate it's aes() when passed as stat= (or define their own geom when used standalone),
but that's apparently not what they are. 
(Under that model, we'd have the inital data (and applied aes) that the stat sees, and the transformed data (and aes on the transformed data) that the geom sees, and an aes 'inheritance' if you don't pass a mapping to the stat.)

To illustrate the confusion this works:
```p9.geom_point(p9.aes(x='x', y='y',color='stat(ymin)'),stat=p9.stat_summary())```
and it happily mixes pre-stat aes and post-stat aes at the geom level,
while stat-level aes *will* be ignored here, they only apply when using the stat 'standalone.

Just for reference, it's even worse in R where you need to something like this:
```R
library(ggplot2)
df = data.frame(x = c('A','A','B','B', 'A'),
    y= c(4,5,6,7,8))
g = ggplot(df)
g = g + stat_summary(aes(x=x,y=y), geom="point", fun.y=min)
```
because doing geom_point(..., stat=stat_summary(...)) will fail with an obscure error message.
