### ISSUE TITLE
Discrete X axis is slow 

### ISSUE THREAD

**Issue by TyberiusPrime** [has2k1/plotnine#209]
I have a use case where I need to sort my (discrete) x-axis by y-axis values.
I'd usually do this by turning it into a pd.Categorical,
and it works, but plotting is very slow.

Here's a minimal example with a 1000 points
which reports about 12 seconds on my machine:

```python
import pandas as pd
import numpy as np
import plotnine as p9
pdf = pd.DataFrame({
    'x': [str(x) for x in range(0,1000)],
    'y': np.random.normal(0, 1, 1000)
})

g = p9.ggplot(pdf)
g += p9.geom_point(p9.aes('x','y'))
import time
s = time.time()
g.save("test.png")
e = time.time()
print('time for rendering', e - s, 'seconds')
```

The non-discrete scatter plot plotting
```python 
pdf = pd.DataFrame({
    'x': [x for x in range(0,1000)],
    'y': np.random.normal(0, 1, 1000)
})
```
takes 0.46 seconds!

Note that it's the cardinality of the x-axis, not the number of points as 
plotting ```'x': [str(x) for x in ['A','B'] * 500],``` is just as fast (or even faster) than plotting
continous data.

My debugging suggests that geom_point.draw_group is called once per x-value, leading to many many 
draw_unit and ax.scatter calls. 
This occurs because each data point get's it's own group.

Specifying a constant 'dummy group' by having a constant column 'group' in the dataframe and adding group='group' reduces run time by about half (12.3 vs 6.7 seconds). Better but not good.

How can we approach making this use case faster?

**Comment by has2k1** [comment]
The simplest solution is thinking about [this](https://github.com/has2k1/plotnine/blob/283c4e746eb7eda735a3f9d0343b56ca341d4a1f/plotnine/geoms/geom.py#L227-L229), which if viable (e.g for [geom_rect](https://github.com/has2k1/plotnine/blob/283c4e746eb7eda735a3f9d0343b56ca341d4a1f/plotnine/geoms/geom_rect.py#L27-L31) should give the same performance as the `group='constant'` trick.

I think it should work for `geom_point` but I don't know why I did not do it in the first place either a simple oversight or the code changed making it viable afterwards.

**Comment by TyberiusPrime** [comment]
I can confirm that a 'pass-throu' draw_panel in geom_point achieves the same performance as the group='constant' trick, while still allowing (at least) color aes.

I don't think I've ever used 'group' with geom_point, but I found one example from ggplot where grouping on a geom_point is necessary:
https://stackoverflow.com/questions/21468380/overlay-geom-points-on-geom-boxplotfill-group
which looks like this in p9:
```python
pdf = pd.DataFrame({
    'variable': ['A','A','A','A','B','B','B','B'],
    'value': np.random.normal(0,1,8),
    'group': ['C','C', 'D','D', 'C','C','D','D']
})
g = p9.ggplot(pdf, p9.aes(x='variable', y='value'))
g += p9.geom_boxplot(p9.aes(fill='group'))
g += p9.geom_point(group='group', position=p9.position_dodge(width=0.75), color='hotpink')
g
```
![image](https://user-images.githubusercontent.com/1257580/47013564-ed5d5480-d147-11e8-8cde-69295f3472d2.png)

which still works with the pass-through draw_panel (don't know why though).

So I think it's viable.


It still leaves us with factor of about 10 between the categorical and real valued case though.

I've attached a 'flame graph' (using py-spy) for drawing 5000-point discrete x-axis
[flame_graph.zip](https://github.com/has2k1/plotnine/files/2482808/flame_graph.zip)
maybe it's illuminating to you.

**Comment by TyberiusPrime** [comment]
Most of the remaining time is spent drawing the ticks/labels,
doing ```g += p9.scale_x_discrete(breaks = [])``` goes from ~12 seconds down to 1.2s.
Removing just the labels, but not the breaks goes down to about 6s.

I don't think there's a whole lot to be done here as far as speed ups go - we could not label/break at every value of the discrete scale if there are 'many' values, but I think it's highly context dependent.

**Comment by has2k1** [comment]
`breaks=[]` short-circuits the areas where Matplotlib is slow (from my memory of MPL issues and the discussions) i.e the axis ticks and text. Text is worse because there is no `TextCollection` class so each label is assigned it's own artist class leading to multiple drawing events. I do not think it can be solved/mitigated in plotnine.
