### ISSUE TITLE
facet_wrap broken in new release

### ISSUE THREAD

**Issue by jbloom** [has2k1/plotnine#210]
The `facet_wrap` command is broken in the latest release (0.5.0): it only plots the data for the first facet.

See this example:

```python
import pandas
import plotnine
from plotnine import *

print(f"Using plotnine {plotnine.__version__}")

df = pandas.DataFrame({'facet_var':['a', 'a', 'a', 'a', 'b', 'b', 'b'],
                        'hist_var':[1, 2, 3, 3, 3, 4, 5]})

print(df)

ggplot(df, aes('hist_var')) + geom_histogram(binwidth=1, center=0) + facet_wrap('~ facet_var')
```

    Using plotnine 0.5.0
      facet_var  hist_var
    0         a         1
    1         a         2
    2         a         3
    3         a         3
    4         b         3
    5         b         4
    6         b         5

![output_0_1](https://user-images.githubusercontent.com/1906801/47051168-f48c5e80-d157-11e8-9c2c-628789c177c2.png)

**Comment by TyberiusPrime** [comment]
It appears to not be a faceting bug per se (faceting geom_line works as expected), 
but to be triggered by the combination of changes in 
https://github.com/has2k1/plotnine/commit/401741c68c15de3e112777ab0cc5de8f8d8a1a4a

I've tracked it down to an indexing problem in transform_position/squish_infinite.
Line 97 in positions/position.py reads
```data[xs] = data[xs].apply(trans_x)```
but bounds.squish_infinite will return an index that does not match the one passed in.

**Comment by has2k1** [comment]
@TyberiusPrime, thanks for the debugging. The solution is to fix the functions in `mizani` so that the index of series objects is always preserved, i.e since `np.asarray` has a side-effect of stripping away the index information, need to put a guard around it.

**Comment by jbloom** [comment]
Thanks, this indeed fixed my problems.
