### ISSUE TITLE
Plot multiple plots in the same cell

### ISSUE THREAD

**Issue by tuanna35** [has2k1/plotnine#214]
I have been searching all over for this but couldn't find how to do it.

Can I plot multiple plots in the same cell (Jupiter Notebook)??

**Comment by has2k1** [comment]
On 22/10/18, tuanna35 wrote:
> I have been searching all over for this but couldn't find how to do it.
> 
> Can I plot multiple plots in the same cell (Jupiter Notebook)??
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/has2k1/plotnine/issues/214

Just print the ggplot objects.

```python
from plotnine import *
from plotnine.data import *

g1 = ggplot(mtcars, aes('wt', 'mpg')) + geom_point(color='red')
g2 = ggplot(mtcars, aes('wt', 'mpg')) + geom_point(color='blue')

# Do the prints in the same cell.
print(g1)
print(g2)
```

**Comment by tuanna35** [comment]
Of course. Thank you.
