### ISSUE TITLE
..count.. equivalent for geom_text()

### ISSUE THREAD

**Issue by tuanna35** [has2k1/plotnine#215]
I'm trying to add a geom_text() to a 100% stacked bar chart without aggregating the data before hand.

`(ggplot(df,aes(x,fill=y)) +
 geom_bar(position='fill') 
)`

In R I would use `geom_text(stat='count', aes(label=..count..))`. Is there any equivalent in plotnine?

**Comment by has2k1** [comment]
Do the same thing in plotnine. i.e.

```python
 + geom_text(aes(label='stat(count)'), stat='count', position='fill')
```

Even in R you would have to use matching position values.

**Comment by schrodog** [comment]
This trick should be included in tutorial, it is so commonly used

**Comment by has2k1** [comment]
Reopened so that I can remember to make a tutorial for this.
