### ISSUE TITLE
geom_rug needs to be changed when using coord_flip

### ISSUE THREAD

**Issue by TyberiusPrime** [has2k1/plotnine#216]
geom_rug takes a sides parameter (lrbt),
which is evaluated *after* the coord_flip.

This means you need to change your geom_rug call 
if you're adding a coord_flip() to a plot.

Example:
```python
import plotnine as p9
from plotnine.data import mtcars
g = p9.ggplot(mtcars,p9.aes('wt','mpg'))
g += p9.geom_point()
g += p9.geom_rug(sides='l')
g
```
![image](https://user-images.githubusercontent.com/1257580/47342065-02376c00-d6a3-11e8-97b3-7b0e7540eeb4.png)
and after the coord_flip:

```python
from plotnine.data import mtcars
g = p9.ggplot(mtcars,p9.aes('wt','mpg'))
g += p9.geom_point()
g += p9.geom_rug(sides='l')
g += p9.coord_flip()
g
```
![image](https://user-images.githubusercontent.com/1257580/47342084-15e2d280-d6a3-11e8-9d59-7d74cac5462e.png)

To my mind that is unfortunate, but required for full ggplot2 compability.

I have been thinking we might extend the accepted values of sides to include
perhaps y/Y/x/X which would read 'at y-axis, opposite y-axis ...', which would
flip 'correctly' when coord_flip is applied. 

This would maintain ggplot2 compability, while actually improving the situation.
The actual values are of course up to debate.
And it would cause an exception to use both kinds of sides at once in one geom_rug.

**Comment by TyberiusPrime** [comment]
I'm open to submitting a pull request - just tell me how you'd like this fixed.

**Comment by has2k1** [comment]
This is clearly a bug that should also be fixed in ggplot2. I usually fix them there first if I can or just submit a bug report.
