### ISSUE TITLE
Add adjustText (for text repelling) to geom_text

### ISSUE THREAD

**Issue by has2k1** [has2k1/plotnine#218]
[adjustText](https://github.com/Phlya/adjustText).

See also:
1. https://gist.github.com/votti/885672c90b4550154215e07190730a1b
2. https://github.com/Phlya/adjustText/wiki

**Comment by TyberiusPrime** [comment]
That's cool.

It think ggrepel does it as a custom geom - I guess it would be hard to do it as a position, 
since that happens way earlier?

**Comment by TyberiusPrime** [comment]
See pull request #220
