### ISSUE TITLE
Including multiple plots in a single animation

### ISSUE THREAD

**Issue by ExcaliburZero** [has2k1/plotnine#223]
Currently I am working on visualizing some data using `PlotnineAnimation`, which works well for making an animation of a single plot. However, I have a case where I want to show two plots of different data (and axes) in an animation simultaneously (next to each other), both of which would change as time passes in the animation.

Is it possible to do this currently in plotnine?

**Comment by has2k1** [comment]
It is not possible in plotnine. If you can then do the plots separately (at the same frame rate) and merge them side by side using [ffmpeg](https://unix.stackexchange.com/a/233833/200327).
