### ISSUE TITLE
Facetting and preserve = 'single' produces ever narrower bars.

### ISSUE THREAD

**Issue by nathaneastwood** [has2k1/plotnine#224]
Similar to [this issue](https://github.com/tidyverse/ggplot2/issues/2493) that was in **ggplot2** exists within **plotnine**. It was fixed in [this](https://github.com/tidyverse/ggplot2/pull/2562) pull request. In **plotnine**, however the bars get narrower and still have different sizes for each facet.

```
n = 10
df = pd.DataFrame({'x': np.arange(n),
                   'y': np.arange(n),
                   'yfit': np.arange(n) + np.tile([-.2, .2], n//2),
                   'Top': ['cat1', 'cat1', 'cat1', 'cat2', 'cat2', 'cat3', 'cat3', 'cat3', 'cat3', 'cat3'], 
                   'cat': ['a', 'b', 'a', 'b', 'a', 'b', 'c', 'a', 'd', 'd']})

(ggplot(df)
 + geom_col(aes('cat', 'y', fill='cat'), position=position_dodge(preserve='single'))
 + facet_wrap('~Top', scales='free_x')
)
```

**Comment by has2k1** [comment]
This issue looked familiar. I [fixed](https://github.com/tidyverse/ggplot2/pull/2154) it in ggplot2 but it was not merged.
