### ISSUE TITLE
edge color for labels

### ISSUE THREAD

**Issue by TyberiusPrime** [has2k1/plotnine#225]
I'd like to introduce edge colors for labels.

I can either expose them as (unmapped) parameter, or as a full aesthetic,
but I run into the issue that I then need a third color scale, besides color and fill.

What's the preferred way to tackle this?

**Comment by has2k1** [comment]
Use a parameter for `box_color` so that if specified it overrides the `color`.

**Comment by TyberiusPrime** [comment]
done in #226
