### ISSUE TITLE
axis_ticks_x and axis_ticks_y

### ISSUE THREAD

**Issue by dputhier** [has2k1/plotnine#227]
Hi,
Plotnine benefits from the 'axis_ticks' argument. But, ss there a way to have a control on  ticks from x and y axis (something like axis_ticks_x and axis_ticks_y) ?
Best

**Comment by has2k1** [comment]
See [themeables](https://plotnine.readthedocs.io/en/stable/api.html#themeables).

... | ...  
--|--
axis_ticks | x & y major and minor axis tick lines
axis_ticks_major | x & y axis major tick lines
axis_ticks_major_x | x-axis major tick lines
axis_ticks_major_y | y-axis major tick lines
axis_ticks_minor | x & y axis minor tick lines
axis_ticks_minor_x | x-axis tick lines
axis_ticks_minor_y | y-axis minor tick lines

**Comment by dputhier** [comment]
Sorry...
Thanks a lot.
