### ISSUE TITLE
Legend order

### ISSUE THREAD

**Issue by TyberiusPrime** [has2k1/plotnine#229]
The legend order is not properly defined.
This code will produce both images on different invocations of the python interpreter:
```python
pdf = mtcars.assign(gear=pd.Categorical(mtcars.gear), am=pd.Categorical(mtcars.am))
pdf = pdf[sorted(pdf.columns)]  # should constrain, but doesn't.
p = (
    ggplot(pdf)
    + geom_point(
        aes("gear", "wt", shape="gear", color="am"),
    )
)
p

```
![image](https://user-images.githubusercontent.com/1257580/48407180-888d1e00-e736-11e8-9adc-91a5a0975b60.png)

![image](https://user-images.githubusercontent.com/1257580/48407295-c2f6bb00-e736-11e8-8173-6fd5b5b2f3ff.png)

My suggested fix would be to change line 308ff of guides/guides.py from
```python
for gdef in gdefs:
    if gdef.order == 0:
                gdef.order = 100         
```
to
```python
for ii, gdef in enumerate(sorted(gdefs, key=lambda gdef: gdef.title)):
    if gdef.order == 0:
                gdef.order = 100 + ii        
```

Which will still allow the user to set the order by hand if desired,
and would induce a simple alphabetical order otherwise.

We could also sort by DataFrame column order (followed by anything that's not a column, alphabetically), but it would be much more code, and I think not actually that transparent for the user.

ggplot2 doc states "if 0 (default), the order is determined by a secret algorithm.", so I guess sorting alphabetically would be ok then - at least it would be *stable*.

**Comment by has2k1** [comment]
This behaviour is certainly undesirable. I am surprised that there is no test that has revealed it. 
Since dictionaries are ordered in python >= 3.6, I prefer to have a deterministic order that is not alphabetic.

That means the following will lead to different legend orderings.

```python
aes('gear', 'wt', shape='gear', color='am')
aes('gear', 'wt', color='am', shape='gear')
```
