### ISSUE TITLE
Doc request: add breadcrumbs about linetype

### ISSUE THREAD

**Issue by jwhendy** [has2k1/plotnine#233]
Coming from R, I was expecting `linetype=int` would [work](https://ggplot2.tidyverse.org/reference/aes_linetype_size_shape.html). It didn't, so I went to look for what kind of linetype values I could use. The [api page](https://plotnine.readthedocs.io/en/stable/api.html) does't say anything about this that I could find.

I found it referenced in [elements.py](https://github.com/has2k1/plotnine/blob/283c4e746eb7eda735a3f9d0343b56ca341d4a1f/plotnine/themes/elements.py#L19) which suggests looking at `matplotlib`. Indeed, that has what I was [looking for](https://matplotlib.org/api/_as_gen/matplotlib.lines.Line2D.html#matplotlib.lines.Line2D.set_linestyle).

Is this something that could be added to the api so users know allowable types without requiring the hunt above?

**Comment by has2k1** [comment]
Where did first look for the allowable types?

**Comment by jwhendy** [comment]
I assumed it would be somewhere in [the api overview](https://plotnine.readthedocs.io/en/stable/api.html) so I just searched the page there and nothing stood out. I was looking for something like:

>`linetype`: one of 'solid', 'dashed', ... 'foo' or a corresponding int 1, 2, ..., n

Re-looking at all the hits for `linetype` on that page, the closest is in [`element_line`](https://plotnine.readthedocs.io/en/stable/generated/plotnine.themes.element_line.html#plotnine.themes.element_line):

>linetype : str | tuple
>Line style. See matplotlib.lines.Line2D.set_linestyle() for specification.

Comparing to ggplot2, I'd search [this page](https://ggplot2.tidyverse.org/reference/) for 'linetype' and get `aes_linetype_shape_size` which points [here](https://ggplot2.tidyverse.org/reference/aes_linetype_size_shape.html) and has the allowable styles.

If you're game to make this change (and if you want help, I could take a whirl), I really like the printout messages for `facet_grid/wrap` where you say something like:

>Typical formulas look like 'var1~var2' or '~var1+var2'

Linetype could say:
```
'Unrecognized type: {}; allowed styles are 'dashed', 'dotted'...'.format(user_provided_option)
```

Just some thoughts!

**Comment by jwhendy** [comment]
Awesome, thanks for the additions in your commit!
