### ISSUE TITLE
How to plot ccdf?

### ISSUE THREAD

**Issue by guilhermeleobas** [has2k1/plotnine#234]
Hi,

I am having some problems trying to plot the `ccdf` with plotnine. In R, I can do the following:

```
p <- ggplot(df, aes(x=Z))
p + geom_line(aes(y = 1 - ..y..), stat='ecdf')
```

But I can't replicate this same functionality on plotnine.

**Comment by has2k1** [comment]
Please post at minimal reproducible example in python.

**Comment by guilhermeleobas** [comment]
```python
df = pd.DataFrame({'x' : [1, 2, 2.5, 4], 'y' : [2, 10, 40, 52]})

(ggplot(df, aes(x='x'))
 + geom_line(aes(y='1-..y..'), stat='ecdf')
)
```

**Comment by guilhermeleobas** [comment]
Oh, I can work on a PR to fix this if you want. Just guide me a bit on what should be the expected result for this specific case I will work on a fix.

**Comment by has2k1** [comment]
No worries I fixed it and stashed it. I just need to commit and push.
