### ISSUE TITLE
'We only accept x&y as positional parameters' and geom_hline/geom_vline

### ISSUE THREAD

**Issue by TyberiusPrime** [has2k1/plotnine#237]
Would you be open to let geom_hline/geom_vline accept their x_intercept/y_intercept by position?

It's cumbersome to have to use geom_hline(y_intercept=X) every time.

**Comment by has2k1** [comment]
In `aes()`, `x` and `y` are only positional parameters.
In `geoms` , the `data` and `mapping` are the only positional parameters.

I do not think it is a good idea to make a special case for `geom_hline` and `geom_vline`.

**Comment by TyberiusPrime** [comment]
These two geoms are already special in that they can be used as annotations (ie. you set an non-aes y-intercept and they overwrite data). It's not a big step from that to also accept this magic as a positional parameter while keeping the behaviour intact if you pass in a mapping.

But then, ggplot2 never bothered with it either.

**Comment by has2k1** [comment]
The geoms are "special" as a matter of history and backwards compatibility.

And it would be convenient as shown below;

```python
+ annotate('vline', xintercept=[1, 2, 3])  # 1
+ geom_vline(xintercept=[1, 2, 3])         # 2
+ geom_vline([1, 2, 3])                    # 3
```

but then `geom_vline` and `geom_hline`, become different from all others even `geom_abline` which also has roots as an annotation geom. The "specialness" would have to be documented, and general statements like the first two in my [comment](https://github.com/has2k1/plotnine/issues/237#issuecomment-443215541) would no longer hold.
