### ISSUE TITLE
legend at the bottom blocks x axis

### ISSUE THREAD

**Issue by koaning** [has2k1/plotnine#239]
It seems there is not enough distance between the axis and the bottom legend at times. 

```
(p9.ggplot() +
            p9.ggtitle(f"loss function over {xaxis}") +
            p9.theme(legend_position="bottom") +
            p9.geom_line(data=pltr,
                         mapping=p9.aes(x=xaxis, y="mse",
                                        group="run", color="group")))
```

The code above resulted in the bottom chart. 

![image](https://user-images.githubusercontent.com/1019791/50057350-6c333580-0169-11e9-8a0f-31e65726bb2e.png)

**Comment by has2k1** [comment]
This is a know issue generally related to not having a good [layout manager](https://github.com/has2k1/plotnine/issues/46).

You have to manually adjust the legend with 

```python
+ theme(subplots_adjust={'bottom':  .75}  # find a value that works
```

**Comment by Hungreeee** [comment]
Does not work
