### ISSUE TITLE
Authorization for a book in Chinese introducing plotnine

### ISSUE THREAD

**Issue by jianshu93** [has2k1/plotnine#244]
Dear Hassan,

This is Jayson. I am writing to you to discuss the possibility of writing a book introducing your package plotnine in Chinese. ggplot2 has receive great popularity in China and all over the world and I believe plotnine will also be welcomed by the science community all over the world. I am going to work with Jie Zhang, who is very familiar with publication of books and both he and I have lots of experience in visualization of data using different packages. We will ask you to write a preface for the new book. We are just start to write the book and wondering whether you can authorize the book introducing your package.

Looking forward to your reply.
Best,
Jianshu (Jayson) Zhao

**Comment by has2k1** [comment]
Hello Jason,

Please send me an email `has2k1 gmail com`.

Thanks
