### ISSUE TITLE
bottom legend position

### ISSUE THREAD

**Issue by mbanghart** [has2k1/plotnine#245]
The bottom legend is positioned over the x axis text.  I have tried using 

theme(subplots_adjust={'bottom': 0.15}) 

I have tried various values for the bottom parameter and the legend continues to overwrite the axis text.  The plot does shrink.  The legend moves with the shrinking plot.

**Comment by has2k1** [comment]
This is related to #46.

You can set the legend position explicitly e.g `theme(legend_position=(.5, -.1))`.

**Comment by mbanghart** [comment]
Thank you.

I was able to put the legend horizontally on the bottom by adding the following to my ggplot code.

  p9.theme(subplots_adjust={'bottom': 0.2}) +
  p9.theme(legend_position=(.5, .05), legend_direction='horizontal', legend_title=p9.element_blank()) +
