### ISSUE TITLE
Got ModuleNotFoundError: No module named 'pandas.tseries.tools' during import

### ISSUE THREAD

**Issue by tvirot** [has2k1/plotnine#252]
Hi, 

I'm trying to use plotnine on Google Colaboratory. It was working fine a week or two ago. Below is the full stack trace. If you want to try it yourself, https://colab.research.google.com/drive/1FO6HVLCUEl7jf1--15LbtTyY6A6nYmko

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/statsmodels/compat/pandas.py in <module>()
     52 try:
---> 53     import pandas.tseries.tools as datetools
     54     import pandas.tseries.frequencies as frequencies

ModuleNotFoundError: No module named 'pandas.tseries.tools'

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-1-e36b44751b17> in <module>()
----> 1 from plotnine import *

/usr/local/lib/python3.6/dist-packages/plotnine/__init__.py in <module>()
----> 1 from .qplot import qplot            # noqa: F401
      2 from .ggplot import ggplot, ggsave  # noqa: F401
      3 from .ggplot import save_as_pdf_pages  # noqa: F401
      4 from .watermark import watermark    # noqa: F401
      5 from .aes import *                  # noqa: F401,F403,E261

/usr/local/lib/python3.6/dist-packages/plotnine/qplot.py in <module>()
      7 from patsy.eval import EvalEnvironment
      8 
----> 9 from .ggplot import ggplot
     10 from .aes import aes, all_aesthetics, scaled_aesthetics
     11 from .labels import labs

/usr/local/lib/python3.6/dist-packages/plotnine/ggplot.py in <module>()
     15 from .aes import aes, make_labels
     16 from .layer import Layers
---> 17 from .facets import facet_null
     18 from .facets.layout import Layout
     19 from .options import get_option

/usr/local/lib/python3.6/dist-packages/plotnine/facets/__init__.py in <module>()
----> 1 from .facet_grid import facet_grid
      2 from .facet_null import facet_null
      3 from .facet_wrap import facet_wrap
      4 from .labelling import label_value, label_both, label_context
      5 from .labelling import labeller, as_labeller

/usr/local/lib/python3.6/dist-packages/plotnine/facets/facet_grid.py in <module>()
      4 from ..utils import match, join_keys
      5 from ..exceptions import PlotnineError
----> 6 from .facet import facet, layout_null, combine_vars, add_missing_facets
      7 from .facet import eval_facet_vars
      8 

/usr/local/lib/python3.6/dist-packages/plotnine/facets/facet.py in <module>()
     10 from ..utils import cross_join, match
     11 from ..exceptions import PlotnineError
---> 12 from ..scales.scales import Scales
     13 
     14 # For default matplotlib backend

/usr/local/lib/python3.6/dist-packages/plotnine/scales/__init__.py in <module>()
     77 from .scale_xy import scale_y_timedelta
     78 # limits
---> 79 from .limits import xlim, ylim, lims, expand_limits
     80 
     81 

/usr/local/lib/python3.6/dist-packages/plotnine/scales/limits.py in <module>()
      6 
      7 from ..aes import all_aesthetics
----> 8 from ..geoms import geom_blank
      9 from ..scales.scales import make_scale
     10 from ..exceptions import PlotnineError

/usr/local/lib/python3.6/dist-packages/plotnine/geoms/__init__.py in <module>()
      4 
      5 # geoms
----> 6 from .geom_abline import geom_abline
      7 from .geom_area import geom_area
      8 from .geom_bar import geom_bar

/usr/local/lib/python3.6/dist-packages/plotnine/geoms/geom_abline.py in <module>()
      5 from ..doctools import document
      6 from ..aes import aes
----> 7 from .geom import geom
      8 from .geom_segment import geom_segment
      9 

/usr/local/lib/python3.6/dist-packages/plotnine/geoms/geom.py in <module>()
      1 from copy import deepcopy
      2 
----> 3 from ..stats.stat import stat
      4 from ..aes import rename_aesthetics, is_valid_aesthetic
      5 from ..layer import layer

/usr/local/lib/python3.6/dist-packages/plotnine/stats/__init__.py in <module>()
      4 from .stat_bindot import stat_bindot
      5 from .stat_boxplot import stat_boxplot
----> 6 from .stat_density import stat_density
      7 from .stat_density_2d import stat_density_2d
      8 from .stat_ecdf import stat_ecdf

/usr/local/lib/python3.6/dist-packages/plotnine/stats/stat_density.py in <module>()
      3 import numpy as np
      4 import pandas as pd
----> 5 import statsmodels.api as sm
      6 
      7 from ..doctools import document

/usr/local/lib/python3.6/dist-packages/statsmodels/api.py in <module>()
      5 from . import regression
      6 from .regression.linear_model import OLS, GLS, WLS, GLSAR
----> 7 from .regression.recursive_ls import RecursiveLS
      8 from .regression.quantile_regression import QuantReg
      9 from .regression.mixed_linear_model import MixedLM

/usr/local/lib/python3.6/dist-packages/statsmodels/regression/recursive_ls.py in <module>()
     14 from statsmodels.regression.linear_model import OLS
     15 from statsmodels.tools.data import _is_using_pandas
---> 16 from statsmodels.tsa.statespace.mlemodel import (
     17     MLEModel, MLEResults, MLEResultsWrapper)
     18 from statsmodels.tools.tools import Bunch

/usr/local/lib/python3.6/dist-packages/statsmodels/tsa/statespace/mlemodel.py in <module>()
     15 from .kalman_filter import (KalmanFilter, FilterResults, INVERT_UNIVARIATE,
     16                             SOLVE_LU)
---> 17 import statsmodels.tsa.base.tsa_model as tsbase
     18 import statsmodels.base.wrapper as wrap
     19 from statsmodels.tools.numdiff import (_get_epsilon, approx_hess_cs,

/usr/local/lib/python3.6/dist-packages/statsmodels/tsa/base/tsa_model.py in <module>()
      1 from statsmodels.compat.python import lrange, long
----> 2 from statsmodels.compat.pandas import is_numeric_dtype
      3 
      4 import datetime
      5 

/usr/local/lib/python3.6/dist-packages/statsmodels/compat/pandas.py in <module>()
     54     import pandas.tseries.frequencies as frequencies
     55 except ImportError:
---> 56     from pandas.core import datetools
     57     frequencies = datetools

ImportError: cannot import name 'datetools'
```

**Comment by TyberiusPrime** [comment]
It's an issue with an older version of statsmodels which apparently is installed by default on google colab.

"!pip install statsmodels -U"
fixes it for me.

**Comment by tvirot** [comment]
Thanks for your prompt response! Works like a charm. Shall we make plotnine require statsmodels 0.9.0 instead of 0.8.0 then?

**Comment by priyanshgupta1998** [comment]
> Hi,
> 
> I'm trying to use plotnine on Google Colaboratory. It was working fine a week or two ago. Below is the full stack trace. If you want to try it yourself, https://colab.research.google.com/drive/1FO6HVLCUEl7jf1--15LbtTyY6A6nYmko
> 
> ```
> ---------------------------------------------------------------------------
> ModuleNotFoundError                       Traceback (most recent call last)
> /usr/local/lib/python3.6/dist-packages/statsmodels/compat/pandas.py in <module>()
>      52 try:
> ---> 53     import pandas.tseries.tools as datetools
>      54     import pandas.tseries.frequencies as frequencies
> 
> ModuleNotFoundError: No module named 'pandas.tseries.tools'
> 
> During handling of the above exception, another exception occurred:
> 
> ImportError                               Traceback (most recent call last)
> <ipython-input-1-e36b44751b17> in <module>()
> ----> 1 from plotnine import *
> 
> /usr/local/lib/python3.6/dist-packages/plotnine/__init__.py in <module>()
> ----> 1 from .qplot import qplot            # noqa: F401
>       2 from .ggplot import ggplot, ggsave  # noqa: F401
>       3 from .ggplot import save_as_pdf_pages  # noqa: F401
>       4 from .watermark import watermark    # noqa: F401
>       5 from .aes import *                  # noqa: F401,F403,E261
> 
> /usr/local/lib/python3.6/dist-packages/plotnine/qplot.py in <module>()
>       7 from patsy.eval import EvalEnvironment
>       8 
> ----> 9 from .ggplot import ggplot
>      10 from .aes import aes, all_aesthetics, scaled_aesthetics
>      11 from .labels import labs
> 
> /usr/local/lib/python3.6/dist-packages/plotnine/ggplot.py in <module>()
>      15 from .aes import aes, make_labels
>      16 from .layer import Layers
> ---> 17 from .facets import facet_null
>      18 from .facets.layout import Layout
>      19 from .options import get_option
> 
> /usr/local/lib/python3.6/dist-packages/plotnine/facets/__init__.py in <module>()
> ----> 1 from .facet_grid import facet_grid
>       2 from .facet_null import facet_null
>       3 from .facet_wrap import facet_wrap
>       4 from .labelling import label_value, label_both, label_context
>       5 from .labelling import labeller, as_labeller
> 
> /usr/local/lib/python3.6/dist-packages/plotnine/facets/facet_grid.py in <module>()
>       4 from ..utils import match, join_keys
>       5 from ..exceptions import PlotnineError
> ----> 6 from .facet import facet, layout_null, combine_vars, add_missing_facets
>       7 from .facet import eval_facet_vars
>       8 
> 
> /usr/local/lib/python3.6/dist-packages/plotnine/facets/facet.py in <module>()
>      10 from ..utils import cross_join, match
>      11 from ..exceptions import PlotnineError
> ---> 12 from ..scales.scales import Scales
>      13 
>      14 # For default matplotlib backend
> 
> /usr/local/lib/python3.6/dist-packages/plotnine/scales/__init__.py in <module>()
>      77 from .scale_xy import scale_y_timedelta
>      78 # limits
> ---> 79 from .limits import xlim, ylim, lims, expand_limits
>      80 
>      81 
> 
> /usr/local/lib/python3.6/dist-packages/plotnine/scales/limits.py in <module>()
>       6 
>       7 from ..aes import all_aesthetics
> ----> 8 from ..geoms import geom_blank
>       9 from ..scales.scales import make_scale
>      10 from ..exceptions import PlotnineError
> 
> /usr/local/lib/python3.6/dist-packages/plotnine/geoms/__init__.py in <module>()
>       4 
>       5 # geoms
> ----> 6 from .geom_abline import geom_abline
>       7 from .geom_area import geom_area
>       8 from .geom_bar import geom_bar
> 
> /usr/local/lib/python3.6/dist-packages/plotnine/geoms/geom_abline.py in <module>()
>       5 from ..doctools import document
>       6 from ..aes import aes
> ----> 7 from .geom import geom
>       8 from .geom_segment import geom_segment
>       9 
> 
> /usr/local/lib/python3.6/dist-packages/plotnine/geoms/geom.py in <module>()
>       1 from copy import deepcopy
>       2 
> ----> 3 from ..stats.stat import stat
>       4 from ..aes import rename_aesthetics, is_valid_aesthetic
>       5 from ..layer import layer
> 
> /usr/local/lib/python3.6/dist-packages/plotnine/stats/__init__.py in <module>()
>       4 from .stat_bindot import stat_bindot
>       5 from .stat_boxplot import stat_boxplot
> ----> 6 from .stat_density import stat_density
>       7 from .stat_density_2d import stat_density_2d
>       8 from .stat_ecdf import stat_ecdf
> 
> /usr/local/lib/python3.6/dist-packages/plotnine/stats/stat_density.py in <module>()
>       3 import numpy as np
>       4 import pandas as pd
> ----> 5 import statsmodels.api as sm
>       6 
>       7 from ..doctools import document
> 
> /usr/local/lib/python3.6/dist-packages/statsmodels/api.py in <module>()
>       5 from . import regression
>       6 from .regression.linear_model import OLS, GLS, WLS, GLSAR
> ----> 7 from .regression.recursive_ls import RecursiveLS
>       8 from .regression.quantile_regression import QuantReg
>       9 from .regression.mixed_linear_model import MixedLM
> 
> /usr/local/lib/python3.6/dist-packages/statsmodels/regression/recursive_ls.py in <module>()
>      14 from statsmodels.regression.linear_model import OLS
>      15 from statsmodels.tools.data import _is_using_pandas
> ---> 16 from statsmodels.tsa.statespace.mlemodel import (
>      17     MLEModel, MLEResults, MLEResultsWrapper)
>      18 from statsmodels.tools.tools import Bunch
> 
> /usr/local/lib/python3.6/dist-packages/statsmodels/tsa/statespace/mlemodel.py in <module>()
>      15 from .kalman_filter import (KalmanFilter, FilterResults, INVERT_UNIVARIATE,
>      16                             SOLVE_LU)
> ---> 17 import statsmodels.tsa.base.tsa_model as tsbase
>      18 import statsmodels.base.wrapper as wrap
>      19 from statsmodels.tools.numdiff import (_get_epsilon, approx_hess_cs,
> 
> /usr/local/lib/python3.6/dist-packages/statsmodels/tsa/base/tsa_model.py in <module>()
>       1 from statsmodels.compat.python import lrange, long
> ----> 2 from statsmodels.compat.pandas import is_numeric_dtype
>       3 
>       4 import datetime
>       5 
> 
> /usr/local/lib/python3.6/dist-packages/statsmodels/compat/pandas.py in <module>()
>      54     import pandas.tseries.frequencies as frequencies
>      55 except ImportError:
> ---> 56     from pandas.core import datetools
>      57     frequencies = datetools
> 
> ImportError: cannot import name 'datetools'
> ```
I also got the same problem.
that's the version required by statsmodels
`!pip3 install pandas==0.19.*`
After that you can import 
`from pandas import datetools`

**Comment by jakevdp** [comment]
Colab now has statsmodels 0.10.0 and plotnnine 0.5.1 in its default environment.
