### ISSUE TITLE
scale_y_reverse and transformations does not reverse

### ISSUE THREAD

**Issue by TyberiusPrime** [has2k1/plotnine#253]
Example
 ```python
from plotnine import *
import pandas as pd

df = pd.DataFrame({
    'p': [0.1, 0.2, 0.3, 0.4, 0.5],
    'c': ['red','blue','lightblue','purple','green'],
    'x': ['x'] * 5
    
})
g = ggplot(df)
g += geom_point(aes('x','p', color='c'))
g += scale_color_identity()
g += scale_y_reverse(trans='log10')
g += ggtitle('scale_y_reverse')
g
```

![image](https://user-images.githubusercontent.com/1257580/51921174-295eb180-23e7-11e9-8460-d22123866c6a.png)

Looks identical to scale_y_continuous:
![image](https://user-images.githubusercontent.com/1257580/51921228-41363580-23e7-11e9-80b8-6118022ce4b7.png)

**Comment by TyberiusPrime** [comment]
Ok, looking in the code it's clear why this is the case - scale_y_reverse is scale_y_continous(trans='reverse'), and it's this way because that's how ggplot2 does it.

If that is the expected behaviour, scale_y_reverse(trans=anything) should raise an exception.

The documentation of trans on scale_continuous says:
'Name of a trans function or a trans function' - but the naive trans=lambda x: -np.log(10)
does not work. (Reasonable since we probably also need the inverse transform).

But then we should change the documentation to say 'a mizani.transform.trans' object, created e.g. with mizani.transform.trans_new instead of a 'trans function'.

**Comment by TyberiusPrime** [comment]
All right, please check out #254, which is a tiny puppy that fixes this ggplot2 neglect :)

**Comment by has2k1** [comment]
Solution is

```python
+ coord_trans(y='reverse')
```

**Comment by TyberiusPrime** [comment]
Coord_trans will not work for discrete scales according to the ggplot documentation. Does it work in plotnine?

**Comment by has2k1** [comment]
`coord_trans` works for discrete scales, it just may not make sense except for the 'reverse' transform. It should also work in ggplot.

**Comment by TyberiusPrime** [comment]
The ggplot documentation has an unfortunate statement "Transformations only work with continuous values: " which I had misread.

**Comment by has2k1** [comment]
> The ggplot documentation has an unfortunate statement "Transformations only work with continuous values: "

It is an implementation detail, but one that may not change for a long time; by the time the coordinate transformations take place all values being being transformed are numeric. So you can probably apply any transform on "discrete" axes but they may not make much sense except for the reverse transform.
