### ISSUE TITLE
Cannot set axis limits when using a datetime axis

### ISSUE THREAD

**Issue by jghose360** [has2k1/plotnine#259]
```
data_df = pd.melt(raw_data, id_vars="date")
p = ggplot(aes(x="date", y="value", color="...", group="..."), data=data_df)
plot = p + geom_line() + scale_x_datetime(labels=date_format('%m-%d')) + ...
``` 
works fine
If I try to change the y axis limits using `ylim()`, `aes(ymin=y_min, ymax=y_max)` or anything else, it throws this error `TypeError: Discrete value supplied to continuous scale`, presumably, because the x axis is discrete
Is there any straightforward way to fix it? Using any of the `coord_*` functions didn't render the chart properly

**Comment by TyberiusPrime** [comment]
I can not reproduce your issue
```
import datetime
g = ggplot(presidential)
g += geom_point(aes(x='name', y='start', color='party'))
g += scale_y_date(limits=[datetime.date(1980,1,1), datetime.date(2010,1,1)])
g
```
works as you'd expect it to
![image](https://user-images.githubusercontent.com/1257580/52355908-88e63e00-2a33-11e9-81b5-2d4b35e91f5e.png)


(scale_y_date(limits=[datetime.date(1980,1,1), None)]) does not, but that's a different issue)

This works as well for me
```g += coord_cartesian(ylim=[datetime.date(1980,1,1), datetime.date(2010,1,1)])```

**Comment by jghose360** [comment]
x should be a date time axis and y a continuous variable (just add a column of random numbers to the presidential df and you should be able to replicate it)

**Comment by TyberiusPrime** [comment]
I still can not reproduce your issue. 
Please add a minimal example.

![image](https://user-images.githubusercontent.com/1257580/52374680-2b1b1b80-2a5e-11e9-994e-f9cff28e9bd6.png)

**Comment by jghose360** [comment]
You can mark this issue as closed
The y value passed in my code was not a float, hence the error
running `data_df["value] = data_df["value].astype("float")` and converting it from object to float fixed it

**Comment by has2k1** [comment]
@jghose360, can post a minimal example. I think I am missing something! You should not have to convert the column to a float. Plus I think, `xlim` and `ylim` could be a little smart
