### ISSUE TITLE
geom_bar isn't allowing fractional weights

### ISSUE THREAD

**Issue by benlindsay** [has2k1/plotnine#260]
If I try to use fractional weights in a bar chart, plotnine seems to be truncating the weights to integers. For example, If I do this:

```
import pandas as pd
import plotnine as pn
tmp = pd.DataFrame({‘x’: [0, 1], ‘weight’: [1.5, 0.9]})
pn.ggplot(tmp) + pn.geom_bar(pn.aes(x=‘x’, weight=‘weight’))
```
 I get

![image](https://user-images.githubusercontent.com/9361152/52367938-37ca5000-2a1b-11e9-8d1e-11aea94b844a.png)

Whereas if I do something similar in R, like

```
> library(ggplot2)
> ggplot() + geom_bar(aes(x=c(0,1), weight=c(1.5, 0.9)))
```

I get

![image](https://user-images.githubusercontent.com/9361152/52368008-647e6780-2a1b-11e9-81a5-6c71a412d6af.png)

Is there any way to make that match the R functionality? Or let me know if I'm doing something wrong.

Thanks!

**Comment by TyberiusPrime** [comment]
> , plotnine seems to be truncating the weights to integers

yes, yes it does: stat_count, compute_group:
```python
  return pd.DataFrame({'count': count.astype(int),
                             'prop': count / np.abs(count).sum(),
                             'x': x,
                             'width': width})
```

That int cast seems to me to be the culprit - and unnecessary.
@has2k1 what do you think?

**Comment by has2k1** [comment]
@TyberiusPrime, yes that is the problem line. https://github.com/has2k1/plotnine/commit/832e29ff7981b14fd8d14aaba42d3dc0a66d636f is the commit that changed it.

**Comment by benlindsay** [comment]
@has2k1 Thanks for making this change!
