### ISSUE TITLE
How to modify legend title?

### ISSUE THREAD

**Issue by omidnabavi** [has2k1/plotnine#263]
Hi,
I am trying to convert an script written in R to python. For plotting I used your module. Everything is fine except that I cannot change the title of legend. In R and ggplot I use  labs( colour='Mytitle' ). What is the equivalent in plotnine?

**Comment by yimingli** [comment]
It's the same. Would be helpful if you could provide a minimal working example.

**Comment by yimingli** [comment]
Just found that "color" works while "colour" does not. Should file a bug.

**Comment by yimingli** [comment]
https://github.com/has2k1/plotnine/issues/264

**Comment by has2k1** [comment]
Same fix as for #264.
