### ISSUE TITLE
Cannot use logistic regression with stats_smooth

### ISSUE THREAD

**Issue by machow** [has2k1/plotnine#265]
Hey, really incredible work with plotnine!

I noticed recently that stat_smooth can take a custom method (e.g. glm), but since it doesn't pass `**method_args` when statsmodels initializes the glm, I'm not able to specify the family for the glm to use.

Here's the relevant [plotnine code](https://github.com/has2k1/plotnine/blob/97563c50d10deeb2d1c29d9e65e742c148db54ef/plotnine/stats/smoothers.py#L115).

Here's an [example](https://stackoverflow.com/a/17011659/1144523) of a logistic regression w/ stat_smooth in ggplot2

It looks like the `fit` method in the glm will ignore unused keywords, so I wonder if `method_args` could be passed both at model initializing and fitting? Maybe not the cleanest solution--I'm happy to look further into anything, if it's useful.

**Comment by has2k1** [comment]
>Maybe not the cleanest solution

Also because we support methods from different packages even the current state  is not uniform, e.g. for the `gaussian process` the `method_args` are passed at initialisation and not at fitting time. And if we pass all `method_args` all the time some methods will probably complain.

I think we can inspect the method for valid kwargs, and there is a [function](https://github.com/has2k1/plotnine/blob/97563c50d10deeb2d1c29d9e65e742c148db54ef/plotnine/utils.py#L878) in the utils module for that.

Maybe something like;

```python
def separate_method_kwargs(method_args, init_method, fit_method):
    # inspect the methods
    init_kwargs = get_valid_kwargs(init_method, method_args)
    fit_kwargs = get_valid_kwargs(fit_method, method_args)
    # Warn about unknown kwargs
    ...
    return init_kwargs, fit_kwargs
```

**Comment by machow** [comment]
Thanks for your quick response! Seems like a great solution--the one place where it might run into trouble is when the function uses `**kwargs` in its signature, rather than explicitly putting into signature.

In the current implementation, all `kwargs` are passed to fit, so fit can use `**kwargs` in its signature. However, it looks like ultimately it will be a trade-off, since we can't use a single argument in stat_smooth, and allow it to specify args for 2 functions in all cases.

I guess that's not totally true, since the `method_args` dict could allow entries like `{'.fit_kwargs': {...}, '.init_kwargs': {...} }`

IMO If the approach you lay out above appears to work with the most common use cases, then it seems perfect, since people can always specify their own smoother funcs for edge cases.
