### ISSUE TITLE
How to use geom_errorbar()

### ISSUE THREAD

**Issue by MisterBiggs** [has2k1/plotnine#268]
I have the following Python plotnine code:

```python
    ggplot(df)
    + geom_point(aes("Distance", "Force"), size=2)
    + geom_path(aes("xfit", "yfit"))
```
Where Distance, Force, xfit, and yfit are just lists of values from my dataframe.

That produces this plot:

![enter image description here][1]

I am trying to add error bars to all the points. The way to do this seems to be using: `+ geom_errorbar()` which in R with ggplot2 is very straightforward: `geom_errorbar(ymin = Length - yerr, ymax = Length + yerr)`. However, I haven't been able to get it to work in python with plotnine, and there don't seem to be any code examples using errorbars.

[Here is the documentation on the function](https://plotnine.readthedocs.io/en/stable/generated/plotnine.geoms.geom_errorbar.html#plotnine.geoms.geom_errorbar). I didn't find it helpful though.

  [1]: https://i.stack.imgur.com/YIOAo.png

**Comment by TyberiusPrime** [comment]
It's just as straight forward in plotnine, using strings instead of alternative evaluation. Note that you have defined your aes on the geom_point and not on the plot, so you have to tell the error bar about the x values.


```python
from plotnine import *
import pandas as pd
df = pd.DataFrame({"Distance": [1,2,3], 'Force': [4,5.5,6], 'yerr': [0.1, 0.5, 3]})
ggplot(df) + geom_point(aes("Distance", "Force"), size=2) + geom_errorbar(aes(x="Distance", ymin="Force-yerr",ymax="Force+yerr"))
```

![image](https://user-images.githubusercontent.com/1257580/54718321-87438600-4b5a-11e9-94a2-845ac2084f96.png)

**Comment by MisterBiggs** [comment]
Worked like a charm. Doing the math in the quotes is what threw me off. Thanks for the example.
