### ISSUE TITLE
Compatibility issues with python 3.7.2

### ISSUE THREAD

**Issue by Sil68** [has2k1/plotnine#269]
Great product! Kudos!

I'm sporting a python 3.7.2 setup under macOS Mojave, and when trying to generate a plot with

```
(ggplot(df, aes('x', 'y'))
 + geom_point()
 + stat_smooth(method='lm')
 + geom_hline(aes(yintercept=d)))
```

the chart appears along with some warnings

```
/usr/local/pyenv/versions/3.7.2/Python.framework/Versions/3.7/lib/python3.7/site-packages/plotnine/layer.py:517: MatplotlibDeprecationWarning: isinstance(..., numbers.Number)
  return not cbook.iterable(value) and (cbook.is_numlike(value) or
/usr/local/pyenv/versions/3.7.2/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/fromnumeric.py:2389: FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
  return ptp(axis=axis, out=out, **kwargs)
```

**Comment by has2k1** [comment]
These are fixed in https://github.com/has2k1/plotnine/commit/2fdd1c42d0ce6b2414bbb3ed40b835b3c52f1512, though not in a release yet.

**Comment by NeduOrekie** [comment]
Hello.

I just had the same experience working with python kernel 3.7.3 (Error msg: numpy\core\fromnumeric.py:2389: FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead. return ptp(axis=axis, out=out, **kwargs).

Any thoughts?

**Comment by TyberiusPrime** [comment]
Yo can either wait for the next release, or use the github version (pip install https://github.com/has2k1/plotnine/ ).

**Comment by NeduOrekie** [comment]
Much appreciated @TyberiusPrime.
