### ISSUE TITLE
using matplotlib's constrained_layout

### ISSUE THREAD

**Issue by jkrumbiegel** [has2k1/plotnine#273]
I tried enabling constrained_layout via the rcParams for a single subplot with a legend. It gave a warning that the layout collapsed, and there was a big gap between subplot squashed to the left and legend out on the right. Are layouts currently implemented in a way that doesn't work with matplotlib's new geometry manager? I'd really like to be able to use that feature as it works great for me with manually prepared plots (no more overlapping titles, labels, legends, etc), but I wonder whether the internals of plotnine are just incompatible.

**Comment by has2k1** [comment]
> ... but I wonder whether the internals of plotnine are just incompatible.

That is most likely what happened. When it was first merged into Matplotlib, I tried wrapping my head around integrating `constrained_layout` and maybe even have on by default but it would not be an easy task.

**Comment by has2k1** [comment]
There is now a layout manager.
