### ISSUE TITLE
Issue adding treatment line (x-intercept is a date)

### ISSUE THREAD

**Issue by leigh32michael** [has2k1/plotnine#281]
Hi there,

I'm fairly new to R, and am trying to plot a scatterplot with three elements: Time (y-axis), Date (x-axis), and Miles Walked (dots). 

I'd like to add a vertical line at April 8, as this marks the pre-treatment/post-treatment period. However, when I enter the code below, the treatment line doesn't show up. I'm assuming it's something to do with the date format, but appreciate any advice you have. I've also uploaded my data set if that's helpful. Thanks!

**CODE:**
df$Date <- as.Date( df$Date, '%m/%d')
ggplot(data = df, aes(x = Date, y = Wakeup)) +
    geom_point(aes(color = MilesWalked),size=3) +
  geom_vline(xintercept=04/08,linetype="dashed", color="red") +
    xlab("Date") +
  ylab("Date") +
  ggtitle("Distance Walked Before 7am") + 
  theme(
  panel.border = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.line = element_line(colour = "darkgrey"))

[LMdata.xlsx](https://github.com/has2k1/plotnine/files/3268684/LMdata.xlsx)

**Comment by has2k1** [comment]
You posted to the wrong project. Try asking at [stackoverflow.com](https://stackoverflow.com/).
