### ISSUE TITLE
Legend title align only aligns first legend title

### ISSUE THREAD

**Issue by jaybundy** [has2k1/plotnine#282]
I need to make a legend with multiple titles. However, only the first one responds to the title align command.

        evolved_vs_ancestor_plot = (ggplot(data=ACH_phase2_final_update_dataframe, mapping=aes(x='ancestor_value_log10', y='evolved_population_average_value_log10',  color='factor(ancestor_run_length)', shape='factor(ancestor_seed)'))
        + geom_point()
        + scale_color_discrete(h=0.01, l=0.6, s=0.65, color_space='hls')
        + geom_abline( data=None, stat='identity', position='identity',
        na_rm=True, inherit_aes=False, show_legend=None, color='black', linetype='solid')
        + facet_wrap('~replicate_environment')
        + theme(figure_size=(12, 6),
        legend_title_align= 'center',
        text=element_text(fontproperties=text_properties),
        title=element_text(margin= {'b': 20}, fontproperties=plot_title_properties),
        legend_title= element_text(fontproperties=legend_title_properties), 
        plot_background=element_rect(fill='white'),
        axis_text_x=element_text(margin={'t':6}, color='gray', size=8),
        axis_text_y=element_text(margin={'r':6}, color='gray', size=8),
        axis_title_x=element_text(margin= {'t': 12}, fontproperties=axis_title_properties), 
        axis_title_y=element_text(margin= {'r': 12}, fontproperties=axis_title_properties),
        axis_ticks_major_x=element_blank(),
        axis_ticks_major_y=element_blank(),
        rect=element_rect(color='white', size=3, fill='white'),
        panel_grid_major_y=element_line(linetype='solid', color='gray', size= .3))
        +labs(title='Evolved vs Ancestor  %s After 10000 Updates ' % (trait_label.title()),  color='Depth', shape= 'Lineage', x=  'Log\u2081\u2080 Ancestor  %s' % (trait_label.title()), y= 'Log\u2081\u2080 Evolved Average %s' % (trait_label.title())))
        print(evolved_vs_ancestor_plot)

<img width="1127" alt="Screen Shot 2019-06-11 at 4 31 57 PM" src="https://user-images.githubusercontent.com/9137434/59304559-7fc9df80-8c66-11e9-8f23-54b4ba1d5c10.png">

**Comment by has2k1** [comment]
I think you need to take a look at [legend_box_just](https://plotnine.readthedocs.io/en/stable/generated/plotnine.themes.themeable.legend_box_just.html)
