### ISSUE TITLE
geom_boxplot() doesn't allow disabling out outliers

### ISSUE THREAD

**Issue by ying-w** [has2k1/plotnine#284]
In r, you can pass in `outlier.shape = NA` to [disable outliers from being plotted](https://github.com/tidyverse/ggplot2/issues/2505). Can this functionality be added to plotnine?

Using version 0.5.1

**Comment by has2k1** [comment]
You can disable outliers from being plotted with `outlier_shape=''`

**Comment by Yaoyx** [comment]
Hello,

I tried this , but it return an error message "geom_point got an unknown shape"

**Comment by has2k1** [comment]
@Yaoyx, make sure you are using the latest version of plotnine.

**Comment by Yaoyx** [comment]
> @Yaoyx, make sure you are using the latest version of plotnine.

Thank you!
