### ISSUE TITLE
hjust/vjust in annotate

### ISSUE THREAD

**Issue by ying-w** [has2k1/plotnine#287]
Would it be possible to add hjust/vjust capability to annotate()? It currently exists only in geom_text

**Comment by has2k1** [comment]
Please include a minimal example of what you are trying to achieve.

**Comment by ying-w** [comment]
I can do something like this in R but isn't supported in plotnine

`ggplot(iris, aes(Petal.Width, Petal.Length)) + geom_point() + annotate("text", x=2, y=2, label="sample text", hjust="left")`

**Comment by has2k1** [comment]
Use `ha="left"`, there is a but in handling the ggplot2 names `vjust` and `hjust`.

**Comment by ying-w** [comment]
is it just copying over

```py
        # Accomodate for the old names
        if 'hjust' in kwargs:
            kwargs['ha'] = kwargs['hjust']

        if 'vjust' in kwargs:
            kwargs['va'] = kwargs['vjust']
```

from `geom_text` to `annotate`?

**Comment by has2k1** [comment]
The problem is that `vjust` and `hjust` parameters are not part of the API for `geom_text`. I have fixed it in my local branch i.e. `kwargs['ha'] = kwargs.pop('hjust')`

**Comment by RSelvaratnam** [comment]
> Use `ha="left"`, there is a but in handling the ggplot2 names `vjust` and `hjust`.

I guess this from the matplotlib analogy where you can have something like this:

`plt.annotate("some text here", xytext=(2, 50), textcoords='data', ha='left', color = 'red')
`
But yest, the suggestion to use ha = "left" works.
