### ISSUE TITLE
control ymax for each facet?

### ISSUE THREAD

**Issue by nextgenusfs** [has2k1/plotnine#289]
Thanks for `plotnine` its quite handy.  I'm trying to get a little bit more control over the y-axis on each facet panel. Basically I'd like limit the y-axis for each facet, ie a ymax=100. 
```
import plotnine as p9
plot = p9.ggplot(data=df, mapping=p9.aes(x='start', y='coverage'))
plot += p9.geom_line(size=0.5, show_legend=False, color='red')
plot += p9.facet_wrap('name', ncol=1, scales='free_y')
```
In this particular data, I'd like to set a maximum y-axis value (even if data in a particular location is greater than that ymax).  There are several facets so I need to set the scale so that the figure is readable and highlights the portion of the data I'm interested in.

I've read a little bit in ggplot that people have been able to get this to work by creating a separate dataframe with essentially the ymin/ymax values and then plot that with `geom_blank()`.  I've tried to to that without success.  The following errors out (df2 contains each 'name' for the facets with a ymin and ymax value in the dataframe):
```
plot = p9.ggplot(data=df, mapping=p9.aes(x='start', y='coverage'))
plot += p9.geom_line(size=0.5, show_legend=False, color='red')
plot += p9.facet_wrap('name', ncol=1, scales='free_y')
plot += p9.geom_blank(data=df2, mapping=p9.aes(x='ymin', y = 'ymax'))
```
Thanks for any help/advice in advance.

**Comment by has2k1** [comment]
Not yet released, but with the current master you can do

```python
+ scale_y_continuous(limits=(None, 100))
```

**Comment by nextgenusfs** [comment]
Okay, so if I know the ymax I want for each facet then I would pass that to limits? i.e there are 3 facets, then would look something like?
```
+ scale_y_continuous(limits=(10, 100, 1000))
```
This seems to fail, so I must not have syntax correct.   I've also the following also errored:
```
+ scale_y_continuous(limits=[[0,10], [0,100], [0,1000]])
```

**Comment by has2k1** [comment]
You cannot set limits per facet. The solution is to manipulate the data before plotting it.

**Comment by nextgenusfs** [comment]
Okay, thanks @has2k1
