### ISSUE TITLE
tag

### ISSUE THREAD

**Issue by JackNelson** [has2k1/plotnine#290]
The tag argument does not show up on plots as it does in ggplot with plotnine.labs()

**Comment by has2k1** [comment]
Yes tags are not supported. We have a problem with stuff that falls outside the main plotting area. This is all part of #46.

**Comment by JackNelson** [comment]
I guess I don't fully understand the complexity of the issue.  There appears to be solutions within matplotlib using text() with the transform parameter.
references:
(https://stackoverflow.com/questions/42435446/how-to-put-text-outside-python-plots) 
(https://stackoverflow.com/questions/45861947/how-to-insert-the-text-below-subplot-in-matplotlib)

This issue was sparked from the inability to watermark a plot with a name/data somewhere on said plot within plotnine.  I am unable to use caption and subtitle (#177) and I also am unable to dynamically use geom_label, geom_text with the inability to plot based on percent relative to plot (x=[0-1], y=[0-1]) or even extract the automated plot coordinates to calculate x,y coordinates in a function.  If there is this functionality and I'm unaware of it please let me know.  I've searched the internet extensively over the past couple of months and have been unable to find a solution.

**Comment by has2k1** [comment]
> I guess I don't fully understand the complexity of the issue.

Have a look at code from the two links you have posted

```python
# 1.
plt.subplots_adjust(left=0.25)

# 2.
ax1.text(0.5,-0.1, "(a) my label", size=12, ha="center", 
         transform=ax1.transAxes)
ax2.text(0.5,-0.1, "(b) my other label", size=12, ha="center", 
         transform=ax2.transAxes)
```

Those two snippets have "magic numbers" that you have to fidget with i.e `0.25` and `0.5, -0.1`.  For different sizes of the figure, plot panels, fonts, font sizes and text lengths, those numbers will be different. It is not feasible to compute those numbers; that is the source of the complexity.

For example, [1](https://github.com/has2k1/plotnine/blob/e647ef965b20a59695d675e1d5cda6d6a74a7df3/plotnine/facets/facet_null.py#L65-L67), [2](https://github.com/has2k1/plotnine/blob/e647ef965b20a59695d675e1d5cda6d6a74a7df3/plotnine/facets/facet_wrap.py#L196-L215), [3](https://github.com/has2k1/plotnine/blob/master/plotnine/facets/facet_grid.py#L205-L223), [4](https://github.com/has2k1/plotnine/blob/e647ef965b20a59695d675e1d5cda6d6a74a7df3/plotnine/ggplot.py#L559-L603), [5](https://github.com/has2k1/plotnine/blob/e647ef965b20a59695d675e1d5cda6d6a74a7df3/plotnine/ggplot.py#L526-L546), [6](https://github.com/has2k1/plotnine/blob/e647ef965b20a59695d675e1d5cda6d6a74a7df3/plotnine/ggplot.py#L440-L494) is all code that deals placing stuff outside the plotting area. It is brittle and I dread touching it. Try `+ facet_grid(scales='free')` and you will notice a case we don't even deal with yet; it requires user intervention.

However if you really need tag/annotations/watermarks for finish up plots, you can drop into Matplotlib.

```python
p = ggplot() + ... + theme(subplots_adjust={...})
fig = p.draw()
axs = fig.get_axes()

# Do whatever you want
for ax in axes:
    ax.text(...)
```

Use [subplot_adjust](https://plotnine.readthedocs.io/en/stable/generated/plotnine.themes.themeable.subplots_adjust.html#plotnine.themes.themeable.subplots_adjust) to make space as you wish.
