### ISSUE TITLE
cannot add smooth line

### ISSUE THREAD

**Issue by DeLaRiva** [has2k1/plotnine#291]
I would like to add a smooth line through a scatter plot, so far I'm aiming at two solutions:

```
(ggplot(A_phsA, aes('timestamp', 'A_phsA'))
    + geom_point(color = 'blue')
    + xlab("2018 - 2019")
    + ylab("Phase current A [A]")
    + scale_x_datetime(breaks=date_breaks('1 month'), labels=date_format('%m %Y'))
    + geom_line(stat="smooth", method="loess", alpha=0.7)
    + theme(figure_size=(11, 6), axis_text_x=element_text(rotation=45))
)
```

```
(ggplot(A_phsA)
    + aes('timestamp', 'A_phsA') 
    + geom_point(color = 'blue')
    + xlab("2018 - 2019")
    + ylab("Phase current A [A]")
    + scale_x_datetime(breaks=date_breaks('1 month'), labels=date_format('%m %Y'))
    + geom_smooth(alpha = 0.1)
    + theme(figure_size=(11, 6), axis_text_x=element_text(rotation=45))
)
```
but none is working. What am I doing wrong?

![plot](https://user-images.githubusercontent.com/29283287/61115128-0fdf8c80-a492-11e9-8c98-e9cba61a8f5a.JPG)

**Comment by has2k1** [comment]
I cannot run the code, so I cannot tell what is wrong. Try changing the smoothing function (e.g. `method='lm')`, or with a smaller sample of the data.

**Comment by jtrakk** [comment]
Here's a minimal example.

```py
import pandas as pd
import plotnine as p9 

data = pd.DataFrame({'date': ['1990-01-01', '1995-01-01', '2000-01-01'], 'num': [1, 2, 5]})
(
    p9.ggplot(p9.aes(x='date', y='num',), data=data) 
    + p9.geom_point() 
    + p9.geom_smooth(method='lm', color='red')
    + p9.theme(axis_text_x = p9.element_text(angle = 90, hjust = 1)) 
    + p9.scale_x_date(date_breaks='5 years')
)   
```

![image](https://user-images.githubusercontent.com/43392409/65395145-b4603380-dd4b-11e9-85ef-80afb0537d44.png)

**Comment by has2k1** [comment]
@jtrakk, thanks. That is helpful. As a work around, you can set the group variable manually.

```python
 p9.ggplot(p9.aes(x='date', y='num', group=1), data=data)
...
```

The issue is that the date column is being identified as discrete, so every point is in a group of it's own. This is a bug.

**Comment by jtrakk** [comment]
I see. In that case it would be nice to have a helpful exception message instead of silent failure.
