### ISSUE TITLE
Order bar charts

### ISSUE THREAD

**Issue by Akaban** [has2k1/plotnine#295]
Hello,

I would like to reopen issue [94](https://github.com/has2k1/plotnine/issues/94) I don't think it's really user friendly to not include automatic sorting in geom_bar function. If I understand correctly we need to make a pandas.Categorical each time we want to define the order of our graph. 

That's something I find really painful. Can't we implement a keyword_argument sort_by="xxxx" in geom_bar?

I can do the MR if it's not too much complicated, I don't know plotnine code as of now :)

Thanks for the answer

By the way thanks for this incredible package, easily the best python package for graphs available :)

**Comment by Akaban** [comment]
I think we should at least respect the order of the dataframe, it does not seem to be the case today

**Comment by Akaban** [comment]
For readers just so you know I found a "hack" to get cool bar plots without much effort.

1/ Sort your dataframe as you wish
2/ Compute a column rank which indicates the rank of the line (you may want to do this with group by)
3/ Compute new string column `df["column"] = df["rank"].map(chr) + " - " + df["column"]`

:) I would still have preferred an explicit way to do this through plot nine

**Comment by TyberiusPrime** [comment]
Plotnine has inherited this from ggplot2, which respects the sort order of the datatypes involved, not the order of the data points. 
I actually think that's a perfectly valid point of view that leads to fewer unexpected changes in plots.

Turning a column in a sorted dataframe into a categorical isn't that bad, though a bit verbose:
```df.assign(column = pd.Categorical(df.column, df.column))```.

Guess I'll be adding a convenient method for that in my dppd library...

**Comment by has2k1** [comment]
Sorting is standard and is handled automatically by the `scale` depending on the datatype (mentioned by @TyberiusPrime) , not the `geom`. Plus the scales are independent, the x scale knows nothing about any other column!
