### ISSUE TITLE
Update on conda/pypi without deprication warnings

### ISSUE THREAD

**Issue by RavagingCare** [has2k1/plotnine#300]
The last update on conda/pypi is almost 10 month old. With that version I get several deprecation warnings. Even if I pip install from github, some deprecation warnings remains. This suggests (to me) that the developers are not very responsive and show lack of commitment to this project. Earlier projects of bringing R's ggplot2 on python have failed. Is this also moving in the same direction?

Need clear answers, so that Data Scientists may not "waste" time developing visualization on this and more to other stable packages.

**Comment by has2k1** [comment]
@RavagingCare, thanks for your interest in the direction of the project. It is still actively developed and a release is in the works.

**Comment by TyberiusPrime** [comment]
The release has now happend. Thank you, @has2k1
