### ISSUE TITLE
layout issue in readthedocs

### ISSUE THREAD

**Issue by TyberiusPrime** [has2k1/plotnine#303]
![image](https://user-images.githubusercontent.com/1257580/63504372-b7100480-c4d1-11e9-9e0d-39c786825f9b.png)

Note the missing space after "breaks" - this is just a random example,
it's apparently in all the API docs.

Unfortunately, I can't reproduce it with 'make html' locally.

**Comment by has2k1** [comment]
I saw this in [mizani](https://mizani.readthedocs.io/en/stable/breaks.html) when I released last week. It is not there anymore. I checked to make sure the plotnine [dev](https://plotnine.readthedocs.io/en/dev/generated/plotnine.ggplot.html) is not affected and it wasn't. Now, after the release it is.

I think it is a browser cache issue, please confirm. I do not see it in incognito mode.

**Comment by TyberiusPrime** [comment]
Yes it was a browser caching issue. My apologies, should've caught on when I couldn't reproduce it locally!
