### ISSUE TITLE
Please provide some example with plain Python

### ISSUE THREAD

**Issue by CdeMills** [has2k1/plotnine#307]
Hello,
all the examples and tutorial are based on iPython:
%matplotlib inline
# start generating some fancy graph

How can I  produce graphs in a simple python script ?
 f, ax = plt.subplots(figsize=(8, 6)
# generate some graph
plt.show()

Thanks

**Comment by TyberiusPrime** [comment]
like this
```python
from plotnine import *
from plotnine.data import mtcars
p = ggplot(mtcars, aes(x='hp', y='mpg))
p = p + geom_point()
p.save("output.png")
```

**Comment by CdeMills** [comment]
OK, thanks. Is there something similar to plt.show() ?

Thank you
Pascal

**Comment by has2k1** [comment]
> OK, thanks. Is there something similar to plt.show() ?

```python
print(p)
```
