### ISSUE TITLE
specify aes(linetype) in the data?

### ISSUE THREAD

**Issue by jwhendy** [has2k1/plotnine#309]
I'm guessing this is something like applying a factor to the data vs. using the data itself, but wondered if you could confirm:
```
test = pd.DataFrame({'x': [0, 0], 'y': [0, 0], 'xend': [1, 2], 'yend': [2, 3], 'linetype': ['dashed', 'solid'], 'colour': ['red', 'blue']})
ggplot(test, aes(x='x', y='y', xend='xend', yend='yend', linetype='linetype', colour='colour')) + geom_segment()
```

Expected: the linetype and colour would match the entries in the dataframe vs. how they are (reversed).

![grab_2019-08-26_170224](https://user-images.githubusercontent.com/379357/63726596-52cba880-c823-11e9-80b3-5f11cdcf3a40.png)

Any way to accomplish this, or will I always need to manually map some `factor(['foo', 'bar'])` to e.g. `scale_linetype`, even if the assignments already match?

**Comment by TyberiusPrime** [comment]
If you want to use the data literally, you'll need an identity scale such as ```scale_linetype_identity```
