### ISSUE TITLE
Strip text box doesn't adapt to angle

### ISSUE THREAD

**Issue by essicolo** [has2k1/plotnine#31]
A ggplot worth a thousand words.

```
import pandas as pd
from sklearn import datasets
from plotnine import *
iris = datasets.load_iris()

iris_df = pd.concat([pd.DataFrame(iris.data, columns=iris.feature_names),
                     pd.DataFrame(iris.target, columns=['Species'])], axis=1)
iris_m = iris_df.melt(id_vars=['Species'])
iris_m.Species = iris_m.Species.astype('category')

ggplot(iris_m, aes(x='value')) +\
    facet_grid('variable ~ .', scales='free') +\
    geom_histogram(aes(fill='Species'), bins=30) +\
    theme(strip_text_y=element_text(angle=0))
```
![telechargement 2](https://user-images.githubusercontent.com/5118227/27942231-514347d0-62a3-11e7-997c-4307d46f8d67.png)

Similar behavior with `strip_text_x`.

**Comment by has2k1** [comment]
That is how it works, angle *only* applies to `element_text`. You can change the properties of the box through `strip_background_y=element_rect(...)`.

However, if you really want to do crazy stuff then you will have to fidget around with hidden parameters. e.g

```python
theme(strip_text_y=element_text(angle=0, x=1.12),
      strip_background_y=element_rect(x=1, y=.5, width=0.25, height=0.25))
```

**Comment by essicolo** [comment]
Good, but it is still different from ggplot2.

```
library(ggplot2)
library(reshape2)
data(iris)
iris_m = melt(iris)
ggplot(iris_m, aes(x=value)) +
  facet_grid('variable ~ .', scales='free') +
  geom_histogram(aes(fill=Species), bins=30) +
  theme(strip.text.y=element_text(angle=0))
```

![rplot01](https://user-images.githubusercontent.com/5118227/28022107-245df5c8-6558-11e7-9f0e-2fabbcab5f00.png)

**Comment by has2k1** [comment]
Yeah it is different. The key issue is actually much deeper, Matplotlib (the backend) does not have a layout manager so placing stuff around the axes is a real pain.
