### ISSUE TITLE
geom_violin fails when the same values is often in the data

### ISSUE THREAD

**Issue by brechtmann** [has2k1/plotnine#317]
plotnine gives unclear error and shows no violin plot, when a values appears to often in the to be plotted variable.

See the following example code:
```
import plotnine as p9
import pandas as pd
import numpy as np

x = pd.DataFrame(data = np.array([np.ones(10), np.repeat(['A', 'B'], 5)]).T, columns=['ones', 'cat'])

p9.ggplot(x, p9.aes('factor(cat)', 'ones')) + p9.geom_violin()
```
Executing this example gives the following error:
`plotnine.exceptions.PlotnineError: 'Width not defined. Set with `position_dodge(width = ?)`'`

Running the same example in R ggplot2 produces a plot:
```
library(ggplot2)
library(data.table)

 x = data.table(ones = rep(1, 10), cat = rep(c('A', 'B')))
ggplot(x, aes(cat, ones)) + geom_violin()
```

The same happens, when there is only a small fraction of other values in the data.

Thanks!

**Comment by TyberiusPrime** [comment]
Does this happen with the current release or the github master?

**Comment by brechtmann** [comment]
It seems to be a probablem in the density estimation. A similar error happens for:
```
p9.ggplot(x, p9.aes('factor(cat)', 'ones')) + p9.geom_density()
```
