### ISSUE TITLE
legend_key not impacting theme

### ISSUE THREAD

**Issue by darothen** [has2k1/plotnine#32]
Yesterday I wrote a blog post creating a standard visualization from my research in plotnine; the [final plot / code is available here](http://www.danielrothenberg.com/blog/2017/Jul/declarative-visualization-in-python-update/#Putting-it-all-together). Everything works great, but there's one thing that I couldn't get to work: the **legend_key** element I passed to the final call to `theme()` didn't actually change the plot aesthetics. My understanding is that the way I wrote the code, i.e.

``` python
legend_key=element_rect(fill='white', color='white')
```

should've made each of the line marker glyphs in the legend have a white background. But, they remained grey. Is this a mis-understanding on my part, or a glitch?

**Comment by has2k1** [comment]
I saw the post and immediately noticed the grey background in the legend keys. First, the background of the keys defaults to the plot background, but since `theme_seaborn` is entirely specified through `rcParams` and not theme elements there is a glitch. I think having white as a default will lessen the impact.

This

```python
 + theme_seaborn(style='ticks', context='talk', font_scale=0.75)
 + theme(legend_key=element_rect(fill='white', color='white'))
```
should work. Did you add `theme` after `theme_seaborn`?

**Comment by has2k1** [comment]
> Sometimes there are weird edge cases that cause plotnine plots to break (although as an important note, resetting your kernel tends to fix them. I have no idea why this happens and I can't faithfully reproduce it), and they arise from complicated layering of plot elements

Any more on this? I do complicated layering without issues.

**Comment by darothen** [comment]
Hi @has2k1, I do call `theme_seaborn` before `theme` in the manner you suggest, and it doesn't resolve the issue. Explicitly setting the plot_background doesn't work either, before or after the call to `theme_seaborn`. [Here is a gist with the original notebook and the data - just change the path in the first cell](https://gist.github.com/darothen/73234ceed9aa07d73f9c41dec5e97609).

On the layering issue, like I mentioned, I haven't been able to consistently reproduce any issues, but if I stumble across an MWE that works, I'll be sure to post it.

**Comment by has2k1** [comment]
Sorry I meant 'panel_background'.

**Comment by darothen** [comment]
Nope, that doesn't fix the legend key background either.

**Comment by has2k1** [comment]
Ahh I have seen this before. The confidence interval markers for `stat_smooth` have a default grey background and that is showing up in the legend. Try `stat_smooth(se=False)`.

**Comment by darothen** [comment]
Aha! That did the trick. Is there a way to clip the way the confidence interval markers are drawn so they don't 100% fill the legend_key box? That way we would have some feedback on how theming is changing that element.

**Comment by has2k1** [comment]
That is what I immediately thought about.
