### ISSUE TITLE
automatic ticks distribute unexpectedly in log scale

### ISSUE THREAD

**Issue by katosh** [has2k1/plotnine#320]
Using `scale_y_log10` for my data `df` produces unhelpful ticks as in this example:
```
pl = (pn.ggplot(pn.aes('iteration', 'loss', color='lable'), df)
      + pn.geom_line(alpha=.6) + pn.scale_y_log10())
pl.draw();
```
![image](https://user-images.githubusercontent.com/4857068/66646054-5aa1a980-ec25-11e9-8f3d-28ed1c8d77e4.png)

Admittedly, the range of `loss` is rather large and goes up to `1e+171`. Setting the ticks manually works better but not as satisfying as the automatic placement usually works and the minor ticks also seem off:
```
def breaks(limits):
    return np.geomspace(limits[0], limits[1], 10)
pl = (pn.ggplot(pn.aes('iteration', 'loss', color='lable'), df)
      + pn.geom_line(alpha=.6) + pn.scale_y_log10(breaks=breaks))
pl.draw();
```
![image](https://user-images.githubusercontent.com/4857068/66646045-51184180-ec25-11e9-9289-e54dcdb05d68.png)

I used plotine from the current master branch 19f3172a77996860cf409000e9f687a666e39b1f and `df.loss.min() == 722399634.4616433`, `df.loss.max() == 4.995598277152082e+170`.

**Comment by katosh** [comment]
Here is a small example self-contain example:
```
import pandas as pd
from plotnine import *

df = pd.DataFrame({'x':[1, 2], 'y':[1e20, 1e140]})
pn.ggplot(pn.aes('x', 'y'), df) + pn.scale_y_log10()
```
![image](https://user-images.githubusercontent.com/4857068/66662406-09a3ac80-ec49-11e9-9759-3b5dffdf3efd.png)

So the ticks distribute unexpectedly when the lower bound is very large. Matplotlib has a nicer distribution of ticks:
```
import matplotlib.pyplot as plt

_, ax = plt.subplots(1, 1)
ax.plot([1, 2], [1e20, 1e140])
ax.set_yscale('log')
```
![image](https://user-images.githubusercontent.com/4857068/66662549-538c9280-ec49-11e9-9f40-84f51785de65.png)

**Comment by has2k1** [comment]
This is due to an overflow in mizani.breaks.log_breaks.

```python
10 ** np.arange(10, 15)  # good
10 ** np.arange(20, 25)  # overflow
```

**Comment by katosh** [comment]
This might help:
```
>>> 10. ** np.arange(20, 25)
array([1.e+20, 1.e+21, 1.e+22, 1.e+23, 1.e+24])
```
