### ISSUE TITLE
Name of variables with spaces in facet functions (grid or wrap)

### ISSUE THREAD

**Issue by juanramonua** [has2k1/plotnine#321]
There is some way to pass parameters with names of variables with blank spaces. When function `aes()` is used there is no problems. 

`facet_grid( ' Age of mother ~ hospital ')`

or 

`facet_grid(  ['Age of mother',  'hospital')`

The examples do not work. I'm sure Age_of_mother works correctly.

Thanks for this version of ggplot in Python.

**Comment by has2k1** [comment]
Please post a recent version of plotnine. I recall that issue to have been fixed. Or post minimum reproducible example of the bug.
