### ISSUE TITLE
adjust_text fails with placing arrows

### ISSUE THREAD

**Issue by Hoeze** [has2k1/plotnine#322]
Hi, I tried to label some values with geom_text but the labels were overlapping. Therefore, I tried to use `adjust_text`:
![image](https://user-images.githubusercontent.com/1200058/67013009-ad320880-f0f2-11e9-96eb-228d5c02513b.png)

data: 
![image](https://user-images.githubusercontent.com/1200058/67012843-6217f580-f0f2-11e9-8f0b-10c52b3aeb25.png)

source code:
```python
plot = pn.ggplot(df.query('x_is_finite & y_is_finite & outlier_class != "none"'), pn.aes(x=df.columns[0], y=df.columns[1], color='outlier_class', label="gene"))
plot = plot + \
    pn.coord_fixed() + \
    pn.xlab(df.columns[0]) + \
    pn.ylab(df.columns[1]) + \
    pn.ggtitle(str(x.individual.values)) + \
    pn.scale_color_cmap_d("tab10") + \
    pn.geom_text(show_legend=False, adjust_text = {
#         'expand_points': (2, 2),
        'arrowprops': {
            'arrowstyle': '->',
            'color': 'red'
        }
    })
```

**EDIT**
`pn.__version__`: 0.6.0
`adjusttext` installed from conda (`conda-forge/noarch::adjusttext-0.7.3.1-py_0`)

**Comment by mgoadric** [comment]
I also experienced the same behavior.
