### ISSUE TITLE
How order the "color legend"

### ISSUE THREAD

**Issue by geoffreyp** [has2k1/plotnine#323]
Hello, is it possible to reorder the legend ? The current order is alphabetic but "values" are numbers, so I want an ascending order.
In the dataframe, the column "values" have to be strings to use the color parameter, I can't use integers.

The code :
`ggplot(data=df) + aes(x='algo', y='hv', color='values') `

The figure :
<img width="467" alt="image" src="https://user-images.githubusercontent.com/9945579/67087912-348b8480-f1a4-11e9-8445-01d1625ea8ad.png">

Thank you

**Comment by TyberiusPrime** [comment]
You have to turn your data into a pandas.Categorical
```
df2 = df.assign(values = pd.Categorical(df['values'], [optional ordered, unique list showing value order])
```
Don't think you need to provide the optional list when dealing with 
integers.

**Comment by geoffreyp** [comment]
Its work, thank you !

**Comment by cyapur** [comment]
Can you explain how it works a little bit? Because when I use `pd.Categorical()` it changes the order of the legend color, but it doesn't change the order of the dataframe. So, where this "legend color order" is stored in the dataframe before plotting it?

**Comment by TyberiusPrime** [comment]
> So, where this "legend color order" is stored in the dataframe before plotting it?
in the categories/levels of the categorical. That second parameter defines the level values used and thereby the ordering in plotting.

**Comment by cyapur** [comment]
> > So, where this "legend color order" is stored in the dataframe before plotting it?
> > in the categories/levels of the categorical. That second parameter defines the level values used and thereby the ordering in plotting.

I don't understand. Are you saying that a categorical column of a dataframe has some kind of levels like the `levels` of a `factor `in R? If that is what you are saying, how can I see those 'levels'? If you are not saying that, what's the difference between ordering with `sort_values()` and ordering with `pd.Categorical()` when trying to order the color legend?

**Comment by TyberiusPrime** [comment]
It is 'exactly' like factors and levels in R.

You can access the categorical attributes with df.column.cat.
See https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Categorical.html
