### ISSUE TITLE
Text may disappear with adjust_text

### ISSUE THREAD

**Issue by jeroenjanssens** [has2k1/plotnine#324]
I'm trying to recreate the fourth figure in [section 28.3 from R for Data Science](https://r4ds.had.co.nz/graphics-for-communication.html#annotations). The ggplot2 code is as follows:

```r
class_avg <- mpg %>%
  group_by(class) %>%
  summarise(
    displ = median(displ),
    hwy = median(hwy)
  )

ggplot(mpg, aes(displ, hwy, colour = class)) +
  ggrepel::geom_label_repel(aes(label = class),
    data = class_avg,
    size = 6,
    label.size = 0,
    segment.color = NA
  ) +
  geom_point() +
  theme(legend.position = "none")
```

![](https://d33wubrfki0l68.cloudfront.net/7e8337dff68b63ffdc82a6e90d97aee522352803/6d5cb/communicate-plots_files/figure-html/unnamed-chunk-10-1.png)

In plotnine, the text disappears when using `adjust_text`:

```python
from plotnine import *
from plotnine.data import mpg

class_avg = mpg\
.groupby("class")["displ","hwy"].median()\
.reset_index()

ggplot(mpg, aes("displ", "hwy", colour="class")) +\
geom_label(aes(label="class"), data=class_avg, size=16, label_size=0, adjust_text={'expand_points': (0, 0)}) +\
geom_point() +\
theme(legend_position="none")
```

![download](https://user-images.githubusercontent.com/1368256/67103546-a4f6cd80-f1c5-11e9-85fa-0c7e1fd30114.png)

When switching the order of `geom_point()` and `geom_label()` the text remains:

```python
ggplot(mpg, aes("displ", "hwy", colour="class")) +\
geom_point() +\
geom_label(aes(label="class"), data=class_avg, size=16, label_size=0, adjust_text={'expand_points': (0, 0)}) +\
theme(legend_position="none")
```

![download (1)](https://user-images.githubusercontent.com/1368256/67103604-c061d880-f1c5-11e9-9acc-e40236d5de1d.png)

And interestingly enough, when adding another layer with `geom_point()`, the text remains and the points are on top, which resembles the original figure made in R.

```python
ggplot(mpg, aes("displ", "hwy", colour="class")) +\
geom_point() +\
geom_label(aes(label="class"), data=class_avg, size=16, label_size=0, adjust_text={'expand_points': (0, 0)}) +\
geom_point() +\
theme(legend_position="none")
```

![download (2)](https://user-images.githubusercontent.com/1368256/67103645-d8395c80-f1c5-11e9-9a2b-b3722369dfcd.png)

So there's a work-around, but this might still be something worthwhile fixing. Hope this helps.

Thank you for this wonderful package.

Best,

Jeroen

**Comment by has2k1** [comment]
This will likely require an API change to fix. According to the `adjust_text` documentation,  `geom_text` or `geom_label` should be the last geom for it to work properly! We need to make a provision for that.

**Comment by chrisjcameron** [comment]
If you are redesigning the API at some point, It would be helpful to be able tell adustText to ignore some layers so you could have two different text layers where the top layer adjustText applies only within that geom. Alternatively, if you have 3 or more text layers, you might want adjustText to apply to two levels but ignore the third.
