### ISSUE TITLE
nudge_x and nudge_y breaking bar plot with position='fill'

### ISSUE THREAD

**Issue by mandoir** [has2k1/plotnine#326]
I'm using plotnine in a Python notebook on the Azure Databricks platform (Spark 2.4).

I have a dataset with -- for these purposes -- three related categorical variables. I am trying to visually represent the relative frequency of one of them (`vs`) given a second variable with three groups (`cyl`) and stratified by the last variable with two groups (`am`). I prefer to use the relative frequency because the absolute frequency (counts) of `vs` are scaled differently across the `cyl` groups.

This is my current code (separately, I am working out the best way to get the % label by group, since currently it is calculating the proportion of `vs` across all `cyl` and not just within each `cyl` group, but I'm leaving it in to complete the example):

```
from plotnine.data import mtcars

g = (ggplot(mtcars, aes('factor(cyl)', fill = 'factor(vs)'))
         + geom_bar(position = 'fill')
         + scale_y_continuous(labels=lambda l: ["%d%%" % (v * 100) for v in l])
         + facet_wrap('am')
         + geom_text((aes(label = 'stat(count)')),
                    stat = 'count',
                    size=8, 
                    position = 'fill',
                    nudge_x=-0.3, 
                    nudge_y=-0.1,
                    va = 'top')
         + geom_text((aes(label = 'stat(prop)*100', group = 'vs')), # This isn't currently giving me the right % share
                    stat = 'count',                               
                    format_string = '({:.1f}%)',
                    size=8, 
                    position = 'fill',
                    nudge_x=0.3, 
                    nudge_y=-0.1,
                    va = 'top')
        )
```
The problem is that the inclusion of either `nudge_x` or `nudge_y` completely does away with the placement from `position = 'fill'`. I haven't come across any documentation where that would be intentional. If I ignore them for now:

```
from plotnine.data import mtcars

g = (ggplot(mtcars, aes('factor(cyl)', fill = 'factor(vs)'))
         + geom_bar(position = 'fill')
         + scale_y_continuous(labels=lambda l: ["%d%%" % (v * 100) for v in l])
         + facet_wrap('am')
         + geom_text((aes(label = 'stat(count)')),
                    stat = 'count',
                    size=8, 
                    position = 'fill',
  ##                  nudge_x=-0.3, 
  ##                  nudge_y=-0.1,
                    va = 'top')
         + geom_text((aes(label = 'stat(prop)*100', group = 'vs')), # This isn't currently giving me the right % share
                    stat = 'count',                               
                    format_string = '({:.1f}%)',
                    size=8, 
                    position = 'fill',
##                    nudge_x=0.3, 
##                    nudge_y=-0.1,
                    va = 'top')
        )
```

I get a plot like this: 
![image](https://user-images.githubusercontent.com/16313397/67345813-1d74cb80-f4f1-11e9-9ab4-b577c44a5c76.png)

It's close to what I want, but I'd like to replicate the labeling from <a href="https://plotnine.readthedocs.io/en/stable/tutorials/miscellaneous-show-counts-and-percentages-for-bar-plots.html">the "show counts and percentages for bar plots" plotnine tutorial</a> and obviously I need to get better separation between the labels. The code that includes `nudge_x` and `nudge_y`, however, produces this:
![image](https://user-images.githubusercontent.com/16313397/67345895-83615300-f4f1-11e9-8d16-4d4ee0d0ba92.png)

Note how the y-axis has been rescaled and the value labels no longer retain the positions that actually correspond to the bars. I tried just using `nudge_x`, just in case that could be done without affecting the scaling of the y-axis, but the result was the same.

**Comment by has2k1** [comment]
There are two issues:

1. When you specify `nudge_x` and/or `nudge_y`, `position_nudge` is used. I think there should be a warning when overriding another position that is not identity.

2. You can only calculate proportions for items in the same group, yet you are juggling two groups,
   i.e;

      i) `vs`
      ii) combination of `cyl` & `vs`

   You will have to calculate the percentages of the second grouping by other means.

For example

```python
from plotnine import *
from plotnine.data import mtcars
from plydata import *

def lbl(count, pct):
    fmt = '{} ({:g}%)'.format
    return [fmt(a, b) for a, b in zip(count, pct)]

# You could use, pure pandas but I find this easier
def count_vs(gdf):
    counts = gdf['vs'].value_counts()
    df = pd.DataFrame({
        'vs': counts.index,
        'vs_count': counts,
        'vs_pct': 100*counts/counts.sum()
    })
    return df

cyl_vs_df =  (
    mtcars
    >> group_by('am', 'cyl')
    >> do(count_vs)
)

"""  
   am  cyl  vs  vs_count  vs_pct
0   1    6   0         3   100.0
1   1    4   1         7    87.5
2   0    6   1         4   100.0
3   0    8   0        12   100.0
4   0    4   1         3   100.0
5   1    4   0         1    12.5
6   1    8   0         2   100.0
"""

# OR
# cyl_vs_df =  (
#     mtcars
#     >> group_by('am', 'cyl', 'vs')
#     >> summarize(vs_count='len(vs)')
#     >> group_by('am', 'cyl')
#     >> define(vs_pct='vs_count*100/vs_count.sum()')
# )

(ggplot(mtcars, aes('factor(cyl)', fill='factor(vs)'))
 + geom_bar(position='fill')
 + scale_y_continuous(labels=lambda l: ["%d%%" % (v * 100) for v in l])
 + facet_wrap('am')
 + geom_text(
     cyl_vs_df,
     aes(y='vs_pct', label='lbl(vs_count, vs_pct)'),
        size=8, 
        position='fill',
        va='top'
 )
)
```

![vs](https://user-images.githubusercontent.com/780341/67438228-95c7b380-f5fb-11e9-9175-536d8d27228b.png)

I used [plydata](https://github.com/has2k1/plydata) (a dplyr like package) because it is easier to think about and do calculations on groups, but, you can do the same thing with regular pandas.

**Comment by mandoir** [comment]
This looks great, thank you -- I'll try it out. I'm pretty new to Python so the tidyverse <-> python/pandas fluency isn't there yet.
