### ISSUE TITLE
some shapes are rounded in legend

### ISSUE THREAD

**Issue by katosh** [has2k1/plotnine#327]
Specifically, the shape `c` (the square) in the example below seems much rounder in the legend. The triangles `b` and `e` have a slightly rounded base, the pendagon `g` seems like a hexagon and the eliptical `h` seems more like a circle in the plot. I admitt the resolution is very low but and some form of antialising probably distorts the shapes but I would expect the antializing to effect the legend and plot euqally. At least `c` could look a lot more like a square.
```
import numpy as np
import plotnine as pn
n = 13
df = pd.DataFrame({'x':np.ones(n), 'y':-np.arange(n), 'shape':map(chr, range(97, 97+n))})
pn.ggplot(pn.aes('x', 'y', shape='shape'), df) + pn.geom_point()
```
![image](https://user-images.githubusercontent.com/4857068/67777888-b318d980-fa62-11e9-9e50-7299c9635e47.png)

**Comment by has2k1** [comment]
I know this "bug", it happens at  when the sizes are small for`.png` plots. pdf plots are fine. I think Matplotlib has it too. The issue is the plot uses `pathcollections` but the legend is made of using `Line2d`.

I have failed to fix it the times I tried.

**Comment by has2k1** [comment]
```python
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
from matplotlib.offsetbox import AnchoredOffsetbox, DrawingArea

class AnchoredDrawingArea(AnchoredOffsetbox):
    def __init__(self, width, height, xdescent, ydescent, loc):
        self.da = DrawingArea(width, height, xdescent, ydescent, clip=True)  # clip=True, is the problem
        super().__init__(loc, child=self.da)


plt.rcParams['figure.dpi'] = 100
fig, ax = plt.subplots(1, 1)

size, stroke = 3, 1
line = Line2D([25], [25], marker='s', markersize=size, markeredgewidth=stroke)
line2 = Line2D([.5], [.5], marker='s', markersize=size, markeredgewidth=stroke)

ada = AnchoredDrawingArea(50, 50, 0, 0, loc='center right')
ada.da.add_artist(line)

ax.add_artist(ada)
ax.add_line(line2)
```

![t](https://user-images.githubusercontent.com/780341/68062305-b0e0a480-fd1a-11e9-9722-935917e0b450.png)

**Comment by katosh** [comment]
It may be interesting to note that the rounding effect only comes from a strangely shaped edge path. I colored it read and slightly enlarged the makers to demonstrate that:
```python
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
from matplotlib.offsetbox import AnchoredOffsetbox, DrawingArea

class AnchoredDrawingArea(AnchoredOffsetbox):
    def __init__(self, width, height, xdescent, ydescent, loc):
        self.da = DrawingArea(width, height, xdescent, ydescent, clip=True)  # clip=True, is the problem
        super().__init__(loc, child=self.da)


plt.rcParams['figure.dpi'] = 100
fig, ax = plt.subplots(1, 1)

size, stroke = 5, 1
line = Line2D([25], [25], marker='s', markersize=size, markeredgewidth=stroke, markeredgecolor='red')
line2 = Line2D([.5], [.5], marker='s', markersize=size, markeredgewidth=stroke, markeredgecolor='red')

ada = AnchoredDrawingArea(50, 50, 0, 0, loc='center right')
ada.da.add_artist(line)

ax.add_artist(ada)
ax.add_line(line2)
```
![image](https://user-images.githubusercontent.com/4857068/69056192-b6730580-0a0f-11ea-83bf-b853d3e144cf.png)

If the `stroke` is only slightly smaller or larger the issue disappears:
```python
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
from matplotlib.offsetbox import AnchoredOffsetbox, DrawingArea

class AnchoredDrawingArea(AnchoredOffsetbox):
    def __init__(self, width, height, xdescent, ydescent, loc):
        self.da = DrawingArea(width, height, xdescent, ydescent, clip=True)  # clip=True, is the problem
        super().__init__(loc, child=self.da)


plt.rcParams['figure.dpi'] = 100
fig, ax = plt.subplots(1, 1)

size, stroke = 3, 1.1
line = Line2D([25], [25], marker='s', markersize=size, markeredgewidth=stroke)
line2 = Line2D([.5], [.5], marker='s', markersize=size, markeredgewidth=stroke)

ada = AnchoredDrawingArea(50, 50, 0, 0, loc='center right')
ada.da.add_artist(line)

ax.add_artist(ada)
ax.add_line(line2)
```
![image](https://user-images.githubusercontent.com/4857068/69056311-fafea100-0a0f-11ea-9973-d959fc021114.png)

**Comment by katosh** [comment]
Not sure if this might help: Just adding the line to the plot fixes the issue and does not draw it twice:
```python
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
from matplotlib.offsetbox import AnchoredOffsetbox, DrawingArea

class AnchoredDrawingArea(AnchoredOffsetbox):
    def __init__(self, width, height, xdescent, ydescent, loc):
        self.da = DrawingArea(width, height, xdescent, ydescent, clip=True)  # clip=True, is the problem
        super().__init__(loc, child=self.da)


plt.rcParams['figure.dpi'] = 100
fig, ax = plt.subplots(1, 1)
ax.set_xlim(0,50)
ax.set_ylim(0,50)

size, stroke = 3, 1
line = Line2D([25], [25], marker='s', markersize=size, markeredgewidth=stroke)
line2 = Line2D([10], [25], marker='s', markersize=size, markeredgewidth=stroke)

ada = AnchoredDrawingArea(50, 50, 0, 0, loc='center right')
ada.da.add_artist(line)

ax.add_artist(ada)
ax.add_line(line2)
ax.add_line(line)
```

![image](https://user-images.githubusercontent.com/4857068/69057443-30a48980-0a12-11ea-9a8b-5c4457855323.png)

**Comment by has2k1** [comment]
> Just adding the line to the plot fixes the issue and does not draw it twice:

The solution has to work for lines that are not added to the axes. The legend is independent of the axes.

**Comment by has2k1** [comment]
One is much more unlikely to encounter this issue anymore. Since v0.13, the default `dpi` is 100 but the `figure_format` is retina, which make the rendering dpi 200. This is outside the buggy (`81 < dpi < 115`) range.
