### ISSUE TITLE
What's the idiomatic way to do line/ribbon geom for y/ymin/ymax stats?

### ISSUE THREAD

**Issue by cooijmanstim** [has2k1/plotnine#328]
Sorry for posting a question rather than a bug, but this has bothered me for a long time. I love how simple it is to use `stat_summary` with `geom=pointrange`, but what I really want is to plot the central tendency with a `geom_line` and the `[ymin,ymax]` with a  `geom_ribbon`, which is much easier on the eyes than the `pointrange` geom. What's the proper way to achieve this?

If I have

```python
(ggplot(df, aes(x="x", y="y"))
 + stat_summary(geom="pointrange")
)
```

then I can instead do

```python
(ggplot(df, aes(x="x", y="y"))
 + stat_summary(geom="geom_ribbon", fill="#999999")
 + stat_summary(geom="geom_line", color="#333333")
)
```

but I worry this recomputes the statistics. The documentation for `stat_summary` says

> Calculated aesthetics are accessed using the _calc_ function. e.g. `stat(ymin)`.

This suggests I can add one instance of `stat_summary` to my plot and then add geoms that use the results, e.g. something like:

```python
(ggplot(df, aes(x="x", y="y"))
 + stat_summary(geom="ribbon", fill="#999999")
 + geom_line(aes(y="stat(y)"), color="#333333")
)
```

Unfortunately I haven't found any variation of this incantation that works. Maybe I shouldn't be using `stat(ymin)` literally, or maybe the word `calc` should be involved somehow? Am I thinking about this all wrong?

**Comment by has2k1** [comment]
> but I worry this recomputes the statistics.

No need to worry that is how to do it.

> This suggests I can add one instance of stat_summary to my plot and then add geoms that use the results, e.g. something like:

You can only have use a `stat` with a `single` geom.

If you really wish to have one computation, then create an "umbrella" geom whose default `stat='summary'` uses `geom_ribborn` and `geom_line`.
