### ISSUE TITLE
Use clip_on to show full geom on axis?

### ISSUE THREAD

**Issue by aaronbarzilai** [has2k1/plotnine#330]
Hassan,

Thanks for the amazing library.  One question: I am trying to show full points that are on an axis, but they are being truncated. I don't want to use expand, I want to keep the axes where they are.  From [what I have read](https://stackoverflow.com/questions/9912206/how-do-i-let-my-matplotlib-plot-go-beyond-the-axes), I believe I need to somehow pass clip_on = False to the underlying matplotlib call. I've tried it a couple of ways in this example (both simultaneously), but it doesn't seem to work. How can I show the full circle for all 4 points in this toy example, which I've executed in Jupyter Lab?

Thanks,
Aaron

```from plotnine import *
import plotnine
import matplotlib
import pandas as pd

print(f"plotnine version: {plotnine.__version__}, matplotlib version {matplotlib.__version__}")
thechart = (
    ggplot(mapping=aes(clip_on=False))
    + geom_point(data=pd.DataFrame([[0,0],[0.5,0],[1,1],[2,2]],columns= ['x','y']),
                mapping=aes(x='x',y='y',clip_on=False),
                size=4)
    + scale_y_continuous(expand=[0, 0])
    + scale_x_continuous(expand=[0, 0])
)
display(thechart)
```
Here's the output

![Selection_039](https://user-images.githubusercontent.com/15833991/68878659-1b5bf200-06d6-11ea-9be1-2aff2babe723.png)

Thanks,
Aaron

**Comment by has2k1** [comment]
You cannot do it in plotnine, you have to drop into matplotlib.

```python
fig = (
    ggplot()
    + geom_point(data=pd.DataFrame([[0,0],[0.5,0],[1,1],[2,2]],columns= ['x','y']),
                mapping=aes(x='x',y='y'),
                size=4)
    + scale_y_continuous(expand=[0, 0])
    + scale_x_continuous(expand=[0, 0])
).draw()

ax = fig.axes[0]
ax.collections[0].set_clip_on(False)
```

![clipon](https://user-images.githubusercontent.com/780341/68898523-ad004980-0740-11ea-9bfe-ec6c54b3ca7f.png)

**Comment by aaronbarzilai** [comment]
Thanks so much!

**Comment by aaronbarzilai** [comment]
Hassan, thanks again for this.  It mostly works, I can reproduce the example you provided and apply it to my specific case.  

However, I noticed one thing for my case, was wondering if there was a solution.  Apolgies if it's a matplotlib functionality I'm unaware of.

I am also drawing the average of my points as a horizontal line.  The median is drawn as well, and text labels.  If I follow your code and add the line after the geom_point, then it correctly does not clip but as expected the line covers the point.
```
fig = (
    ggplot()
    + geom_point(data=pd.DataFrame([[0,0],[0.75,0],[1,1],[1.5,1.5],[2,2]],columns= ['x','y']),
                mapping=aes(x='x',y='y'),
                color='#4682b4',
                fill='blue',
                shape='o',
                size=4)
    + geom_hline(yintercept=1,size=2,color='red')
    + annotate(geom="text", x=0.25, y=1.1,label='Line 1')
    + geom_hline(yintercept=1.5,size=2,color='orange')
    + annotate(geom="text", x=0.25, y=1.6,label='Line 2')
    + scale_y_continuous(expand=[0, 0])
    + scale_x_continuous(expand=[0, 0])
).draw()

ax = fig.axes[0]
ax.collections[0].set_clip_on(False)
```

![image](https://user-images.githubusercontent.com/15833991/70473765-b363b600-1a9f-11ea-8e85-be4aacaff682.png)

What I really want, and what I had before reaching out to you, was the geom_point as the last tiem, so that it covered the lines.  If I do that with your fix, for some reason it undoes the clipping=off fix you provided. Do you have any idea how to implement your fix while also putting the points over the lines(last element)?

```
fig = (
    ggplot()

    + geom_hline(yintercept=1,size=2,color='red')
    + annotate(geom="text", x=0.25, y=1.1,label='Line 1')
    + geom_hline(yintercept=1.5,size=2,color='orange')
    + annotate(geom="text", x=0.25, y=1.6,label='Line 2')
    + scale_y_continuous(expand=[0, 0])
    + scale_x_continuous(expand=[0, 0])
    + geom_point(data=pd.DataFrame([[0,0],[0.75,0],[1,1],[1.5,1.5],[2,2]],columns= ['x','y']),
            mapping=aes(x='x',y='y'),
            color='#4682b4',
            fill='blue',
            shape='o',
            size=4)

).draw()

ax = fig.axes[0]
ax.collections[0].set_clip_on(False)
```
![image](https://user-images.githubusercontent.com/15833991/70474316-5ddbd900-1aa0-11ea-8f31-cfabfb7ddf7b.png)

Note that this happens even if i just put the geom_point after the first geom_hline.  From my experimenting I seem to run into the problem when the geom_point is not immediately after ggplot().

Thanks so much,
Aaron

**Comment by has2k1** [comment]
`geom_point` is no longer the first, you have to adjust index on `ax.collections`  accordingly.

```python
ax.collections[2].set_clip_on(False)
```

**Comment by aaronbarzilai** [comment]
Thank so much, this worked perfectly.  I very much appreciate it and hope this issue helps others with the same question.
