### ISSUE TITLE
geom_line and discrete axis

### ISSUE THREAD

**Issue by TyberiusPrime** [has2k1/plotnine#335]
I'm probably just having a bad day, but this doesn't work as expected:
```
p = p9.ggplot(p9.data.mtcars)
p += p9.geom_line(p9.aes(x='name', y='mpg'))
p
```
Get's me an empty plot and a warning 'PlotnineWarning: geom_path: Each group consist of only one observation. Do you need to adjust the group aesthetic?
  "group aesthetic?", PlotnineWarning)'.

So I have to introduce a throway column:
![image](https://user-images.githubusercontent.com/1257580/70239237-3963c200-176b-11ea-9c96-fcfe8efa1ac7.png)

Can anyone enlighten me why plotnine groups-by-x-values-on-discrete-scales by default?

**Comment by has2k1** [comment]
The plotting system is *always* groups on all the mapped discrete variables, unless the *group* aesthetic is mapped or set. When `x` is discrete and there is only one value for each `x` value, then no group has enough points for a line. This makes sense if you think about it.

Check out the [tutorial](https://plotnine.readthedocs.io/en/stable/tutorials/miscellaneous-automatic-grouping-insufficient.html) for more.

**Comment by TyberiusPrime** [comment]
Thanks, it does make some sense, and I won't argue for special casing when using just a line,
but perhaps we could detect it and improve the error message (since #336 was another person being confused by this).

Also I feel there is still a bug in here somewhere:
```python
p9.geom_line(p9.aes(x='name', y='mpg'), group=1)
```
works, 
but 
```
p9.geom_line(p9.aes(x='name', y='mpg'), group="ignored")
```
gives me 
```
NameError: name 'ignored' is not defined

During handling of the above exception, another exception occurred:
...
PlotnineError: "Could not evaluate the 'group' mapping: 'ignored' (original error: name 'ignored' is not defined)"
```
where I think that shouldn't be a mapping (it's outside of aes), but an 'unmapped' value?

Possibly just one more case of we-should-have-a-better-error-message-guiding-the-user.

**Comment by has2k1** [comment]
> p9.geom_line(p9.aes(x='name', y='mpg'), group="ignored")

Is a bug.
