### ISSUE TITLE
setting up x-ticks

### ISSUE THREAD

**Issue by wangjiawen2013** [has2k1/plotnine#336]
Dear,
I wannt know how to set up x-ticks, for example, my x-ticks was (0, 2.5, 6, 7.5) by default, but I wanna set up it as (0, 1,2,3,4,5,6,7,8). Besides, geom_line() failed when x-axis are discrete strings, such as ('a','b','c','d') for x while (1,2,3,4) for y. Does geom_line() support string-like x value ?

**Comment by TyberiusPrime** [comment]
x_ticks: scale_x_continuous(breaks=list(range(0,9)), minor_breaks=[...])

geom_line: You need to add a 'group' column to your data frame, df = df.assign(group='ignored'),
and then do geom_line(p9.aes('x','y', group='group'). Not sure if that's a bug, see #335.

**Comment by has2k1** [comment]
See [https://plotnine.readthedocs.io/en/stable/tutorials/miscellaneous-automatic-grouping-insufficient.html](this) to understand what is happening.
