### ISSUE TITLE
How do I transform tick labels without explicitly specifying breaks?

### ISSUE THREAD

**Issue by lorin** [has2k1/plotnine#34]
Let's say I have a scatter plot where the x-axis date is pandas.Timestamp objects. By default, plotnine renders the x tick labels on my plot such such that they run into each other.

I'd like to do an arbitrary transformation on the x-axis tick labels. For example, I'd like the tick labels to be blank except for the first day of the year, in which case I want the tick label to just be the year, so `"2017-03-04"` would transform to `""`, and `"2016-01-01"` would transform to `"2016"`.

However, I don't want to explicitly specify the breaks. Instead, I want plotnine to use its default algorithm for determining where to put the breaks.

Is this possible to do with plotnine?

**Comment by has2k1** [comment]
Use [date_format](https://mizani.readthedocs.io/en/stable/formatters.html#mizani.formatters.date_format) from mizani. 

```python
+ scale_x_datetime(labels=date_format('%Y'))
```

**Comment by lorin** [comment]
The [scale](http://plotnine.readthedocs.io/en/stable/generated/plotnine.scales.scale.scale.html#plotnine.scales.scale.scale) docs describe the labels argument as a list, specifically:

>  labels (list, optional) – List of str. Labels at the breaks.


However, it appears that the labels argument can also be a callable that takes a list (array_like?) of breakpoints as input and returns a list of strings as output. 

Should the docs be updated? If so, I'm willing to submit a PR.

**Comment by has2k1** [comment]
Yes the docs should be updated and a PR would be great. Also, can you add something for the `breaks` argument. It can be a callable that takes a tuple of limits and returns a list of breaks.

Plus, would something of the sort 

```python
+ scale_x_datetime(breaks=date_breaks('2 year'), labels=date_format('%Y'))
```
have worked for you.

**Comment by lorin** [comment]
This was exactly what I was looking for:

```
+ scale_x_datetime(breaks=date_breaks('1 year'), labels=date_format('%Y'))
```

I'll submit a PR for the docs.

**Comment by lorin** [comment]
https://github.com/has2k1/plotnine/pull/35

**Comment by has2k1** [comment]
Re-opened to serve as a reminder for a tutorial section on date labels and breaks.
