### ISSUE TITLE
ImportError: cannot import name 'scale_alpha_ordinal'

### ISSUE THREAD

**Issue by alekszaf** [has2k1/plotnine#340]
The error appears when I am trying to import plotnine in jupyter notebooks. I am using Scipy version 1.2

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-30-eaf5908b65b6> in <module>()
----> 1 import plotnine
      2 
      3 ggplot(train_data) + geom_bar(aes(x='Survived', fill='Sex'))

C:\Anaconda3\lib\site-packages\plotnine\__init__.py in <module>()
----> 1 from .qplot import qplot            # noqa: F401
      2 from .ggplot import ggplot, ggsave  # noqa: F401
      3 from .ggplot import save_as_pdf_pages  # noqa: F401
      4 from .watermark import watermark    # noqa: F401
      5 from .aes import *                  # noqa: F401,F403,E261

C:\Anaconda3\lib\site-packages\plotnine\qplot.py in <module>()
      7 from patsy.eval import EvalEnvironment
      8 
----> 9 from .ggplot import ggplot
     10 from .aes import aes, all_aesthetics, scaled_aesthetics
     11 from .labels import labs

C:\Anaconda3\lib\site-packages\plotnine\ggplot.py in <module>()
     16 from .aes import aes, make_labels
     17 from .layer import Layers
---> 18 from .facets import facet_null
     19 from .facets.layout import Layout
     20 from .options import get_option

C:\Anaconda3\lib\site-packages\plotnine\facets\__init__.py in <module>()
----> 1 from .facet_grid import facet_grid
      2 from .facet_null import facet_null
      3 from .facet_wrap import facet_wrap
      4 from .labelling import label_value, label_both, label_context
      5 from .labelling import labeller, as_labeller

C:\Anaconda3\lib\site-packages\plotnine\facets\facet_grid.py in <module>()
      4 from ..utils import match, join_keys
      5 from ..exceptions import PlotnineError
----> 6 from .facet import facet, layout_null, combine_vars, add_missing_facets
      7 from .facet import eval_facet_vars
      8 

C:\Anaconda3\lib\site-packages\plotnine\facets\facet.py in <module>()
      9 from ..utils import cross_join, match
     10 from ..exceptions import PlotnineError
---> 11 from ..scales.scales import Scales
     12 
     13 # For default matplotlib backend

C:\Anaconda3\lib\site-packages\plotnine\scales\__init__.py in <module>()
      2 from .scale_alpha import scale_alpha
      3 from .scale_alpha import scale_alpha_continuous
----> 4 from .scale_alpha import scale_alpha_ordinal
      5 from .scale_alpha import scale_alpha_discrete
      6 from .scale_alpha import scale_alpha_datetime

ImportError: cannot import name 'scale_alpha_ordinal'

​
​

**Comment by has2k1** [comment]
Make sure the installation is not corrupt. Find `scale_alpha.py` and look for `scale_alpha_ordinal` class.
