### ISSUE TITLE
how to get values from boxplot?

### ISSUE THREAD

**Issue by MAGALLANESJoseManuel** [has2k1/plotnine#341]
In ggplo2 from R we have a function ggplot_build(), I used to recover the values of boxplots: quartles, min, max and outliers. What can I do in plotnine?

**Comment by has2k1** [comment]
There is a private function `ggplot._build()`.

```python
p = ggplot(..) + geom_boxplot(..)
p._build()
p.layers[0].data # <- What you are looking for
```
