### ISSUE TITLE
Incorrect discrete limits

### ISSUE THREAD

**Issue by psandev** [has2k1/plotnine#342]
When I limit the number of x values, the last one contains the data of the rest of the elements.
Please, see below.
![image](https://user-images.githubusercontent.com/30928228/70871151-cf39f100-1fa4-11ea-9ceb-531d16384a11.png)

**Comment by has2k1** [comment]
@psandev , thanks for submitting. It has been fixed.

**Comment by psandev** [comment]
Thank you, Hasan. How do I get the fix? Do I have to build the library?

**Comment by psandev** [comment]
I got it. Thank you again for the swift response.
