### ISSUE TITLE
Reuse figure that is already open

### ISSUE THREAD

**Issue by DiogoFerrari** [has2k1/plotnine#343]
Every plot opens a new figure, even with `plt.ion()`. Is there any way to re-use the figure that is already open, as in matplotlib when we clean the figure or axis first and then plot?

**Comment by has2k1** [comment]
There is an internal method [_draw_using_figure](https://github.com/has2k1/plotnine/blob/e77a2cb4eca82cfa46c132b535091ec5940bf8c5/plotnine/ggplot.py#L221) that is used when creating [animations](https://github.com/has2k1/plotnine/blob/master/plotnine/animation.py#L9).

**Comment by joelostblom** [comment]
@has2k1 Could you provide an example of how to use `_draw_using_figure` for this purpose? When I try the below, I run into `AttributeError: 'Figure' object has no attribute '_themeable'`

```python
from plotnine import ggplot, geom_histogram, aes
from plotnine.data import mpg
import matplotlib.pyplot as plt


cols = mpg.select_dtypes('number').columns
fig, axes = plt.subplots(1, len(cols))
for col, ax in zip(cols, axes.flat):
    print(col)
    p = (ggplot(mpg)
        + aes(x=col)
        + geom_histogram(color='white', fill='#4c78a8'))
    p._draw_using_figure(figure=fig, axs=[ax])
```

**Comment by has2k1** [comment]
You can add this

   fig, axes = plt.subplots(1, len(cols))
   fig._themeable = {}

But using internal methods -> you are on your own!

**Comment by joelostblom** [comment]
Works like a charm, thank you!

> But using internal methods -> you are on your own!

Understood! =)
