### ISSUE TITLE
horizontal spacing between facet plots

### ISSUE THREAD

**Issue by kraxli** [has2k1/plotnine#344]
the space between two plots in a facet plot is not large enough for the tick values. Hence the values overlap with the left adjacent figure (please see screenshot).

![image](https://user-images.githubusercontent.com/8371948/71806448-204f7900-3069-11ea-943b-43efdb7dada8.png)

I use the command:
```p9.facet_wrap(facets = 'currency', nrow=2, scales='free_y', shrink=True)```
with plotnine 0.6 with Python 3.6.5 on Windows

**Comment by TyberiusPrime** [comment]
this is a known bug: #106 
The workaround is to use [subplot_adjust](https://plotnine.readthedocs.io/en/stable/generated/plotnine.themes.themeable.subplots_adjust.html),

We probably should place some more references to this on the facet documentation?

**Comment by kraxli** [comment]
thanks for coming back on this. `gg += p9.theme(subplots_adjust={'wspace':0.15})` helps to manually fix the issue. Do I understand correctly that this issue needs to wait for a better _layout manager_ of Matplotlib?

**Comment by TyberiusPrime** [comment]
Basically, yes.
As far as I'm aware we went from 'waiting for a matplotlib layout manager' to 'waiting for a better one'. 
Not sure that anyone is working on it though :(.

**Comment by has2k1** [comment]
> As far as I'm aware we went from 'waiting for a matplotlib layout manager' to 'waiting for a better one'.

Yes this is the case. With matplotlib it is hard to manage (in a predictable way) the space outside the plot areas.

> Not sure that anyone is working on it though

I have tried a few times and backed off because of the complexity of the code.

**Comment by TyberiusPrime** [comment]
Since this a reoccurring question, and we can't solve it properly, 
maybe we could add a warning that,
if you're using facet...(ncol>1) and a free y axis and no subplots_adjust, suggests the user to use subplots_adjust?

Yes that's ugly, but the current situation is plain bad and the workaround is difficult to find for the users.

**Comment by machow** [comment]
Hey, I've run into this a few times, and am happy to open a PR for it. I'm looking at the [code for face_wrap](https://github.com/has2k1/plotnine/blob/master/plotnine/facets/facet_wrap.py#L95-L121), and seeing there is a check_dimensions function that issues warnings.

Would it work to add a `check_labels` function (or something), that...

* runs in the init (like check_dimensions)
* issues the warning mentioned above

**Comment by has2k1** [comment]
@machow, yes please. It should run in `spaceout_and_resize_panels` that is where the spacing code is located. So create a function in `facet.py` which gets called by `facet_wrap.spaceout_and_resize_panels` and `facet_grid.spaceout_and_resize_panels`.

May be a signature like,

```python
def check_axis_text_space(facet):
    ...
```
