### ISSUE TITLE
How to rasterize large scatter plots?

### ISSUE THREAD

**Issue by Hoeze** [has2k1/plotnine#347]
Hi, is there an option to rasterize scatter plot?
Something like `rasterized=True` in matplotlib:
https://brushingupscience.com/2017/05/09/vector-and-raster-in-one-with-matplotlib/

For reference, I'm currently writing PDF's with ~ 500MB size per figure...

**Comment by has2k1** [comment]
You can drop into matplotlib to do it.

```python
from plotnine import *
from plotnine.data import mtcars

p = (ggplot(mtcars, aes('wt', 'mpg'))
     + geom_point()
     + geom_smooth()
)

# Get figure and access the points to be rasterized
fig = p.draw()
points = fig.axes[0].collections[0]
points.set_rasterized(True)
fig.savefig('raster_points.pdf')
```

**Comment by Hoeze** [comment]
Thanks, this was quite helpful!

**Comment by Hoeze** [comment]
Would you agree changing this to a feature request for "rasterized=True" option maybe?
A native option would simplify the task.

**Comment by has2k1** [comment]
@Hoeze, I will consider it, may be the realise after the next one.

**Comment by Hoeze** [comment]
Thanks a lot @has2k1!
