### ISSUE TITLE
Inconsistent tick behavior between themes

### ISSUE THREAD

**Issue by jbechtel** [has2k1/plotnine#348]
When switching between different themes, the minor ticks are inconsistently displayed. For instance, for `theme_grey()` and `theme_538()` the minor ticks are not displayed, but for `theme_bw()` and `theme_xkcd()` they are displayed. It would be great if the minor ticks were displayed consistently between all themes (I prefer not showing them!). But in the meantime, if I would like to use the `theme_bw()` with no minor ticks (but keeping the minor grid lines), how would I go about that?

Here are some examples:

```
from plotnine import *
from plotnine.data import mtcars

(ggplot(mtcars, aes('wt', 'mpg', color='factor(gear)'))
 + geom_point()
 + stat_smooth(method='lm')
 + facet_wrap('~gear')
 + theme_grey()
)
```
![Screen Shot 2020-01-30 at 8 33 23 AM](https://user-images.githubusercontent.com/6655075/73454073-536ceb80-433b-11ea-96da-4787aed694d1.png)
```
(ggplot(mtcars, aes('wt', 'mpg', color='factor(gear)'))
 + geom_point()
 + stat_smooth(method='lm')
 + facet_wrap('~gear')
 + theme_bw()
)
```
![Screen Shot 2020-01-30 at 8 35 11 AM](https://user-images.githubusercontent.com/6655075/73454132-73041400-433b-11ea-9963-9e3694b63f66.png)
```
(ggplot(mtcars, aes('wt', 'mpg', color='factor(gear)'))
 + geom_point()
 + stat_smooth(method='lm')
 + facet_wrap('~gear')
 + theme_538()
)
```
![Screen Shot 2020-01-30 at 8 36 10 AM](https://user-images.githubusercontent.com/6655075/73454202-962ec380-433b-11ea-9146-2d6fce07ca55.png)
```
(ggplot(mtcars, aes('wt', 'mpg', color='factor(gear)'))
 + geom_point()
 + stat_smooth(method='lm')
 + facet_wrap('~gear')
 + theme_xkcd())
```
![Screen Shot 2020-01-30 at 8 36 45 AM](https://user-images.githubusercontent.com/6655075/73454250-ab0b5700-433b-11ea-9179-ef963e9b02b4.png)

**Comment by has2k1** [comment]
>  But in the meantime, if I would like to use the theme_bw() with no minor ticks (but keeping the minor grid lines), how would I go about that?

```python
+ theme(
    axis_ticks_minor=element_blank(),
    panel_grid_minor=element_line(color='red')
)
```
