### ISSUE TITLE
error while rotating x-axis labels

### ISSUE THREAD

**Issue by alexeykosh** [has2k1/plotnine#350]
Hello, 

when I add this to my plot to rotate the x-axis labels:

`+theme(axis.text.x=element_text(angle=90, hjust=1))`

I get this error: 

`  File "<ipython-input-154-0e3d83d3cbdd>", line 7
    theme(axis.text.x=element_text(angle=90, hjust=1))
          ^
SyntaxError: expression cannot contain assignment, perhaps you meant "=="?

`

**Comment by has2k1** [comment]
In python valid parameter names cannot have a `.`, so plotnine uses underscores. For your case that becomes `axis_text_x`.
