### ISSUE TITLE
Plotting Shapefiles Results in Error: AttributeError: 'GeometryArray' object has no attribute 'view'

### ISSUE THREAD

**Issue by bryantsa08** [has2k1/plotnine#354]
I attempted to follow the example for plotting shapefiles via plotnine on the documentation site for geom_map (https://plotnine.readthedocs.io/en/stable/generated/plotnine.geoms.geom_map.html). This is the plot of westeros. After downloading the data, and copying the code, I received the error in the title. The most recent traceback is below:
~\.conda\envs\scratch\lib\site-packages\pandas\core\internals\managers.py in concatenate_block_managers(mgrs_indexers, axes, concat_axis, copy)
   2052                 values = values.copy()
   2053             elif not copy:
-> 2054                 values = values.view()
   2055             b = b.make_block_same_class(values, placement=placement)
   2056         elif is_uniform_join_units(join_units):

AttributeError: 'GeometryArray' object has no attribute 'view'

**Comment by maxibor** [comment]
Hi @bryantsa08,
I also had the same problem at first, but creating a dedicated conda environment with just **geopandas**, **pandas**, and **plotnine** fixed it.
I guess this is more of a version incompatibility between plotnine/geopandas/pandas.
The last version of these libraries seems to fix it.
For reference, here is the [conda env](https://gist.github.com/maxibor/d695a8d006ad543397f5cddfef8df22c) I used.

And the code to test that it is working:

```python
world = geopandas.read_file(geopandas.datasets.get_path('naturalearth_lowres'))
ggplot() + geom_map(world, fill=None)
```

**Comment by has2k1** [comment]
> I guess this is more of a version incompatibility between plotnine/geopandas/pandas.

Yes you need the latest version of these packages, and make sure that the environment is not "leaky".
