### ISSUE TITLE
geom_ribbon does not allow fill as an aesthetic

### ISSUE THREAD

**Issue by PaulHiemstra** [has2k1/plotnine#356]
I just tried to make a plot that included a geom_ribbon. I often do this to highlight sections of data in a timeseries plot. Using my ggplot2 experience I tried;

```
from plydata import group_by, mutate, query
import numpy as np


plotdata = (all_vip >> 
     group_by('path') >> 
     mutate(timechunk_id = "(exogeneous_insuline > 0).cumsum()") >> 
     query('timechunk_id < 5')) 
plotdata >> (
    ggplot(aes(x="TimeStamp", y='base_plasma_glucose')) + 
        geom_ribbon(aes(ymin=-np.inf, ymax=np.inf, fill="timechunk_id"), alpha=0.5) + 
        geom_line() +
        facet_wrap('~ path') + 
        theme_bw() + 
        theme(figure_size=(16,9))
)
```
This did, however, not have the intended effect. I got:

    PlotnineError: 'Aesthetics cannot vary within a ribbon.'

If I subset the data for the `geom_ribbon` to have just one value for `timechunk_id`, the plot works. 

Is this an inherent limitation of `plotnine`, or am I doing something wrong?

**Comment by has2k1** [comment]
I do not have access to your data so I cannot replicate your example. But you could try `fill='factor(timechunk_id)'` to make the *fill* value discrete and therefore separate the groups.

**Comment by PaulHiemstra** [comment]
This worked beautifully! Many thanks for your help.

**Comment by has2k1** [comment]
The issue is `fill` being numeric was treated as a continuous variable, so it was varying withing the group being plotted.
