### ISSUE TITLE
reverse brewer color scale?

### ISSUE THREAD

**Issue by projectsUW** [has2k1/plotnine#357]
In R you can reverse the palette min-max:
scale_fill_brewer(palette = "Greys",
                                            direction = -1)

what alternative can I have in plotnine for a brewer palette?

**Comment by has2k1** [comment]
The direction option is missing in plotnine, but you can create your own brewer palette with it.

```python
from mizani.palettes import brewer_pal
from plotnine.scales.scale import scale_discrete

class my_scale_color_brewer(scale_color_brewer):
    def __init__(self, type='seq', palette=1, direction=1, **kwargs):
        self.palette = brewer_pal(type, palette, direction)
        scale_discrete.__init__(self, **kwargs)
```

**Comment by projectsUW** [comment]
Thank you!.

**Comment by has2k1** [comment]
This issue needs to stay open so that this gets implemented.
