### ISSUE TITLE
`geom_map` uses incorrect color/fill indexing, is incompatible with faceting

### ISSUE THREAD

**Issue by nbolten** [has2k1/plotnine#359]
### Overview

Hey there!

When attempting to add `facet_wrap` to a plot using `geom_map`, I ran into this exception:

   IndexError: positional indexers are out-of-bounds

In the Traceback, it is this section of `geom_map.py` that's the culprit:

https://github.com/has2k1/plotnine/blob/246252c6b2e84a8e7dc83ee8661972496d22a1ab/plotnine/geoms/geom_map.py#L98-L105

After a bit of messing around, I discovered two bugs in the code.

### Bug 1

`cidx` and `fidx` are indices produced through subsetting and therefore have in-index values, but the lines where `color` and `fill` columns are set use `iloc`, which uses a positional indices. This works for non-faceted plots (and the first facet) because the index is created as an Int64Index, where positional index is the same as the associated index value, but not for other facets, where they do not match.

One potential fix is to use `.loc` instead of `.iloc` and ignore the `_loc` function:

        cidx = data.index[data['color'].isnull()]
        fidx = data.index[data['fill'].isnull()]
        data.loc[cidx, 'color'] = 'none'
        data.loc[fidx, 'fill'] = 'none'

### Bug 2

I thought this would fix everything, but the same type of issue occurs just after when figuring out the geometry type.

Specifically, `data.geometry.loc[0].geom_type` looks up the index value of 0, rather than the positional value, and facets other than the first one won't have this value. The easiest fix is to use `iloc`: `data.geometry.iloc[0].geom_type`.

### Summary

Replacing the current lines 98-105 with this code should fix the issue. Let me know if it's better for me to create a pull request:

        _loc = data.columns.get_loc
        cidx = data.index[data['color'].isnull()]
        fidx = data.index[data['fill'].isnull()]
        data.loc[cidx, 'color'] = 'none'
        data.loc[fidx, 'fill'] = 'none'
        data['fill'] = to_rgba(data['fill'], data['alpha'])

        geom_type = data.geometry.iloc[0].geom_type

`_loc` is also no longer used in this code and could be removed.

**Comment by has2k1** [comment]
@nbolten, yes please create a pull request.

**Comment by jwhendy** [comment]
I can open up a new issue if you prefer. I'm not sure if my problem is the same or different. I was plotting some covid19 data vs. census populations. Here is the code:

```
import numpy as np
import pandas as pd
from plotnine import *

dat_county = pd.read_csv('https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv')
dat_county = dat_county[-dat_county['fips'].isna()]
dat_county['fips'] = dat_county['fips'].astype(int)

pop = pd.read_csv('https://raw.githubusercontent.com/jwhendy/covid19/master/data/population.csv')
land = pd.read_csv('https://raw.githubusercontent.com/jwhendy/covid19/master/data/land_sqm.csv')

dat_m = dat_county.merge(pop, on=['state', 'county'])
dat_m = dat_m.merge(land, on=['state', 'county'])
dat_m['rho'] = dat_m['pop']/dat_m['land_sqm']
dat_m['cases_pop'] = dat_m['cases'] / dat_m['pop']
dat_m['rho_log'] = np.log10(dat_m['rho'])
dat_m['grp'] = dat_m['state'] + '_' + dat_m['county']

p = ggplot(dat_m, aes(x='date', y='cases_pop*1000', color='rho_log', group='grp')) + geom_line(alpha=0.2, size=0.5)
p = p + scale_x_datetime(breaks=['2020-01-30', '2020-02-15', '2020-02-29', '2020-03-15', '2020-03-30'])
p = p + scale_y_log10(name='log(cases per 1000 people)') + scale_color_cmap(breaks=[1, 2, 3, 4, 5], labels=[10**i for i in range(1, 6)])
p = p + guides(color=guide_colorbar(title='pop/sqm'))
p = p + theme_bw() + theme(axis_text_x = element_text(angle=315, hjust=0))
p
```

I get this error on `plotnine==0.6.0`, but not when installing from `git`.
```
IndexError: index 32391 is out of bounds for size 32391
```

I add this here 1) to verify this is a duplicate and that this PR addressed it (`geom_line` vs. `geom_map`) and 2) in case someone else finds this. I do not get the error on `0.6.0` if I drop `color` from `aes`.
