### ISSUE TITLE
[Question] Is there a way to get the fig, ax from a ggplot?

### ISSUE THREAD

**Issue by gepcel** [has2k1/plotnine#36]
A silly question.  But I've been googling around and digging into the source code since the day I knew **plotnine**. No good luck.

I've used matplotlib for a long time. From time to time, I encounter with the ggplot2 code or figure of *R*. I don't understand neither ggplot2 nor *R*. So I just copy the code, change a few lines to match my data, and draw the figure. If I couldn't get what I want by this, nor could I  do it the matplotlib way, I'm out of choice. And also I have to export my data from python to *R*.

**plotnine** is very useful for me to draw some ggplot2 figure in python. It will be more useful if I can just get the figure and axis from plotnine's ggplot object, and do something with them.

**Comment by has2k1** [comment]
Sure, you can get both with

```python
p = ggplot(...) + geom_point()
fig = p.draw()
axs = fig.get_axes()
```
