### ISSUE TITLE
legend_key_width 

### ISSUE THREAD

**Issue by projectsUW** [has2k1/plotnine#360]
Hi,

I had a heatplot (geom_tile), then I put the element on top, but I want to make the legend wider, but this is not workig no matter what number I write in width:

heat1 = heat1 + theme(legend_title = element_blank(),
                      legend_position="top",
                      legend_key_width=2) #NOT MAKING ANY CHANGE

**Comment by has2k1** [comment]
@projectsUW, please include a reproducible example. That makes it easy to verify the issue.

**Comment by projectsUW** [comment]
Check here:
https://colab.research.google.com/drive/1dS71QM7pLG8-plSKtGJQlYSUKDTTwTVG

**Comment by has2k1** [comment]
That is an oversight `legend_key_width` only adjusts the width of box legend entries and not the colorbar. 

Use this

```python
 + guides(color=guide_colorbar(barwidth=40))
```

**Comment by projectsUW** [comment]
In R:
legend.key.width=unit(1.5, "cm")

that's why I used it.
