### ISSUE TITLE
legend symbols

### ISSUE THREAD

**Issue by projectsUW** [has2k1/plotnine#363]
Hi there,

I can't make the legends have the right symbols when using stat_summary:
https://colab.research.google.com/drive/1xTzw979cspvPj2xi419YT6wDWgPLnUAv

**Comment by has2k1** [comment]
What symbols do you expect? I cannot reproduce that example. Try with something simpler and find the mistake you are making or a new bug, the `geom` determines the legend not the `stat`.

**Comment by projectsUW** [comment]
Hi, so this is working, with no mistake, but I want to know:
1) Is there an easier way to declare the colors in the aes() in every stat_summary()
2) How can I change the symbols manually in the LEGEND, so that I see ONE LINE and two DOTS.

**Comment by has2k1** [comment]
> Is there an easier way to declare the colors in the aes() in every stat_summary()

Easier than what? Do you mean `ggplot(aes(...))`

> How can I change the symbols manually in the LEGEND, so that I see ONE LINE and two DOTS.

I think the legend works fine.

```python
from plotnine import *
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'x': list('aaaaabbbbcccccc'),
    'y': [1, 2, 3, 4, 5, 1.5, 1.5, 6, 6, 5, 5, 5, 5, 5, 5]
})


(ggplot(df, aes('x', 'y', color='x')) 
 + stat_summary(geom='line', group=1, fun_y=np.mean)
 + stat_summary(geom='point', group=1, size=5, alpha=.3, fun_y=np.mean)
 + stat_summary(geom='point', group=1, fun_y=np.mean)
)
```

![stat_summary_legend](https://user-images.githubusercontent.com/780341/75973397-21c0e480-5ee6-11ea-9e0f-79aada1a9fa9.png)

That has a line and 2 points.

Simplify your plot and find out why it is not what you expect, if you think it is a bug then submit it with a minimal reproducible example.
