### ISSUE TITLE
rounding Dates

### ISSUE THREAD

**Issue by projectsUW** [has2k1/plotnine#365]
Lubridate in R, allows you to round dates with a function:
https://www.rdocumentation.org/packages/lubridate/versions/1.3.3/topics/floor_date
So in R you can have:
ggplot(DF,(x=floor_date(date, "month"),y=count))

How can that be implemented in plotnine?

**Comment by has2k1** [comment]
You need to find away to do it with pandas. See the pandas documentation, maybe [this](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DatetimeIndex.floor.html) maybe helpful.
