### ISSUE TITLE
TypeError: frame_apply() got an unexpected keyword argument 'broadcast' when I try to plot some data.

### ISSUE THREAD

**Issue by EmmeMax** [has2k1/plotnine#367]
I tried to copy and paste the code down below found on the [web site of Plotnine](https://plotnine.readthedocs.io/en/stable/) in Atom but the output is `TypeError: frame_apply() got an unexpected keyword argument 'broadcast' `.

```
from plotnine import ggplot, geom_point, aes, stat_smooth, facet_wrap
from plotnine.data import mtcars

(ggplot(mtcars, aes('wt', 'mpg', color='factor(gear)'))
 + geom_point()
 + stat_smooth(method='lm')
 + facet_wrap('~gear'))
```

I've tried the same code in Jupyter and it works!
Has someone an idea? 

Thanks ❤️

*(Sorry for my bad english, it's not my mother tongue)*

**Comment by has2k1** [comment]
plotnine does not make any explicit calls to the `frame_apply` function. Make sure the packages in your environment are up-to-date and that they are properly isolated.
