### ISSUE TITLE
get automatically created tick breaks from plot

### ISSUE THREAD

**Issue by DamianLodz** [has2k1/plotnine#368]
Hi, i've got a function that takes a value(list of values) and is changing it to specific string with annotation (%, $ etc.). I use this function like for example below:

+scale_y_continuous(labels=[function_format(x) for x in np.linspace(0,300_000, 4)])

the thing is that I need to specify values for the labels on every plot. Is there any way to put arguments x for the function as automatically created tick breaks for the plot?

**Comment by has2k1** [comment]
See [formatters](https://mizani.readthedocs.io/en/stable/formatters.html), if none suit your needs you can function that accepts the breaks and returns a list of labels.

```python
from mizani.formatters import custom_format

... + scale_x_continuous(labels=custom_format('{}%'))

# OR
def labelling_func(breaks):
    return ['{}%'.format(x) for x in breaks]

... + scale_x_continuous(labels=labelling_func)
```
