### ISSUE TITLE
add geom_half_violin

### ISSUE THREAD

**Issue by jorvlan** [has2k1/plotnine#369]
Would it be an idea to add the geom_half_violin option to create plots like these? (the first was made in R, the second in python using plotnine, where I'm struggling to recreate the first plot). Curious to hear your thoughts. Thanks, J 

![figure5](https://user-images.githubusercontent.com/46848177/76482357-087ce280-6468-11ea-8814-c1ee81e38f83.png) 

![repmes_python](https://user-images.githubusercontent.com/46848177/76482407-28140b00-6468-11ea-9226-0cd2dea716d3.png)

**Comment by krassowski** [comment]
A "silly" workaround would be to plot the violin first and then add a white `geom_rect` on half of the violin. Have a look:

![plotnine halves](https://user-images.githubusercontent.com/5832902/77862232-f1811300-7211-11ea-8c3d-940d1634494d.png)

```Python
# MIT, copyright @jorvlan 
# see https://github.com/jorvlan/open-visualizations for more
violin_width = 0.2
fig6 = (
    ggplot()
    + geom_violin(d.iloc[:50,:], aes(x='factor(x)', y = 'y'), color = 'white', fill = 'dodgerblue', show_legend=False, position = position_nudge(x=-.2), width = violin_width, alpha = .6)
    + geom_rect(d.iloc[:50,:], aes(xmin=1, xmax=1 + violin_width / 2, ymin = 'min(y)', ymax='max(y)'), fill='white', position = position_nudge(x=-.2))
    + geom_violin(d.iloc[50:100,:],aes(x='factor(x)', y = 'y'), color = 'white', fill = 'darkorange', show_legend=False, position = position_nudge(x=.2), width = violin_width, alpha = .6)
    + geom_rect(d.iloc[50:100,:], aes(xmin=2 - violin_width / 2, xmax=2, ymin = 'min(y)', ymax='max(y)'), fill='white', position = position_nudge(x=.2))
    + geom_point(d.iloc[:50,:],aes(x='xj', y = 'y'), color = 'dodgerblue', show_legend=False, alpha = .6, size = 2)
    + geom_point(d.iloc[50:100,:],aes(x='xj', y = 'y'), color = 'darkorange', show_legend=False, alpha = .6, size = 2)
    + geom_line(d,aes(x='xj', y = 'y', group = 'id'), color = 'lightgray', alpha = .5)
    + geom_boxplot(d.iloc[:50,:],aes(x='factor(x)', y = 'y'), fill = 'dodgerblue', show_legend=False, position = position_nudge(x=-.15),width = .05, alpha = .6)
    + geom_boxplot(d.iloc[50:100,:], aes(x='factor(x)', y = 'y'), fill = 'darkorange', show_legend=False, position = position_nudge(x=0.15),width = .05, alpha = .6)
    + theme_classic()
    + scale_x_discrete(labels=labels, name='Conditions')
    + ylab('Value')
    + ggtitle('Figure 6: repeated measures grouped by color with box- and violinplots')
)
```

BTW, I really appreciate your work on promoting good visualisation of repeated measures data - sadly I still see papers using a single barplot :(

**Comment by has2k1** [comment]
That combination of violin, box and points is interesting.

**Comment by Fischmiep** [comment]
This may be a nice example for the gallery once #463 gets merged if someone feels like adding it.

**Comment by has2k1** [comment]
> This may be a nice example for the gallery once #463 gets merged if someone feels like adding it.

Yes it would be great for the gallery, but there is still the issue of all violins being same-sided! So I think one would have to partition the data into two parts and make two calls to `geom_violin`.

**Comment by has2k1** [comment]
@Fischmiep, I have added alternating `left-right` or `right-left` violins so you would not have to partition data to create these duo -category comparison half violins.

@jorvlan, checkout multistage aesthetic evaluation, it will ship in the next version v0.8.0 of plotnine. It makes generating these kinds plots easier. See the [example](https://plotnine.readthedocs.io/en/latest/generated/plotnine.geoms.geom_violin.html) of the latest build of the documentation. Thanks for the open-visualisations work.
