### ISSUE TITLE
scale_fill_gradient's na_value parameter doesn't work

### ISSUE THREAD

**Issue by songxxiao** [has2k1/plotnine#370]
When using `scale_fill_gradient` and setting the na value color, but it doesn't work. 

For example, I create a `pd.DataFrame` below:
```python
import pandas as pd
import numpy as np
data = pd.DataFrame([['a', 'i', 34], ['a', 'j', np.nan], 
                     ['b', 'i', np.nan], ['c', 'j', 21],
                     ['c', 'i', np.nan], ['c', 'i', 32],
                     ['b', 'k', np.nan], ['b', 'j', 34],
                     ['a', 'j', np.nan], ['c', 'k', 15],
                     ['b', 'k', np.nan], ['a', 'k', 12]],
                     columns = ['High', 'Low', 'Value']
                   )
data
```

High | Low | Value
-- | -- | --
a | i | 34.0
a | j | NaN
b | i | NaN
c | j | 21.0
c | i | NaN
c | i | 32.0
b | k | NaN
b | j | 34.0
a | j | NaN
c | k | 15.0
b | k | NaN
a | k | 12.0

I want to plot `High` & `Low` crosstable in rectangles filled  by  `Value` colors, and I want NA value to be white:

```
from plotnine import ggplot, aes, geom_tile, scale_fill_gradient
(
ggplot(data, aes('High','Low',fill = 'Value')) +
  geom_tile(color ='gray') +
  scale_fill_gradient(low = "yellow", high="blue", na_value='white')
)
```
However, it turns out that the white doesn't show:

![](https://i.loli.net/2020/03/12/uiKhS4ArHXIF15p.jpg)

It is replaced by `low` color: yellow.

**Comment by has2k1** [comment]
Fixed in mizani.
