### ISSUE TITLE
Setting name of scale_color_continuous legend

### ISSUE THREAD

**Issue by jwhendy** [has2k1/plotnine#371]
Greetings,

I was puzzled by this on a recent plot. Here's a reproducible example:

```
import pandas as pd
import random
from plotnine import *

random.seed(1)

df = pd.DataFrame({'x': [random.randrange(100) for _ in range(100)],
                   'y': [random.randrange(100) for _ in range(100)],
                   'c': [random.randrange(5) for _ in range(100)]})
p = ggplot(df, aes(x='x', y='y', color='c')) + geom_point()
p
```

By default, we get a `viridis` continous color scale:
![grab_2020-03-14_132014](https://user-images.githubusercontent.com/379357/76688001-e2397d00-65f6-11ea-9a26-e72dde5cb0db.png)

I wanted to change the name, so I added this line:
```
p = ggplot(df, aes(x='x', y='y', color='c')) + geom_point()
p = p + scale_color_continuous(name='foo')
p
```

I got this error instead:
```
ValueError: 'foo' is not a valid value for name; supported values are [list of color palette names]
```

For some silly reason I thought to try the european R ggplot spelling instead, which works but changes the color scale...
```
p = ggplot(df, aes(x='x', y='y', color='c')) + geom_point()
p = p + scale_colour_continuous(name='foo')
p
```
![grab_2020-03-14_132222](https://user-images.githubusercontent.com/379357/76688004-e82f5e00-65f6-11ea-84f1-cc74479f1e66.png)

How can I have both a `viridis` palette and a custom scale name? I'm sure this is something trivial I'm overlooking, but I haven't figured it out! Many thanks.

**Comment by has2k1** [comment]
You have hit upon two issues.

1. `scale_color_continuous` and `scale_colour_continuous` do not refer to the same scale.
2. The `name` parameter for `scale_color_continuous` which is an alias of `scale_color_cmap`  refers to the name of the colormap and not the name of the scale.

You can use this work around.

```python
import pandas as pd
import random
from plotnine import *

random.seed(1)

df = pd.DataFrame({'x': [random.randrange(100) for _ in range(100)],
                   'y': [random.randrange(100) for _ in range(100)],
                   'c': [random.randrange(5) for _ in range(100)]})
p = ggplot(df, aes(x='x', y='y', color='c')) + geom_point()
p + guides(color=guide_colorbar(title='foo'))  # <- Title of the colorbar
```

**Comment by jwhendy** [comment]
Thanks for clarifying. Any particular reason this is like that? I'm guessing it's due to passing on `name` to `matplotlib`? I ask as I'm curious if there's any interest in standardizing, for example having `name` always refer to the legend title as with other scales and, for example, `colormap` becomes the new arg name for `scale_color_cmap` instead if `name`.

Obviously this is a breaking change, but just throwing it out there. It would seem that 1:1 parity with R's `ggplot` would be great, and I can't recall any analogs like this off the top of my head (where two arguments with the same name mean different things for different scales).

Thanks for the workaround. My current solution was just to rename the column directly, but this is easier.

**Comment by has2k1** [comment]
> Any particular reason this is like that?

No, just an oversight which came about because when making a scale for the colormap palette [cmap_pal](https://mizani.readthedocs.io/en/stable/palettes.html#mizani.palettes.cmap_pal), I used the same parameter names.

The think new parameter for the scale will become `cmap_name`.
