### ISSUE TITLE
PlotnineError: "'position_jitterdodge' requires at least one aesthetic to dodge by."

### ISSUE THREAD

**Issue by jvschoen** [has2k1/plotnine#372]
https://github.com/has2k1/plotnine/blob/90412f4b88ae217a378c7a15b7db579add8a9fef/plotnine/positions/position_jitterdodge.py#L50-L58

```
(
    ggplot(df, aes(x='x_val', y='y_val', color='device'))
    + geom_boxplot() 
    + geom_jitter(position=position_jitterdodge())
)
```
The code works fine when using geom_dodge:
```
(
    ggplot(df, aes(x='x_val, y='y_val, color='device'))
    + geom_boxplot() 
    + geom_jitter(position=position_dodge(0.75))
)
```

![image](https://user-images.githubusercontent.com/35496082/77100313-cfa2b780-69eb-11ea-9376-cc139ecf46c6.png)

**Comment by has2k1** [comment]
This is a bug. In the meantime, use british spelling `colour='device'`.

**Comment by jvschoen** [comment]
@has2k1 This does not resolve the issue. I have changed my code to use the british spelling, but I still get the same error

**Comment by has2k1** [comment]
> .. but I still get the same error

Sorry I was mistaken. But as you are using points, I think you can safely `fill='device'`. However, the underlying bug was definitely fixed.

**Comment by jvschoen** [comment]
@has2k1 Using fill corrected this for me. When you say the bug is fixed, is it fixed in a `pip install update`?

Glad you  got it working! Thanks!

**Comment by has2k1** [comment]
It will be in the next release. I am *hoping* for next week.
