### ISSUE TITLE
Easy way to combine two or more plotnine figures ?

### ISSUE THREAD

**Issue by projectsUW** [has2k1/plotnine#373]
ANy update on having an array of plots? can't a plotnine plot become a subfigure in matplotlib easily?

**Comment by has2k1** [comment]
It is not possible, matplotlib is not flexible enough to get it. See https://github.com/has2k1/plotnine/issues/46.

**Comment by SkepticRaven** [comment]
I did a lot of searching and came up with a functional, yet hacky solution. Might be useful for those that "just need something functional to not go back to R's ggplot2". It heavily relies on the "_draw_using_figure" function in plotnine, and uses gridspec to control where things are plotting. Most definitely wasn't designed for this subplot stuff, but appears to fill the function pretty well.

I haven't tested if it breaks anything related to legends and whatnot and might rely heavily upon the versions...

```
import plotnine as p9
from matplotlib import gridspec
import matplotlib.pyplot as plt
from plotnine import data

# Create subplots using plotnine
p1 = (p9.ggplot(data.diamonds, p9.aes(x='cut',y='carat'))+p9.geom_point())
p2 = (p9.ggplot(data.diamonds, p9.aes(x='x',y='y'))+p9.geom_point())

# Empty plotnine figure to place the subplots on. Needs junk data (for backend "copy" reasons).
fig = (p9.ggplot()+p9.geom_blank(data=data.diamonds)+p9.theme_void()).draw()

# Create gridspec for adding subpanels to the blank figure
gs = gridspec.GridSpec(1,2)
ax1 = fig.add_subplot(gs[0,0])
ax2 = fig.add_subplot(gs[0,1])

# Add subplots to the figure
_ = p1._draw_using_figure(fig, [ax1])
_ = p2._draw_using_figure(fig, [ax2])

fig.show()
```

Functions in versions:
plotnine: 0.6.0
matplotlib: 3.2.1

**Comment by has2k1** [comment]
@SkepticRaven, good hacking. That has always been possible, I tested it out after creating `_draw_using_figure`, but obviously it does not play well with and facets, legends. You can definitely away with only one of the plots having a legend.

**Comment by honghuzi** [comment]
@SkepticRaven  This is a very good work around. However, xlabels and ylabels are missing.

**Comment by himalayajung** [comment]
Any updates on this issue?

**Comment by bioinformatist** [comment]
Why not use opencv for this job?
See https://www.geeksforgeeks.org/concatenate-images-using-opencv-in-python/

**Comment by kendavidn** [comment]
Keeping a close eye on this! I will start moving my workflow from R to Python once a feature like this is implemented!

**Comment by TyberiusPrime** [comment]
> If anyone is still wanting to create combined figures: check out patchworklib that can easily implemented with plotnine figures as wells as seaborn https://github.com/ponnhide/patchworklib

I wish it were that simple, but patchworklib's Readme currently states:
"I could not fully support plotnine version 0.12.1 (It works, but patchworklib arrangement results are not as expected). I will do not support plotnine in the future."
