### ISSUE TITLE
Figure size is not identical to width and height setting in ggplot.save()

### ISSUE THREAD

**Issue by ZhenCaoJack** [has2k1/plotnine#374]
Hi,

I got a question about saving the picture as a png file. 

I set the **width=20,height=10,units="cm"** but only got a figure of **size 16.6cm by 8.7cm**. I searched a lot but could not figure out the question.

This is quite different from the R ggsave function. Is there any design consideration?

Best

**Comment by has2k1** [comment]
Given how we use matplotlib, it is not possible to have accurate figure sizes. It is tangentially related to #46.
