### ISSUE TITLE
scale_*_distiller diverging palette colors are reversed by default

### ISSUE THREAD

**Issue by gokceneraslan** [has2k1/plotnine#377]
Hi,

This code 

```py
ggplot(aes(x='gene', y='tissue'), data=df) +
    geom_point(aes(size='neglog_pval_adj', fill='logodds', color='significant'))+
    scale_fill_distiller(type='div', limits=limit, name='log odds')
```

produces this fill legend:

![image](https://user-images.githubusercontent.com/1140359/77834679-bcdf5f80-711c-11ea-86ec-d0e4b41cef81.png)

However, as we see in colorbrewer the diverging palette looks like the reverse (i.e. brown first, green last)

![image](https://user-images.githubusercontent.com/1140359/77834700-e304ff80-711c-11ea-830f-a1709ff0a0a3.png)

Am I wrong?

When I run:

```py
import mizani

mizani.palettes.brewer_pal(type='div')(7)
```

I get:

```
['#8C510A', '#D8B365', '#F6E8C3', '#F5F5F5', '#C7EAE5', '#5AB4AC', '#01665E']
```

which looks correct, so I'm a bit puzzled why colors are flipped in my plot. Is this related to the direction argument of `mizani.palettes.brewer_pal`?

(I'm using mizani 0.6.0 and plotnine 0.6.0)

**Comment by gokceneraslan** [comment]
Reproducible example:

```py
from plotnine import *
from plotnine.data import mtcars
(ggplot(mtcars, aes('wt', 'mpg', color='disp'))
 + geom_point() + scale_color_distiller(type='div'))
```

Result:

![image](https://user-images.githubusercontent.com/1140359/77834887-991d1900-711e-11ea-8c03-61c2cbaa4d1a.png)

**Comment by gokceneraslan** [comment]
![image](https://user-images.githubusercontent.com/1140359/77834916-cf5a9880-711e-11ea-8fd0-fe75251ac1b3.png)

other palettes have the same problem, too.

**Comment by gokceneraslan** [comment]
R example:

![image](https://user-images.githubusercontent.com/1140359/77835011-b6061c00-711f-11ea-8195-fa31d59cefcc.png)

**Comment by gokceneraslan** [comment]
Hmm colors in Palettable looks reverse: https://jiffyclub.github.io/palettable/colorbrewer/diverging/#brbg_7, maybe @jiffyclub can comment on the issue.

**Comment by has2k1** [comment]
> Hmm colors in Palettable looks reverse: https://jiffyclub.github.io/palettable/colorbrewer/diverging/#brbg_7, maybe @jiffyclub can comment on the issue.

Yes the order is being carried over all the way from palettable.

**Comment by jiffyclub** [comment]
Palettable is creating a matplotlib colormap using the colors in the same order given by colorbrewer, which is brown -> blue -> green (see e.g. [here](https://github.com/axismaps/colorbrewer/blob/e46fd6e6bc6b85fed9d914437636715ad5d3492b/export/colorbrewer.json#L8)). Since the lowest index value in that list is brown, brown ends up mapping to the lowest values in your dataset. Interesting that in R it's reversed, wonder why that is.

**Comment by gokceneraslan** [comment]
Puzzling. For palettes like RdBu, blue is supposed to show lower values I guess. Maybe what they show on the map on colorbrewer2.org and what they provide as output do not agree.
