### ISSUE TITLE
Incomplete display of generated image information

### ISSUE THREAD

**Issue by reBiocoder** [has2k1/plotnine#380]
Picture information is not all displayed

![AOA 5 3T%HFW)KFB`J8 )0W](https://user-images.githubusercontent.com/39401819/78212086-5aea7580-74e1-11ea-8e1d-91e5b76667c7.png)

**Comment by has2k1** [comment]
Please post some more information. What environment are you working in? Does it happen in other environments?

**Comment by reBiocoder** [comment]
thank you, i find the solution of this problem
