### ISSUE TITLE
scale_x_discrete could not recognise parameter `reverse`

### ISSUE THREAD

**Issue by aniruhil** [has2k1/plotnine#383]
```
import pandas as pd
import numpy as np
from pandas.api.types import CategoricalDtype
from plotnine import *
from plotnine.data import mpg
%matplotlib inline
manufacturer_list = mpg['manufacturer'].value_counts().index.tolist()

(ggplot(mpg)
 + aes(x='manufacturer_cat')
 + geom_bar(size=20)
 + scale_x_discrete(limits=manufacturer_list, reverse=True)
 + coord_flip()
 + labs(y='Count', x='Manufacturer', title='Number of Cars by Make')
)
```

>/anaconda3/lib/python3.7/site-packages/plotnine/scales/scale.py:91: PlotnineWarning: >scale_x_discrete could not recognise parameter `reverse`
>  warn(msg.format(self.__class__.__name__, k), PlotnineWarning)

Rest of the code in the plotnine tutorials for ordering bar-charts works fine so I am puzzled why this parameter is failing. 

!< edited >! 
Don't know if this helps but FWIW, `reverse` works if I run the code in a Jupyter notebook but not if I run it in Spyder.

**Comment by has2k1** [comment]
You cannot reverse a discrete scale. The order is determined by the order of the categorical.

>Don't know if this helps but FWIW, reverse works if I run the code in a Jupyter notebook but not if I run it in Spyder.

Was it the same example?

**Comment by aniruhil** [comment]
Yup, exact same piece of code as in the tutorial and it works as it does in the tutorial  in jupyter but not Spyder.

**Comment by has2k1** [comment]
Okay. That was a mistake that worked by accident. So for your case jupyter and spyder are running different versions of plotnine? See the value of  `plotnine.__version__`.

Thanks for catching this, I have fixed the example.
