### ISSUE TITLE
scale_x_discrete using limits breaks tick marks

### ISSUE THREAD

**Issue by katosh** [has2k1/plotnine#389]
This issue is not explained by #342.

## Problem
This assigned tick marks in this plot seem incorrect:
```python
import plotnine as pn
import pandas as pd
pn.ggplot(pn.aes('a'), pd.DataFrame({'a':[2,2,3]})) + pn.geom_bar() \
    + pn.scale_x_discrete(limits=list(range(4)))
```
![image](https://user-images.githubusercontent.com/4857068/80003010-b1374c80-84c0-11ea-8513-209a556f43fd.png)

However, using other limits does work correctly:
```python
pn.ggplot(pn.aes('a'), pd.DataFrame({'a':[2,2,3]})) + pn.geom_bar() \
    + pn.scale_x_discrete(limits=list(range(1, 5)))
```
![image](https://user-images.githubusercontent.com/4857068/80003574-84d00000-84c1-11ea-8ae2-c20151f4f22c.png)

But there seems to be no way to include `0` without having a seemingly wrong assignment of tickmarks.

## Expected Behavior

The tick marks of the bars should correspond to the values associated to the bars.

## Versions
I installed the current master of this repo
```python
>>> import plotnine as pn
>>> pn.__version__
'0.6.0+48.g8125f00'
```
and run it under Python 3.7.3 in a x86_64-conda environment on Ubuntu 18.04.4 LTS.

**Comment by has2k1** [comment]
What is happening is that you confusing the plot. Variable `a` is continuous, but you are giving it a discrete scale. 

> However, using other limits does work correctly:

Even that is just a coincidence, it just appears right. Try altering the limits to `range(2, 6)`! Then also, perhaps if the scaling cannot handle it, it should probably throw an error. So far I do not know if we can detect that.

So, you have two options

```python
# 1. Treat variable `a` as discrete
aes('factor(a)')

# 2. Use a continuous scale
+ pn.scale_x_continuous(limits=(0, 4))
```

**Comment by katosh** [comment]
I expected `geom_bar` to somehow make the x-axis discrete but I guess this is completely determined by the data. Your suggestions work perfectly so I do not consider this an issue anymore. Thank you for your support!
