### ISSUE TITLE
Documentation: link to stat_bin vs. python bin()

### ISSUE THREAD

**Issue by jwhendy** [has2k1/plotnine#391]
Greetings,

I was just looking to refresh myself on the keywords to `geom_historgram`, reading [this page](https://plotnine.readthedocs.io/en/stable/generated/plotnine.geoms.geom_histogram.html). I realized that to find args like `bins` and `binwidth`, I need to look at the stat documentation, not `geom_histogram`:

> stat: str or stat, optional (default: [bin](https://docs.python.org/3/library/functions.html#bin))

Maybe just my opinion, but I'd guess most people don't want to go from plotnine docs to the general formula for bin(), they want to know how to use binning within the context of plotnine. But the only other relevant link is to [stat](https://plotnine.readthedocs.io/en/stable/glossary.html#term-stat), which looks like a class hierarchy page, not one listing stats/explaining how to use them.

Finding what I actually want required: API -> [stats](https://plotnine.readthedocs.io/en/stable/api.html#stats) -> [stat_bin](https://plotnine.readthedocs.io/en/stable/generated/plotnine.stats.stat_bin.html#plotnine.stats.stat_bin)

My opinion: if I'm looking at a page on usage, it makes the most sense to link to other relevant _usage_ pages (which is why I came to the docs), not something like object hierarchies or root function docs.

If you agree, I'd be glad to make PRs as I see things like this.

**Comment by has2k1** [comment]
Thanks for catching that. We can fix this case in the documentation building machinery [here](https://github.com/has2k1/plotnine/blob/8125f0038b948462afd50099a917133d364a2f10/plotnine/doctools.py#L376-L377).

**Comment by jwhendy** [comment]
Wow, that just exploded my mid-level python brain! That's super cool, though I haven't quite digested how things are linked up or where, for example, the link to `bin()` comes from. If you wish to handle this, no problem. I am happy to help with PRs if I can assist, I just might need some coaching! Many thanks.
