### ISSUE TITLE
stat_smooth gives errors for method='loess' and fullrange=True

### ISSUE THREAD

**Issue by MaxThomas90** [has2k1/plotnine#393]
I'm writing writing some code to perform a loess regression using plotnine and skmisc. 
I get  errors when using:
    **lw_model.compute_group(data_inp,xsel,n=len(xsel),fullrange=True,method='loess',method_args={},span=0.8,se=True,level=0.95)**
This is the call back:
  **File "/Users/max/opt/anaconda3/envs/d13C_2/lib/python3.6/site-packages/plotnine/stats/stat_smooth.py", line 191, in compute_group
    rangee = scales.x.dimension()**

  **File "/Users/max/opt/anaconda3/envs/d13C_2/lib/python3.6/site-packages/pandas/core/generic.py", line 5179, in __getattr__
    return object.__getattribute__(self, name)**

**AttributeError: 'Series' object has no attribute 'dimension'**

When **fullrange=False** the loess works well.

The issue is that .dimension is not an attribute of pandas dataframes or numpy arrays, and so returns an error. What data format should 'scales' be?  

Cheers,
Max

**Comment by has2k1** [comment]
Please include a minimal reproducible example. `scales.x` is a supposed to be a scale, how it becomes a Series is likely particular to the code you have. Also make sure you are running the latest version of plotnine.

**Comment by MaxThomas90** [comment]
Thanks for the quick reply. Here's the example:

import numpy as np
import pandas as pd
import plotnine as p9
data = pd.DataFrame({'x':np.random.choice(10,30),'y':np.linspace(1940,2009,30)})
# From what I understand, these are the points at which to output loess predictions
# You mentioned this should be a scale. What is that?
x_scale = pd.DataFrame({'x':np.linspace(1940,2009,100)})
model = p9.stat_smooth()
loess = model.compute_group(data,x_scale,n=100,fullrange=True,method='loess',method_args={},span=0.8,se=True,level=0.95)

This code runs with fullrange=False and fails with fullrange=True.

I'm running plotnine 0.4.0 so I'll update.

**Comment by MaxThomas90** [comment]
Quick update, I've updated to 0.6.0 but the error remains.

**Comment by has2k1** [comment]
I do not understand what you are trying to do.

```python
x_scale = pd.DataFrame({'x':np.linspace(1940,2009,100)})
model = p9.stat_smooth()
loess = model.compute_group(data,x_scale,n=100,fullrange=True,method='loess',method_args={},span=0.8,se=True,level=0.95)
```
This isn't a bug in plotnine, but you using plotnine internals to access loess smoothing. If you want to investigate loess smoothing, use the `skmisc.loess` directly.
