### ISSUE TITLE
facet_grid option to have scales match facet_wrap?

### ISSUE THREAD

**Issue by nikostr** [has2k1/plotnine#394]
Currently `facet_grid` follows the syntax of ggplot2 by having the scales fixed across rows or columns. I would like to be able to have the scales vary by panel as in `facet_wrap` rather than by row or column. Would this be possible? If I understand this correctly, this was also the behavior prior to commit https://github.com/has2k1/plotnine/commit/7df71763830c03d9484263e3ec70052a55dc2877. Perhaps adding an option defaulting to the ggplot2 settings, but allowing scales per panel would be possible?

**Comment by has2k1** [comment]
If you really want it you can override `facet_grid` 

```python
class my_facet_grid(facet_grid):
    def compute_layout(self, data):
        layout = super().compute_layout(data)
        layout['SCALE_X'] = range(1, len(layout)+1)
        layout['SCALE_Y'] = range(1, len(layout)+1)
        layout['AXIS_X'] = True
        layout['AXIS_Y'] = True
        return layout
```

But then you would have to intervene to make space for the labels. So far I do not think there is a strong enough reason have it as one of the options.
