### ISSUE TITLE
Using geom_smooth or stat_smooth with formula

### ISSUE THREAD

**Issue by omrihar** [has2k1/plotnine#395]
What is the correct way to pass a formula to `geom_smooth` or `stat_smooth`? I've tried both using `method_args=dict(formula='y~x')` and `stat_smooth(..., formula='y~x')` and `geom_smooth(...,formula='y~x')`, all without luck.

I looked into the code (e.g. here: https://github.com/has2k1/plotnine/blob/3ea42ce3224572800e791cab9ee540efee6d6ff3/plotnine/stats/smoothers.py#L52) and it seems that formula parameter is taken directly from the geom parameters (not `method_args`), but that it is also not recognized as a valid parameter of the geom. Am I missing something?

Thanks for the awesome library!

**Comment by omrihar** [comment]
I realize now that I'm using plotnine version 0.6.0, which did not include yet the formula parameter :sweat_smile: , so I will close the issue! Do you know, however, when this will be released?

**Comment by has2k1** [comment]
> I realize now that I'm using plotnine version 0.6.0, which did not include yet the formula parameter sweat_smile , so I will close the issue! Do you know, however, when this will be released?

Hopefully in about 2 weeks, but I tend to be at that kind of estimation.
