### ISSUE TITLE
Plotnine throwing error

### ISSUE THREAD

**Issue by Siddharth8** [has2k1/plotnine#396]
When I try to run this below one it says **ValueError: The number of observations must be larger than the number of variables.**

import plotnine as p9
from plotnine import ggplot, aes
import matplotlib.pyplot as plt

p9.options.figure_size = (15,15)
g = (ggplot(data=x2)
     + p9.geom_density_2d(aes(x='age', y='height', color='Class'))
)
g.save('geyser.png')

Note : x2 is a dataframe which has 3 columns (age, height, Class) 
So based on age and height, i have predicted whether it belongs to Class A or B. 

Can someone please help me with this, I need to plot this urgently.

**Comment by has2k1** [comment]
Data `x2` has too few items (rows) or one of the classes A or B has too few items. Either way, the data is being broken down into a group that does not have enough information to compute a density.

**Comment by Siddharth8** [comment]
I have exact no. of rows and for each column in Data x2. So do you mean that we should have more data to compute density ?

**Comment by Siddharth8** [comment]
And to be specific about data size of x2, it is 2000 * 3

**Comment by has2k1** [comment]
Yes make sure there is sufficient data for all the groups in the dataframe. That error is from statsmodels.
