### ISSUE TITLE
Layout Abnormality for show() 

### ISSUE THREAD

**Issue by yangziy** [has2k1/plotnine#397]
Please refer to the picture below. This bug happens only for figures drawn by `show()`. `save()` output is layouted correctly. 

Versions: plotnine == 0.6.0; matplotlib == 3.1.3; python == 3.6; backend: interagg of PyCharm

```
import plotnine as p9
import plotnine.data

import matplotlib
df = plotnine.data.mpg
# print(matplotlib.get_backend())

fig_withoutColorAes = (p9.ggplot(df, p9.aes('displ', 'hwy'))
                    + p9.geom_point()
                    + p9.facet_wrap('class')
                    + p9.ggtitle('faceting figure withColorAes')
                    )
print(fig_withoutColorAes)

fig_withColorAes = (p9.ggplot(df, p9.aes('displ', 'hwy', color='class'))
                       + p9.geom_point()
                       + p9.facet_wrap('class')
                       + p9.ggtitle('faceting figure withoutColorAes')
                       )
print(fig_withColorAes)
```

Warning message:
```
UserWarning: Tight layout not applied. tight_layout cannot make axes width small enough to accommodate all axes decorations
  self.figure.tight_layout()
```

![image](https://user-images.githubusercontent.com/13228324/81675338-4a98b500-9414-11ea-8a4b-407cb21a7d14.png)

![image](https://user-images.githubusercontent.com/13228324/81675353-508e9600-9414-11ea-9c05-28c3a6c390c6.png)

**Comment by has2k1** [comment]
I do not know what backend you are using. But the proper way to get the plots is to print them.

```python
print(fig_withoutColorAes)
print(fig_withColorAes)
```

**Comment by yangziy** [comment]
Thank you for your kind reply. I was using PyCharm SciView and they implemented their own backend called "interAgg" which is the cause. There are other complaints about the backend, so it's probably their fault.

**Comment by has2k1** [comment]
> I was using PyCharm SciView and they implemented their own backend called "interAgg" which is the cause.

I do not use SciView yet I think that explains issue https://github.com/has2k1/plotnine/issues/137 too.

**Comment by yangziy** [comment]
The source of the backend is here for anyone who's interested in it.

https://github.com/JetBrains/intellij-community/tree/master/python/helpers/pycharm_matplotlib_backend
