### ISSUE TITLE
Removing numbers from y-axis, while retaining tickmarks

### ISSUE THREAD

**Issue by vsahil** [has2k1/plotnine#399]
Hello, I have a facet plot in which all have the same y axis: 0 to 20. Therefore I want to remove the numbers from all plots, except the leftmost, but I want to retain the tickmarks in the remaining. Here is how the plot looks like and my code. Can you please tell me what should I add in the code to achieve this? If this is not possible, can I put a space between the facets so that they don't overlap? 
<img width="982" alt="Screenshot 2020-05-13 at 7 18 13 PM" src="https://user-images.githubusercontent.com/17141214/81885131-7e77f580-954e-11ea-866a-886509ec3db7.png">
<img width="973" alt="Screenshot 2020-05-13 at 7 19 24 PM" src="https://user-images.githubusercontent.com/17141214/81885195-a9fae000-954e-11ea-97c9-e86b63159d0b.png">

**Comment by has2k1** [comment]
You can increase the spacing with

```python
+ theme(subplots_adjust={'wspace': 0.2})
```

If you want finer control of the text, then you have to drop into matplotlib.

```python
fig = (ggplot(..) + ...).draw()

# Iterate through the axes and manipulate whatever you want
# Look up the matplotlib documentation on how to access different attributes
for ax in fig.axes:
    ...
```
