### ISSUE TITLE
Display legend in individual subplots

### ISSUE THREAD

**Issue by PedroBarbosa** [has2k1/plotnine#400]
Hi,

I'm having a hard time to figure out a way to display multiple legends in a GridSpec. Maybe it is something trivial, but I kindly ask for help. Why doesn't the legend automatically appears for all the axes ? It just shows up the last one. Additionally, a large empty space is displayed between axes (1st fig). If I remove the legend from plotnine (`p9.guides(fill=False)`), the plot layout is fine (2nd fig), but I can't find a way to manually add the proper legend to each subplot. I tried to iterate through each ax and `ax.legend(...)`, without any success. Any help ?

Fig1
![Screenshot 2020-05-17 at 01 19 10](https://user-images.githubusercontent.com/4269608/82132940-6f5aa700-97dd-11ea-8d82-f1b5543b2a6f.png)

Fig2
![Screenshot 2020-05-17 at 01 18 12](https://user-images.githubusercontent.com/4269608/82132943-7aadd280-97dd-11ea-8ff2-920221de79d6.png)

Code:
```  
import plotnine as p9
from matplotlib import gridspec
import matplotlib.pyplot as plt
        
#Line plot 
p1 = (p9.ggplot(time_df, p9.aes(x='Context', y='Parameters')) + p9.geom_line(group=1, size = 1) + p9.geom_point()     
            + p9.theme(axis_text_x = p9.element_blank(), axis_title_x= p9.element_blank(), text = p9.element_text(size = 12))
            + p9.scale_y_continuous(name = "Number of parameters", labels = add_units))


#Grouped barplot of the training and testing time for each experiment
p2 = (p9.ggplot(time_df, p9.aes(x='Context', y='Time_elapsed', fill = "variable")) 
            + p9.geom_col(stat = "identity", position = "dodge", width = 0.5, alpha = .5, colour = "black") 
            + p9.scale_y_continuous(name = "Time elapsed (min)") 
            + p9.theme(axis_text_x = p9.element_text(angle = 45, hjust = 1), 
                    text = p9.element_text(size = 12),
                    subplots_adjust={'bottom': 0.25, 'right': 0.85},figure_size=(12,7))
             )
        
 
##Stacked and grouped barplot with counts of each label per experiment
p4 = (p9.ggplot(label_counts_grouped[label_counts_grouped.Data == "Train"], p9.aes(x='Context', y="Count", fill = "Label")) +
              p9.geom_col(stat = "identity", position = 'dodge', alpha=0.7, colour= "black", width=0.7) +
              p9.scale_y_continuous(name = "# Training instances", labels = add_units) +
              p9.scale_fill_manual(values = ["darkgrey","darkslateblue","brown"]) +
              p9.theme(figure_size = (10,7), axis_text_x = p9.element_blank(), axis_title_x= p9.element_blank(),
                       text = p9.element_text(size = 12), subplots_adjust={'right': 0.85}) 
             )
```
#This next chunk I copied from #373
``` 
fig = (p9.ggplot()+ p9.geom_blank(data=time_df) + p9.theme(subplots_adjust={'bottom': 0.25, 'right': 0.85}, figure_size=(12,12))).draw()
        

gs = gridspec.GridSpec(3,1)
ax1 = fig.add_subplot(gs[0,0])
ax2 = fig.add_subplot(gs[1,0])
ax3 = fig.add_subplot(gs[2,0])
        
# Add subplots to the figure
 _ = p1._draw_using_figure(fig, [ax2])
 _ = p2._draw_using_figure(fig, [ax3])
 _ = p4._draw_using_figure(fig, [ax1])
```

Thanks,
Pedro

**Comment by benjaminleroy** [comment]
I assume this was resolved off this github page, but through looking at code, the current implementation ties legend to the figure structure itself, whereas the plots are connected to the axes elements (if we're thinking in terms of Matplotlib fig and axes - which we should). This actually is the same problem that @has2k1 has been emphasizing with his requests for changes to the [Matplotlib fig/axes structure](https://github.com/matplotlib/matplotlib/issues/1109#issuecomment-319424072). 

The methods that effect that the printing of legends that you are using is [`._draw_using_figure`](https://github.com/has2k1/plotnine/blob/cefaf3e1923c4839825b4a3030e22cadfa1f666d/plotnine/ggplot.py#L223) in that function there is a call for [`._draw_legend`](https://github.com/has2k1/plotnine/blob/cefaf3e1923c4839825b4a3030e22cadfa1f666d/plotnine/ggplot.py#L412). It's in that function `._draw_legend`, that affects where the legend location (and it's figure related). Corrections to this aren't global - the structure still can't deal with a 2 x 2 grid with legends for each. On the other hand - defining a `._draw_legend2` and then a  `._draw_using_figure2` could give you more control over where the legends are placed.

**Comment by has2k1** [comment]
Using private methods from the plotnine code base is out of scope for the help that I can offer. But hopefully, the desired outcome of this issue will be easier to achieve in the future.
