### ISSUE TITLE
Custom fun_data for stat_summary

### ISSUE THREAD

**Issue by psandev** [has2k1/plotnine#405]
Hi,
 I wrote the following function for fun_data according to the user manual. The function accepts and array and returns a three-row dataframe with indexes  y, ymin and ymax.
```python
def custom_stat(ar):
    return pd.DataFrame([np.mean(ar), np.percentile(ar, 2.5), np.percentile(ar, 97.5)], index=['y', 'ymin', 'ymax'])
```

and I am using it like this:

 stat_summary(fun_data = custom_stat, geom = "errorbar")
The error I am getting is: plotnine.exceptions.PlotnineError: 'geom_errorbar requires the following missing aesthetics: ymax, ymin'
plotnine version: 0.70

**Comment by has2k1** [comment]
It is a mistake in the documentation. They should be columns, `y`, `ymin` & `ymax`.

So this should give you what you want.

```python
def custom_stat(ar):
    return pd.DataFrame({
        'y': [np.mean(ar)],
        'ymin': np.percentile(ar, 2.5),
        'ymax': np.percentile(ar, 97.5)
    })
```

**Comment by psandev** [comment]
Thank you very much.
