### ISSUE TITLE
Incorrect grouped bar chart label positioning

### ISSUE THREAD

**Issue by psandev** [has2k1/plotnine#406]
Hi,
my plot is this:
p = ggplot(df_focus, aes(x='Focus',  fill='Repetition')) +\
   geom_bar(position='dodge') +\
    geom_text(aes(label='stat(count)'),
              position=position_dodge(width=0.9),
         stat='count',
         nudge_y=0.125,
         va='bottom'
     )
 I used this tutorial: https://plotnine.readthedocs.io/en/stable/generated/plotnine.geoms.geom_col.html

What I get is that the labels are not split to the separate columns no matter what width I use in position_dodge. Here is what I get:

![image](https://user-images.githubusercontent.com/30928228/84566941-d9834f00-ad7d-11ea-8018-83c1cceadd27.png)

I am pretty sure this worked before, but I also went back to version 0.6 and it was the same

**Comment by has2k1** [comment]
Do not nudge the text, `nudge_y` overrides `position_dodge` width `position_nudge(y=0.125)`.

**Comment by psandev** [comment]
Thanks a lot. If only all developers were as quick as you...
Now there is another issue, which I keep seeing. Sometimes the notation of the highest bar is cut.
Please, see the selected area.

![image](https://user-images.githubusercontent.com/30928228/84568938-8b754800-ad8b-11ea-9c3c-fc58ffc24e9a.png)

**Comment by psandev** [comment]
Here is another snapshot, which emphasizes better the issue:

![image](https://user-images.githubusercontent.com/30928228/84569047-4d2c5880-ad8c-11ea-886f-143aa60d3c94.png)

**Comment by has2k1** [comment]
Extend the high limit of the y scale i.e  `+ lims(y=(None, 1100))` or in this case it is more accurate to the limits of the coordinate system  `+ coord_cartesian(ylim=(None, 1100))`.

**Comment by psandev** [comment]
Thank you again. This workaround works when all plots have the same height. How to apply it when scales is 'free_y' in facet_grid?

**Comment by has2k1** [comment]
See the [expand](https://plotnine.readthedocs.io/en/stable/generated/plotnine.scales.scale_y_continuous.html#plotnine.scales.scale_y_continuous) parameter of continuous scales. You get to do something like

`+ scale_y_continuous(expand=(0.05, 0, 0.15, 0))`

**Comment by psandev** [comment]
Again, many thanks. It is not perfect since y-axis values are quite different and the scale affects them proportionally, but it is the best available. I learnt a lot today.
