### ISSUE TITLE
Can you demonstrate a method to add a watermark to an image?

### ISSUE THREAD

**Issue by BlackArbsCEO** [has2k1/plotnine#41]
Here are a couple examples: 

bottom left corner:
![image](https://user-images.githubusercontent.com/7452471/28689947-b264e0f0-72d4-11e7-850e-acddfc02ba9c.png)

across the middle: 
![image](https://user-images.githubusercontent.com/7452471/28689998-d9ecca5c-72d4-11e7-9a5f-79a79b9e30ab.png)

**Comment by has2k1** [comment]
You will have to drop down into matplotlib for that.

```python
wm = plt.imread('watermark.png')
p = ggplot() + ...
fig = p.draw()
fig.figimage(wm, ...)
```
