### ISSUE TITLE
Incorrect plot layout when plotting from IDE. Legend gets cut.

### ISSUE THREAD

**Issue by psandev** [has2k1/plotnine#412]
Hi,
I am plotting from PyCharm using plot(p). The plot does not take into account the legend width and as a result, it is cut. See below.

![image](https://user-images.githubusercontent.com/30928228/86792565-4d5e0200-c073-11ea-8c56-a780d1283973.png)

**Comment by has2k1** [comment]
Make space for the legend e.g 

```python
(ggplot(...)
 ...
 + theme(subplots_adjust={'right': 0.80}) # choose an appropriate value
)
```
