### ISSUE TITLE
How to support CJK character (chinese, japanese and korea) in plotnine

### ISSUE THREAD

**Issue by thunderhit** [has2k1/plotnine#414]
Hello,

Plotnine is a wonderful package, I really loved it. I am trying to figure out how to support CJK character in plotnie. I know plotnine is based on matplotlib, I tried add the below code before using plotnine

```python
import matplotlib.pyplot as plt

plt.rcParams['font.sans-serif'] = ['SimHei', 'Arial Unicode MS']
```

But this method dont work!Now I'm confused, and don't know how to make it work. Any guidance is greatly appreciated.

Thank you.

**Comment by has2k1** [comment]
Use `theme` to set the family for the text.

```python
(ggplot()
  ...
 + theme(text=element_text(family=['SimHei', 'Arial Unicode MS']))
)
```

**Comment by thunderhit** [comment]
Really appreciate your reply，Thanks！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Hassan Kibirige"<notifications@github.com&gt;; 
发送时间: 2020年7月9日(星期四) 下午3:33
收件人: "has2k1/plotnine"<plotnine@noreply.github.com&gt;; 
抄送: "邓旭东"<thunderhit@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [has2k1/plotnine] How to support CJK character (chinese, japanese and korea) in plotnine (#414)





 
Use theme to set the family for the text.
 (ggplot()   ...  + theme(text=element_text(family=['SimHei', 'Arial Unicode MS'])) )
