### ISSUE TITLE
tips for adding / testing new geoms for image data and labels

### ISSUE THREAD

**Issue by orm011** [has2k1/plotnine#416]
Thanks for your library, it saves me a lot of time to be able to use gg API while still in python.

I work a lot with image data and image labels, and want to try applying some of the same ideas of gg to visualize this type of data . Some things about images are different from what current geoms offer (eg, you need to call imshow somewhere), but some others like the need to encode certain data attributes, such as box color, text, etc. are similar to what you already have in plotnine. 

It seemed to me like extending plotnine by adding some basic geoms may be an easy way to prototype these ideas while getting a lot of functionality out of the box.  I have a couple of geometries I'd like to implement to get something useful. One is a way to show an image (or set of images), another is a way to display bounding boxes over the images, while using other attributes of the boxes to determine aesthetics such as color. I'd like to be able to remain able to use facets over all this. (eg, imagine I have two images, and boxes for each, or same image, but want to show predicted boxes on left facet and real boxes on right facet). 

My first attempt was to  define a new geom like this:

```
class geom_image(geom):
    DEFAULT_AES = {'alpha': 1}#, 'color': None, 'fill': '#333333',
                   #'linetype': 'solid', 'size': 0.5 }
    DEFAULT_PARAMS = {'stat': 'identity', 'position': 'identity',
                      'na_rm': False, 'inherit_aes': False} # no idea if I need this
    REQUIRED_AES = {'image'} # just need an image column

    def draw_panel(self, data, panel_params, coord, ax, **params):
        """
        assume only one image per panel,
        """
        w,h = data['image'].iloc[0].size
        ax.imshow(data['image'].iloc[0], alpha=data['alpha'].iloc[0], 
                 extent=(-.05,1.05,-.05,1.05),  aspect=h/w) 
```

0) This actually worked (showed an image with the right ratio) for expression  `ggplot() + geom_image(...)`
But it stopped working if I added a geom_map() as a way to try to show boxes. In that case only the boxes were shown,
 and I noticed the draw_panel() method in geom_image() was never called. ~I also found geom_map() didn't play well with facet_wrap(), it crashed instead.~ (fixed after upgrading to 0.7)

1) Any tips on how to add such a geom? what are the plotnine basics  I should know in order to add a geom and get to 
having both of these geoms. 

2) one point of friction is the way coordinates work for images vs. other plots. often, top left is (0,0), and annotations within
images eg for boxes or text are based on that system.  imshow() lets one specify this, but if I use geom_image()  and would like to inter operate with things like geom_text or geom_map, with the user thinking in image style coordinates on both geoms.  

3) Another thing when working with images is we probably want by default to preserve individual image aspect ratios

PS. There are other geoms I would like to try out as well (eg, one that calls matshow(), eg for overlaying some type of heatmap on top of geom_image(), expressed as numpy array, using a similar coordinate system to the image.

**Comment by has2k1** [comment]
You are on the right track. If it gives you what want then it is okay. However, consider this.
How general do you want `geom_image` to be. Can it plot multiple images in one call, or is it just to
provide a background image? If it is the later then consider calling it an annotation and not a geom.

The best way to creating any geom is to figure exactly how to create the plot, preferably using plain matplotlib and then decompose into a `geom` and/or `stat`.

Keep the issues focused on one thing and try to make sure the code you post is simple and can be run to show what you are trying to do.
