### ISSUE TITLE
bw parameter in stat_density

### ISSUE THREAD

**Issue by jvinte** [has2k1/plotnine#418]
First of all, thanks for providing this awesome package!

However, there is an issue w.r.t. to setting the bandwidth parameter. When setting the bw parameter in `stat_density` it is not passed through. Instead, the default value 'normal_reference' is used. Here is my small example:

`(ggplot(stats_plot_all, aes(x='values', color='task', fill='task'))
            + geom_density(alpha=0.1)
            + stat_density(bw=1.5)
            + facet_wrap('~metrics', nrow=6, ncol=3, scales='free'))`

Thanks for your time!

**Comment by has2k1** [comment]
Make sure you are using the latest version `0.7.0`.
