### ISSUE TITLE
putting tick labels in LaTex formatted scientific notation?

### ISSUE THREAD

**Issue by jbloom** [has2k1/plotnine#42]
Is there a way to put tick labels in real scientific notation using LaTex formatting? I want something like `1e7` to appear as a 10 with the superscript exponent 7.

**Comment by has2k1** [comment]
Yes, assuming you know the breaks.

```python
df = pd.DataFrame({'x': [1, 10, 100, 1000, 10000, 100000]})

(ggplot(df)
 + geom_point(aes('x', 'x'))
 + scale_x_log10(labels=['$10^1$', '$10^3$', '$10^5$'])
)
```

Otherwise, you can write a function (takes breaks and returns labels enclosed in `$$`) to do the labelling.

```python
def label_func(breaks):
    return ['$10^{}$'.format(int(np.log10(i))) for i in breaks]

(ggplot(df)
 + geom_point(aes('x', 'x'))
 + scale_x_log10(labels=label_func)
)
```
