### ISSUE TITLE
Rasterized colorbars in PDFs are not recognized by Adobe Illustrator

### ISSUE THREAD

**Issue by gokceneraslan** [has2k1/plotnine#422]
When I try to edit a PDF generated by plotnine in Illustrator, I get an `An unknown imaging construct was encountered.` warning if there is a continuous color scale in the plot (e.g. gradient). This also makes the color legend uneditable. I was wondering why this might be happening and so I made some experiments with matplotlib and also ggplot2 in R.

This is a simple example to generate such a plot:

```python
from plotnine import *
import numpy as np

x = np.linspace(0, 1, 10)
g = qplot(x, x, color=x, geom='point')
ggsave(g, 'ggplot-python.pdf')
```

Here is how it looks like in Illustrator, big X sign indicates the "unknown imaging construct" (for some reason it covers the entire image but it is actually only due to the color legend):

![image](https://user-images.githubusercontent.com/1140359/88247844-3ae7e900-cc6d-11ea-912b-192ad9e9896f.png)

When I move the legend around:

![image](https://user-images.githubusercontent.com/1140359/88249633-07a85880-cc73-11ea-9349-7c13a31ae859.png)

However a simple gradient produced directly by matplotlib renders fine and is editable:

```python
f, ax = plt.subplots(figsize=(4,0.5))
gradient = np.linspace(0, 1, 256)
gradient = np.vstack((gradient, gradient))
ax.imshow(gradient, aspect='auto', cmap=plt.get_cmap('viridis'))
f.savefig('matplotlib.pdf')
```

![image](https://user-images.githubusercontent.com/1140359/88248113-0c1e4280-cc6e-11ea-8f7a-51d648d64a90.png)

Last, I tried the R equivalent of the first code:

```r
library(ggplot2)

x = seq(0, 1, by=0.1)
g = qplot(x, x, color=x)

ggsave('ggplot-R.pdf')
```

Color bar in this PDF looks perfectly fine and there is no warning at all:

![image](https://user-images.githubusercontent.com/1140359/88248055-d7aa8680-cc6d-11ea-9e38-ec7d6c8983bb.png)

I know that asking for a fix that affects only (and is reproducible only with) Illustrator which is a proprietary software, is not very meaningful, given that plotnine is a great free software. But I just wanted to ask if there is anything weird about the PDFs with gradients produced by plotnine, or can we make them more "R-like" so that they are easier to edit.

Cheers.

**Comment by gokceneraslan** [comment]
Apparently this is about the rasterization of the colorbar. But I'm still confused.

```python
ggplot(aes(x='x', y='x', color='x'), data=df) + geom_point() + guides(color=guide_colorbar(raster=False, nbin=100))
```

This plot looks fine and the colorbar is editable, it's bunch of rectangles after all. However I still do not understand why rasterized colorbar is not recognized by Illustrator. Interestingly, R also rasterizes the colorbar by default but it looks totally fine in Illustrator.

@has2k1 Could this be about the shading in QuadMesh? I'm sure you looked into it before.

**Comment by gokceneraslan** [comment]
```python
import matplotlib.pyplot as plt;
import numpy as np;

x1 = np.random.randn(100);
x2 = np.random.randn(100);
x3 = np.random.randn(100, 100);

fig, ax = plt.subplots();

quadMeshCol = ax.pcolormesh(x1, x2, x3, shading='gouraud');

plt.show();
```

gives the same error whereas

```python
import matplotlib.pyplot as plt;
import numpy as np;

x1 = np.random.randn(100);
x2 = np.random.randn(100);
x3 = np.random.randn(100, 100);

fig, ax = plt.subplots();

quadMeshCol = ax.pcolormesh(x1, x2, x3, shading='flat');

plt.show();
```

therefore it seems like shading is the problem.

**Comment by gokceneraslan** [comment]
I was wondering if we can simply pass `rasterized=True` to the `PolyCollection`, so I made the following modification:

![image](https://user-images.githubusercontent.com/1140359/88299628-91d2da00-ccd0-11ea-9844-b6409ffd877d.png)

But then the colorbar is misplaced in the plot:

![image](https://user-images.githubusercontent.com/1140359/88301520-b5971f80-ccd2-11ea-802d-a8b9a9614834.png)

**Comment by gokceneraslan** [comment]
I also wonder if there are things to borrow from mpl's colorbar, which renders fine, is editable and not rasterized at all.

![image](https://user-images.githubusercontent.com/1140359/88307061-7b7d4c00-ccd9-11ea-844f-cdab3601daf2.png)

**Comment by has2k1** [comment]
Thanks for trying to get to the bottom of this. This issue is like bad xml/html markup where some tag/attribute is badly encapsulated. I think I will wait and see want comes from the matplotlib bug report.

**Comment by gokceneraslan** [comment]
Thanks @has2k1 . Do you remember why you do not simply rasterize the PolyCollection and use QuadMesh without `rasterized=True` (so actually without any rasterization) instead?

**Comment by has2k1** [comment]
I recall to have looked at how the colorbar was implemented in Matplotlib, it was quite involved but I noticed that `Quadmesh` was used and so I build a solution using Quadmesh. I do not recall even thinking about PolyCollection!
