### ISSUE TITLE
Labelling x-axis for facet wrapped bar charts with ordered categories

### ISSUE THREAD

**Issue by zeyalt** [has2k1/plotnine#423]
[top5.xlsx](https://github.com/has2k1/plotnine/files/4992974/top5.xlsx)
![image](https://user-images.githubusercontent.com/58053561/88764303-a1d53880-d16c-11ea-9f50-82e7d3aa260c.png)

Hello, 

I'm trying to use Plotnine to draw a facet wrap using the attached data. The attached picture shows something very close to what how I want the graph to look like, except that instead of the numbers on the x-axis, I would like to display the names of the corresponding categories according to the data. My code is as follows:

```
index_list = list(b_top5_1.index)
labels_list = list(b_top5_1.scam_type)


g9 = (p9.ggplot(data=b_top5_1, 
           mapping=p9.aes(x='index', y='count'))
+ p9.geom_col(fill = "#ADD8E6", width=0.7)
+ p9.facet_wrap("~year", ncol=5, scales='free')
+ p9.theme_minimal() 
+ p9.theme_bw() 
+ p9.ylab("Number of Scam Reports")
+ p9.xlab("") 
+ p9.theme(subplots_adjust={'wspace': 0.25}, figure_size=(13, 5), axis_text_x = element_text(rotation=90)))


g9
```

I know that in order to do that, I need to use the function `scale_x_discrete`, specifying the arguments for breaks, labels and/or limits. However, I've been trying to do that but have not been successful. Can you advise me please?

Zeya

**Comment by TyberiusPrime** [comment]
It appears to me that all you need to do is replace 
```mapping=p9.aes(x='index', y='count'))```
with 
```mapping=p9.aes(x='scam_type', y='count'))```

To change the order, convert your scam_type column to a pandas.Categorical(b_top5_1.scam_type, [...]).

**Comment by zeyalt** [comment]
Thanks for that suggestion. That works partially! 

The reason I used 'index' was so that I could sort the values within each year from largest to smallest. When I changed `x='index'` to `x='scam_type'`, the x-axis labels changed to the names of the categories, but they are now no longer sorted from largest to smallest. Please see the image attached.

![image](https://user-images.githubusercontent.com/58053561/88769230-13fd4b80-d174-11ea-8a08-6de381821ab2.png)

Is there a way to sort them from largest to smallest within each year?

**Comment by zeyalt** [comment]
Thanks for that suggestion! That works to change the x-axis labels to the names of the categories, but I still need to change the order. Could you guide me on how to use pandas.Categorical(b_top5_1.scam_type, [...])? I'm trying but I'm not very sure and I still couldn't do it. Thanks so much.

**Comment by TyberiusPrime** [comment]
All you need to do is pass in the desired order of labels in the [...].
It will be the same order in each facet though. 

That is by design and the 'grammar of graphs', 
and I'd humbly suggest to rethink your goal if you want them sorted by size in
each subgraph - you are violating the reader's assumptions that the x-axis
stays the same order in each graph and making it very hard to compare the year-to-year
changes. 

Possibly try faceting the other way - by scam type. Or even a stacked bar plot with colors (uhg) if you want to show the year-to-year distribution.

**Comment by zeyalt** [comment]
Thanks so much for your advice. 

My intention is actually to show how the top 5 changed year to year, not so much of how the individual scam types changed (I have a separate plot showing that already). 

I'm adopting the idea from https://drsimonj.svbtle.com/ordering-categories-within-ggplot2-facets in creating this plot.  

I've taken your advice regarding pd.Categorical and now my code looks like this:

```
b_top5_1.scam_type = pd.Categorical(b_top5_1.scam_type, list(b_top5_1.scam_type.unique()), ordered=True)

index_list = list(b_top5_1.index)
labels_list = list(b_top5_1.scam_type)

g9 = (p9.ggplot(data=b_top5_1, 
           mapping=p9.aes(x='scam_type', y='count'))
+ p9.geom_col(fill = "#ADD8E6", width=0.7)
+ p9.facet_wrap("~year", ncol=5, scales='free_x')
+ p9.theme_minimal() 
+ p9.theme_bw() 
+ p9.ylab("Number of Scam Reports")
+ p9.xlab("") 
+ p9.theme(subplots_adjust={'wspace': 0.25}, figure_size=(13, 5), axis_text_x = element_text(rotation=90))
+ p9.scale_x_discrete(breaks=index_list, labels=labels_list, expand=(0,0)))

g9
```
However, I'm getting this error: `TypeError: object of type 'NoneType' has no len()`. Can't figure out what's wrong.

**Comment by has2k1** [comment]
You can do per facet ordering by creating a variable whose values are unique to each facet and then order that variable by the count. In your case, prepend the `year` (facetting variable) to the `scam_type` to create such a variable and using a labeling function to correct the labels for the x scale.

```python
import plotnine as p9
import pandas as pd

df = pd.read_excel('top5.xlsx', usecols='B:E')
df['scam_type_pa'] = df['year'].astype(str) + df['scam_type']

g9 = (p9.ggplot(data=df, 
           mapping=p9.aes(x='reorder(scam_type_pa, count)', y='count'))
+ p9.geom_col(fill = "#ADD8E6", width=0.7)
+ p9.facet_wrap("~year", ncol=5, scales='free')
+ p9.theme_bw() 
+ p9.ylab("Number of Scam Reports")
+ p9.xlab("") 
+ p9.theme(subplots_adjust={'wspace': 0.25}, figure_size=(13, 5), axis_text_x = p9.element_text(rotation=90))
+ p9.scale_x_discrete(labels=lambda lbls : [s[4:] for s in lbls])
)
```

![scam](https://user-images.githubusercontent.com/780341/88864535-1a400600-d20e-11ea-9f81-c1e6012b605e.png)

**Comment by zeyalt** [comment]
That's perfect! I'm just wondering, if I would like to make a small tweak - to order the bars from largest to smallest, instead of smallest to largest - how should I do that?

**Comment by has2k1** [comment]
mapping=p9.aes(x='reorder(scam_type_pa, -count)', y='count'))
