### ISSUE TITLE
Plot with different geoms and legend

### ISSUE THREAD

**Issue by zePanzerfaust** [has2k1/plotnine#426]
Hello,

how can I combine multiple geoms and get a legend?
The first image is using separate data in a pandas data frame, see the code below to produce such an output.
![separate_columns](https://user-images.githubusercontent.com/14841658/89157443-d3834080-d56c-11ea-9c93-85fa6e05799d.png)
The second image uses tidy data, as far as I understood it. This produces the desired legend.
![tidy_data](https://user-images.githubusercontent.com/14841658/89157448-d54d0400-d56c-11ea-858a-beea3cee8482.png)
My goal is to get the first image but with legend. One data set as a black geom_line() and the other red geom_point() with tidy data, as this seems to be how it is done.
```
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
import plotnine as pn

# define your x_values, measurements, data here

df = pd.DataFrame(data={
    'x': x_values,
    'y_measurement': measurements,
    'y_data': data
    })
df_melt = df.melt(id_vars=['x'], value_vars=['y_data', 'y_measurement'], var_name='data_type', value_name='data_and_measurement')
pn_handle = pn.ggplot(df) \
            + pn.aes(x='x') \
            + pn.geom_line(pn.aes(y='y_data'), color='black', alpha=1.0) \
            + pn.geom_point(pn.aes(y='y_measurement'), color='red', alpha=0.5) \
            + pn.labs(title='Title', x='Samples [n]', y='Value') \
            + pn.theme_light()
pn_handle.draw()
plt.show()

pn_handle = pn.ggplot(df_melt) \
            + pn.aes(x='x', y='data_and_measurement') \
            + pn.geom_line(pn.aes(color='data_type'), alpha=1.0) \
            + pn.geom_point(pn.aes(color='data_type'), alpha=0.5) \
            + pn.labs(title='Title', x='Samples [n]', y='Value') \
            + pn.theme_light()
pn_handle.draw()
plt.show()
```

**Comment by has2k1** [comment]
This type of plot is of a bad taste because one variable is represented by a different categories geometries. As a result you end up fighting the system. But if you really must go ahead with it, here is the trick. Create function that nulls unwanted values of the variable and those values will be dropped by the geoms. e.g.

```python
def drop(s, idx):
    s[idx] = None
    return s

(ggplot(...)
 + geom_point(aes(y='drop(data_and_measurement, data_type!="y_data")'))
 + geom_line(aes(y='drop(data_and_measurement, data_type!="y_measurement")'))
)
```

**Comment by zePanzerfaust** [comment]
Using the suggested workaround did not produce the result. It does not want to draw the geom_line. If I change it to geom_point too, it draws both geoms, but there is no legend.
The following code was used.
```
pn_handle = pn.ggplot(df_melt) \
            + pn.aes(x='x', y='data_and_measurement') \
            + pn.geom_line(pn.aes(y='drop(data_and_measurement, data_type!="y_data")'), color='black', alpha=1.0) \
            + pn.geom_point(pn.aes(y='drop(data_and_measurement, data_type!="y_measurement")'), color='red', alpha=0.5) \
            + pn.labs(title='Title', x='Samples [n]', y='Value') \
            + pn.theme_light()
pn_handle.draw()
plt.show()
```
But if it is not meant to be used in that way, that is fine with me. No need for hacky workarounds.
Thank you for taking the time.

**Comment by has2k1** [comment]
> Using the suggested workaround did not produce the result. It does not want to draw the geom_line. If I change it to geom_point too, it draws both geoms, but there is no legend.
> The following code was used.
> 
> ```
> pn_handle = pn.ggplot(df_melt) \
>             + pn.aes(x='x', y='data_and_measurement') \
>             + pn.geom_line(pn.aes(y='drop(data_and_measurement, data_type!="y_data")'), color='black', alpha=1.0) \
>             + pn.geom_point(pn.aes(y='drop(data_and_measurement, data_type!="y_measurement")'), color='red', alpha=0.5) \
>             + pn.labs(title='Title', x='Samples [n]', y='Value') \
>             + pn.theme_light()
> pn_handle.draw()
> plt.show()
> ```
> 
> But if it is not meant to be used in that way, that is fine with me. No need for hacky workarounds.
> Thank you for taking the time.

The modifications were meant for the 2nd chunk of code i.e the one that gives the legend.
