### ISSUE TITLE
An issue in datetime transformation

### ISSUE THREAD

**Issue by randomizedthinking** [has2k1/plotnine#429]
I would like to apply a tranformation on x-axis, which is a datatime field, yet receive the following errors:

````
TypeError: Discrete value supplied to continuous scale
````

Below is a simple code for duplicate the problem. Note that the transformation is actually an identity transformation, but it still does not work.

````python
import pandas as pd
from datetime import datetime, timedelta
from plotnine import ggplot, geom_line, aes, scale_x_datetime

t0 = datetime(2020, 8, 13, 12, 24, 12)
data = pd.DataFrame({'X': [6,7,9,10,13]})
data['Time'] = [t0+timedelta(seconds=i) for i in range(5)]
 
from mizani.transforms import trans
class id_trans(trans):
    @staticmethod
    def transform(x):
        return x
    @staticmethod
    def inverse(x):
        return x

(
    ggplot()
    + geom_line(aes(x="Time", y="X"), data=data)
    + scale_x_datetime(trans=id_trans)
)
````

**Comment by has2k1** [comment]
The output of the `transform` method should be in numerical form i.e float or integer and the `inverse` method should undo that. For example `timedelta_trans.transform` returns the time difference in microseconds which is an integer, and `timedelta_trans.inverse`  takes the microseconds (an integer) and returns timedeltas.

That is why an identity transform will not work for timedeltas, the plotting system cannot handle timedeltas (or any other non-numerical formats) directly.

**Comment by randomizedthinking** [comment]
Thanks. Based on the information, the code is now revised as:

````python
import pandas as pd
from datetime import datetime, timedelta
from plotnine import ggplot, geom_line, aes, scale_x_datetime

t0 = datetime(2020, 8, 13, 12, 24, 12)
data = pd.DataFrame({'X': [6,7,9,10,13]})
data['Time'] = [t0+timedelta(seconds=i) for i in range(5)]
 
from mizani.transforms import trans
class id_trans(trans):
    @staticmethod
    def transform(x):
        t0 = datetime(2020, 8, 13, 12, 24, 12)
        return (x - t0).apply(lambda t: t.seconds)
    @staticmethod
    def inverse(x):
        t0 = datetime(2020, 8, 13, 12, 24, 12)
        return [t0 + timedelta(seconds=s) for s in x]

(
    ggplot()
    + geom_line(aes(x="Time", y="X"), data=data)
    + scale_x_datetime(trans=id_trans)
)
````

The logic should be correct, but we receive another error message now:

````
TypeError: '>=' not supported between instances of 'float' and 'datetime.datetime'
````

**Comment by has2k1** [comment]
You are in for some pain, dealing with datetimes is a kind of hell in python. Little details matter. I suggest you look at the implementation of [datetime_trans](https://github.com/has2k1/mizani/blob/116bd09768d02c0fbbbc7ff243ca80505cb57541/mizani/transforms.py#L591) and maybe even [timedelta_trans](https://github.com/has2k1/mizani/blob/116bd09768d02c0fbbbc7ff243ca80505cb57541/mizani/transforms.py#L618) in mizani. Your transform object is missing key attributes. Also do not assume that `x` is a pandas Series, it is either an array-like or a single value.

I think it would be easier to inherit from `datetime_trans` and use the conversion functions `date2num`, `num2date` (from matplotlib), then make your adjustments before or after those calls.

**Comment by randomizedthinking** [comment]
Thanks for the suggestion. I just tried, and simply using `date2num` and `num2date` will still fail.

My finding is that: a few configurations need to be set up before using these functions... datetime in python is such headache.

**Comment by has2k1** [comment]
You need [these], that is why you would subclass `datetime_trans`.
