### ISSUE TITLE
Alpha for points is ignored in aes() call.

### ISSUE THREAD

**Issue by naught101** [has2k1/plotnine#43]
```{python}
df = pd.DataFrame(np.random.random([10, 2]), columns=['X', 'Y'])
ggplot(df, aes(x='X', y='Y', alpha=0.1)) + geom_point()
```
produces this:

![point_alpha](https://user-images.githubusercontent.com/167164/29258179-d92d7bdc-80fa-11e7-988f-4d053e786dd3.png)

**Comment by has2k1** [comment]
What you want is

```python
ggplot(df, aes(x='X', y='Y')) + geom_point(alpha=0.1)
```

Any values you assign in `aes()` are treated just like a column in the dataframe what has the same value(s).
