### ISSUE TITLE
Group facet_grid labels

### ISSUE THREAD

**Issue by jroessler** [has2k1/plotnine#431]
Is there a way to group labels when using plotnine's `facet_grid` function? 

For example, take the following DataFrame (I made the example up such that you can reproduce my problem. In real my DataFrame is much bigger but the structure is almost identical):

    df_test = pd.DataFrame(data= {'rate_1': [0.0,0.1,0.2,0.3,0.0,0.1,0.2,0.3,0.3,0.2,0.1,0.0],
                                  'rate_2': [0.0,0.1,0.2,0.3,0.0,0.1,0.2,0.3,0.3,0.2,0.1,0.0],
                                  'rate_3':[0.0,0.1,0.2,0.3,0.0,0.1,0.2,0.3,0.3,0.2,0.1,0.0],
                                  'rate_4': [0.0,0.1,0.2,0.3,0.1,0.2,0.3,0.0,0.2,0.3,0.0,0.1],
                                  'samples': [50000, 100000, 50000, 100000,50000, 100000, 50000, 100000,50000, 100000, 50000, 100000],
                                  'model': ['model 1', 'model 2', 'model 3', 'model 4','model 1', 'model 2', 'model 3', 'model 4','model 1', 'model 2', 'model 3', 'model 4'],
                                  'metric': [0.5,0.4,0.3,0.2,0.5,0.4,0.3,0.2,1,0.3,0.4,0.3]})

I created the following function to plot the absolute metric depending on the rates, sample size and model:

    # Plotting
    my_plot = ggplot(data=df_test, mapping=aes('rate_1', 'rate_2', fill='metric'))
    my_plot += geom_tile()
    my_plot += theme(axis_text_x=element_text(rotation=90), figure_size=(16, 8), strip_background_x=element_text(width=1.))
    my_plot += scale_x_continuous(breaks=[.0, .1, .2, .3, .4, .5])
    my_plot += scale_y_continuous(breaks=[.0, .1, .2, .3, .4, .5])
    my_plot += facet_grid('rate_3 + samples  ~ model + rate_4', labeller=label_value)
    my_plot += scale_fill_gradient2(midpoint=0, low='blue', mid="white", high="red")
    my_plot

The resulting plot looks like:

[![enter image description here][1]][1]

Is there a way to group model names (model 1, model 2, model 3, model 4) and rate_4 when labeling the facet_grid? I'm looking for a result such that the 'columns' are named like the following (I used Excel for the illustration):

[![enter image description here][2]][2]

I also posted my question on [stackoverflow](https://stackoverflow.com/questions/63338071/plotnine-group-facet-grid-labels)

Thanks!

  [1]: https://i.stack.imgur.com/o3zIL.png
  [2]: https://i.stack.imgur.com/rbQVp.png

**Comment by has2k1** [comment]
You can approximate that by dropping into matplotlib and manipulation the text and background objects directly. *You are on your own*, but here is a hint.

```python
fig = my_plot.draw() # Draw and return the fig object
fig._themeables # Has the themed objects
fig._themeable['strip_text_x'][1].set_text('Model ABC') # Change text for the 2nd column, use "\n" for multiple lines 
fig._themeable['strip_background_x'][0].set_width(1.1) # Increase width of background for the first strip.
```

**Comment by jroessler** [comment]
Thank you so much! With your help I was able to "group" the labels. 

Although it is not really related to plotnine, I would like to share my code: 

```
# Plotting
my_plot = ggplot(data=df_test, mapping=aes('rate_1', 'rate_2', fill='metric'))
my_plot += geom_tile()
my_plot += theme(axis_text_x=element_text(rotation=90), figure_size=(16, 8), strip_background_x=element_text(width=1.))
my_plot += scale_x_continuous(breaks=[.0, .1, .2, .3, .4, .5])
my_plot += scale_y_continuous(breaks=[.0, .1, .2, .3, .4, .5])
my_plot += facet_grid('rate_3 + samples  ~ model + rate_4', labeller=label_value)
my_plot += scale_fill_gradient2(midpoint=0, low='blue', mid="white", high="red")

fig = my_plot.draw()
fig._themeable['strip_text_x'][0].set_text('\n 0.0')
fig._themeable['strip_text_x'][1].set_text('model 1 \n 0.10')
fig._themeable['strip_text_x'][2].set_text('\n 0.20')
fig._themeable['strip_background_x'][0].set_width(3.0)

fig._themeable['strip_text_x'][3].set_text('\n 0.00')
fig._themeable['strip_text_x'][4].set_text('model 2 \n 0.10')
fig._themeable['strip_text_x'][5].set_text('\n 0.20')
fig._themeable['strip_background_x'][3].set_width(3.0)

fig._themeable['strip_text_x'][6].set_text('\n 0.00')
fig._themeable['strip_text_x'][7].set_text('model 3 \n 0.10')
fig._themeable['strip_text_x'][8].set_text('\n 0.20')
fig._themeable['strip_background_x'][6].set_width(3.0)

fig._themeable['strip_text_x'][9].set_text('\n 0.00')
fig._themeable['strip_text_x'][10].set_text('model 4 \n 0.10')
fig._themeable['strip_text_x'][11].set_text('\n 0.20')
fig._themeable['strip_background_x'][9].set_width(3.0)

plt.show()
```

The result looks like:

![Bildschirmfoto 2020-08-21 um 07 50 11](https://user-images.githubusercontent.com/23525054/90856791-07d76900-e383-11ea-84c2-27a453649d52.png)

**Comment by tabedzki** [comment]
What is the current way to do this? I tried this example but got 

```  
fig._themeable['strip_text_x'][idx].set_text(f'\n 0.0')
```

```

---> [45] fig._themeable['strip_text_x'][0].set_text(f'\n 0.0')

AttributeError: 'Figure' object has no attribute '_themeable'
```

**Comment by maikol-solis** [comment]
@has2k1 I got the same question as @tabedzki. In the documentation, there is no guidance on how to implement something like this. Best.
