### ISSUE TITLE
Set the font family in `rcParams` as default for some themes

### ISSUE THREAD

**Issue by Gedevan-Aleksizde** [has2k1/plotnine#436]
Hello, thank you for this great package!

Some themes' default font family is set as DejaVu Sans, which has large coverage for unicode -- Extended Latin, Cyrricil, Arabic, and so on. But this font doesn't cover CJK (Chinese, Japanese and Korean) fonts.
I usually set a CJK font in `rcParams` but these themes' default values overwrite it.  I want to avoid to set the same font again. Why don't you change the default value to `None`

**Comment by has2k1** [comment]
In the next version of plotnine you will be able to set a default font for all your themes with

```python
from plotnine.options import set_option
set_option('base_family',  'My Font')
```
