### ISSUE TITLE
`strip_text` sizing in `facet_wrap` is off

### ISSUE THREAD

**Issue by jbloom** [has2k1/plotnine#44]
The sizing of the strips with the labels above the plots in `facet_wrap` is inconsistent. If I `facet_wrap` a plot with just two rows, I get what seem to me to be overly narrow strips such that the label text is at the edges of the strip. 

I can increase the strip height with `+ theme(strip_text=element_text(lineheight=1.8))`. But then the strips become far too tall when there are more rows in the faceted plot.

I have played around with this some, and I think the ultimate problem is that the way that the height of the strip text is computed must depend on the total height of the faceted plots, such that plots with more rows end up with taller strip texts.

Let me know if you want me to post example images.

**Comment by jbloom** [comment]
The same phenomenon also applies to the vertical spacing between the facet rows -- as the overall plot gets taller (more rows), the spacing between the rows also gets relatively larger.

**Comment by has2k1** [comment]
You have come across a very hairy [1] part of the package. However, I recall making sure that you can at least get consistent spacing. Please do include plots, I may be able to give a precise solution.

[1] The underlying issue is a lack of a [layout manager](https://github.com/matplotlib/matplotlib/issues/1109)

**Comment by jbloom** [comment]
![many_rows](https://user-images.githubusercontent.com/1906801/29280745-56803630-80d1-11e7-9a04-6d00ff2c45ac.png)
Hi Hassan,

Thanks for the quick reply. I have attached examples of two plots generated by identical code except that one is faceted over more samples, and so has more rows. As you can see, the height of the strip goes from too small in the first attachment to too large in the second one.

The code that generates these is a bit complex as the underlying data frame is complicated, so I'm not attaching that.

However, if it is helpful I can create a toy example that gives the same problem on a simpler toy data frame -- just let me know. 

Thanks,
Jesse
![few_rows](https://user-images.githubusercontent.com/1906801/29280743-50636f10-80d1-11e7-878e-77345c168974.png)

**Comment by has2k1** [comment]
That does not look good, I expect consistent margins (top, bottom) around the `strip_text`. A simpler example would be helpful.

I'm wondering if this

```python
...
+ theme(figure_size=(2.25 * (0.6 + ncol), 1.3 * (0.3 + nrow)))
)
p.save(plotfile)
```

would give a  better plots.

**Comment by jbloom** [comment]
Your suggestion was a good one. The problem exists when the plot size is set via `save` but not when it is set by `theme(figure_size=(x, y))`.

The following attachment has a Jupyter notebook (and HTML rendering) that
[plotnine_facet_wrap.zip](https://github.com/has2k1/plotnine/files/1223006/plotnine_facet_wrap.zip)
 illustrates this on a toy example. 

I'm not sure if this would still be considered a bug (you could argue that maybe the strips should be right regardless of how the figure size is set), but this certainly fixes my problem from a practical perspective!

Thanks so much for the help, and feel free to close the issue if you'd like.

**Comment by has2k1** [comment]
Great. Yes, it is still a bug.
