### ISSUE TITLE
[Feature request] Matplotlib-style API options? 

### ISSUE THREAD

**Issue by jolespin** [has2k1/plotnine#441]
Your package produces beautiful graphs.  I've seen a lot of plots like this in publications and never knew what they were using to make it.  I see that this is similar to ggplot and was wondering if it would be possible to have an API more similar `Matplotlib` or `Seaborn` where we can use functions and write directly to `ax` objects?  I understand this is a monumental task but thought it would more effectively integrate into the `SciPy` ecosystem since many Python users are already familiar with `matplotlib` style APIs? 

For example:

```python
import plotnine.apis.matplotlib as pn # p9
import matplotlibt.pyplot as plt

arguments = {
"data":data,
"something":else,
}
with plt.style.context("seaborn-white"):
    fig, axes = plt.subplots(ncols=3)
    pn.some_plotting_function(**arguments, ax=axes)

```

**Comment by has2k1** [comment]
Supporting Matplotlib style API is not an option. It would not be easy to do, let alone to do it well. Such alternatives would be best suited to a third-party library that would use plotnine. Checkout [dppd](https://github.com/TyberiusPrime/dppd_plotnine) for one such library.
