### ISSUE TITLE
Python 2.7.

### ISSUE THREAD

**Issue by karlpetri** [has2k1/plotnine#442]
Hi,
Fantastic tool! Thank you so much.
Can I use this safely with python 2.7 or is only python 3 supported?
Thank you so much,
-Karl

**Comment by has2k1** [comment]
v0.4.0 (released 2 years ago) was the last version to support python 2. So there is no way you can use the current version of with Python 3.

**Comment by karlpetri** [comment]
Gotcha! Thanks for the quick response!
