### ISSUE TITLE
Save 2 plots (and if possible a table) to pdf

### ISSUE THREAD

**Issue by hermankant** [has2k1/plotnine#443]
I saw the method of saving plot per page, however, I would like to save 2 plots into 1 page if possible.
Additionally, I would like to save another dataframe under these plots.

Any suggestions of how do I do that?
Not sure where to start. I can provide my plots code but I assume it is irrelevant for the solution given I have 2 plot objects as p1 and p2.

**Comment by has2k1** [comment]
It is not possible with plotnine, the only option is to do it afterwards. If you use linux or OS X and have `texlive` installed then you can use [pdfjam](https://github.com/DavidFirth/pdfjam) to stitch together pdf image files anyway you want

For example, if you have two plots in files p1.pdf and p2.pdf, you can have them side-by-side on one page with this command.

```
pdfjam p1.pdf p2.pdf --nup 2x1 --landscape --outfile output.pdf
```
