### ISSUE TITLE
Support for testing output of plotnine

### ISSUE THREAD

**Issue by bxp151** [has2k1/plotnine#444]
Hi,

I was wondering if there was or there are plans for the ability to validate / test the output of plots generated in plotnine like for example in pytest.

Thanks,
Brian

**Comment by TyberiusPrime** [comment]
Plotnine had extensive test cases in plotnine/tests and is indeed using pytest.

**Comment by bxp151** [comment]
Sorry, I didn't ask the question well.  Suppose I created a plotnine object p.  

p = ( 
      pn.ggplot(freqdf) +
      pn.aes(x = aesx, 
             y = 'freq', 
             fill = 'freq', 
             label = lbl) +
      pn.geom_bar(stat = 'identity') +
      pn.coord_flip() +
      pn.theme(axis_text_y = pn.element_text(size=6, weight = 'bold'), 
            legend_position = 'none') + 
      pn.labs(x=freqdf.columns[0], y="Freq") +
      pn.scale_fill_gradient2(mid='bisque', high='blue') +
      pn.geom_text(size = 6,
                   nudge_y = .7)
    )

Is there any way for me to query all of the parameters that make up the object?  For example:

p.labels
p.data

Provide some of the information for these pieces:

      pn.ggplot(freqdf) +
      pn.aes(x = aesx, 
             y = 'freq', 
             fill = 'freq', 
             label = lbl)

**Comment by has2k1** [comment]
> Is there any way for me to query all of the parameters that make up the object? For example:

You can query most of the parameters, but since they are not simple scalars you may have to query deeper. The [scales](https://github.com/has2k1/mizani/issues/14) would have some problems.

**Comment by has2k1** [comment]
The attributes of the plot are listed here 

https://github.com/has2k1/plotnine/blob/5e90856f0724f7ae9e65b5d279b920df4c6eb445/plotnine/ggplot.py#L67-L80

but while not part of the public API,  they have been relatively stable over the years.
