### ISSUE TITLE
how to control spacing in dashed lines?

### ISSUE THREAD

**Issue by glassTransition** [has2k1/plotnine#447]
I am trying to draw some horizontal lines as a workaround for not being able to create a secondary axis. I would like to be able to control the spacing of the dashes, but can't find how to do that? This works, but the dashes are too short:

import pandas as pd
import numpy as np
from plotnine import *

x = np.linspace(1.0,10.0,50)
y=[ np.sin(ang) for ang in x]

d = {'x':x,'y':y}
df = pd.DataFrame(d)

(ggplot() 
     
    + geom_line(df,aes(x='x',y='y'),color='red',size=.3) 
    + scale_y_continuous(minor_breaks=10) # use this line for auto y range
    + annotate('line',x=[0,10],
            y = [.25,.25],
            color='blue',
            linetype='dashed',
            size=.3
            )
    + annotate('line',x=[0,10],
            y = [-.25,-.25],
            color='blue',
            linetype='dashed',
            size=.3
            )
    + theme_light() 
    + theme(figure_size=(15, 10))

    )

**Comment by has2k1** [comment]
Use tuples of the form (offset, (on, off, on, off, ....)) e.g. (0, (1, 1)), (1, (2, 2)), (2, (5, 3, 1, 3))

**Comment by glassTransition** [comment]
Thank you. 

I replaced the 'dashed' linetype argument above with tuples e.g. linetype=((0, (50, 50)),(1, (20, 20))) as you recommend and indeed it affects the length of dashes and spaces, but I don't exactly understand what the components of the tuple mean. It also seems that only the first offset has an effect?

**Comment by has2k1** [comment]
The specification is (offset, (on, off, on, off, ....))

- offset - How many points to skip at the start.
- on - How many points to turn on
- off - How many points to turn off

Examples, (assume 0 is for space, 1 is for dash point)

(0, (1, 1)) -> "1010101010101010..."
(0, (2, 2)) -> "11001100110011001100..."
(1, (2, 2)) -> "011001100110011001100..."
(2, (5, 3, 1, 3)) -> "00111110001000111110001000..."

**Comment by glassTransition** [comment]
Ok, I have it working now.  I added a third point in the middle of the line and can see the pattern change between the second and third points. I didn't realize that it was possible to change the pattern starting at each point. That explains why there must be one tuple specified for each point the defines the line or an exception is raised. Originally I only had two points so it appeared as though the second tuple did not have an affect since there was nothing plotted past the second one.
