### ISSUE TITLE
goem_text -  ValueError: The truth value of a DataFrame - python 3.8.3

### ISSUE THREAD

**Issue by nicomy** [has2k1/plotnine#449]
Hello,
It seems that geom_text() in plotnine version '0.7.1' is not compatible with python 3.8.3. 

In the function` __init__` of the class geom_text: 

`if  mapping` 
raise:
`ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().`

This two lines need to be updated : 
```
        if mapping and 'hjust' in mapping:
            mapping['ha'] = mapping.pop('hjust')

        if mapping and 'vjust' in mapping:
            mapping['va'] = mapping.pop('vjust')

```

Ty for your work, plotnine is awesome :)

**Comment by has2k1** [comment]
Use keyword arguments for `data=*`.
