### ISSUE TITLE
scale_x_continuous() raises TypeError: Discrete value supplied to continuous scale

### ISSUE THREAD

**Issue by fgenoese** [has2k1/plotnine#450]
I am trying to create an hourly heatmap. A code example of such a graph made in R is available here: r-graph-gallery.com/283-the-hourly-heatmap.html. (It relies on ggplot2).

A Google Codelab notebook of my code can be found here:
https://colab.research.google.com/drive/1OFF9NbbmPwa5nuAJH2tjI4K22iv__CS6?usp=sharing

I noticed that **scale_x_continuous()** can only be applied to DataFrame columns that are not explicitly declared as numeric. Otherwise, the following error is raised:
**TypeError: Discrete value supplied to continuous scale**

In my case, I was calculating a column (hour #) from a datetime column using **strftime()** which by default returns an object type and has to be cast explicitly to numeric:
```
df['hour'] =  pd.to_datetime(df.index, utc=False).strftime('%-H')
df['hour'] = df['hour].astype(str).astype(int)
```

This is probably not a bug, hence the issue can be closed.

**Comment by has2k1** [comment]
There is no way to confirm the error without a minimal reproducible example.

**Comment by fgenoese** [comment]
Attached a link to a Google Codelab notebook

**Comment by has2k1** [comment]
When submitting an minimal reproducible example, simplify it to the absolute minimum. Trim the dataset as much as possible, remove the plotting code not related to the issue and make sure it is copy-pastable.
