### ISSUE TITLE
Feature request: support legend.justification

### ISSUE THREAD

**Issue by bersbersbers** [has2k1/plotnine#452]
ggplot's `theme()` has `legend.justification`, which I cannot find in `plotnine`: see https://ggplot2.tidyverse.org/reference/theme.html, in particular, this example:

![image](https://user-images.githubusercontent.com/12128514/97292591-b7313000-184b-11eb-91a3-a8e7fd7bb59b.png)

**Comment by has2k1** [comment]
We cannot have this kind of alignment for the positions of objects placed around the plot area. The backend (Matplotlib) does not have  a layout manager that would support it.

On the other hand you can place the legend using coordinates (relative to the original size of the figure). e.g.

```python
+ theme(legend_position=(1, .8))
```

**Comment by bersbersbers** [comment]
Alright, thanks! This position is the center of the legend, is it? Any chance I can pick a corner coordinate?

**Comment by has2k1** [comment]
> Alright, thanks! This position is the center of the legend, isn't it? Any chance I can pick a corner coordinate? I guess I would simply like something like `legend_position="top right"` ;)

Yes the position is the center of the legend. "top right" is not possible.

**Comment by bersbersbers** [comment]
Okay, thank you. I'll get in line waiting for a better matplotlib then ;) Specifying the center coordinate does not help in top-aligning two legends with different height ;)

**Comment by has2k1** [comment]
> Okay, thank you. I'll get in line waiting for a better matplotlib then ;) Specifying the center coordinate does not help in top-aligning two legends with different height ;)

You can justify two legends of different heights and the place the two by their combined centre e.g.

```python
+ theme(legend_position=(1, .8), legend_box='horizontal', legend_box_just='top')
```

**Comment by bersbersbers** [comment]
> > Specifying the center coordinate does not help in top-aligning two legends with different height ;)
> 
> You can justify two legends of different heights and the place the two by their combined centre

Yes, that's right. I forgot to mention, though, that the two legends are in different plots: I generate two plots running the same script twice, let's say once with 5 breaks in the size aesthetics and once with 3 breaks (there's more differences than that, but that's the main difference in terms of layout of the plot). That's why the two size legends have different height, and that impacts positioning of other legends as well, visually implying differences where there aren't any.

I'm not sure there is a more "grammatically" correct approach to this (like using facets?), but I don't see it. Anyway, that's a pretty small issue which I can just let be.
