### ISSUE TITLE
__str__ method for ggplot objects

### ISSUE THREAD

**Issue by rhalbersma** [has2k1/plotnine#453]
I would be nice if ggplot objects had a `__str__` method that draws the plot without the `<ggplot:hash>` annotation. For pretty printing, users could then write `print(p)` and for debugging `print(repr(p))` would still be available.

**Comment by has2k1** [comment]
What is your main working environment? Jupyter-notebook, pycharm, ... ? If not jupyter-notebook (it uses `__repr__`), does it use `__str__` or `__repr__` for printing the last statement of a code block/cell?

**Comment by rhalbersma** [comment]
I am working in a Jupyter-notebook. If Jupyter-notebook would call `__repr__` then I can still do `print(str(p))` and then `print(p)` would even be backwards compatible.

**Comment by has2k1** [comment]
So, this is how the cases would turn out

1. `repr(p)` - Show Plot, Return `'<ggplot:hash>'`
2. `str(p)`  - Show Plot, Return `''`
3. `print(p)` - Show Plot, Print `''`
4. `print(str(p))` - Show Plot, Print `''`

am I missing anything?

**Comment by rhalbersma** [comment]
> So, this is how the cases would turn out
> 
> 1. `repr(p)` - Show Plot, Return `'<ggplot:hash>'`
> 2. `str(p)`  - Show Plot, Return `''`
> 3. `print(p)` - Show Plot, Print `''`
> 4. `print(str(p))` - Show Plot, Print `''`
> 
> am I missing anything?

AFAIK, currently, `print(p)` does the same as `repr(p)`, so the two primitives would be `repr(p)` and `str(p)` and user can forget about doing `print(p)` altogether.

**Comment by has2k1** [comment]
> AFAIK, currently, `print(p)` does the same as `repr(p)`

Yes that is the case; and it is what is going to change.

**Comment by rhalbersma** [comment]
Yes, so people who really like the hash codes in their publication-ready plots, need to change their code to `repr(p)`.  So it's not backward compatible.
