### ISSUE TITLE
Best way to work with datetime histogram bins?

### ISSUE THREAD

**Issue by CarlosGrohmann** [has2k1/plotnine#454]
Sorry if this is not the place, but what is the best way to work with datetime histogram bins?
My data (movies from TMDb) has a column 'release' which was created as 

`df_movies['release'] = pd.to_datetime(df_ft['release_date'])`

Then I made a histogram:

```
(p9.ggplot(df_movies) 
+ p9.geom_histogram(mapping=p9.aes(x='release'), binwidth=365*5)
+ p9.labs(title='Movies releases')
+ p9.scale_x_datetime(date_breaks='5 years',date_labels='%Y',
                     limits=[datetime.date(1890,1,1), datetime.date(2020,1,1)])
+ p9.theme(axis_text_x = p9.element_text(angle=90))
)
```

Is this a good way to define the bins? Or is there a better way?

Thanks for the help and for making plotnine.

**Comment by has2k1** [comment]
That is a good way to do it.
