### ISSUE TITLE
Histogram made only of the outline of bars?

### ISSUE THREAD

**Issue by CarlosGrohmann** [has2k1/plotnine#455]
Since it seems that there's an issue with statsmodels kde density (see #332, #407, #430), one workaround would be to make histograms made of only the outline of the bars. Is that possible? I couldn't find it via the usual googling or in the gallery. I can have more than one histogram in the same plot, but if they are too similar, it gets hard to see the differences, so the outlines could help by being set to different linewidths, for instance.

![hists_p9](https://user-images.githubusercontent.com/1870265/98889151-21ff7f80-2478-11eb-943e-5a06d3fbc5e4.png)

**Comment by has2k1** [comment]
If you are going for the naive density function, then you can use `geom_line` with `stat_bin`.

**Comment by CarlosGrohmann** [comment]
Sorry but may I ask for an example? Do I use stat_bin as mapping to Y values?

**Comment by has2k1** [comment]
> Do I use stat_bin as mapping to Y values?

Yes. So instead of `geom_histogram(n=100)` you use `geom_line(stat='bin', n=100)`

**Comment by CarlosGrohmann** [comment]
Thank you!
That worked just as I needed. 
(I used `bins=100` instead of `n=100`)

**Comment by has2k1** [comment]
Oh, yes the parameter is `bins`.
