### ISSUE TITLE
Proportion (percentage) with geom_line and stat_bin ?

### ISSUE THREAD

**Issue by CarlosGrohmann** [has2k1/plotnine#459]
I see that with `geom_line` and `stat_bin`, I can have the y-values either as `count`, `ncount`, etc:
```
p9.geom_line(data=pd_rasters, stat='bin', bins=200, na_rm=True,
                mapping=p9.aes(x='Slope', color='Algorithm', y='stat(count)'),
                position='position_identity',
                alpha=0.8, size=1)
```

Can I get this as a percentage of values (rows)? something like using `y='stat(prop)'` ? 

I thought about a custom function as in #231 but I'm not sure how to get the total size of each group.

**Comment by has2k1** [comment]
`y = 'stat(density*width)'` will get you the proportion. The reason, dividing the proportion by the width of the bars turns gives you normalises the area to one i.e. a density; here we reverse that.

You can check by creating your own stat and calculating the `prop` within the the group computation.

```python
class stat_bin2(stat_bin):
    @classmethod
    def compute_group(cls, data, scales, **params):
        res = stat_bin.compute_group(data, scales, **params)
        res['prop'] = res['count'] / res['count'].sum()
        return res

(... + geom_line(aes(y='stat(prop)'), stat=stat_bin2))
```

**Comment by CarlosGrohmann** [comment]
Thank you


It worked as  `(... + geom_line(aes(y='stat(prop)'), stat='bin2'))` after adding `stat_bin2` to `stat_bin.py`

I also managed to alter `binning.py` and added a new column in the resul dataframe of `result_dataframe`.

While we're at it, I'm trying to recreate one output of MicroDEM in which the y-axis is called "concentration". The author defines it as "the number of points in the bin divided by the number of points if every bin had the same number of points."

Do you think that this would be ok : `'concentration': count/(np.sum(np.abs(count)/len(x)))`

**Comment by has2k1** [comment]
You should not add `stat_bin2` to `stat_bin.py` or change the files directly. When you upgrade the package those modifications will be overwritten.

> "the number of points in the bin divided by the number of points if every bin had the same number of points."

That description is not clear. That said, I interpret it as `number-of-points-in-bin / average-number-points-per-bin` where given this
implementation

```python
class stat_bin2(stat_bin):
    @classmethod
    def compute_group(cls, data, scales, **params):
        res = stat_bin.compute_group(data, scales, **params)
        res['ngroup'] = res['count'].sum()  # Number of points per group
        return res
```

I would defined the parameters you want as

```
prop = count / ngroup
concentration = count / (ngroup/bins) # Which looks like what you have over there but in a very fragile form.
```

This then makes the case for adding `ngroup` to the result dataframe. Do you want to do it?

**Comment by CarlosGrohmann** [comment]
I understand that I should not add things directly to the files, but it was interesting to see a bit more of the inner workings of plotnine and add something new. I am running this analysis in a jupyter-notebook and creating the class and function within the notebook dodn't worked, so I went to the source. 

I also agree that the description of concentration is not clear, but it's what I have to work with.. :) Anyway I think that adding `ngroup` is very welcome

When you ask if I want to do it, you mean a PR? I've never done one before but could try. To what part of the code it should be added?

**Comment by has2k1** [comment]
> When you ask if I want to do it, you mean a PR? 

Yes

> To what part of the code it should be added?

In the `result_dataframe` routine. Then add the book keeping info about it in `stat_bin.py`, just like the others `count`, `ndensity`, ... .

**Comment by CarlosGrohmann** [comment]
Ok, did it. Please check if I did it the right way.
Thanks the oppportunity to contribute
