### ISSUE TITLE
Non-alphabetical order of legend itens with custom colors

### ISSUE THREAD

**Issue by CarlosGrohmann** [has2k1/plotnine#464]
I'm trying to adjust the order of the items in the legend of a line plot. The dataframe has a column for values of "slope" (calculated from a series of digital elevation models) and a column of "algorithm". The legend is automatically set in alphabetical order, but in order to set my custom colors, I'd like that to follow the order of the algorithms in the dataframe. I tried the approach in [here](https://plotnine.readthedocs.io/en/stable/tutorials/miscellaneous-order-plot-series.html) and also in #323 but it didn't work, the legend still is in alphabetical order. 
The data in the dataframe is in the same order as in the `alg_geo` list. (and the colors in `dem_cols`)

This is what I've been doing:

```
alg_geo = ['LL_ArcGIS_planar','LL_ArcGIS_geodesic','LL_GRASS','LL_MicroDEM','LL_WhiteBox','LL_ERDAS_autoTool','LL_ERDAS_spatialModeler']
dem_cols=['#000000','#0000FF','#8181F7','#01DF01','#FFBF00','#A4A4A4','#1A98BB','#1AB4C5','#F78181','#F7819F','#FE2EF7']
df_slope = df_slope.assign(values = pd.Categorical(df_slope['Algorithm'], alg_geo))
 
binw = 2

(p9.ggplot(pd_slope_l_ll)
+p9.geom_line(stat='bin', binwidth=binw, na_rm=True,
                mapping=p9.aes(x='Slope', color='Algorithm',
                y='stat((count/ngroup)*100)'), position='position_identity',
                alpha=0.8, size=1)
+p9.scales.xlim(0,200)
+p9.scales.ylim(0,3.5)
+p9.xlab(f'Slope (percent)')
+p9.ylab(f'Percent of total')
+p9.scale_color_manual(values=dem_cols)
+p9.ggtitle(f'Slope - Histograms (bin={binw}%)')
+p9.theme(figure_size=(8, 6))#,legend_position=(0.75,0.7))
).draw();


```

**Comment by has2k1** [comment]
The legend takes the order of the categorical. Confirm that whatever manipulation you are doing the result is a categorical and that the categories are listed in the wanted order. 

And, *make sure you are plotting the right dataframe!*

**Comment by CarlosGrohmann** [comment]
Sorry my mistake.

The error in the code wasn't real, it was me trying to simplify the real code for the example.

but I found the real problem. The list of algorithms (`alg_geo`) was missing one entry, so it would fall back to default.
