### ISSUE TITLE
How to avoid scale_x_datetime to shift data to next month

### ISSUE THREAD

**Issue by xiaoxi-david** [has2k1/plotnine#467]
How can I plot data on the right month with scale_x_datetime?

It seems scale_x_datetime shifts data to next month.

**With scale_x_datetime**
![plot_with_scale](https://user-images.githubusercontent.com/24303680/102481253-c40b1c80-4061-11eb-9992-ab3973c3be53.png)

**Without scale_x_datetime** (Wider graph to read labels better)
![plot_without_scale2](https://user-images.githubusercontent.com/24303680/102482704-edc54300-4063-11eb-8ba9-b9531e426371.png)

Here is the code to create both graphs.
> import pandas as pd
> import numpy as np
> import plotnine as p9
> 
> idx = pd.period_range("1/1/2020", periods=12, freq="M")
> df = pd.DataFrame(
>     data={"date": idx, "number": np.random.randint(low=20, high=40, size=12)}
> )
> 
> p1 = (
>     p9.ggplot(df, p9.aes(x="date", y="number"))
>     + p9.geom_col()
>     + p9.scale_x_datetime(date_breaks="1 month", date_labels="%b", name="date")
> )
> print(p1)
> 
> p2 = (
>     p9.ggplot(df, p9.aes(x="date", y="number"))
>     + p9.geom_col()
>     # + p9.scale_x_datetime(date_breaks="1 month", date_labels="%b", name="date")
> )
> print(p2)

**Comment by has2k1** [comment]
Well, dates are evil. The period objects are not exactly what you would expect them to be, they carry two dates and you have to map to the right one.

```python
In [1]: import pandas as pd

In [2]: idx = pd.period_range('1/1/2020', periods=12, freq='M')

In [3]: idx
Out[3]: 
PeriodIndex(['2020-01', '2020-02', '2020-03', '2020-04', '2020-05', '2020-06',
             '2020-07', '2020-08', '2020-09', '2020-10', '2020-11', '2020-12'],
            dtype='period[M]', freq='M')

In [4]: [f'{x}' for x in idx]
Out[4]: 
['2020-01',
 '2020-02',
 '2020-03',
 '2020-04',
 '2020-05',
 '2020-06',
 '2020-07',
 '2020-08',
 '2020-09',
 '2020-10',
 '2020-11',
 '2020-12']

In [5]: [f'{x.year}/{x.month}/{x.day}' for x in idx]
Out[5]: 
['2020/1/31',
 '2020/2/29',
 '2020/3/31',
 '2020/4/30',
 '2020/5/31',
 '2020/6/30',
 '2020/7/31',
 '2020/8/31',
 '2020/9/30',
 '2020/10/31',
 '2020/11/30',
 '2020/12/31']

In [6]: [f'{x.start_time}' for x in idx]
Out[6]: 
['2020-01-01 00:00:00',
 '2020-02-01 00:00:00',
 '2020-03-01 00:00:00',
 '2020-04-01 00:00:00',
 '2020-05-01 00:00:00',
 '2020-06-01 00:00:00',
 '2020-07-01 00:00:00',
 '2020-08-01 00:00:00',
 '2020-09-01 00:00:00',
 '2020-10-01 00:00:00',
 '2020-11-01 00:00:00',
 '2020-12-01 00:00:00']

In [7]: [f'{x.start_time.year}/{x.start_time.month}/{x.start_time.day}' for x in idx]
Out[7]: 
['2020/1/1',
 '2020/2/1',
 '2020/3/1',
 '2020/4/1',
 '2020/5/1',
 '2020/6/1',
 '2020/7/1',
 '2020/8/1',
 '2020/9/1',
 '2020/10/1',
 '2020/11/1',
 '2020/12/1']
```

As you can see your first plot is plotting the wrong numbers. So you have to map to start of each period. i.e.

```python
p9.ggplot(df, p9.aes(x="date.dt.start_time", y="number"))
```
