### ISSUE TITLE
How to set lower axis limit only

### ISSUE THREAD

**Issue by votti** [has2k1/plotnine#47]
To better appreciate relative differences, having plots starting at 0 is often required (e.g. https://stackoverflow.com/questions/11214012/set-only-lower-bound-of-a-limit-for-ggplot)

In ggplot2 there are several options to achive this with options, e.g.
 the 'expand_limits' function,
`scale_y_continious(limits=c(0, NA))`
or `ylim(c(0, NA))`.

However I did not manage to replicate this function in plotnine, apart from calculating the limits 'manually' beforehand (see below). Is there any nicer way to do this?

```python
from plotnine import *
from plotnine.data import mtcars

ymax = mtcars['mpg'].max()*1.1
(ggplot(mtcars, aes('wt', 'mpg'))
 + geom_point()
+ ylim(0, ymax))`
```

**Comment by has2k1** [comment]
Though not the most obvious, this works

```python
ggplot(mtcars, aes('wt', 'mpg')) + geom_point() + aes(ymin=0)
```
