### ISSUE TITLE
Cannot display Chinese normally

### ISSUE THREAD

**Issue by CDPDisk** [has2k1/plotnine#471]
Although my matplotlib can display Chinese normally, it cannot be displayed normally on plotnine, and it is displayed as '□'.

And part of the error message is like this:
\lib\site-packages\matplotlib\backends\backend_agg.py:201: RuntimeWarning: Glyph 21452 missing from current font.

I have tried to modify the \Lib\site-packages\matplotlib\mpl-data\matplotlibrc file, which makes my matplotlib successfully display Chinese, but it is still not available on plotnine

**Comment by has2k1** [comment]
What about if you set your font using `+ theme(text=(family='my-font')`? If that works then this issue is the same as  https://github.com/has2k1/plotnine/issues/436 which was resolved.

**Comment by CDPDisk** [comment]
It works, thanks
