### ISSUE TITLE
Feature request: allow ggplot() + None

### ISSUE THREAD

**Issue by bersbersbers** [has2k1/plotnine#474]
I have just learned that `ggplot2::ggplot()` supports adding `NULL` to allow conditional constructs without changing the element structure of a `ggplot` command. See also https://youtu.be/nqI5CmdUYRQ?t=454

Would it be possible to support `plotnine.ggplot() + None`? Or is there something similar that one could use?

**Comment by has2k1** [comment]
You can add `geom_blank()`. But `None` does seem nifty.

**Comment by bersbersbers** [comment]
> You can add `geom_blank()`.

True - although that might behave a little differently, at least in `ggplot2` - see the same video a bit later: https://youtu.be/nqI5CmdUYRQ?t=1234

> But `None` does seem nifty.

Yes - thanks!
