### ISSUE TITLE
Documentation shows tuples as separate arguments

### ISSUE THREAD

**Issue by joshhartmann11** [has2k1/plotnine#475]
Documentation shows default tuples as separate arguments

Example:
![err](https://user-images.githubusercontent.com/29384703/104131504-8ed5af80-532b-11eb-8793-eafd316cac61.png)
[https://plotnine.readthedocs.io/en/stable/generated/plotnine.scales.scale_size_continuous.html#plotnine.scales.scale_size_continuous)
](https://plotnine.readthedocs.io/en/stable/generated/plotnine.scales.scale_size_continuous.html#plotnine.scales.scale_size_continuous)

Below is a list of locations that may have this issue:
```
./plotnine/scales/scale_alpha.py may have tuple argument:
    [line: 25]: def __init__(self, range=(0.1, 1), **kwargs):
    [line: 47]: def __init__(self, range=(0.1, 1), **kwargs):
    [line: 88]: def __init__(self, range=(0.1, 1), **kwargs):
./plotnine/scales/scale_stroke.py may have tuple argument:
    [line: 25]: def __init__(self, range=(1, 6), **kwargs):
    [line: 44]: def __init__(self, range=(1, 6), **kwargs):
./plotnine/scales/scale.py may have tuple argument:
    [line: 344]: def dimension(self, expand=(0, 0, 0, 0), limits=None):
    [line: 708]: def dimension(self, expand=(0, 0, 0, 0), limits=None):
./plotnine/scales/scale_xy.py may have tuple argument:
    [line: 114]: def dimension(self, expand=(0, 0, 0, 0), limits=None):
./plotnine/scales/scale_size.py may have tuple argument:
    [line: 26]: def __init__(self, range=(2, 6), **kwargs):
    [line: 68]: def __init__(self, range=(1, 6), **kwargs):
    [line: 90]: def __init__(self, range=(1, 6), **kwargs):
    [line: 128]: def __init__(self, range=(1, 6), **kwargs):
./plotnine/geoms/annotation_stripes.py may have tuple argument:
    [line: 46]: def __init__(self, fill=('#AAAAAA', '#CCCCCC'), fill_range='auto',
```

**Comment by has2k1** [comment]
This was probably a regression bug in one of the upstream packages either sphinx or numpydoc.  The latest documentation was [okay](https://plotnine.readthedocs.io/en/latest/generated/plotnine.scales.scale_size_continuous.html), so I triggered a rebuild of the stable docs wasn't a good idea. It fixes the issue but it pulls in examples in the gallery that will only work in the next release!
