### ISSUE TITLE
How to print ggplot without blocking?

### ISSUE THREAD

**Issue by randomizedthinking** [has2k1/plotnine#476]
I create a series of plots in the course of my code, and would like to print them without blocking on the go, like `plt.show(block=False)`. I searched the plotnine documentation, yet didn't find anything related.

So far, the save_as_pdf_pages is used to save all plots in the end. It is great if we can print plots in the middle of the run.

**Comment by has2k1** [comment]
@randomizedthinking, please post some code so that I can get a better idea of the workflow.

**Comment by randomizedthinking** [comment]
@has2k1 Here is a simple example. Basically, I tried to print a `plotnine.ggplot` inside a loop. The drawing routine is blocking, and I would like to have the programming running after showing the graph.

```python
from plotnine import ggplot, aes, geom_point, ggtitle
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.randn(20, 2))
df.columns = ['x', 'y']

for i in range(5):
    # create a new df here...
    p = ggplot(df, aes(x="x", y="y")) + geom_point()
    print(p + ggtitle("Plot " + str(i)))
```

**Comment by has2k1** [comment]
It is still not clear.

Is this with an interactive backend e.g. PyQt5? If this is the case, then I assume you are not interested in seeing the plots since if you don't block the plots close with no time to view them! If the plots will close why print them in the first place?

**Comment by mike-lawrence** [comment]
Sorry to resurrect a dead/closed thread, but I just started using plotnine and came here with the same question as OP. The use case is when you want to have a number of plots visible at the same time, so you loop their creation without blocking and (at least when using native matplotlib) it creates a new window for each plot.

**Comment by has2k1** [comment]
@mike-lawrence please open a new issue and reference this one.
