### ISSUE TITLE
Cannot suppress plot output( e.g. <ggplot: (8768683283809)>  in plotnine

### ISSUE THREAD

**Issue by greglyon** [has2k1/plotnine#478]
I am using plotnine (which is great, btw!) and cannot suppress the plot output info, (e.g. <ggplot: (8768683283809)>) below the plot when using the plotnine in Jupyter notebook.

The %matplotlib inline magic works for `matplotlib` but not `plotnine`.

Works: 

```
%matplotlib inline

# Packages
import pandas as pd
import matplotlib.pyplot as plt

# Data
df = pd.DataFrame({"var1": [1, 2, 3, 4],
                  "var2": [1, 2, 3, 4]})

# Plot
plt.plot(df["var1"], df["var2"])
plt.show()
```

Does not work (still get <ggplot: (394...etc.> output below plot):

```
%matplotlib inline

# Packages
import pandas as pd
import plotnine as p9

# Data
df = pd.DataFrame({"var1": [1, 2, 3, 4],
                  "var2": [1, 2, 3, 4]})

# Plot
(p9.ggplot(data=df,
       mapping=p9.aes(x="var1", y="var2")) +
p9.geom_line())

```

I noticed output info is also present in the `plotnine` documentation (https://plotnine.readthedocs.io/en/stable/generated/plotnine.aes.html#aes).

**Comment by has2k1** [comment]
This issue was addressed in #453 and will available in the next version.

`print(p)` will print an empty string and not a hash value, `repr(p)` will print a hash value and `p.draw(show=True)` will not print any string.
