### ISSUE TITLE
geom_violin and stat_ydensity do not accept bw=0.1 parameter

### ISSUE THREAD

**Issue by swenlaur** [has2k1/plotnine#489]
Sometimes you need to fix the smooting paremeter to avoid craches. 
But plotnine does not accept that although help suggest otherwise. What is wrong 

`
p = ggplot(data = df) 
p = p + geom_violin(aes(x = 'training_size', y = 'error', fill='type'), bw = 0.1)
p = p + facet_grid(['method', 'type'])
p
`
PlotnineError: "Parameters {'bw'}, are not understood by either the geom, stat or layer.

**Comment by has2k1** [comment]
I cannot reproduce this. What version of plotnine are you using?
