### ISSUE TITLE
scale differs when starting at zero

### ISSUE THREAD

**Issue by aflueckiger** [has2k1/plotnine#49]
First of all, thanks for the great implementation of ggplot2 for Python.

Unfortunately, I might have spotted an issue with the scaling of a smoothed facet plot. The following code creates a plot that starts at 0.01 based on the data:

    plot = (ggplot(df_docs_model) +
        aes(x='quarter_num', y='value', color='factor(topic)') +
        geom_smooth(method='loess', span = 0.1, alpha=0.2, size=2, show_legend=False) + 
        scale_x_continuous(breaks=list(range(1994, 2019, 2))) +
        scale_y_continuous(breaks=[y / 100 for y in range(0, 15, 1)]) +
        facet_wrap('~topic')) 

When I set the scale manually to make sure the y-axis starts by zero, the axis adjusts accordingly. As you can tell from the plots, however, the values between these figures differ. 
To set the y-scale I used the this statement:

        scale_y_continuous(expand = (0,0), limits = (0,0.1))

I suspect that the statement above restricts the data (only values between 0 and 0.1 are considered) instead of limiting the scale. Do I use the wrong statement? Or is this an issue in the present implementation? Thanks for any clarification.
 
![v2_fig_start_at_zero](https://user-images.githubusercontent.com/11177998/29559820-6a0224ec-8730-11e7-9f9d-bb96d2787b17.png)
![v1_fig_start_at_0 01](https://user-images.githubusercontent.com/11177998/29559821-6a04f8b6-8730-11e7-97ac-d2caf2f6ed04.png)

**Comment by votti** [comment]
I think this is the 'correct' or at least the  behaviour consistent with R ggplot2. I think coord_cartesian should be used instead.
http://ggplot2.tidyverse.org/reference/coord_cartesian.html

**Comment by aflueckiger** [comment]
@votti Thanks for pointing out that I used the wrong statement to adjust the visible scale. However, the issue is still present even when using the coord_cartesian syntax. 
This code produces the plot below that doesn't start at zero yet.

    plot = (ggplot(df_docs_model) +
        aes(x='quarter_num', y='value', color='factor(topic)') +
        geom_smooth(method='loess', span = 0.1, alpha=0.2, size=2, show_legend=False) + #  
        scale_x_continuous(breaks=list(range(1994, 2019, 2))) +
        scale_y_continuous(breaks=[y / 100 for y in range(0, 15, 1)]) +
        coord_cartesian(ylim = (0, 0.14)) +
        facet_wrap('~topic'))
![fig_coord_cart](https://user-images.githubusercontent.com/11177998/29588716-dbb779cc-8792-11e7-9a3b-0c2ad6c66d8d.png)

Is this feature already properly implemented in plotnine? I'm asking this again since the respective ggplot2 documentation, posted by votti, explicitly specifies this use case.

**Comment by has2k1** [comment]
@votti is right. However, there was a bug in `coord_cartesian` when setting the `ylim`. It was fixed in #30.

Try the development version

```python
pip install git+https://github.com/has2k1/plotnine.git
``` 
to see if it works for you.

**Comment by aflueckiger** [comment]
It worked fine with the current development version. I appreciate your help. Thanks.
