### ISSUE TITLE
coord_cartesian with datetime axis

### ISSUE THREAD

**Issue by dopazo** [has2k1/plotnine#490]
Hi,
Is there a way to use `coord_cartesian` when one of my axis is datetime format? Im trying to make a "zoom" but i cant use `scale_x_continuous` since i need to have a segment in a future date.

Example of what i have:
![imagen](https://user-images.githubusercontent.com/30671074/107834242-73b7ee80-6d74-11eb-84c1-6a1890affda9.png)

Trying to add `coord_cartesian` results in an error:
```python
plot = (ggplot(df_total, aes(x="date",y="value"))
        +annotate("segment",
                  x=datetime.datetime(2021, 2, 2),
                  xend=datetime.datetime(2021, 8, 1),
                  y=0,yend=5000000,
                  alpha=0.5, linetype="dashed")
        +geom_line()
        +labs(title="Title", x="",y="")
	#ERROR: unsupported operand type(s) for +: 'datetime.timedelta' and 'int'
        +coord_cartesian(xlim=(datetime.datetime(2021, 2, 10),
                               datetime.datetime(2021, 2, 14)),
                         ylim=(0,2000000))
)
```
Is this a limitation of plotnine or am i doing something wrong?

Thanks in advance.

**Comment by joshhartmann11** [comment]
Instead of using `coord_cartesian` for setting the limits on the axis, you can use the x and y scales.

```python
plot = (ggplot(df_total, aes(x="date",y="value"))
        + annotate("segment",
                   x=datetime.datetime(2021, 2, 2),
                   xend=datetime.datetime(2021, 8, 1),
                   y=0,yend=5000000,
                   alpha=0.5, linetype="dashed")
        + geom_line()
        + labs(title="Title", x="",y="")
	+ scale_x_datetime(limits=(datetime.datetime(2021, 2, 10),
                                   datetime.datetime(2021, 2, 14)))
        + scale_y_continuous(limits=(0, 2000000))
)
```

**Comment by johnmellor** [comment]
Adding `limits` on a scale isn't the same, since that causes datapoints outside of the limits to be dropped completely. `coord_cartesian` (or other coordinate systems) is the recommended approach for clipping a plot without discarding points per https://ggplot2.tidyverse.org/reference/coord_cartesian.html and https://stackoverflow.com/a/25685952. It would be nice to make it work with Python datetime/timedelta values.

**Comment by has2k1** [comment]
@johnmellor, Please file a separate issue to track this.

**Comment by tyatabe** [comment]
I'm bumping into this now. I'm guessing this was never fixed?
