### ISSUE TITLE
Lots of tests fail: font sizes don't match the reference images

### ISSUE THREAD

**Issue by juliangilbey** [has2k1/plotnine#491]
Hi, what an amazing package - thank you!

I've tried building it, but lots of the tests fail. Exploring a little further, I see it is because the font sizes differ between my results and the reference images. I have build this in a clean chroot, so I have no idea where the problem originates. Perhaps `matplotlib` has changed some default behaviour?

Attached are three examples of the output I am getting so you can see the difference: `test_annotation_logticks_faceting.png`, `test_theme_bw.png`, `test_coord_trans_backtransforms.png`

Best wishes, Julian

![test_annotation_logticks_faceting](https://user-images.githubusercontent.com/1658936/107873042-34d68580-6ea7-11eb-9b3b-45eda1fd3162.png)
![test_theme_bw](https://user-images.githubusercontent.com/1658936/107873040-343def00-6ea7-11eb-94c0-746db8c3d778.png)
![test_coord_trans_backtransforms](https://user-images.githubusercontent.com/1658936/107873041-343def00-6ea7-11eb-8236-af101ed2667b.png)

**Comment by has2k1** [comment]
You want to test locally you need to install Matplotlib from source. For example

    pip install matplotlib --no-binary matplotlib

This way it uses the packaged/local in freetype library for rendering text. Otherwise, different versions of `freetype` may yield minor but bothersome differences in the rendered text.

**Comment by juliangilbey** [comment]
Hi Hassan!

Thanks for looking at this.  Unfortunately, though, this has not solved the problem: I installed plotnine into a virtual environment with matplotlib installed with --no-binary, and I still get 28 failures for the same reasons.
