### ISSUE TITLE
Manually controlling themeable elements in guides

### ISSUE THREAD

**Issue by AlFontal** [has2k1/plotnine#497]
Hi!

I am convinced I solved this issue a long time ago so there must be a way within the API to handle this:

When I manually set a themeable element in the call to a geom, the guides inherit this (and in most cases, this is something we want). However, there are some cases, such as when using low alphas in very dense plots, where I might prefer manual control of the alpha of the guides, otherwise the legend becomes unreadable. 

Minimal example:

```python
n = 10000
df = pd.DataFrame(dict(x=np.random.normal(0, 1, n),
                       y=np.random.normal(0, 1, n),
                       color=np.random.choice(['A', 'B'], n)))

(p9.ggplot(df)
 + p9.aes('x', 'y', color='color')
 + p9.geom_point(alpha=.2)
)
```

![image](https://user-images.githubusercontent.com/10958332/109831010-5376a380-7c3f-11eb-9d8b-a56c8dbaa6ab.png)

Is there any way I can set the alpha in the legend? I have been trying variations of calls to `p9.guides` but I can't seem to find the correct answer.

Thanks!

**Comment by has2k1** [comment]
Use the `override_aes` parameter of `guide_legend`.

```python
(p9.ggplot(df)
 + p9.aes('x', 'y', color='color')
 + p9.geom_point(alpha=.2)
 + p9.guides(color=p9.guide_legend(override_aes={'alpha': 1}))
)
```

**Comment by AlFontal** [comment]
That was it! Thanks :)
