### ISSUE TITLE
Alpha arguments in geom_point, geom_line do not change transparency

### ISSUE THREAD

**Issue by BlackArbsCEO** [has2k1/plotnine#50]
Whenever I try to use the alpha argument to change transparency, especially with geom_point, transparency is left unchanged. Could be a bug?

**Comment by has2k1** [comment]
Please include an example.

**Comment by BlackArbsCEO** [comment]
sure. 
```
g = (pn.ggplot(stack, pn.aes('order_period', 'rank', color='factor(cohort_group)', alpha=0.05))
     + pn.geom_point(pn.aes(shape='factor(is_pos)', size=5, alpha=0.05))
     + pn.scale_y_continuous(labels=mzf.percent_format())
     + pn.theme_light()         
     + pn.theme(figure_size=(12,6), panel_background=pn.element_rect(fill='white'), 
                axis_text_x=pn.element_text(rotation=70),) 
     + pn.ylab('pct of cumulative flows')
     + pn.ggtitle('Account transaction as percent of cumsum flows'))

print(g)
```
![no-transparency-scatter-plot-example](https://user-images.githubusercontent.com/7452471/29638731-6eaaf89e-8815-11e7-83d0-e49ec748154c.png)

**Comment by has2k1** [comment]
You are doing it wrong. You should not set aesthetic values in the `aes()` call. `aes()` maps data to an aesthetic, it *does not set the value* of the aesthetic.

This is what it should look like

```python
     + pn.geom_point(pn.aes(shape='factor(is_pos)'), size=5, alpha=0.05)
```
