### ISSUE TITLE
plot line beyond default clip?

### ISSUE THREAD

**Issue by CarlosGrohmann** [has2k1/plotnine#501]
When plotting a line, I set the x-axis limits to, say, 4200-5000. The line data goes way beyond these values, but give the point spacing, only a portion of the line is plotted (see attached image). Can I plot the entire line inside the x-limits? 

![plot](https://user-images.githubusercontent.com/1870265/112035141-068b3c00-8b1e-11eb-8117-636eca08877f.png)

**Comment by has2k1** [comment]
Use `coord_cartesian` to set the limits.

Data points that are beyond the limits of a scale are dropped as the scale does not know how to handle them; the limits define the domain of the scale. Limits of the coordinate axes do not say anything about the data points, they define the area you are interested in.
