### ISSUE TITLE
Tryout figure.add_subfigure 

### ISSUE THREAD

**Issue by has2k1** [has2k1/plotnine#504]
New (and still experimental) in MPL 3.4.0

https://matplotlib.org/3.4.0/api/figure_api.html#matplotlib.figure.Figure.add_subfigure
https://matplotlib.org/3.4.0/gallery/subplots_axes_and_figures/subfigures.html

**Comment by jianshu93** [comment]
seems doable to make it similar to cowplot in R

Jianshu
