### ISSUE TITLE
Horizontal alignment of facet title not working

### ISSUE THREAD

**Issue by DiogoFerrari** [has2k1/plotnine#506]
If I use `strip_text=element_text(size=11, face='bold',  ha='left', va='center')`, the ha='left' has no effect.

**Comment by rocarvaj** [comment]
Hi! Could you provide a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example#:~:text=In%20computing%2C%20a%20minimal%20working,to%20be%20demonstrated%20and%20reproduced.&text=A%20minimal%20working%20example%20may,short%20self%2Dcontained%20correct%20example.)? That way it will be easier for people here to detect/analyze the issue.
