### ISSUE TITLE
Error in `reorder()` function when using a particular column name

### ISSUE THREAD

**Issue by rocarvaj** [has2k1/plotnine#508]
I was coming up with an example in which I needed to reorder the columns of a `geom_col()` plot. I used the `mpg`database and  created a plot which has the mean of the `cty` variable for each possible value of the `class` variable.
The problem is that when I try to use `aes(x = 'reorder(class, cty)', y = 'cty')` I get an error, but if I change the name of the x variable it works. It seems to be a problem with the name "class".

Here is a MRE of the issue:

```python
import pandas as pd
from plotnine import ggplot, aes, geom_col

from plotnine.data import mpg

# Computing average of cty by class
avg_cty_per_class = pd.pivot_table(mpg, index = 'class', values = 'cty', aggfunc = 'mean').reset_index()

(
    ggplot(avg_cty_per_class, aes(x = 'reorder(class, cty)', y = 'cty')) +
    geom_col()
)
```

I get the error:
`PlotnineError: "Could not evaluate the 'x' mapping: 'reorder(class, cty)' (original error: invalid syntax (<string>, line 1))"`

But if I change the name of the `class` variable, for example with:
```python
avg_cty_per_class.rename(columns = {'class': 'carclass'}, inplace = True)

(
    ggplot(avg_cty_per_class, aes(x = 'reorder(carclass, cty)', y = 'cty')) +
    geom_col()
)
```
it works.

I'm using: 
```
pandas                    1.2.1            py38hb2f4e1b_0
plotnine                  0.7.1                      py_0    conda-forge
```

Thanks!

**Comment by has2k1** [comment]
`class` is python keyword, any expression that includes a keyword will fail. There isn't an easy way to fix it.

**Comment by rocarvaj** [comment]
Thanks for the prompt reply! I understand. May I suggest a warning regarding this in the documentation?
