### ISSUE TITLE
the need to assign ggplot to variable to plot

### ISSUE THREAD

**Issue by ilcaa72** [has2k1/plotnine#513]
i am using Spyder IDE and the only way to plot is assigning the statement to a variable and printing() it.  does anyone have this issue with other (or same Spyder) IDE's? is there a solution, or is this standard .  i dont see tutorials with this need, Spyder uses the Jupyter IPython console... thanks for any info

```
 a = (ggplot(mtcars, aes('wt', 'mpg', color='factor(gear)'))
     + geom_point()
     + stat_smooth(method='lm')
     + facet_wrap('~gear'))

print(a)
```

**Comment by has2k1** [comment]
This is the standard. It is normally not an issue because Jupyter notebook/console automatically prints the last object of the cell and having the plot object be the last in the cell is a common workflow.
