### ISSUE TITLE
stat_sina maxwidth ignores the group aesthetic

### ISSUE THREAD

**Issue by gokceneraslan** [has2k1/plotnine#514]
I am enjoying geom_sina() in the following plot:

<img width="343" alt="image" src="https://user-images.githubusercontent.com/1140359/116819217-15153c00-ab3d-11eb-8190-446d12af7261.png">

However, there is a tiny problem which is that the geom_sina dots are spilling over to the nearby boxes, e.g:

<img width="77" alt="image" src="https://user-images.githubusercontent.com/1140359/116819967-a20dc480-ab40-11eb-8a50-65c54362b6c2.png">

Not sure if it's the right argument, but when I try to reduce the variance of geom_sina() points with a smaller maxwidth (e.g. maxwidth=0.1), the group/color aes() is ignored and they are shrunk jointly:

<img width="337" alt="image" src="https://user-images.githubusercontent.com/1140359/116819201-03339900-ab3d-11eb-84db-669b7f66641e.png">

I was wondering if it's a bug or am I missing something.

**Comment by gokceneraslan** [comment]
I also couldn't make the "group" parameter work here, "color" aesthetic leads to the correct grouping, but not specifying the color aesthetic but providing a group parameter doesn't seem to work:

<img width="190" alt="image" src="https://user-images.githubusercontent.com/1140359/116820105-41cb5280-ab41-11eb-9a49-8c42e5ac7587.png">

**Comment by joshhartmann11** [comment]
Hello,

## MRE
```
import plotnine as gg
import pandas as pd
import numpy as np

SIZE = 10000

df = pd.DataFrame({
    "y": np.random.normal(size=(SIZE)), 
    "x": np.random.choice([0,1,2], size=SIZE)})

plt = (gg.ggplot(df, gg.aes(x="0", y="y", group="x", color="x"))
    + gg.geom_sina()
    + gg.ggtitle("-"))
```
![sina0](https://user-images.githubusercontent.com/29384703/116842283-df9a3e00-ab90-11eb-8e6b-2a42d7d40fb9.png)

## Problem
It looks like you have a single x category and multiple groups. In this case, each group is plotted side-by-side (centred on the single x category).  When you decrease the width of the sina plot, the groups are still plotted side-by-side and no longer match the boxplots.
```
plt = (gg.ggplot(df, gg.aes(x="0", y="y", group="x", color="x"))
    + gg.geom_sina(maxwidth=0.1)
    + gg.ggtitle("maxwidth=0.1"))
```
![sina1](https://user-images.githubusercontent.com/29384703/116842293-ecb72d00-ab90-11eb-875e-6dbf7dc889fd.png)

## Fix 1: Plot each group with their own x category
```
plt = (gg.ggplot(df, gg.aes(x="x", y="y", group="x", color="x"))
    + gg.geom_sina(maxwidth=0.1)
    + gg.ggtitle("maxwidth=0.1, x=x"))
```
![sina3](https://user-images.githubusercontent.com/29384703/116842480-8da5e800-ab91-11eb-9aed-4dfb26d2faf0.png)

## Fix 2: `maxwidth=k`
I don't know the justification behind the default value for `maxwidth`, `params['maxwidth'] = resolution(data['x'], False) * 0.9`, but you can fix this value to some `k` so your sina plot will line up better with the boxplots.  This may require some trial and error or a dig through the boxplot code.
```
plt = (gg.ggplot(df, gg.aes(x="0", y="y", group="x", color="x"))
    + gg.geom_sina(maxwidth=1)
    + gg.ggtitle("maxwidth=1"))
```
![sina4](https://user-images.githubusercontent.com/29384703/116843582-3b66c600-ab95-11eb-9eff-ab2cc62066f3.png)

**Comment by has2k1** [comment]
@gokceneraslan, it certainly seems like the `x` axis and the `color` are different groups as @joshhartmann11 has shown. Otherwise if they belong to the same group, then the `maxwidth` would be sufficient to control the randomness that could have the points fall outside the boxplot limits.

**Comment by has2k1** [comment]
Maybe you could match the width of the points to that of the boxes. e.g

```python
...
 + geom_sina(maxwidth=.95)
 + geom_boxplot(width=.95)
```
