### ISSUE TITLE
Horizontal Box Plots

### ISSUE THREAD

**Issue by cogerk** [has2k1/plotnine#516]
Hi All, 

I am getting some strange behavior with boxplot where horizontal boxplots get pancaked. Verticals are fine:

```
from plotnine.data import diamonds

ggplot(diamonds, aes(x="cut", y="price")) + geom_boxplot()
```
![image](https://user-images.githubusercontent.com/9560816/118318720-9f02c480-b4ae-11eb-9046-ab9fac104e70.png)

And then when I switch X & Y:
```
from plotnine.data import diamonds

ggplot(diamonds, aes(y="cut", x="price")) + geom_boxplot()
```
![image](https://user-images.githubusercontent.com/9560816/118318768-b04bd100-b4ae-11eb-8855-83230d65b07c.png)

Changing width doesn't fix the issue
```
from plotnine.data import diamonds

ggplot(diamonds, aes(y="cut", x="price")) + geom_boxplot(width=100)
```
![image](https://user-images.githubusercontent.com/9560816/118318454-459a9580-b4ae-11eb-8986-4fc6510fa209.png)

Has anyone else seen this? Is this a bug or operator error?

Versions and Environment:
Windows 10 SSH into Azure box
Python - 3.8.5
Virtual Environment -20.0.16 using
    Jupyter-Lab - 3.0.14
    Plotnine - 0.8.0

**Comment by TyberiusPrime** [comment]
Due to limitations in how ggplot worked, some ground have preconceptions about their orientation. Use coord_flip to swap x and y instead.

**Comment by has2k1** [comment]
> Due to limitations in how ggplot worked, some ground have preconceptions about their orientation. Use coord_flip to swap x and y instead.

Yes using `coord_flip` is the right thing to do at the moment.

**Comment by cogerk** [comment]
Gotcha, thanks all! Really appreciate the help.

**Comment by dmi3kno** [comment]
I think this would be good to note as a limitation in the [boxplot documentation](https://plotnine.org/reference/geom_boxplot.html)
