### ISSUE TITLE
Inconsistent spacing between geoms at different figure sizes

### ISSUE THREAD

**Issue by AlFontal** [has2k1/plotnine#519]
This is an issue I usually solve by just increasing the figure size until the rendered figure displays the spacing as desired, however, I believe it could be solved without the need to modify the figure size. 

To illustrate a minimal example:

If I have a dataset with a relatively high amount of unique `x` values as this one:

```python
import numpy as np
import pandas as pd
import plotnine as p9

n=80
np.random.seed(7)
df = pd.DataFrame(dict(x=np.arange(n), y=np.random.randint(1, 10, size=n)))
```
And I try to generate a barplot with default theme:

```python
(p9.ggplot(df) 
 + p9.aes('x', 'y', group='x') 
 + p9.geom_col()
)
``` 
![image](https://user-images.githubusercontent.com/10958332/120791542-a27cef00-c534-11eb-8c35-fdb63a5d0ab0.png)

Some of the bars get spacing between each other, but some other don't.

In order to get all the spacing to be actually drawn, one can either:
1. Increase the horizontal figure size
2. Increase the `dpi`
3. Decrease the `width` argument of `geom_col`

```python
(p9.ggplot(df) 
 + p9.aes('x', 'y', group='x') 
 + p9.geom_col()
 + p9.theme(figure_size=(12, 3))
)
```
![image](https://user-images.githubusercontent.com/10958332/120791579-aad52a00-c534-11eb-8adf-b9f3aafc3616.png)

```python
(p9.ggplot(df) 
 + p9.aes('x', 'y', group='x') 
 + p9.geom_col()
 + p9.theme(dpi=250))
)
```
![image](https://user-images.githubusercontent.com/10958332/120791638-be809080-c534-11eb-8d3f-53e62c4c9a24.png)

```python
(p9.ggplot(df) 
 + p9.aes('x', 'y', group='x') 
 + p9.geom_col(width=.8)
)
```
![image](https://user-images.githubusercontent.com/10958332/120791775-e7a12100-c534-11eb-97d0-82ac8a67a4d5.png)

Notice that while the spaces are now drawn, the actual space between bars is not consistent, and still shows some differences in all of the three cases. I really don't know where to start looking as to understand where the inconsistencies are defined and whether this is something coming from `matplotlib` itself. 

This issue also happens with `geom_bar`, `geom_rect`, `geom_tile` and any other shape based geoms, of course.

It's nothing more than a mild annoyance, but it would be great if it could somehow be resolved, or at least understand how to solve it with less `hacky` methods.

**Comment by has2k1** [comment]
This cannot be fixed. These are rasterizing effects because you are creating a `png` with many objects in a small area. There isn't enough space to place the objects. 

To really understand what is happening save the result as a `pdf`.

```python
(p9.ggplot(df) 
 + p9.aes('x', 'y', group='x') 
 + p9.geom_col()
).save('col-spacing.pdf')
```

When you zoom out of the image in the `pdf` and there isn't enough space to better resolve the positions of the columns, you get the same effect. Yet if you zoom in, the spacing becomes visible. The image `pdf` is fine but space on your screen isn't continuous!

However, in practice you can avoid this effect by increasing the space between the columns using the `width` parameter.

```python
(p9.ggplot(df) 
 + p9.aes('x', 'y', group='x') 
 + p9.geom_col(width=0.7)
)
```

**Comment by AlFontal** [comment]
Fair enough, I understand that to generate a png the vectors are rasterized and each pixel be assigned a value. However, I do believe that the rasterizing algorithm acts as if it was being drawn at a lower resolution than it actually is. See the example with the same figure saved as `pdf` on the left and `png` on the right: 

![image](https://user-images.githubusercontent.com/10958332/121327869-20197400-c914-11eb-8afe-ad7e706f7b00.png)

There are clearly enough pixels to draw the spaces between bars, yet these are not being drawn. I have to zoom out _a lot_ to actually stop seeing the spaces (and I am using a standard 1080p screen).

Nevertheless, I am clearly out of depth here and the resolution of spaces/positions when actually drawing the figure is most certainly handled upstream by `matplotlib`, so most likely this isn't that relevant to the plotnine package after all. 

On top of that, `R`'s `ggplot2` yields practically the same image on the same dataset when using exactly the same resolution:

![image](https://user-images.githubusercontent.com/10958332/121330944-bd75a780-c916-11eb-91a7-e6762fcd473a.png)

**Comment by has2k1** [comment]
>There are clearly enough pixels to draw the spaces between bars, yet these are not being drawn. I have to zoom out a lot to actually stop seeing the spaces (and I am using a standard 1080p screen).

The PDF seems to be more-less antialiasing (or maybe just naively interpolating), which gives the appearance of spaces. So a pixel or two are being stolen from a a couple of columns. So, there isn't enough space, if there were you would expect some of the spaces to be large than the others with the number (of the larger spaces) at least equivalent to the number of the joined columns.

**Comment by AlFontal** [comment]
Makes sense! Thanks for the short lesson on rasterizing and anti-aliasing, I was completely clueless :grin: 

I will close the issue. Thanks again for a great package!
