### ISSUE TITLE
Y-axis labels duplicate 0 with log10 axis

### ISSUE THREAD

**Issue by ctSkennerton** [has2k1/plotnine#52]
I think there is a weird formatting issue where very small numbers get printed as 0 after an axis has been transformed with log10. See example below with two 0 on the y-axis

```python
import pandas as pd
from plotnine import ggplot, aes, scale_y_log10, geom_boxplot

reprex = pd.DataFrame({'value': [0.0000000001,0.00000000001,1,5,100000,4739273,11,0.0001,0.00000000001, 0.00001,0.00001,1,5,100000,4739273,11,0.0001,0.00001],
                           'cat':['1','1','1','1','1','1','1','1','1','2','2','2','2','2','2','2','2','2']})

p = ggplot(reprex, aes('cat', 'value')) + scale_y_log10() + geom_boxplot()
```

![plotnine](https://user-images.githubusercontent.com/685235/29806903-75dd6720-8c46-11e7-9bbf-29c1a9d5536a.png)

compare to `ggplot2` which transforms the numbers into scientific notation

![rplot](https://user-images.githubusercontent.com/685235/29806952-a126fdd8-8c46-11e7-8941-424021ce6d6f.png)

**Comment by has2k1** [comment]
The bug is in mizani i.e `mizani.transforms.log_trans.format` should be a custom formatter for log values.

**Comment by has2k1** [comment]
@ctSkennerton, is it possible for you to try out the solution

```
pip install git+https://github.com/has2k1/mizani.git@dev
```

Thanks.

**Comment by ctSkennerton** [comment]
looks good
![plotnine](https://user-images.githubusercontent.com/685235/29851804-077dd062-8ceb-11e7-97a0-71d240f58074.png)

**Comment by has2k1** [comment]
Great. Have you tried it on any other cases other than the `reprex`?

**Comment by ctSkennerton** [comment]
I've tried it on the 'real' data where I first saw this. It worked fine, but it's also a boxplot with a transformed y-axis

**Comment by has2k1** [comment]
Nice. There are some small arbitrary choices that I made, I was hoping they were not obviously objectionable.
