### ISSUE TITLE
I do not understand the behavior of violins with a categorical X and a facet (examples inside)

### ISSUE THREAD

**Issue by jrr96** [has2k1/plotnine#533]
Hello, I have been fighting with this for a couple of days and I am honestly giving up. I do not understand how to plot what I am looking for.

This code produces the right shapes:
`print(
    ggplot(temp_df3, aes(x=0, y="Value"))
    + geom_violin()
    + facet_grid(["Segment", "Group"])
)`
<img width="306" alt="good" src="https://user-images.githubusercontent.com/92081722/139032936-db723db8-1a41-437e-86e9-0d681c547434.png">

However, for consistency with the rest of the plots I am making, I would like to have the Segment on the X axis. I am using this code:

`print(
    ggplot(temp_df3, aes(x="Segment", y="Value"))
    + geom_violin()
    + facet_wrap("Group")
)`

But then this gets plotted (notice group1-b and group3-b):

<img width="295" alt="bad" src="https://user-images.githubusercontent.com/92081722/139033145-0339e4af-cf63-4320-8808-7f7fb1595a02.png">

The data is in tidy format with columns being ['Group', 'Segment', 'ID', 'Value']
- Group: categorical, unordered. Values: Group 1, Group 2, Group 3, or Group 4
- Segment: categorical, unordered. Values: A or B
- ID: int64
- Value: float64

Additional info, boxplots work just fine.

Please some help would be really appreciated here!

Relevant files:
[exampledf.csv](https://github.com/has2k1/plotnine/files/7424995/exampledf.csv)

**Comment by joshhartmann11** [comment]
# Minimal Reproducible Example (MRE)
```
import pandas as pd
import plotnine as gg

df = pd.DataFrame({
    "Group": "Group 3",
    "Segment": ["B", "B", "A", "A"],
    "Value": [1000.0, 0.0, 0.0, 0.0]})

plt = (gg.ggplot(df, gg.aes(x="Segment", y="Value", group="Segment"))
    + gg.geom_violin()
    + gg.facet_wrap("Group"))

plt.save("test_0.png")

plt = (gg.ggplot(df, gg.aes(x=0, y="Value"))
    + gg.geom_violin()
    + gg.facet_grid(["Segment", "Group"]))

plt.save("test_1.png")
```
![test_0](https://user-images.githubusercontent.com/29384703/140637039-4e28fc5b-4452-455c-b052-b0ab565f179f.png)
![test_1](https://user-images.githubusercontent.com/29384703/140637043-fc12d27e-6446-480d-b73c-e92210e9a238.png)

# Solution

Use the `scale` option. The `width` value for that option gives you what you want.

```
import pandas as pd
import plotnine as gg

df = pd.DataFrame({
    "Group": "Group 3",
    "Segment": ["B", "B", "A", "A"],
    "Value": [1000.0, 0.0, 0.0, 0.0]})

plt = (gg.ggplot(df, gg.aes(x="Segment", y="Value", group="Segment"))
    + gg.geom_violin(scale="width")
    + gg.facet_wrap("Group"))

plt.save("test_0.png")

plt = (gg.ggplot(df, gg.aes(x=0, y="Value"))
    + gg.geom_violin(width=1000, scale="width")
    + gg.facet_grid(["Segment", "Group"]))

plt.save("test_1.png")
```
![test_0](https://user-images.githubusercontent.com/29384703/140637184-aac902c1-6e62-4061-a940-41b5b81a493f.png)
![test_1](https://user-images.githubusercontent.com/29384703/140637187-5f6ebbf6-8058-40c7-9cf0-092126ccc130.png)

**Comment by has2k1** [comment]
@joshhartmann11, That is it. You can see the effect of scaling by the area by varying the range of values from low to high. 
 e.g.

```python
df = pd.DataFrame({
    "Group": "Group 3",
    "Segment": ["B", "B", "A", "A"],
    "Value": [1, 0.0, 0.0, 0.0]  # Try 1, 10, 100, 1000
 })
```
