### ISSUE TITLE
Request: re-license under MIT?

### ISSUE THREAD

**Issue by danking** [has2k1/plotnine#546]
Hello!

We (GitHub.com/hail-is/hail) build a tool similar to pandas and we would like to leverage plotnine as one of the plotting options. Unfortunately, we're concerned that importing a GPLv2 library into our MIT licensed code is not permitted by the GPLv2.

[In 2020, it appears that ggplot2 re-licensed under MIT](https://github.com/tidyverse/ggplot2/issues/4236) ([see also the CRAN page](https://cran.r-project.org/web/packages/ggplot2/index.html)). I believe ggplot2's license was your original motivation for licensing under GPLv2. Would you consider re-licensing under MIT now that ggplot2 is also MIT licensed?

Thank you much!

**Comment by has2k1** [comment]
> I believe ggplot2's license was your original motivation for licensing under GPLv2.

Yes it was.
