### ISSUE TITLE
Combine geom_bin2d and stat_bin2d to show bin counts gives error

### ISSUE THREAD

**Issue by oliverester** [has2k1/plotnine#549]
I would like to create a 2d histogram and show the counts per bin as text.
However, I get an error claiming I have to provide x, y aesthetics which I however provide in the "gloabal" aes.

```
File "/Users/x/Repositories/tmp/plotnine_test.py", line 18, in <module>
    ggsave(plot = p, filename = 'test.jpg', path = ".", verbose = False, width = 8, height = 8)
  File "/Users/x/opt/miniconda3/lib/python3.9/site-packages/plotnine/ggplot.py", line 739, in ggsave
    return plot.save(*arg, **kwargs)
  File "/Users/x/opt/miniconda3/lib/python3.9/site-packages/plotnine/ggplot.py", line 727, in save
    fig, p = self.draw(return_ggplot=True)
  File "/Users/x/opt/miniconda3/lib/python3.9/site-packages/plotnine/ggplot.py", line 205, in draw
    self._build()
  File "/Users/x/opt/miniconda3/lib/python3.9/site-packages/plotnine/ggplot.py", line 308, in _build
    layers.setup_data()
  File "/Users/x/opt/miniconda3/lib/python3.9/site-packages/plotnine/layer.py", line 59, in setup_data
    l.setup_data()
  File "/Users/x/opt/miniconda3/lib/python3.9/site-packages/plotnine/layer.py", line 365, in setup_data
    check_required_aesthetics(
  File "/Users/x/opt/miniconda3/lib/python3.9/site-packages/plotnine/utils.py", line 384, in check_required_aesthetics
    raise PlotnineError(
plotnine.exceptions.PlotnineError: 'geom_text requires the following missing aesthetics: x, y'
```

This is the example I run:
```
import pandas as pd
import random 

from plotnine import (
    aes,
    after_stat,
    ggplot,
    geom_bin2d, 
    ggsave, 
    stat_bin2d)

data = {'col_1': [random.random() for _ in range(1000)], 'col_2': [random.random() for _ in range(1000)]}
df =pd.DataFrame.from_dict(data)
p = ggplot(df, aes(x='col_1', y='col_2')) + \
    geom_bin2d(position="identity", binwidth=0.1) + \
    stat_bin2d(aes(label = after_stat('count')), geom="text")
ggsave(plot = p, filename = 'test.jpg', path = ".", verbose = False, width = 8, height = 8)
```
This is the output without geom_bin2d:
![test](https://user-images.githubusercontent.com/11405884/146366752-d46f793d-b3b6-4fe2-ab0d-4fd1e7ca30f7.jpg)
I would like to see the count per bin as text there.

I guess the aes are not piped through to the geom_text call?

**Comment by has2k1** [comment]
You need to use [staged](https://plotnine.readthedocs.io/en/latest/generated/plotnine.mapping.stage.html#plotnine-mapping-stage) aesthetic evaluation.

`stat_bin_2d` consumes `x` and `y` aesthetics then computes `xmin`, `xmax`, `ymin` & `ymax` aesthetics. I realise this is not documented. The computed aesthetics define the boundaries of the bins. `geom_text` requires `x` and `y` aesthetics at which to place the text. With staged evaluation you tell `stat_bin_2d` to start with `x` and `y` mapped to the columns in the dataframe, and then after the statistic computation to compute the `x` and `y` using the respective minimum and maximum values.

```python
import random
from plotnine import *
import pandas as pd

random.seed(123)
data = {'col_1': [random.random() for _ in range(1000)], 'col_2': [random.random() for _ in range(1000)]}
df =pd.DataFrame.from_dict(data)

(ggplot(df, aes(x='col_1', y='col_2'))
 + geom_bin2d(position="identity", binwidth=0.1)
 + stat_bin2d(
     aes(
         x=stage(start='col_1', after_stat='(xmin+xmax)/2'),
         y=stage(start='col_2', after_stat='(ymin+ymax)/2'),
         label=after_stat('count')
     ), binwidth=0.1, geom="text", size=8
 )
)
```

![staged-evaluation](https://user-images.githubusercontent.com/780341/146439015-0b329efb-f858-48e0-9954-a51f94ad276c.png)

Also note, that you have to match the parameters (in this case _binwidth_) in the two calls to `stat_bin_2d`.

I think this is a good example to add to the documentation for staged aesthetic evaluation.

**Comment by has2k1** [comment]
TODO:

1. Add xmin, ... to the documented computed aesthetics
2. Add example

**Comment by oliverester** [comment]
Great! Thanks for adding this to the documentation.
