### ISSUE TITLE
Possible problem with geom_density() with after_stat('count')

### ISSUE THREAD

**Issue by marcomoretto** [has2k1/plotnine#550]
This code works as expected (density histogram with kde)

```
from plotnine import *
import pandas as pd

p_df = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/penguins.csv')

(
    ggplot(p_df.dropna(), aes(x='body_mass_g', y=after_stat('density')))
    + geom_density(aes(color='species'), alpha=0.8)
    + geom_histogram(aes(fill='species'), bins=20, alpha=0.5, position='identity')
)
```
![image](https://user-images.githubusercontent.com/29454621/146386621-c56e55ec-9339-42da-827e-b66b4a38ad97.png)

But switching from `after_stat('density')` to `after_stat('count')` doesn't.

```
from plotnine import *
import pandas as pd

p_df = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/penguins.csv')

(
    ggplot(p_df.dropna(), aes(x='body_mass_g', y=after_stat('count')))
    + geom_density(aes(color='species'), alpha=0.8)
    + geom_histogram(aes(fill='species'), bins=20, alpha=0.5, position='identity')
)
```
![image](https://user-images.githubusercontent.com/29454621/146386783-54458e68-8bfe-4b0d-b7f6-16c935090f1e.png)

The problem might be related to `geom_density` "ignoring" that `count` should be used instead of `density`. Same code as before with one histogram commented out.

```
from plotnine import *
import pandas as pd

p_df = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/penguins.csv')

(
    ggplot(p_df.dropna(), aes(x='body_mass_g', y=after_stat('count')))
    + geom_density(aes(color='species'), alpha=0.8)
    # + geom_histogram(aes(fill='species'), bins=20, alpha=0.5, position='identity')
)

```
![image](https://user-images.githubusercontent.com/29454621/146387331-b2555337-b383-4677-8947-b30455eb7a5f.png)

[The documentation state that it should work as expected](https://plotnine.readthedocs.io/en/stable/generated/plotnine.geoms.geom_density.html)

**Comment by marcomoretto** [comment]
I think the problem is on my side according to this https://stackoverflow.com/questions/37404002/geom-density-to-match-geom-histogram-binwitdh

So I should rewrite the code as follow

```
(
    ggplot(p_df.dropna(), aes(x='body_mass_g'))
    + geom_density(aes(color='species', y=after_stat('count * 100')), alpha=0.8)
    + geom_histogram(aes(fill='species', y=after_stat('count')), binwidth=100, alpha=0.5, position='identity')
)
```

**Comment by has2k1** [comment]
> I think the problem is on my side according to this https://stackoverflow.com/questions/37404002/geom-density-to-match-geom-histogram-binwitdh
> 
> So I should rewrite the code as follow
> 
> ```
> (
>     ggplot(p_df.dropna(), aes(x='body_mass_g'))
>     + geom_density(aes(color='species', y=after_stat('count * 100')), alpha=0.8)
>     +that is how you match those parameters to account for the fact that the density has a non trivial scale geom_histogram(aes(fill='species', y=after_stat('count')), binwidth=100, alpha=0.5, position='identity')
> )
> ```

Yes you have to match parameters. It makes sense but it is not obvious why. I think it merits an example in the documentation.
