### ISSUE TITLE
geom_line not displaying with datetime.date object coordinate

### ISSUE THREAD

**Issue by ChuliangXiao** [has2k1/plotnine#555]
**plotine** version: 0.8.0

```python
import numpy as np
import pandas as pd
from plotnine import *
import plotnine as p9


data_df = pd.DataFrame({"Date_Pandas": pd.date_range('2022-01-01', periods=10)}) \
    .assign(
        Date_Date=lambda df: df.Date_Pandas.dt.date,
        Value=lambda df: df.index + np.random.rand(len(df))
    )

data_df
```
`data_df.dtypes` shows 

> Date_Pandas    datetime64[ns]
Date_Date              object
Value                 float64
dtype: object

1. When using **Date_Pandas** column, `geom_point` and `geom_line` both work fine
```
(
ggplot(data_df, aes(x='Date_Pandas', y='Value')) \
    + geom_point()
    + geom_line()
)
```
![image](https://user-images.githubusercontent.com/6011789/148981379-9572b967-4a05-4a7f-9c7b-7d58f0933efe.png)

2. When using **Date_Date** column, `geom_line` is not displaying
```
(
ggplot(data_df, aes(x='Date_Pandas', y='Value')) \
    + geom_point()
    + geom_line()
)
```
![image](https://user-images.githubusercontent.com/6011789/148981406-6b8862c8-5a79-48e1-b48d-4c6a770d6fe5.png)

**Comment by has2k1** [comment]
`Date_Date` has a dtype of `object` and this makes it a discrete variable. For a discrete variable different points belong to different groups. `geom_line` only links points in the same group. So you have to override the automatic grouping so that all points are in the same group. e.g. `geom_line(group=1)`.
