### ISSUE TITLE
plot_title (and perhaps text_element() in general) ha argument controls anchor point, not actual alignment/position

### ISSUE THREAD

**Issue by jwhendy** [has2k1/plotnine#556]
Greetings,

I prefer left-aligned titles, and was surprised that the `ha = ['left', 'center', 'right']` applies only to what I'll call the "anchor," not the actual position. The position of `plot_title` is always the plot center, and this `ha` option just adjusts which point of the string is tied to that point. Maybe this is what #506 is also about?

**Setup**
```
import pandas as pd
from plotnine import *

df = pd.DataFrame({'x': [1, 2, 3], 'y': [4, 5, 6]})
```

**left**
```
ggplot(df, aes(x = 'x', y = 'y')) + geom_point() + \
labs(title = 'a plot title as a test') + \
theme(plot_title = element_text(ha = 'left'))
```
![grab_2022-01-17_103836](https://user-images.githubusercontent.com/379357/149808129-6c5c4812-3b5a-475d-933e-2e27673a30e4.png)

**center**
```
ggplot(df, aes(x = 'x', y = 'y')) + geom_point() + \
labs(title = 'a plot title as a test') + \
theme(plot_title = element_text(ha = 'center'))
```
![grab_2022-01-17_103842](https://user-images.githubusercontent.com/379357/149808142-784bd5a7-b773-4066-bf53-e8f895fe2c70.png)

**right**
```
ggplot(df, aes(x = 'x', y = 'y')) + geom_point() + \
labs(title = 'a plot title as a test') + \
theme(plot_title = element_text(ha = 'right'))
```
![grab_2022-01-17_103850](https://user-images.githubusercontent.com/379357/149808159-bd4bbdf8-5d75-4307-a657-c5ebec7058b4.png)

The [workaround hack here on SO](https://stackoverflow.com/questions/63784689/plotnine-how-to-caption) is not possible for long titles because this anchoring behavior also applies to the direction in which additional characters are added. In other words, if you wanted the appearance of a left-aligned title but your title is more than half of the plot width, you can't `ha = 'right'` and pad, because the right end of the text will stay at the centerline, and additional characters just result in additional plot margin whitespace:

**right**
```
ggplot(df, aes(x = 'x', y = 'y')) + geom_point() + \
labs(title = 'a longer and longer and longer plot title as a test') + \
theme(plot_title = element_text(ha = 'right'))
```
![grab_2022-01-17_104343](https://user-images.githubusercontent.com/379357/149808781-717f6854-a546-4629-b42d-57527a423f5e.png)

---

As a comparison, the `hjust` argument in R's `ggplot2` does what I'd expect (and I see that `hjust = [0, 0.5, 1]` in `plotnine` seems to just replicate the `ha` behavior).

```
library(ggplot2)
df = data.frame(x = c(1, 2, 3),  y = c(4, 5, 6))
```

**left**
```
ggplot(df, aes(x = x, y = y)) + geom_point() + ggtitle("a plot title as a test") + theme(plot.title = element_text(hjust = 0))
```
![grab_2022-01-17_104731](https://user-images.githubusercontent.com/379357/149809287-8c0106bc-b916-4b81-af56-823d00b14c65.png)

**center**
```
ggplot(df, aes(x = x, y = y)) + geom_point() + ggtitle("a plot title as a test") + theme(plot.title = element_text(hjust = 0.5))
```
![grab_2022-01-17_104742](https://user-images.githubusercontent.com/379357/149809302-7ca5a8e3-7ce1-4c1a-b950-4c6c0b32f438.png)

**right**
```
ggplot(df, aes(x = x, y = y)) + geom_point() + ggtitle("a plot title as a test") + theme(plot.title = element_text(hjust = 1))
```
![grab_2022-01-17_104753](https://user-images.githubusercontent.com/379357/149809318-bf9681c6-eb6f-4df0-8ee1-a0c5c8972029.png)

I saw the note about #46 in #177 [here](https://github.com/has2k1/plotnine/issues/177#issuecomment-413539848), so perhaps this is also an issue given a layout manager (not sure what it is, just inferring potential relevance). Either way, I thought this could be documented.

**Comment by has2k1** [comment]
`ha = ['left', 'center', 'right']` refer to the position of the text around the anchor point. The anchor point is always in the horizontal center of the panel, it never moves. I see that it is an indirect way to refer to the position of the text.

**Comment by has2k1** [comment]
Oops I did not mean to close.

I will look at this when I do a proper review of #553.

**Comment by jwhendy** [comment]
No worries and thanks for the quick look. It is still useful to have this kind of positional control, it just doesn't allow for a truly "left position" of text and doesn't match R's ggplot2.

If you had some ideas on where to look and/or what files might be involved, I absolutely live and die by plotnine and would be happy to try to implement this to contribute. I'm still newer-to-intermediate on my python-fu, so a pointer in the right direction would be awesome if a few files come to mind where these positions are calculated/applied.

**Comment by jsoma** [comment]
If you want a slightly more effective workaround than the SO one for the time being, setting the `x=` for your theme can do a good job!

```python
(
    ggplot(df, aes(x = 'x', y = 'y'))
    + geom_point()
    + labs(title = 'a longer and longer and longer plot title as a test')
    + theme(plot_title = element_text(ha = 'right', x=0.9))
)
```

![right-aligned title done manually](https://user-images.githubusercontent.com/95126/149930059-c75e0cdb-a07c-4084-928c-8188033b7197.png)

**Comment by jwhendy** [comment]
@jsoma I was going to comment on your PR, but this felt like a better fit to understand your comment :) 

Forgive that I haven't dug in to the existing `labs(title = ...)` or your "bespoke function" as you put it, but is the point that plotnine uses something built-in to matplotlib and your function doesn't? Or that `title` is using something "proper" but you're hacking matplotlib?

I just looked around and noted [`suptitle`](https://stackoverflow.com/questions/1388450/giving-graphs-a-subtitle-in-matplotlib) and [`figtext`](https://stackoverflow.com/questions/34010205/adding-caption-below-x-axis-for-a-scatter-plot-using-matplotlib) as things matplotlib provides... is this general desire for all of titles, subtitles, and captions eventually going to be accomplished through matplotlib mechanisms, or is the point that something entirely new is in the works and being built?

I'm just inquiring since you wrote this re. my offer to help above. Not the same as writing a brand new function... but understanding what TheRightWay, as defined by plotnine's future goal/vision, would be helpful to understand!

**Comment by jwhendy** [comment]
Also, @jsoma cool tip on positioning the title!! Looking back at `element_text` [docs](https://plotnine.readthedocs.io/en/stable/generated/plotnine.themes.element_text.html)... I don't see `x` as an arg; is it part of the catchall `kwargsdict: Parameters recognised by matplotlib.text.Text`, then? I didn't know one could pass `x` to `element_text`!

**Comment by jsoma** [comment]
Oh no, nothing fancy like that! I actually just looked at [how titles are done in plotnine](https://github.com/has2k1/plotnine/blob/master/plotnine/ggplot.py#L545) and reproduced it for captions. It's not the most elegant method, even titles would benefit from a nicer layout engine from matplotlib!

And yup, I believe `x` is part of the catchall.
