### ISSUE TITLE
Warnings when using Pandas 1.4

### ISSUE THREAD

**Issue by drhagen** [has2k1/plotnine#560]
In Pandas 1.4.0, the [`.append` method of data frames and series was deprecated](https://github.com/pandas-dev/pandas/pull/44539). This causes warnings to appear in Jupyter when using lots of `plotnine` functions which use `.append`. For example, the fourth example from the README:

```python
from plotnine import *
from plotnine.data import mtcars

(ggplot(mtcars, aes('wt', 'mpg', color='factor(gear)'))
 + geom_point()
 + stat_smooth(method='lm')
 + facet_wrap('~gear'))
```

![Screenshot from 2022-02-03 11-18-13](https://user-images.githubusercontent.com/2952478/152383065-c221d857-bf84-4d5d-ace4-e8d442b90d85.png)

**Comment by has2k1** [comment]
Resolved in https://github.com/has2k1/plotnine/commit/e9cc70dd544ff90e71b4de7360006315e4dba989.
