### ISSUE TITLE
geom_density2d not working

### ISSUE THREAD

**Issue by wheaton5** [has2k1/plotnine#567]
geom_density_2d is not working for me. I've tried all of the underlying options. I was attempting to show gaussian mixture model clustering. So I generate some data, make some choices of starting values, and try to plot it but I get an error.
[density2d.pdf](https://github.com/has2k1/plotnine/files/8074892/density2d.pdf)
.

**Comment by joshhartmann11** [comment]
Hi @wheaton5,

I am unable to reproduce your error. Below are details of what I've run:
```
import numpy as np
import pandas as pd
from plotnine import *

mus1 = [50,140]
mus2 = [0,70]
sds1 = [15,15]
sds2 = [10,30]
samples = 500
x1 = np.random.normal(mus1[0], sds1[0], samples)
y1 = np.random.normal(mus1[1], sds1[1], samples)
x2 = np.random.normal(mus2[0], sds2[0], samples)
y2 = np.random.normal(mus2[1], sds2[1], samples)
df = pd.DataFrame({'x':np.append(x1,x2), 'y':np.append(y1,y2)})

mus1_index = np.random.choice([i for i in range(len(x1)+len(x2))])
mus2_index = np.random.choice([i for i in range(len(x1)+len(x2))])

mus1 = [df['x'][mus1_index], df['y'][mus1_index]]
mus2 = [df['x'][mus2_index], df['y'][mus2_index]]
sds1 = [np.std(df['x']), np.std(df['y'])]
sds2 = [np.std(df['x']), np.std(df['y'])]
mus = [mus1,mus2]
sds = [sds1,sds2]

x1_samp = np.random.normal(mus1[0],sds1[0],1000)
y1_samp = np.random.normal(mus1[1],sds1[1],1000)
x2_samp = np.random.normal(mus2[0],sds2[0],1000)
y2_samp = np.random.normal(mus2[1],sds2[1],1000)
df3 = pd.DataFrame({'x':x1_samp,'y':y1_samp})
df4 = pd.DataFrame({'x':x2_samp,'y':y2_samp})
df1 = pd.DataFrame({'x':[mus1[0]],'y':[mus1[1]]})
df2 = pd.DataFrame({'x':[mus2[0]],'y':[mus2[1]]})

plt = (ggplot(df)
    + geom_point(aes(x='x', y='y'))
    + geom_point(data=df1, mapping=aes(x='x', y='y'), color='red', size=5)
    + geom_point(data=df2, mapping=aes(x='x', y='y'), color='blue', size=5)
    + geom_density_2d(data=df3,mapping=aes(x='x', y='y'), color='red')
    + geom_density_2d(data=df4,mapping=aes(x='x', y='y'), color='blue'))

plt.save("test.png")
```
![test](https://user-images.githubusercontent.com/29384703/154418204-32b7f6da-6e7e-40f9-8610-d490dee8e557.png)

`df3` and `df4` look like the following:

```
             x           y
0    41.358388  145.909009
1    82.969494  183.321511
2    48.238609  113.100693
3    23.250090  189.769575
4    10.126029  147.975746
..         ...         ...
995  40.005044  136.070897
996  73.297434  164.342133
997  46.439862  196.693862
998  58.523437  117.922434
999  68.831479  144.539182

[1000 rows x 2 columns]
             x           y
0    41.315340  162.119101
1    -1.638481   87.822386
2    22.756806  132.940839
3    43.992522   68.280198
4    28.678413   64.425696
..         ...         ...
995  45.260584  155.110230
996  15.008421  187.526922
997  79.290027  160.068976
998  19.350863  110.391693
999  24.118156  133.219057

[1000 rows x 2 columns]
```
Try chipping away at the code till you can find a MRE, if you're still having trouble, post it here with your environment details and I'll see if I can reproduce it. Good luck!

**Comment by wheaton5** [comment]
It could be an apple m1 issue then. Likely not a plotnine issue but something in one of the dependencies.

**Comment by swenlaur** [comment]
I get the similar error on Apple M1 chip for different density plot. The stack trace is similar but the offending bit seems to be incorrect shaping in the code 

`
....
File ~/Library/miniforge3/envs/machine-learning/lib/python3.8/site-packages/plotnine/stats/stat_density_2d.py:158, in contour_lines(X, Y, Z, levels)
    156 # Collapse the info and make it fit for dataframe columns
    157 if segments:
--> 158     x, y = np.vstack(segments).T
    159     piece = np.hstack(piece_ids)
    160     level = np.hstack(level_values)

File <__array_function__ internals>:5, in vstack(*args, **kwargs)

File ~/Library/miniforge3/envs/machine-learning/lib/python3.8/site-packages/numpy/core/shape_base.py:283, in vstack(tup)
    281 if not isinstance(arrs, list):
    282     arrs = [arrs]
--> 283 return _nx.concatenate(arrs, 0)

File <__array_function__ internals>:5, in concatenate(*args, **kwargs)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 2 has 3 dimension(s)
`
This means that either one triggers some sort of corner case or semantics on `numpy` operations has changed. Is there a way to produce a simple repro for function `plotnine` functions

`
Z = density.reshape(len(x), len(y))
data = contour_lines(X, Y, Z, params['levels'])
`
