### ISSUE TITLE
No jupyter output with this data 

### ISSUE THREAD

**Issue by KralaBenjamin** [has2k1/plotnine#569]
I use the following code

> (
>     p9.ggplot(df, p9.aes(x='x', y='y', color='method'))
>     + p9.geom_line(size=1.5) # line plot
>     + p9.theme_538()
>     + p9.theme(figure_size=(20, 10), legend_key_size=30., legend_text=p9.element_text(size=20))
>     + p9.scales.scale_colour_cmap_d(lut=2)
> )

but the output on jupyter lab is just only 

> <ggplot: (8731374541279)>

I attached the data so you can try by yourself.

[error.csv](https://github.com/has2k1/plotnine/files/8125084/error.csv)

Thank you for the help

**Comment by TyberiusPrime** [comment]
Works in my jupyter notebook.

Have you tried 'printing' the plot object?
Is it just this plot, or all plotnine plots?

**Comment by KralaBenjamin** [comment]
@TyberiusPrime Yes, only this plot has problems.

Printing in the Jupyter sense?

**Comment by TyberiusPrime** [comment]
printing as in 'print(p9.ggplot...)'
