### ISSUE TITLE
True/False both plot as False

### ISSUE THREAD

**Issue by jdanbrown** [has2k1/plotnine#57]
```py
df = pd.DataFrame({'x': [1, 2], 'y': [True, False]})
ggplot(df, aes('x', 'y')) + geom_point()
```

![image](https://user-images.githubusercontent.com/627486/30515986-9ac48d02-9ae7-11e7-9c05-009ec6a0f8fe.png)

**Comment by has2k1** [comment]
This is critical. It forces a new release.

**Comment by jdanbrown** [comment]
Thanks!
