### ISSUE TITLE
Shade area under geom_density curve

### ISSUE THREAD

**Issue by Rishika-Ravindran** [has2k1/plotnine#574]
How can we add a shaded area under a geom_density object?
```
(
    ggplot(mum5, aes(x='consideration_amount'))
    + geom_density(alpha=0.3, size=1.8, color = 'teal', fill = 'teal')  + facet_wrap('year', ncol=3) + geom_vline(xintercept=mum5.consideration_amount.median(), size=1.5) +
geom_vline(xintercept=4500000, size=1.5, color='blue') + geom_vline(xintercept=[np.percentile(mum5.consideration_amount, 25), np.percentile(mum5.consideration_amount, 75), np.percentile(mum5.consideration_amount, 99)], color='red', linetype='dotted', size=1.5)
     + xlim(50000, 10474112)  + theme(
    rect=element_rect(color='white', fill='white')) +  theme(text=element_text(size=24, weight='bold')) + theme(subplots_adjust={'hspace': 0.5}) + theme(figure_size=(28, 10)))
```

The code is pasted above and for the resulting visual refer to the image. If I were to shade xlim from (0,45,00,000) in red, how can Ii add that? I have tried the functions and added other objects, nothing seems to produce the desired effect of only shading the area under the curve from 0 to 45 Lacs.
![Screenshot (2085)](https://user-images.githubusercontent.com/84395834/158063044-d04393d5-cf73-4eac-ae28-3e8151513f31.png)

**Comment by has2k1** [comment]
You can do this by creating a custom geom that inherits from `geom_density` and truncating the data outside the range. I will add an example in the documentation.

**Comment by has2k1** [comment]
@Rishika-Ravindran see https://github.com/has2k1/plotnine-examples/blob/9c65443/plotnine_examples/examples/geom_density.ipynb for the solution.
