### ISSUE TITLE
xlim and ylim on qplot have no effect

### ISSUE THREAD

**Issue by Gaasmann** [has2k1/plotnine#575]
Hello,

I was testing qplot() and it seems the parameters xlim and ylim have no effect. I can't find them used in the qplot function's code either.

An example:
```python
from plotnine import *
from plotnine.data import economics
qplot("carat", data=diamonds, facets="color ~ .", geom="histogram", binwidth=0.1, xlim=(0,3))
```
![image](https://user-images.githubusercontent.com/13124500/158076234-61f186e3-fceb-4354-b95a-a0e3ded78bde.png)

I'm using plotnine 0.8.0 from PyPI with Python 3.10.

Thanks,

-- 
Nicolas

**Comment by has2k1** [comment]
Fixed in #577.
