### ISSUE TITLE
why does mapping come before data?

### ISSUE THREAD

**Issue by wyattleey** [has2k1/plotnine#576]
Thanks for this fantastic package. Plotnine is incredibly helpful for people like me who are familiar with ggplot2.

I was just wondering why in plotnine, mapping comes before data, unlike in R where data comes before mapping.

In Hadley Wickham's paper on the layer of graphics (https://www.tandfonline.com/doi/pdf/10.1198/jcgs.2009.07098), he also introduces data as the first hierarchy (before mapping).

Maintaining the same order will be really helpful for people like me who wish to use their R codes in plotnine, and who tend to omit 'data =' and 'mapping =' in their R codes. Currently, I have to specify mapping and data because the orders are different.

Thank you

**Comment by has2k1** [comment]
In plotnine it really doesn't matter which one comes first, try it! For consistency, I think it makes sense to change the function signature.
