### ISSUE TITLE
Weighted geom_histogram

### ISSUE THREAD

**Issue by mizobe** [has2k1/plotnine#578]
I am estimating the treatment effect among the treated, and one important step is illustrating that I am matching the distributions of treated and control groups.

I rely on a raw geom_histogram and a weighted to show those adjustments.
However, it seems that the weighted version of the histogram is not working correctly.

I am mirroring the same distribution (top and bottom) to show the adjustments.
We can see it in the ggplot version, but not in the plotnine.

Plotnine:

```
_weights
      .withColumn("treatment_p1", F.when(F.col("label")==1, F.col("propensity_score")))
      .withColumn("treatment_p0", F.when(F.col("label")==0, F.col("propensity_score")))
      .ggplot(aes(weight = "w_att"))
      + geom_histogram(aes(x="treatment_p1"), alpha = 0.5, bins = 100, fill = "green")
      + geom_histogram(aes(x="treatment_p0", y='..count..'), alpha = 0.5, bins = 100)
      + geom_histogram(aes(x="treatment_p0", y='-..count..'), alpha = 0.5, bins = 100)
      + geom_histogram(aes(x="treatment_p0", y='-..count..', weight = "w_att"), fill = "blue", alpha = 0.5, bins = 100)
```
![image](https://user-images.githubusercontent.com/353225/162472216-acc468b9-ad64-44df-937f-72170a3edb2c.png)

ggplot on R:

```
[ggplot(weights_rdf) +
  geom_histogram(bins = 100, aes(treatment_p1), alpha = 0.5, fill = "green") +
  geom_histogram(bins = 100, alpha = 0.5, aes(x = treatment_p0, y = ..count..)) + 
  geom_histogram(bins = 100, alpha = 0.5, aes(x = treatment_p0, y = -..count..)) + 
  geom_histogram(bins = 100, aes(x = treatment_p0, weight = w_att, y = -..count..), fill = "blue", alpha = 0.5) + 
  ylab("count") + xlab("p") +
  geom_hline(yintercept = 0, lwd = 0.5)](url)
```

![image](https://user-images.githubusercontent.com/353225/162473576-78fff369-cbc7-4eff-a634-9d569c389d8c.png)

**Comment by joshhartmann11** [comment]
Hi @mizobe!

By including the weight aesthetic in the `ggplot` object as you have in the line below, you are applying the aesthetic to all `geoms`.

```
.ggplot(aes(weight = "w_att"))
```
Remove the aesthetic from the `ggplot` object as below:
```
.ggplot()
```

**Comment by mizobe** [comment]
Thanks for the help.
