### ISSUE TITLE
using a fill argument in aes when using geom_col with scale_y_xxx give wrong tick value  

### ISSUE THREAD

**Issue by ErwanBrisson** [has2k1/plotnine#580]
When using a fill argument in ggplot aes, together with a geom_col provide seems to work correctly. However, when changing the scale (e.g., using scale_y_log), the y axis provides wrong tick values. 
Here is a simple example.
 
`
import pandas as pd
from plotnine import ggplot, scale_y_log10, aes, geom_col

dtframe=pd.DataFrame({'arg1':[0.1,100,1000,10],'cat1':['car','car','bike','bike'],'cat2':['blue','red','blue','red']})
(
    ggplot(dtframe,aes(y='arg1',x='cat1',fill='cat2'))
    + scale_y_log10()
    + geom_col()
)
`

![output](https://user-images.githubusercontent.com/13315611/163413529-4e4a355f-4e81-4859-9a5c-b8a7f8042343.png)

**Comment by has2k1** [comment]
This bug is about position_stack with data modified to be displayed on a non-linear scale. The stacking needs to happen in linear space.
