### ISSUE TITLE
alpha / transparancy in geom_rect

### ISSUE THREAD

**Issue by kraxli** [has2k1/plotnine#587]
I am unfortunately struggling with making the `geom_rect` area transparent (`alpha`). In my plot the area generated is not transparent:

![Screenshot from 2022-05-08 21-43-33](https://user-images.githubusercontent.com/8371948/167313220-2f86b489-7e42-436c-8fa7-95a9a495793f.png)

the example is generated by the code below and with `plotnine 0.8.0` and `python 3.8.10` (and `ipython 7.19.0`):

```python
import pandas as pd
import plotnine as p9
import numpy as np
from matplotlib.dates import date2num
from datetime import datetime as dt

years = 100
data1 = np.random.rand(years).cumsum() # You can use other random functions to generate values with constraints
data2 = np.random.rand(years).cumsum() # You can use other random functions to generate values with constraints
tidx = pd.date_range('1920-01-01', periods=years, freq='A')
data = pd.DataFrame(data=zip(data1, data2), columns=['s1', 's2'], index=tidx)
data.columns.name = 'series'
data.index.name = 'date'
data = data.stack().reset_index()
data.series = data.series.astype('string')
data.rename(columns={0:'values'}, inplace=True)

gg = (p9.ggplot(data=data, mapping=p9.aes(x='date', y='values'))
      + p9.geom_line(p9.aes(color='series'))
      + p9.geom_rect(xmin=date2num(dt.strptime('1950-06-01', '%Y-%m-%d')), xmax=date2num(dt.strptime('2000-06-01', '%Y-%m-%d')),
          ymin=-np.inf, ymax=np.inf,
          alpha=0.1, fill='#595959', color=None)
      )
print(gg)
```
Am I doing sth wrong or is this a bug?

**Comment by has2k1** [comment]
You are doing it wrong, use `annotate`, see https://github.com/has2k1/plotnine/issues/572.

**Comment by kraxli** [comment]
thanks for the hint on `annotate`!
I've read up (as good as possible) and experimented with `geom_rect`. An explicit `dataframe` or `annotate('rect', ...)` are just semi useful for a plot as in the initial issue posted since the `y-limits` are redrawn by `geom_rect` and not based on the original data. The only reasonable way I have found is to use `matplotlib`:

```python
x_min = date2num(dt.strptime('1980-06-01', '%Y-%m-%d'))
x_max = date2num(dt.strptime('2000-06-01', '%Y-%m-%d'))
y_min = -1000
y_max = 1000

gg = (p9.ggplot(data=data, mapping=p9.aes(x='date', y='values'))
      + p9.geom_line(p9.aes(color='series'))
    )

fig, _ = gg.draw(return_ggplot=True)
axes = fig.get_axes()

axs = axes[0]
axs.axvspan(xmin=x_min, xmax=x_max, ymin=y_min, ymax=y_max, alpha=0.1, color='blue')
plt.show()
```
![Screenshot from 2022-05-11 20-11-51](https://user-images.githubusercontent.com/8371948/167917890-89e62962-aca9-4260-bc46-aad0e4eaaa43.png)

Any thoughts I could do this fully and "easy" in `plotnine`?

**Comment by has2k1** [comment]
```python
x_min = dt.strptime('1980-06-01', '%Y-%m-%d')
x_max = dt.strptime('2000-06-01', '%Y-%m-%d')

(
...
+ p9.annotate('rect', xmin=x_min, xmax=x_max, ymin=-np.inf, ymax=np.inf, alpha=0.1, fill='blue',)
)
```

**Comment by kraxli** [comment]
thanks!!! that works :-)
