### ISSUE TITLE
How to apply matplotlib styles/themes?

### ISSUE THREAD

**Issue by CavalloneChen** [has2k1/plotnine#589]
I am aware that there is a theming system inside p9. I wonder if there is a way to apply already existed matplotlib styles directly to p9 plots? For examples themes defined in this repo https://github.com/garrettj403/SciencePlots .

**Comment by has2k1** [comment]
You cannot just apply matplotlib themes, you have to convert them into plotnine themes. And there are some aspects that are not themeable. e.g. point/line colors and styles, those are scale choices.
