### ISSUE TITLE
Proportional Percentage inside a stacked bar

### ISSUE THREAD

**Issue by PEyacher** [has2k1/plotnine#593]
Going from the example here: https://plotnine.readthedocs.io/en/stable/tutorials/miscellaneous-show-counts-on-a-stacked-bar-plot.html

If, instead of the absolute count per "stack", I wanted to print the percentage of that "stack" to its bar, how would I do that?

For example in the first bar, instead of 3 and 8, I wanted to print 27.3% and 72.7% respectively. Is there a way to achieve this?

If I use aes(label=after_stat('prop * 100')) it prints 100 everywhere.
If I use aes(label=after_stat('prop * 100'), group=1) it prints the percentage of the bar in relation to the sum of all bars on top of each bar.
If I use using aes(label=after_stat('prop * 100'), group='factor(am)') it prints the percentage compared to the total of factor(am) from all bars.

What I am looking for is something  like grouping by factor(cyl) and factor(am) simultaniously, but I cannot figure out how this can be done.

Thankful for any help....

**Comment by has2k1** [comment]
The counting is done for each group independently so the proportions are with respect the group as a whole. Grouping by `factor(cyl)` and `factor(am)` simultaneously means that for each `x` position (the `cyl` variable) there are different fill groups depending on the `am` variable.

The right way to do this is pre-compute the proportions you want, and use `geom_col` just for visualisation. Or you can get the get `x` and `count` after the stat computation groupby `x` alone and compute the proportion.

```python
import pandas as pd
from plotnine import *
from plotnine.data import mtcars

def prop_per_x(x, count):
    df = pd.DataFrame({
        'x': x,
        'count': count
    })
    prop = df['count']/df.groupby('x')['count'].transform('sum')
    return prop

(ggplot(mtcars, aes('factor(cyl)', fill='factor(am)'))
 + geom_bar(position='fill')
 + geom_label(
     aes(label=after_stat('prop_per_x(x, count) * 100')),
     stat='count',
     position='fill',
     format_string='{:.1f}%',
     size=9,
 )
)
```
![prop_per_x](https://user-images.githubusercontent.com/780341/169694130-7bf5c188-905e-4853-bed1-bc6aaa804951.png)

**Comment by PEyacher** [comment]
That's great! Thanks a lot. 

Just as a suggestion: Maybe it would be worth to add this code example to the tutorials page ([https://plotnine.readthedocs.io/en/stable/tutorials/miscellaneous-show-counts-on-a-stacked-bar-plot.html](https://plotnine.readthedocs.io/en/stable/tutorials/miscellaneous-show-counts-on-a-stacked-bar-plot.html))

**Comment by has2k1** [comment]
> That's great! Thanks a lot.
> 
> Just as a suggestion: Maybe it would be worth to add this code example to the tutorials page (https://plotnine.readthedocs.io/en/stable/tutorials/miscellaneous-show-counts-on-a-stacked-bar-plot.html)

You are right, and I was onto that, though [this](https://plotnine.readthedocs.io/en/stable/tutorials/miscellaneous-show-counts-and-percentages-for-bar-plots.html) is the place for it.
