### ISSUE TITLE
axis labels in mathtext

### ISSUE THREAD

**Issue by litp** [has2k1/plotnine#594]
Hi, I use `geom_line` and `scale_x_log10` to plot my data in log10 along xaxis, the labels are in scientific notation shown like "1e5", however, I would like the label to be shown as $10^5$. 

In matploblib I can use `rcParams["axes.formatter.use_mathtext"]=True` to achieve that. I tried `theme_matplotlib` with  `theme_matplotlib({'axes.formatter.use_mathtext':True})` but it did not work. Is there a way to do that in plotnine?

**Comment by has2k1** [comment]
You cannot use the rcParams to format the axes. Matplotlib, renders as TeX any text you wrap in `$$`. The solution is to create a labelling function that does that.

```python
from plotnine import *
import pandas as pd
import numpy as np

n = 9
df = pd.DataFrame({
    'y': np.arange(n),
    'x': 10 ** np.arange(n)
})

def label_func(breaks):
    powers = [f'{int(np.log10(x))}' for x in breaks]
    return [f'$10^{p}$' for p in powers]

(ggplot(df, aes('x', 'y'))
 + geom_point()
 + scale_x_log10(labels=label_func)
)
```

Maybe this can be added as an option to [mizani.formatters.log_format](https://mizani.readthedocs.io/en/stable/formatters.html#mizani.formatters.log_format)!
Then the solution would be

```python
from mizani.formatters import log_format
 
( 
  ...
  + scale_x_log10(labels=log_format(mathtex=True))
)

**Comment by litp** [comment]
Got it, many thanks.

**Comment by litp** [comment]
Got it, many thanks.

**Comment by has2k1** [comment]
Done in https://github.com/has2k1/mizani/commit/b1ffd50c47b6addc366e76f808e1077753d29fab.
