### ISSUE TITLE
save background

### ISSUE THREAD

**Issue by wangjiawen2013** [has2k1/plotnine#598]
Hi,

The following code save the transparent background.
p = ggplot(res,aes(x='date',y='Price',fill='Company'))+geom_tile(aes(width=0.95,height=0.95))
p.save("market.pdf")

How to set the backgound in white color ?

**Comment by TyberiusPrime** [comment]
an example
```
import plotnine as p9
import plotnine.data
p= p9.ggplot(p9.data.mtcars)
p += p9.geom_point(p9.aes(x='hp',y='mpg'))
p += p9.theme(plot_background=p9.element_rect(fill='green'), 
              panel_background=p9.element_rect(fill='purple'), 
             )
p
```
