### ISSUE TITLE
Ordering facet sub plots

### ISSUE THREAD

**Issue by fabioannovazzi** [has2k1/plotnine#60]
Is it possible to order plots by some arbitrary order? Now the sub plots are ordered alphabetically. I do not know R but I understand that in ggplot2 you can solve the problem by ordering "levels" that correspond to pandas categoricals.

Thanks and amazing package!

**Comment by has2k1** [comment]
Use an ordered categorical.

**Comment by fabioannovazzi** [comment]
works. Thanks and sorry for the stupid question.
