### ISSUE TITLE
stat_bin2d cuts values

### ISSUE THREAD

**Issue by Hoeze** [has2k1/plotnine#604]
Hi, I'd like to create a 2d bin plot of this dataset:
![grafik](https://user-images.githubusercontent.com/1200058/177963106-2bb0c133-725c-4e9e-8951-6df75efb4a3b.png)

But as soon as I try to plot it:
```python
plot = (
    pn.ggplot(df, pn.aes(x="score", y="residuals"))
    + pn.stat_bin_2d(binwidth=0.1)
)
plot
```
I just see this output:
![grafik](https://user-images.githubusercontent.com/1200058/177963459-a7a786db-288b-45d5-a38e-b32e1e0c27ec.png)

## However, I know that there should be points at `score == 0`:
```python
plot = (
    pn.ggplot(df, pn.aes(x="score", y="residuals"))
    + pn.geom_point()
)
plot
```
![grafik](https://user-images.githubusercontent.com/1200058/177963484-c616a34a-c0e9-496f-ad0e-5b3ba2b44a88.png)

What is the issue here?

**Comment by Hoeze** [comment]
Here is the dataset:
[test.csv.gz](https://github.com/has2k1/plotnine/files/9070968/test.csv.gz)

**Comment by Hoeze** [comment]
Hi @has2k1, is there something we can do about?
This is a really critical bug as it creates misleading results.

**Comment by has2k1** [comment]
Minimal Reprex

```python
import pandas as pd
import numpy as np
from plotnine import *

n = 100
np.random.seed(123)
df = pd.DataFrame({
    'x': np.random.randint(0, 2, n),  # Issue is 
    'y': np.random.randn(n)
})

(ggplot(df, aes('x', 'y'))
 + stat_bin_2d(binwidth=0.1)
)
```

![stat_bin_2d](https://user-images.githubusercontent.com/780341/178735483-3620693d-e224-4a24-9848-46ec66a60c0f.png)

**Comment by Hoeze** [comment]
@has2k1 I'm sorry for bothering you, but is there any solution to this issue yet?

**Comment by has2k1** [comment]
I have a solution, I just wasn't satisfied with it. I will give it another look before the next couple of days and just publish it regardless.

**Comment by Hoeze** [comment]
@has2k1 Thanks for fixing this bug.
Would you mind also releasing a new plotnine version having the bug fix?
