### ISSUE TITLE
Is there a similar method in plotnine to ggplot_add (https://ggplot2.tidyverse.org/reference/ggplot_add.html) in ggplot.

### ISSUE THREAD

**Issue by CaoTianze** [has2k1/plotnine#609]
Hi has2k1:   
I would like to extend your wonderful package to support some domain specific charts. I searched the source code using regular expression matching, but I didn't seem to find any corresponding method support to add custom objects to ggplot. Is there a similar function implementation in your package？

**Comment by has2k1** [comment]
As I see it `ggplot_add` is not necessary, python has `object.__radd__` which one object type can implement to "add" itself to an object of another type. That is what is used internally too!

Do have an example of what you want to do?

**Comment by CaoTianze** [comment]
Thanks for your reply and tips. After I read the source code of ggplot.py, I know how to solve my needs.
