### ISSUE TITLE
qplot: Axis labels can be extracted from pandas.Series names

### ISSUE THREAD

**Issue by mhsekhavat** [has2k1/plotnine#61]
In the command `qplot(x=trips.grut_length, y=trips.erut_length)`, `trips.grut_length` and `trips.erut_length` are instanceof `pandas.Series` and have name. But qplot seems to show their `str()` as axis label instead.
![image](https://user-images.githubusercontent.com/767425/31017518-a4040926-a535-11e7-8c2b-27ae073266fc.png)

**Comment by has2k1** [comment]
Thanks for the suggestion.
