### ISSUE TITLE
Type hints and static type checking with mypy

### ISSUE THREAD

**Issue by dhimmel** [has2k1/plotnine#614]
Have you considered adding type hints to function signatures? This would allow you to remove them from the docs, and if combined with static type checking by mypy could detect places where the current docs are wrong like:

https://github.com/has2k1/plotnine/blob/ad878c21f09de962cfbd166d502072673b4404a9/plotnine/themes/theme_void.py#L16

Also can help catch lot's of types of bugs.

Happy to help set up CI to automate the checks if of interest, but first there'd probably be a good amount of work to get everything typed. Is that of interest?

**Comment by has2k1** [comment]
Yes. Eventually type hints will be added. I am just getting familiar with them else where.

**Comment by Emerentius** [comment]
I'm also interested in having type hints and I would like to help add them. Typing an untyped library is in my opinion best done incrementally so I would start by adding a `mypy.ini` config file with very liberal settings at first and then tighten them down, module by module.

Would you accept PRs adding type hints?

**Comment by TheGBG** [comment]
@Emerentius I think a good staring point would be to have a GitHub pipeline type checking certain files/modules and slowly add more parts of the project

**Comment by Emerentius** [comment]
I've opened #644 to add a mypy run to CI

**Comment by has2k1** [comment]
Type checking is now provided with pyright.
