### ISSUE TITLE
Binning incorrect in geom_bin2d()

### ISSUE THREAD

**Issue by brechtmann** [has2k1/plotnine#616]
Hi there

I found the binning of geom_bin2d() to be incorrect. It always ignores the datapoints at the lower bound. 
Below is an example:

```
import pandas as pd
import plotnine as p9

df = pd.DataFrame({"A": [0,0,0, 0.2, 0.3, 0.5], "B": [0,0,0, 0.2, 0.3, 0.5]})

p9.ggplot(df, p9.aes("A", "B")) + p9.geom_bin2d()
p9.ggplot(df, p9.aes("A", "B")) + p9.geom_point()
```

Below we can see that the points at 0,0 do not show up in the bin2d but in the scatterplot.

![image](https://user-images.githubusercontent.com/37140213/187935655-827940f3-06e8-4350-aeb6-d1d9eb109da5.png)

And below one more example showing that it is not related to zero, but rather the lower bound.
```
df = pd.DataFrame({"A": [2, 4], "B": [3, 2]})
```

![image](https://user-images.githubusercontent.com/37140213/187936506-24423b18-df32-4418-b474-43c13fa18605.png)

**Comment by brechtmann** [comment]
I saw this was adressed in https://github.com/has2k1/plotnine/issues/604

**Comment by has2k1** [comment]
> I saw this was adressed in #604
> 
> Is there already a new release using this?

Not yet. Hopefully next week!
