### ISSUE TITLE
conditioning labelling of geom_text in facet_wrap

### ISSUE THREAD

**Issue by manojbanoth** [has2k1/plotnine#618]
I would like to label some of the data points to the right and others to the left based on the condition in facet_wrap.
if "Average Engagement">=0.8(max("Average Engagement"):
geom_text(mapping=aes("Leader","Average Engagement",label="Average Engagement"), data=df,size=6, ha='left')
Else:
geom_text(mapping=aes("Leader","Average Engagement",label="Average Engagement"), data=df,size=6, ha='right')

Note: There are total 4 groups
Some of the data points are cropping for that, need to write some conditions so that the data point shifts to the right.
And I also tried nudge_x and other options.
But in ggplot(R) we can write with ifelse statement. 

![example](https://user-images.githubusercontent.com/60409337/190179711-0846700b-acf6-4719-9db5-5aee5d6e1353.jpg)

**Comment by has2k1** [comment]
`ha` is an aesthetic, so you can map an expression to it. e.g.


```python
def ha_func(s):
    return ['left' if value < 0.8 else 'right' for value in s]

aes(..., ha=after_scale('ha_func(y)')
```
