### ISSUE TITLE
Is there an alternative to the 'width' argument for boxplots?

### ISSUE THREAD

**Issue by HenrikEckermann** [has2k1/plotnine#62]
I want to make boxplot integrated in a violinplot.

In R, this can be achieved with code like this:

    ggplot(df, aes(x=series,y=value)) +
      geom_violin() +
      geom_boxplot(width=0.2)

In Python with plotnine I miss the _width_ argument and therefore the boxplots cannot be made smaller.  I looked into the documentary of plotnine but did not find it. Does anybody know if there is a different way to make this with plotnine?

Thanks for any suggestion!

**Comment by has2k1** [comment]
It is a bug, the width parameter is being mishandled.

**Comment by HenrikEckermann** [comment]
Hi has2k1,

ok, thanks for pointing that out. It is not a very big issue for me. But of course it would be nice if this would work. Do you think that this will be fixed.

Plotnine is super nice. Thank you for that!

**Comment by has2k1** [comment]
Yes it will be fixed. Here is a quick hack for you

```python
class mystat_boxplot(stat_boxplot):
    def setup_params(self, data):
        self.params['width'] = 0.2
        return self.params
  
(ggplot(df, aes(x='series',y='value')) +
  geom_violin() +
  mystat_boxplot()
)
```

**Comment by HenrikEckermann** [comment]
Hi Hassan,

I have quick question. I try to make a histogram + a normal distribution that uses the mean and sd of the data I make the histogram with.

In R this is this:

ggplot(data, aes(x = residuals.standard)) +
  geom_histogram(aes(y = ..density..)) +
  stat_function(fun = dnorm, args = list(mean = mean(data$residuals.standard), sd = sd(data$residuals.standard)))


I read the documentation but I couldn’t figure it out. I can get the histogram but not the normal curve.

Can you give me a hint or a link?

Henrik

**Comment by has2k1** [comment]
You want something like this

```python
import scipy.stats as st

...
+ stat_function(fun=st.norm.pdf, args=dict(loc=data.residuals.mean(), scale=data.residuals.std())
```
Checkout the `scipy.stats` documentation.

**Comment by HenrikEckermann** [comment]
Exactly, thanks.
