### ISSUE TITLE
Using adjust_text with color aesthetic produces strange result

### ISSUE THREAD

**Issue by sixersfanhal** [has2k1/plotnine#624]
Using `plotnine==0.8.0`, when I run
```
from plotnine import *
from plotnine.data import mtcars

(ggplot(mtcars.head(15), aes(x='wt', y='mpg'))
    + geom_point()
    + geom_text(aes(label='name'), adjust_text={'arrowprops': {'arrowstyle': '-'}}))
```
I get the following, which looks good
![plotnine_test_good](https://user-images.githubusercontent.com/97630895/192876159-ca285958-a891-4fa7-b8e3-23e55f58acee.png)

But if I add a color aesthetic I get something odd:
```
(ggplot(mtcars.head(15), aes(x='wt', y='mpg', color='factor(gear)'))
    + geom_point()
    + geom_text(aes(label='name'), adjust_text={'arrowprops': {'arrowstyle': '-'}}))
```
![plotnine_test_bad](https://user-images.githubusercontent.com/97630895/192876618-6c68d57f-b0a0-4e65-b3e6-296e7ce665c3.png)

Any ideas? Thank you so much for this package, it's been extremely helpful.

**Comment by has2k1** [comment]
Working with `adjust_text` was made a little more robust in v0.9.0. This behaviour does not show up!

**Comment by sixersfanhal** [comment]
Ahh awesome thank you!
