### ISSUE TITLE
version '0.0.0'

### ISSUE THREAD

**Issue by ju-cheng** [has2k1/plotnine#626]
When I installed the package version=0.9.0 and version=0.10.1,  regardless whether I installed by conda or pip, when I imported the package and checked the version, it always showed '0.0.0'

**Comment by has2k1** [comment]
I have reproduced this only for a conda install! pypi install behaves as expected!

**Comment by ju-cheng** [comment]
@has2k1 You are right! The pip install worked! 0.4.7!

**Comment by tabedzki** [comment]
Should we close this?

**Comment by Hoeze** [comment]
I fixed this issue in conda-forge, so can be closed.
