### ISSUE TITLE
Increase line spacing in multiline titles/labels

### ISSUE THREAD

**Issue by Hoeze** [has2k1/plotnine#630]
Hi @has2k1, would it be possible to increase the default linespacing for all labels?
Currently, these are very hard to read:
![grafik](https://user-images.githubusercontent.com/1200058/195213615-79d13bbb-7215-4e9a-b792-0d602a1ee8d9.png)

**Comment by has2k1** [comment]
You can increase the linespacing with `+ theme(title=element_text(linespacing=1.5))`
