### ISSUE TITLE
unexpected transparancy (alpha parameter) behavior

### ISSUE THREAD

**Issue by kraxli** [has2k1/plotnine#632]
Thanks for all the great work also with the most recent update delivered with v0.9!

 Aiming for some transparent color of areas I experience that only the front area is visible without any visual access to the area in the back. E.g. the following code 

````python
hist = p9.ggplot(data=my_data, mapping=p9.aes(x='my_x', fill="fill_dimension"))
hist = hist + p9.geom_histogram(bins=100, alpha=0.5)
````

produces

![image](https://user-images.githubusercontent.com/8371948/195648113-79936f71-438b-4a24-95b4-27de9e145967.png)

--> I don't see the "red" area in the red box at all

I would expect something similar to what `seaborn` or also `matlab` plots do:

![image](https://user-images.githubusercontent.com/8371948/195648599-0aec57be-1a14-46de-86a4-5d26600e1308.png)

where I see through the blue in the red box and get some glimpse of the orange left tail of the orange distribuion

**Comment by has2k1** [comment]
You can split the data into two layers and you will get the overlapping effect.

```python
hist = p9.ggplot(data=my_data, mapping=p9.aes(x='my_x', fill="fill_dimension"))
hist = (hist
 + p9.geom_histogram(mydata.query('fill_dimension == "A"'), bins=100, alpha=0.5)
 + p9.geom_histogram(mydata.query('fill_dimension == "B"'), bins=100, alpha=0.5)
)
```

Maybe there should be a parameter to control this overlapping behaviour? It cannot be the default as it is less efficient!

**Comment by kraxli** [comment]
many thanks for the workaround!

in ggplot it seems to work directly:

```R
# Density plots with semi-transparent fill
ggplot(dat, aes(x=rating, fill=cond)) + geom_density(alpha=.3)
```
![image](https://user-images.githubusercontent.com/8371948/196877618-51f80097-cffd-45d2-baf0-d30a35d7a1ff.png)

reference: http://www.cookbook-r.com/Graphs/Plotting_distributions_(ggplot2)/

**Comment by has2k1** [comment]
This was never an issue. The plotting used the default position `stack`, so it looked like transparency did not work. The solution is to use `position="identity"`. i.e.

```
hist = hist + p9.geom_histogram(position="identity", bins=100, alpha=0.5)
```
