### ISSUE TITLE
parameter scales='free' does not provide independent own label on second axis

### ISSUE THREAD

**Issue by kraxli** [has2k1/plotnine#633]
I experience that the parameter `scales='free'` does not behave as I would expect (potentially my expectation is wrong)

```python
 p9.facet_grid('my_y_ grid_dim ~ my_x_ grid_dim', scales='free')
```

does not lead to a second independent scaled axis

![image](https://user-images.githubusercontent.com/8371948/195652617-fbe7472e-384d-4b82-8d9e-ee5ac2bc144f.png)

**Comment by tabedzki** [comment]
Please note that the correct values for facet_grid are 
` ['fixed', 'free', 'free_x', 'free_y']`

This can be found from https://plotnine.readthedocs.io/en/stable/generated/plotnine.facets.facet_grid.html

Using `scales='free_y"` produce your intended behavior

**Comment by has2k1** [comment]
The description in the documentation is not accurate. The was changed to match ggplot2, so the scales only vary along the rows and/or columns and not per individual facet.

**Comment by has2k1** [comment]
Corrected in https://github.com/has2k1/plotnine/commit/4992e3c3e79cc5c9faa7f34d86c7ad8bc80c115a.
