### ISSUE TITLE
the level of borders is messed up

### ISSUE THREAD

**Issue by ZhangliLu** [has2k1/plotnine#638]
![image](https://user-images.githubusercontent.com/94358311/196978648-4c430a4d-08e4-4fce-9a89-5ac998365087.png)

In some themes, the level of borders is messed up. (e.g. theme_light(), theme_bw())

**Comment by has2k1** [comment]
Please post a full image, I cannot tell what I am looking at!

**Comment by ZhangliLu** [comment]
> Please post a full image, I cannot tell what I am looking at!

![image](https://user-images.githubusercontent.com/94358311/196981193-e88caf62-dd93-4b3c-b28e-cd367c109cb5.png)

![image](https://user-images.githubusercontent.com/94358311/196981249-e8826924-9859-478f-b66b-cce2a167184e.png)

I think this is an obscure bug. This doesn't happen when I use the R version of ggplot

**Comment by has2k1** [comment]
This is a matplotlib issue. I will raise it over there.

**Comment by JonathanDobresSonos** [comment]
As a workaround (at least for theme_bw), I have found that setting the grid color to black with a low alpha of around 0.03 makes this bug practically invisible.
