### ISSUE TITLE
Scaling dates 

### ISSUE THREAD

**Issue by RishiSadhir** [has2k1/plotnine#64]
How can achieve this ggplot2 functionality in plotnine?

```
ggplot() +
     geom_line(data=df, aes(x=date, y=value)) +
     scale_x_date(date_breaks = "1 week")
```

Right now, my x-axis defaults to hundreds of smashed together dates which is completely unreadable.

Thanks!

**Comment by has2k1** [comment]
Do the same thing in plotnine.

**Comment by RishiSadhir** [comment]
The code above gives me the following error message:

```
UserWarning: scale_x_datetime could not recognise parameter `date_breaks`
  warn(msg.format(self.__class__.__name__, k))
```

You can recreate it fully like so:

```
import pandas as pd
from plotnine import *

df = pd.DataFrame(pd.np.random.randn(6,4),columns=list('ABCD'))
df["dates"] = pd.date_range('20130101',periods=6)

ggplot(df, aes("dates", "A")) + geom_point() + scale_x_date(date_breaks = "1 week")
```

**Comment by has2k1** [comment]
Sorry, I did not look closely, the ggplot2 API changed!!

```python
from mizani.breaks import date_breaks

scale_x_date(breaks=date_breaks("1 week"))
```

See: http://plotnine.readthedocs.io/en/dev/tutorials/miscellaneous-manipulating-date-breaks-and-date-labels.html
