### ISSUE TITLE
data is transformed twice when using scale_y_log10 and nonstandard geom/stat combo

### ISSUE THREAD

**Issue by ilia-kats** [has2k1/plotnine#640]
I have the following code:
```
ggplot(df,
        aes("sample", "weighted_distance")) +
        scale_y_log10() +
        geom_crossbar(aes(ymin=after_stat("lower"), y=stage(start="weighted_distance", after_stat="middle"), ymax=after_stat("upper")), stat="boxplot", color="white", fill="white")
```
which prints an empty plot.

Poking around in ipdb, it turns out that this is because [the calculated statistics are log10-transformed](https://github.com/has2k1/plotnine/blob/main/plotnine/layer.py#L353), even though they were computed on already log10-transformed data and are therefore negative. The second transform thus returns NaN and there is nothing to plot.

I'm not too familiar with plotnine code, but in R ggplot2 stats run on already transformed data, and it looks like it's also the case here, so I'm not sure why this line of code is even necessary.

**Comment by adunmore** [comment]
I've been looking into this issue... I agree with @ilia-kats assessment. It looks like the log transform is applied the second time [here](https://github.com/has2k1/plotnine/blob/2405442dfd59f966ad98a6461ef870ea8e406235/plotnine/layer.py#L303) in `layer.map_statistic`. 

I was curious if I could fix it by setting `stat_boxplot.retransform = False`. That does fix this case, but appears to break other cases (for example, when I swapped `scale_y_log10` for `scale_y_sqrt` in the above example, the sqrt transform simply wasn't appled).

**Comment by has2k1** [comment]
> I was curious if I could fix it by setting `stat_boxplot.retransform = False`. That does fix this case, but appears to break other cases (for example, when I swapped `scale_y_log10` for `scale_y_sqrt`

Yes it is not that simple. I started working on a fix but did not complete it before the last release. It will definitely make the next one.

**Comment by adunmore** [comment]
Interesting. I'm interested in contributing to the fix, could you point me in the right direction to understand what's needed?

**Comment by has2k1** [comment]
@adunmore, thanks for you interest. I have pushed the [branch](https://github.com/has2k1/plotnine/tree/retransform) where I last worked on this. The codebase has changed somewhat but the relevant partial work is the last commit at https://github.com/has2k1/plotnine/commit/faccb89b3721166c52d5a84fa7e95ffd22cad33f. 

I will need to properly reacquaint myself with the issue and where that solution was heading, but I recall I there were some unnecessary retransformations that I was not happy with and wanted to avoid.
