### ISSUE TITLE
How to increase the number of ticks

### ISSUE THREAD

**Issue by Yaoyx** [has2k1/plotnine#641]
I tried to increase the number of ticks in my plot, and I have tried all parameters of scale_x/y_continuous function, but I still cannot figure out a way to do it.

**Comment by has2k1** [comment]
Use a function to calculate the breaks or set the breaks explicitly. 
See [extended_breaks](https://mizani.readthedocs.io/en/stable/breaks.html#mizani.breaks.extended_breaks). It is the default function that computes the breaks and you can use it directly.

```python
scale_x_continuous(breaks=extended_breaks(n=10))
scale_x_continuous(breaks=[1, 2, 3, 4, 5])
```

**Comment by Yaoyx** [comment]
> Use a function to calculate the breaks or set the breaks explicitly. See [extended_breaks](https://mizani.readthedocs.io/en/stable/breaks.html#mizani.breaks.extended_breaks). It is the default function that computes the breaks and you can use it directly.
> 
> ```python
> scale_x_continuous(breaks=extended_breaks(n=10))
> scale_x_continuous(breaks=[1, 2, 3, 4, 5])
> ```

Thank you so much for your help!
