### ISSUE TITLE
Tests fail with ImportError

### ISSUE THREAD

**Issue by penguinpee** [has2k1/plotnine#643]
Running tests in the Fedora 36 build environment with Python 3.10.7, pytest-6.2.5, py-1.11.0, pluggy-1.0.0, test_geom_bar_col_histogram.py and test_geom_bin_2d.py fail with:

```python
ImportError while importing test module '/builddir/build/BUILD/plotnine-0.10.1/tests/test_geom_bar_col_histogram.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/test_geom_bar_col_histogram.py:8: in <module>
    from .conftest import layer_data
E   ImportError: attempted relative import with no known parent package
```
```python
ImportError while importing test module '/builddir/build/BUILD/plotnine-0.10.1/tests/test_geom_bin_2d.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/test_geom_bin_2d.py:6: in <module>
    from .conftest import layer_data
E   ImportError: attempted relative import with no known parent package
```

I tried working around it by providing an empty __init__.py in tests/, but that was intercepted by conftest.py itself:

```python
../../BUILDROOT/python-plotnine-0.10.1-2.fc36.x86_64/usr/lib/python3.10/site-packages/tests/conftest.py:30: in <module>
    raise OSError(
E   OSError: The baseline image directory does not exist. This is most likely because the test data is not installed. You may need to install plotnine from source to get the test data.
```

Running the tests in Fedora 37, which has Python 3.11.0rc2, pytest-7.1.3, pluggy-1.0.0, as is (without empty __init__.py) works fine.

**Comment by has2k1** [comment]
It looks like Fedora did not package the reference images for the tests. It is a reasonable decision since they `x4` the size of the package.

**Comment by penguinpee** [comment]
So, the OSError tells me it's missing the reference images. I used the PyPI tarball in the installation and the `baseline_images` directory is present in the tarball, but it might indeed not be part of the wheel the build system produces. Will check.

However, why does that not lead into trouble when running the tests in Fedora 37 / Rawhide with Python 3.11.0rc2, pytest-7.1.3, pluggy-1.0.0? Conditions are the same. Same source, same build and install steps.

**Comment by penguinpee** [comment]
> but it might indeed not be part of the wheel the build system produces. Will check.

It wasn't. I created symlinks in the tests directory for `baseline_images` and `images` and have come full circle:

```python
E   ImportError: attempted relative import with no known parent package
```

I think I'll just disable the two tests in F36 for now.
