### ISSUE TITLE
Usage of format_string of geom_text is undocumented

### ISSUE THREAD

**Issue by davidaknowles** [has2k1/plotnine#646]
The documentation
`format_string[str](https://docs.python.org/3/library/stdtypes.html#str) (default: [None](https://docs.python.org/3/library/constants.html#None))
If not None, then the text if formatted with this string using [str.format()](https://docs.python.org/3/library/stdtypes.html#str.format)`
None of format_string="%.2f", "{.2f}" etc seem to work. A working example would likely clarify how this is meant to be used.

**Comment by has2k1** [comment]
`"{.2f}"` -> `"{:2f}"`

**Comment by davidaknowles** [comment]
Thanks! It's a great project btw :) making me miss R a lot less.
