### ISSUE TITLE
geom_ribbon and geom_smooth problems

### ISSUE THREAD

**Issue by laurivil** [has2k1/plotnine#654]
I've previously used geom_ribbon() and geom_smooth() without problems, but now I cannot make my old scripts work. I keep bumping to this:

   2357 
   2358     """
-> 2360     return masked_where(~(np.isfinite(getdata(a))), a, copy=copy)

TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

All data types are correct and no inf or na values are present.

**Comment by LoicGrobol** [comment]
This seems to be [a regression in numpy 1.24.0](https://github.com/numpy/numpy/issues/22842). While waiting for a fix, downgrading to 1.23.x should fix the issue.

**Comment by laurivil** [comment]
Thanks, solved it!

**Comment by LoicGrobol** [comment]
<https://github.com/numpy/numpy/pull/22858> should have fixed it, so this should not be an issue for [numpy 1.24.1](https://github.com/numpy/numpy/releases/tag/v1.24.1)

**Comment by alexkyllo** [comment]
I'm experiencing this same error message whenever I attempt to combine more than one geom with a date x axis on a time series plot. For example, I can use any of `geom_point()`, `geom_smooth()`, or `geom_line()` by itself, but when I use any two together, I get the `TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''` error.

**Comment by has2k1** [comment]
> I'm experiencing this same error message whenever I attempt to combine more than one geom with a date x axis on a time series plot. For example, I can use any of `geom_point()`, `geom_smooth()`, or `geom_line()` by itself, but when I use any two together, I get the `TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''` error.
> 
> I have versions:
> 
> numpy==1.24.3 plotnine==0.10.1
> 
> Edit: the problem seems to not actually be with the date column, but rather with my y-variable which was an Int64 type. After casting it to a Float64, the error goes away.

Can you create a separate issue with a minimal reproducible example?

**Comment by alexkyllo** [comment]
> > I'm experiencing this same error message whenever I attempt to combine more than one geom with a date x axis on a time series plot. For example, I can use any of `geom_point()`, `geom_smooth()`, or `geom_line()` by itself, but when I use any two together, I get the `TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''` error.
> > I have versions:
> > numpy==1.24.3 plotnine==0.10.1
> > Edit: the problem seems to not actually be with the date column, but rather with my y-variable which was an Int64 type. After casting it to a Float64, the error goes away.
> 
> Can you create a separate issue with a minimal reproducible example?

Yes, created #683
