### ISSUE TITLE
How To Use Custom Label In Aes?

### ISSUE THREAD

**Issue by YaFeiPeng** [has2k1/plotnine#656]
Hi,
  I have to overwrite the R script using python，so i choose plotnine replacing ggplot2.Here's part of R code:

```r
...
geom_text(data = summary, aes(x = mean.bg + 3 * sd.bg, y = 24, label = sprintf("\nMEAN+3Sigma=%.2f\n", ceiling(mean.bg + 3 * sd.bg)))+
... 
```

`mean.bg` and `sd.bg` are variables in `summary`,the result looks like this:

![2023-01-24-21-01-30-image](https://user-images.githubusercontent.com/115513204/214303336-5f06ab92-b62b-4350-8ec9-5b40f30cb855.png)

but when i follow the code above using plotnine,there seem to be some problems:

![2023-01-24-21-00-48-image](https://user-images.githubusercontent.com/115513204/214303152-c0459714-47c7-4330-99ef-16ccc76aebf4.png)

here's the python code:

```python
geom_text(data=summary, mapping=aes(x="bg_mean + 3 * bg_sd", y="24",
                                       label='f"MEAN-3Sigma={ceil(bg_mean + 3 * bg_sd)}"'), color="black", )
```

i use the `f-string` replacing `sprintf` method in R.

So how can i display the same result?Thanks.

**Comment by b-lac** [comment]
I think you should use the `format_string` argument of [`geom_text`](https://plotnine.readthedocs.io/en/stable/generated/plotnine.geoms.geom_text.html#plotnine.geoms.geom_text)
Try something like this:
```python
 geom_text(data=summary,
           mapping=aes(x="bg_mean + 3 * bg_sd", y="24", label = "bg_mean + 3 * bg_sd"),
           format_string="MEAN-3Sigma={:,.2f}"))
```

**Comment by YaFeiPeng** [comment]
@b-lac thanks,it works,but i have another question,sometimes i need to format multiple parameters,like this:

```python
geom_text(data=summary,apping=aes(x="bg_mean", y="24", label='f"MEAN={bg_mean} CV={bg_cv}"')
```

how can i do this?I've tried some ways,for example:

> `label='bg_mean bg_cv'` and `format_string="MEAN={:,.2f} CV={:,.2f}"`

or

> `label='bg_mean,bg_cv'`and`format_string="MEAN={:,.2f} CV={:,.2f}"`

but it throw an error:

```
Could not evaluate the 'label' mapping: 'bg_mean bg_cv' (original error: unexpected EOF while parsing
```

or

```
"The 'label' mapping: 'bg_mean,bg_cv' produced a value of type '<class 'tuple'>',but only single items and lists/arrays can be used. (original error: Length of values (2) does not match length of index (4))"
```

it say only `single items`or `lists/arrays `can use,but i don't quite understand how to use `lists/arrays`,i have tried `label='[bg_mean,bg_cv]'`or `label='(bg_mean,bg_cv)'`,but it doesn't work.

finally,i try a more complicated approach,split one geom_text into two geom_text.but isn't there an easier way?

**Comment by b-lac** [comment]
This should work:

```python
ggplot(summary)+
geom_text(aes(x="bg_mean",
              y="24",
              label="[bg_mean, bg_cv]"),
          format_string="MEAN={0[0]} CV={0[1]}")
```
Also [Format String Syntax](https://docs.python.org/3/library/string.html#formatstrings) documentation can help !

**Comment by YaFeiPeng** [comment]
thanks a lot @b-lac
