### ISSUE TITLE
Transforming the axis with my function

### ISSUE THREAD

**Issue by jonvitale** [has2k1/plotnine#66]
Hello, 

I am trying to do a custom scaling of the x-axis. I see that the scale_x_continuous function accepts a "trans" parameter, which can be a function. Here's my function (pretty simple)

```python
def scale_frets(frets):
     return ([math.log(x + 1, 1.3) for x in frets])
```
It's not clear how I should use this. Should I be calling by a string representation of the name, like:
```python
scale_x_continuous(trans = 'scale_frets', breaks = list(range(0,1)), minor_breaks = list(range(0,22)), limits=(0, 21))
```
Thank you.
(p.s. in case you're wondering, I'm making a graphical representation of a guitar neck. I'm not sure my scaling function is correct, but once I get this function working I'll play around with it until it looks right.)

**Comment by has2k1** [comment]
It is not properly documented. You need use the scaling package [mizani](https://github.com/has2k1) to create a transform object. For that you need  a transform function and an inverse function. Checkout some of the simpler [transforms](https://github.com/has2k1/mizani/blob/7da32cca5af673157038b6414ab60de255ff8770/mizani/transforms.py) like [*sqrt_trans*](https://mizani.readthedocs.io/en/stable/transforms.html#mizani.transforms.sqrt_trans) or [*reverse_trans*](https://mizani.readthedocs.io/en/stable/transforms.html#mizani.transforms.reverse_trans).

```python
from mizani.transforms import trans

# 1.
class my_trans(trans):
    """
    My Transformation
    """
    @staticmethod
    def transform(x):
        return x

    @staticme
    def inverse(x):
        return x
# 2.
# OR you could use the trans_new function to create the trans
# class for you.

def my_transform(x):
    return x

def my_inverse(x):
    return x

my_trans = trans_new('my', my_transform, my_inverse, ...)


scale_x_continuous(trans=my_trans, ...)
```

When you are done, can you post the final class, data and plotting code that shows the guitar neck. It would be great for the documentation. Thanks.

**Comment by jonvitale** [comment]
Thanks, I tentatively have something working. When I put together some runnable code I'll update this space.

**Comment by has2k1** [comment]
I am musically illiterate, so
 
> It shows a sequence through a "c chord" in standard tuning

plucks at untuned neurons in my brain. At least, I appreciate the scale manipulation.

Given that transform uses custom methods, it is clearer to declare a class the usual way. On the python style, you can use numpy, e.g `np.range(0, 10)` instead of `list(range(0, 10))` [1].

Here, I have changed a few things:

```python
import numpy as np
import pandas as pd
from plotnine import *

from mizani.transforms import trans,

# Notes: the 0 fret is an open strum, all other frets are played half-way between fret bars.
# The strings are 1:low E, 2: A, 3: D, 4: G, 5: B, 6: E
c_chord = pd.DataFrame({
    'Fret':   [0, 2.5, 1.5, 0, 0.5, 0],
    'String': [1, 2, 3, 4, 5, 6]
})

# adding the sequence based on the number of notes in the chord
c_chord['Sequence'] = list(range(1, 1+len(c_chord['Fret'])))

# create the standard markings for a Stratocaster
markings = pd.DataFrame({
    'Fret':   [2.5, 4.5, 6.5, 8.5, 11.5, 11.5, 14.5, 16.5, 18.5, 20.5],
    'String': [3.5, 3.5, 3.5, 3.5, 2, 5, 3.5, 3.5, 3.5, 3.5]
})

# create a transformation update the x-axis to resemble the narrowing width of frets on a 25.5 inch Strat
class frets_trans(trans):
    number_of_frets = 23               # Including 0
    domain = (0, number_of_frets-1)
    
    @staticmethod
    def transform(x):
        x = np.asarray(x)
        return 25.5 - (25.5 / (2 ** (x/12)))
    
    @staticmethod
    def inverse(x):
        x = np.asarray(x)
        return 12 * np.log2(25.5/(25.5-x))
    
    @classmethod
    def breaks_(cls, limits):
        return cls.domain
    
    @classmethod
    def minor_breaks(cls, major, limits):
        _major = cls.inverse(major)
        # minor = cls.transform(np.arange(*np.round(_major)))  # previous (potentially bad)
        minor = cls.transform(np.linspace(*_major, cls.number_of_frets))
        return minor


# Plot the chord on top of the transformed scales, add markings.
# Note: To make the frets marks and strings look different I use the minor and major breaks independently.
g = (ggplot(c_chord, aes('Fret', 'String')) +
    geom_path(aes(color='Sequence'), size=3) +
    geom_point(aes(color='Sequence'), fill='#FFFFFF', size=3.5) +
    geom_point(data=markings, fill='#000000', size=5) +
    scale_x_continuous(trans=frets_trans) +
    scale_y_continuous(breaks=list(range(0, 7)), minor_breaks=[]) +
    guides(color=False) +
    theme(figure_size=(10, 1.43),
          panel_background = element_rect(fill='#FFDDCC'),
          panel_grid_major = element_line(color='#AA9944', size=2.2),
          panel_grid_minor = element_line(color='#998888', size=1)
    )
)
g
```

The key difference is how the minor breaks are computed. When you `round`, you hope that you get there right whole numbers. This *may* not work when the numbers (number of frets aka domain) change, due to off by one errors.

It is easy to overlook, but this scale transformation demonstrates a use case where the breaks are fixed (I guess it is invaluable for demonstration graphics) I will include a little more explanation in the notebook for the documentation.

[1] I found a bug that prevents `scale_y_continuous(breaks=np.arange(0, 7), ...)` from working.

**Comment by has2k1** [comment]
Example added [at](https://github.com/has2k1/plotnine-examples/blob/4d3fe764913f59c0d0e5ac8ab94240adffc0c6ed/plotnine_examples/examples/scale_x_continuous.ipynb). It will show up in the gallery for the next release.
