### ISSUE TITLE
How to have "free_fill" in facet_grid?

### ISSUE THREAD

**Issue by Hoeze** [has2k1/plotnine#660]
Hi, I have a heatmap which is `facet_grid` with `"bound ~ trait"`:
![grafik](https://user-images.githubusercontent.com/1200058/214908671-c3a0ce7c-f79f-48f5-b69b-d13ff130d272.png)
The problem is that the fill values in the rows are in a different scale but I still want to see the absolute numbers. Is it possible to have in each row a different fill color scale?

**Comment by has2k1** [comment]
> The problem is that the fill values in the rows are in a different scale but I still want to see the absolute numbers. Is it possible to have in each row a different fill color scale?

I am lost. Can you clarify.

**Comment by Hoeze** [comment]
@has2k1 My aim would be to have a different legend (with a different scale) in every row of the grid like here:
![grafik](https://user-images.githubusercontent.com/1200058/214911240-038a7182-08e6-49e4-8724-1d5cb9407656.png)

**Comment by has2k1** [comment]
Thanks, I get it. It is not possible.
