### ISSUE TITLE
how to support image?

### ISSUE THREAD

**Issue by tianliuxin** [has2k1/plotnine#661]
this is very useful,but this don't support image

I try to define geom to support image,but fail,matplotlib may be hard for me

this will support image  in the future?

or please give me some code  about this

very thanks~

**Comment by has2k1** [comment]
There is [watermark](https://plotnine.readthedocs.io/en/stable/generated/plotnine.watermark.watermark.html#plotnine.watermark.watermark) which you can use to add image layers. i.e. `+ watermark("file.jpg", 0, 0)`
