### ISSUE TITLE
scale_colour_manual html hex colour transparency doesn't appear in legend

### ISSUE THREAD

**Issue by harrig12** [has2k1/plotnine#665]
I'd like to set point transparency using html hex code

I don't want a separate alpha legend, just the colour one to be transparent. Although this works for the points themselves, the transparency doesn't seem to propagate to the legend when using `set_colour_manual`

In R, I might use `override.aes` but I haven't found the equivalent in plotnine

Any suggestions?

```
import numpy as np
import pandas as pd
from plotnine import * 

data = np.random.rand(20, 4)
df = pd.DataFrame(data)
df.columns = ['x', 'facet 1', 'facet 2', 'facet 3']
df['label'] = ['label 1']*10 + ['label 2']*5 + ['label 3']*5
df = pd.melt(df, id_vars=['x', 'label'])

g=(ggplot(df)
+ aes(x='x', y='value', color='label')
+ geom_point(size=10)
+ theme_seaborn('white')
+ scale_colour_manual({'label 1': 'orange', 'label 2': 'red', 'label 3': '#0000FF4D'})
)
```
![image](https://user-images.githubusercontent.com/23587234/219815575-6239c5c4-2b88-4e32-b85b-b3c2fea892e7.png)

**Comment by harrig12** [comment]
appears to also apply to `scale_colour_identity`

```
import numpy as np
import pandas as pd
from plotnine import * 

data = np.random.rand(20, 4)
df = pd.DataFrame(data)
df.columns = ['x', 'facet 1', 'facet 2', 'facet 3']
df['label'] = ['label 1']*10 + ['label 2']*5 + ['label 3']*5
df['colour'] = ['orange']*10 + ['red']*5 + ['#0000FF4D']*5
df = pd.melt(df, id_vars=['x', 'label', 'colour'])

g=(ggplot(df)
+ aes(x='x', y='value', color='colour')
+ geom_point(size = 10)
+ theme_seaborn('white')
+ scale_color_identity(guide='legend')
)

```
![image](https://user-images.githubusercontent.com/23587234/219816451-f658addf-849e-44ff-a54a-e1f1f1155349.png)

**Comment by harrig12** [comment]
I tracked this down! 

in `draw_legend`, `lines.Line2D()` forces the alpha if provided, because it uses [to_rgba](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.colors.to_rgba.html) internally

alpha defaults to 1 for `geom_point`

https://github.com/has2k1/plotnine/blob/main/plotnine/geoms/geom_point.py#L140-L149

Fix is easy enough - alpha should default to `None`. As far as I can tell, this doesn't break anything. 
There are several geoms with default `alpha = 1`. I changed their defaults (except for geom_raster) with  #666

**Comment by has2k1** [comment]
> Fix is easy enough - alpha should default to None.

As plotnine is getting type annotations, it is more coherent to have variables initialised with values of the correct type.

The solution is to merge the alpha into fill/colour using [`plotnine.utils.to_rgba`](https://github.com/has2k1/plotnine/blob/1cee0c7395ce7eacea0eba4e201c71cfc88bfecf/plotnine/utils.py#L538) in the `geom.draw_legend` methods as we do in the `geom.draw_group` methods. [`geom_rect.draw_legend`](https://github.com/has2k1/plotnine/blob/1cee0c7395ce7eacea0eba4e201c71cfc88bfecf/plotnine/geoms/geom_rect.py#L61-L96) has it [right](https://github.com/has2k1/plotnine/blob/1cee0c7395ce7eacea0eba4e201c71cfc88bfecf/plotnine/geoms/geom_rect.py#L80), so the other cases are an oversight.

That means there should be no cases of `alpha=data['alpha']` in the `geom.draw_legend` functions.

**Comment by harrig12** [comment]
👍 makes sense! thanks for the quick response
