### ISSUE TITLE
importing fonts by linking path to operating system directory

### ISSUE THREAD

**Issue by IGGold** [has2k1/plotnine#67]
Hi Hassan and crew, 

**@has2k1**

Trying to work out how to load fonts by linking path to operating system directory e.g. font_path = C:\windows

not sure if this feature has been added to plotnine api list yet? 

couldn't find anything in documentation, just a referral to see matplotlib.font_manager under the seaborn theme. and creating themes such as:

```
plotnine.theme.example(base_size = 8.5, base_family = "Tahoma")  etc...
```

looking for plotnine method for the examples below

matplotlib example for .tff file. 
[https://matplotlib.org/gallery/api/font_file_sgskip.html](url)

```
import matplotlib.font_manager as fm
import matplotlib.pyplot as plt

if sys.platform == 'win32':
        fpath = 'C:\\Windows\\Fonts\\Tahoma.ttf'
elif sys.platform.startswith('linux'):
        basedir = '/usr/share/fonts/truetype'
        fonts = ['freefont/FreeSansBoldOblique.ttf',
                        'ttf-liberation/LiberationSans-BoldItalic.ttf',
                        'msttcorefonts/Comic_Sans_MS.ttf']
        for fpath in fonts:
           if os.path.exists(os.path.join(basedir, fpath)):
                    break
```

R Example 
[https://github.com/yixuan/showtext](url)
[https://github.com/yixuan/sysfonts](url)

```
font.add(family = "<family_name>", regular = "/path/to/font/file")
e.g
font.add(family = "<Tahoma>", regular = "C:\Windows\Fonts"
```

**Comment by has2k1** [comment]
Dealing with fonts is all Matplotlib. Just pass the `fontproperties` in `element_text`. Something like this should work.

```python
import matplotlib.font_manager as fm
fpath = '/path/to/your/font.ttf'
prop = fm.FontProperties(fname=fpath)

(ggplot(data)
 ...
 + theme(text=element_text(fontproperties=prop))
)
```
