### ISSUE TITLE
facetting plot with multiple lines in abline does not work

### ISSUE THREAD

**Issue by JenniferHem** [has2k1/plotnine#670]
I tried to generate a plot which adds multiple lines via geom_abline(), however then trying to facet the plot leads to missing ablines in other facets or a crash due to aesthetics: 

```
from plotnine import *
from plotnine.data import *

(
    ggplot(mpg, aes(x='displ', y='hwy'))
    + geom_point()
    + geom_abline(aes(intercept=[45,30],slope=[-5, -5], color = ["blue","black"]))
    + facet_grid('drv ~ .')
    + labs(x='displacement', y='horsepower')
)

```
Leads to: PlotnineError: 'Aesthetics must either be length one, or the same length as the data'

```
from plotnine import *
from plotnine.data import *

(
    ggplot()
    + geom_point(mpg, aes(x='displ', y='hwy'))
    + geom_abline(aes(intercept=[45,30],slope=[-5, -5], color = ["blue","black"]))
    + facet_grid('drv ~ .')
    + labs(x='displacement', y='horsepower')
)

```
Leads to:
![image](https://user-images.githubusercontent.com/68546404/222104459-334e8dc9-8b1d-4261-a4dc-b1f441c39813.png)

where only the first facet contains the abline. 

Expectation: faceting with multi-line should plot the abline in all facets.

**Comment by has2k1** [comment]
The right way to do this is to set the aesthetics outside `aes()`, but then two bugs prevent that from working too.

```python
from plotnine import *
from plotnine.data import *

(
    ggplot()
    + geom_point(mpg, aes(x='displ', y='hwy'))
    + geom_abline(intercept=[45,30],slope=[-5, -5], color = ["blue","black"])
    # Better to use annotate so that the intent is clear
    # + annotate("abline", intercept=[45,30],slope=[-5, -5], color = ["blue","black"])
    + facet_grid('drv ~ .')
    + labs(x='displacement', y='horsepower')
)
```
