### ISSUE TITLE
please fix wrong links in docs

### ISSUE THREAD

**Issue by abubelinha** [has2k1/plotnine#672]
See https://plotnine.readthedocs.io/en/stable/external-resources.html

- The "[Comparing plotnine and ggpy](http://pltn.ca/plotnine-superior-python-ggplot/)" mentioned by @pteehan [in #1](https://github.com/has2k1/plotnine/issues/1#issuecomment-303319007) points to a dead link, but I found this archive.org backup:
  http://web.archive.org/web/20181012022314/http://pltn.ca/plotnine-superior-python-ggplot/

- Same thing happens to this "[Introduction to Plotnine](http://www.mbel.io/2019/08/06/introduction-to-plotnine-ggplot-port-in-python/)" (domain for sale, backup available in archive.org):
  https://web.archive.org/web/20200926231003/http://www.mbel.io/2019/08/06/introduction-to-plotnine-ggplot-port-in-python/

Thanks
@abubelinha

**Comment by abubelinha** [comment]
Oh, you finally preferred to delete them.

Just curious: Don't you find it appropriate linking to archived webpages?

**Comment by has2k1** [comment]
Yes

> Oh, they seemed very useful to me, but you finally preferred to delete them.
> 
> Just curious: Don't you find it appropriate linking to archived webpages?

Yes, my interpretation was they were dead and did not feel like they merited a link into archives. As you found them helpful enough, I was wrong!

I also plan to put up a wide range of examples going forward. Maybe we can have them back until we actually have more examples.

**Comment by abubelinha** [comment]
> I also plan to put up a wide range of examples going forward. Maybe we can have them back until we actually have more examples.

Great!
I would also love to see some examples of using this library in standalone console scripts (I have no idea about jupyter).
i.e. #307 or #274
