### ISSUE TITLE
Request: faster loading of plotnine

### ISSUE THREAD

**Issue by wch** [has2k1/plotnine#676]
I’d like to make use of plotnine for examples for shiny, but I think the load time is too slow for the examples served by shinylive. 

plotnine loads fast enough for use in shiny applications deployed on a server running python, but when running on shinylive in the browser (which is what we do for the documentation and live examples), the load time is very long. On my M1 Mac, running `import plotnine` takes about 10.5 seconds in shinylive (it only takes about 1.5 seconds in normal Python session). I think that needs to be reduced by 2x at the very minimum for it to be usable for examples. (And ideally even more.)

I did some investigation into why it takes so long, and I believe it is because plotnine loads all of its submodules by default, and they load various submodules of other packages (like matplotlib), which can result in a lot of computation. I believe it’s possible to greatly reduce the amount of computation by importing submodules only when necessary.

For example, if you open the pyodide web console and run `import matplotlib`, it takes about 1 second. Then if you run `import matplotlib.pyplot as plt`, that takes another 1 second. In the plotnine code, there are many submodules that are loaded as soon as you run import plotnine. I recorded it in a gist here: https://gist.github.com/wch/369ac5da6055ea482c76694a7472f386
If the load time for plotnine is reduced by 2x (or even more) then we can start using it for shiny examples, which will be good for shiny and good for plotnine.

For example, in [stat/smoothers.py](https://github.com/has2k1/plotnine/blob/1cee0c7395ce7eacea0eba4e201c71cfc88bfecf/plotnine/stats/smoothers.py#L8
), it calls `import statsmodels.formula.api as smf` at the top, but `smf` is only actually used inside of the functions, so for many use cases, it is loaded unnecessarily.

**Comment by has2k1** [comment]
Loading in v0.12.0 has been reduced to quarter of previous loading time. `import plotnine` no longer loads the diverse collection of packages that it depends on. With the exception of `pandas` and `numpy` all other packages are loaded when they are first required.

Though, on a web platform e.g. shinylive(pyodide) doing a cold `import plotnine` downloads and installs  plotnine dependencies (pandas, matplotlib, scipy, statsmodels, ...), before installing plotnine. As it may seem needlessly long.

**Comment by bugzpodder** [comment]
How did you guys get plotnine v0.12 to load in pyodide? I only find v0.10 to be supported.
