### ISSUE TITLE
how to access to the data used for stat_smooth()?

### ISSUE THREAD

**Issue by ahnchive** [has2k1/plotnine#681]
I'd like to know the exact values for drawing a regression line used by stat_smooth(). In the original ggplot, this seems to be done by either using the separate method called "ggplot_build()" or directly accessing the data attribute (e.g., g.data). I assume this hasn't been implemented in the plotnine yet but is there any easy workaround to access the data?

Any input will be appreciated!

**Comment by b-lac** [comment]
You can access the predicted values of the smooth model, but I don't think you can easily access the coefficients used to compute the model.

```python
import plotnine as p9
import pandas as pd

df = pd.DataFrame({'x':[1,2,3,4,8,6,9,7], 'y':[1,9,5,4,7,4,4,1]})
g = p9.ggplot(df) + p9.geom_point(p9.aes(x="x", y="y")) + p9.geom_point(p9.aes(x="x", y="y"), stat='smooth', color='red', method='lm')
```

![image](https://user-images.githubusercontent.com/114392778/234622681-59d56886-16fa-44da-9ed5-c179006dfbce.png)

**Comment by has2k1** [comment]
Modelling parameters are outside the scope of the project as we strike a balance between exploratory visualisation and straight out modelling. For each smoothing method, you can [look up](https://plotnine.readthedocs.io/en/stable/generated/plotnine.stats.stat_smooth.html#plotnine.stats.stat_smooth) the package & routine and do the modelling explicitly.

If you simply want access to the data, you can use the "private" `_build` method. e.g.

```python
g = ggplot(...) + ...

g._build()

# Data for each layer
g.layers[0].data
g.layers[1].data 
```

**Comment by ahnchive** [comment]
Thanks so much! This is what I was looking for.
