### ISSUE TITLE
geom_line() with color mapping for discrete ordered variable + continuous cmap

### ISSUE THREAD

**Issue by lukaszkadlubowski** [has2k1/plotnine#682]
Hello,

First of all, thank you for working on this very interesting project!

I am struggling with creating a figure consisting of several lines with different colors. Family of plots is for the variable which is not indeed categorical, I would rather call it a "discrete ordered variable". I want to have some nice colorbar in the legend, but I have not been able to make this work and have not found any examples. Below is the exemplary code and resulting figures:

# Example

```python
# %%
import numpy as np
import pandas as pd
from plotnine import *

# %%
NO_LINES = 24
X_RANGE = 64
df = pd.DataFrame(
    {
        "c": np.arange(NO_LINES).repeat(X_RANGE),
        "x": np.tile(np.arange(X_RANGE), NO_LINES),
        "y": np.random.rand(X_RANGE*NO_LINES),
    }
)
df["y"] = 0.2*df["x"]**1.2 + 2*df["c"] + df["y"]

# CASE 1. Problem demonstration
gg1 = (
    ggplot(df)
    + aes(x="x", y="y", color="c")
    + geom_line()
)
print(gg1)

# CASE 2. Change "c" column to categorical
df["c"] = df["c"].astype("category")

gg2 = (
    ggplot(df)
    + aes(x="x", y="y", color="c")
    + geom_line()
)
print(gg2)

# CASE 3. Try using sequential palette
gg3 = (
    ggplot(df)
    + aes(x="x", y="y", color="c")
    + geom_line()
    + scale_color_brewer(type="seq", palette="YlOrBr")
)
print(gg3)
```

# Results

## CASE 1

<img src="https://user-images.githubusercontent.com/65432554/235584233-cc5953a6-7d90-4a89-9ec8-84ed5ff227c7.png" width=400>

## CASE 2

<img src="https://user-images.githubusercontent.com/65432554/235584249-dc1caec1-50de-4cba-943e-8c19aa14a34a.png" width=400>

## CASE 3

<img src="https://user-images.githubusercontent.com/65432554/235584270-b1938963-d8a1-4907-a844-e7409e1c33c3.png" width=400>

# Summary and question

So it seems for me that the color-mapped variable must be categorical to avoid the behavior in Case 1.  In case 2, it somehow works, but I would like to have continuous, not sequential palette for the "c" variable. I am not able to use `scale_color_gradientn` or `scale_color_distiller`, it results in `TypeError: Discrete value supplied to continuous scale`. I can use `scale_color_brewer` (result in case 3), but it does not work well in this case.

Expected behavior:
- colorbar as in case 1
- but plot as in case 3
   - with color scale spanning whole range of possible `c` values
- without being forced to make `c` column categorical

Can it be done in the current version?

Regards,
Lukasz

**Comment by b-lac** [comment]
Is it what you want to obtain?

![index](https://user-images.githubusercontent.com/114392778/236140955-1830012f-0215-4f9d-a58a-acd6db505bb4.png)

```python
gg1 = (
    ggplot(df)
    + aes(x="x", y="y", color="c", group="c")
    + geom_line()
)
print(gg1)
```

**Comment by lukaszkadlubowski** [comment]
Exactly what I wanted :) thank you very much for the advice.

However, I am still struggling with more generalized example, where I also use `linetype` aesthetics. The code is as follows:

```python
# %%
import numpy as np
import pandas as pd
import plotnine as p9

# %%
NO_DASHES = 2
NO_LINES = 24
X_RANGE = 64

idx = pd.MultiIndex.from_product(
    [np.arange(NO_DASHES), np.arange(NO_LINES), np.arange(X_RANGE)],
    names=["d", "c", "x"],
)
df = pd.DataFrame(
    np.random.rand(idx.size), index=idx, columns=["y"]
).reset_index()

df["y"] = 0.2 * df["x"] ** (1 + df["d"] / 2) + 2 * df["c"] + df["y"]

df_cat = df.copy()
df_cat["d"] = df_cat["d"].astype("category")  # commenting causes an error

gg1 = (
    p9.ggplot(df_cat)
    + p9.aes(
        x="x",
        y="y",
        color="c",
        group="c",
        linetype="d",
    )
    + p9.geom_line()
    + p9.scale_color_distiller(type="seq", palette="YlGn", direction=1)
)
print(gg1)
```

The result and similar-to-expected behavior (except the presence of colorbar) are shown below. It seems that the lines are not grouped by `"d"` column and their point are connected. To remedy that, I tried to pass `group=("c", "d")` or `group=["c", "d"]` argument (no idea how to find it in the API reference), but I get `PlotnineError: 'Aesthetics must either be length one, or the same length as the data'`.

### What I get
<img src="https://user-images.githubusercontent.com/65432554/236272209-5d61e888-ae26-4d93-a93e-ce3f67f7dfe6.png" width="400">

### What I expect (+colorbar if possible)

<img src="https://user-images.githubusercontent.com/65432554/236272207-52a04033-b5ab-4d77-b258-dcf22e296b28.png" width="400">

**Comment by has2k1** [comment]
Before plotting, create a column that is combination of `c` and `d` then use that as the group.

**Comment by lukaszkadlubowski** [comment]
Thank you very much, works perfectly! Thank you for the hard work you put into the project.
