### ISSUE TITLE
Suggestion for more informative error message for undefined theme elements

### ISSUE THREAD

**Issue by gracelawley** [has2k1/plotnine#689]
Hi! Thanks for bringing the grammar of graphics to Python!

The current error message that prints when you pass an undefined theme element to `theme()` is not very helpful and is confusing.

For example, if I accidentally use `axis.text.x` instead of `axis_text_x` in `theme()`, plotnine gives me an error message about syntax and indentation.
```python
from plotnine import ggplot, aes, geom_bar, theme, element_text
from plotnine.data import mtcars

(ggplot(mtcars, aes(x='factor(cyl)', fill='factor(cyl)'))
 + geom_bar()
 + theme(axis.text.x=element_text(angle=90))
)
```
```
SyntaxError: '(' was never closed (<string>, line 1)
IndentationError: unexpected indent (<string>, line 1)
SyntaxError: unmatched ')' (<string>, line 1) 1)
```

I frequently make the mistake of using periods instead of underscores since the theme elements in ggplot2 have periods. While I understand why this change was made for plotnine, I imagine others also make this mistake. The current error message can change what should be a quick fix into a much longer debugging session.

I think that a more informative error message for situations like this would be great -- see example below from ggplot2.

Here's the equivalent example but in ggplot2/R and the resulting error message:

```r
library(ggplot2)

ggplot(mtcars, aes(x = factor(cyl), fill = factor(cyl))) +
  geom_bar() +
  theme(axis_text_x = element_text(angle = 90))
```
```
Error in `mapply()`:
! The `axis_text_x` theme element is not defined in the element hierarchy.
Run `rlang::last_trace()` to see where the error occurred.
```

**Comment by has2k1** [comment]
We can improve the error messages but not in this particular case. In python `axis.text.x` is not a valid identifier, so python is complaining before even plotnine knows what is happening!

**Comment by gracelawley** [comment]
@has2k1 That totally makes sense and didn't occur to me before. Improving the error message for situations other than this specific one would be great though, thanks!
