### ISSUE TITLE
Setting up minor ticks

### ISSUE THREAD

**Issue by cmrejen** [has2k1/plotnine#69]
Hi Hassan & team,

I'm trying to get minor ticks set up the way ggplot2 allows it (i.e. with the minor_breaks arg) but I noticed from the doc that that was not an option for the scale_y_continuous method

For instance, if I would like to have 4 minor ticks between each major ticks, would that be possible?

p1 = (ggplot(df, aes(x=df.index))
+ geom_line(aes(y='Python'), color='#00355F', size=1)
+ geom_line(aes(y='Javascript'), color='#2494EA', size=1)
+ labs(x="", y="")
+ scale_x_datetime(breaks=date_breaks('1 year'), labels=date_format("'%y"))
+ scale_y_continuous(minor_breaks=list(np.linspace(-0.2,0.2,45)),
                     breaks=(list(np.linspace(-0.2,0.2,9))),
                     labels = lambda lst: ['{:3.0f}%'.format(x*100) for x in lst],
                     limits = (-0.2, 0.2)))

Thanks!

**Comment by has2k1** [comment]
You can use the `minor_breaks` arg. The documentation does not show the inherited parameters, that will change in the next release.

For 4 breaks you will have to create a transform for that

```python
from mizani.breaks import minor_breaks
from mizani.transforms import identity_trans

class _trans(identity_trans):
    minor_breaks=staticmethod(minor_breaks(4))
    
(ggplot(data)
 ...
 + scale_y_continuous(trans=_trans)
)
```

**Comment by cmrejen** [comment]
Thanks for the prompt answer!

I'm quite new to classes. Currently the following makes no changes but I suppose I'm overriding the transformation setup with the second part of the scale_y_continuous method

I'm actually not sure how much of the scale_y_continuous part of the equation I should transform..

class _trans(identity_trans):
    minor_breaks=staticmethod(minor_breaks(4))
...
+ scale_y_continuous(trans=_trans,
                     breaks=(list(np.linspace(-0.2,0.2,9))),
                     labels = lambda lst: ['{:3.0f}%'.format(x*100) for x in lst],
                     limits = (-0.2, 0.2)))

Thx!

**Comment by has2k1** [comment]
> I'm actually not sure how much of the scale_y_continuous part of the equation I should transform.

I'm lost on what else you are trying to do.

**Comment by cmrejen** [comment]
This is what I currently have:

![image](https://user-images.githubusercontent.com/32913737/31851141-d442443c-b65f-11e7-97a2-86e6bf38cb17.png)

 scale_y_continuous(trans=_trans,
                     breaks=(list(np.linspace(-0.2,0.2,9))), --> Setting 9 ticks from -.2 to .2
                     labels = lambda lst: ['{:3.0f}%'.format(x*100) for x in lst], ---> Formatting the labels into %
                     limits = (-0.2, 0.2))) ---> Setting up the limits

Interestingly, I actually managed to get them minor ticks as soon as I changed the spines position.
This also requires to set back up a couple of things (like background, grid etc.) but it works!

fig = p1.draw()
axes = fig.get_axes()
for ax in axes:
    ax.set_facecolor('white')
    ax.yaxis.set_ticks_position("right")
    ax.spines["left"].set_position(("axes", + 1.09))
    ax.spines['right'].set_visible(True)
    ax.grid(False, which='both')

I get:
![image](https://user-images.githubusercontent.com/32913737/31851328-ed9fa7ea-b663-11e7-8578-ce4345dcecd5.png)

**Comment by has2k1** [comment]
Example added [at](https://github.com/has2k1/plotnine-examples/blob/f2e0fbdf395b88dc93a79bffb9e896d31bea248e/plotnine_examples/tutorials/miscalleneous-changing-the-number-of-minor-breaks.ipynb). It will show up in the documentation for the next release.
