### ISSUE TITLE
Cannot change name of scale_color_cmap_d

### ISSUE THREAD

**Issue by caseygrun** [has2k1/plotnine#691]
The first argument to [`scale_color_cmap_d`](https://github.com/has2k1/plotnine/blob/b855157ee5834e6b96e591407869b5d5859b4b0e/plotnine/scales/scale_color.py#L502-L507) is used to specify the matplotlib colormap, but the argument is called `name` so you can't also change the name of the scale (e.g. to affect the title of the legend). 

By contrast, the continuous version, [`scale_color_cmap`](https://github.com/has2k1/plotnine/blob/b855157ee5834e6b96e591407869b5d5859b4b0e/plotnine/scales/scale_color.py#L451-L455) doesn't have this problem; it uses a different argument called `cmap_name` to specify the matplotlib colormap name.  Easy fix would be to rename the first argument to `scale_color_cmap_d` to `cmap_name` as well. There might be other scales that have this problem---haven't checked. 

Example:
```
from plotnine.data import mpg
(
    ggplot(mpg, aes(x='displ', y='hwy', color='factor(drv)'))
    + geom_point()
    + scale_color_cmap_d('viridis', name='drive train type')
)
```

```
TypeError: scale_color_cmap_d.__init__() got multiple values for argument 'name'
```

For now, can use `guide_legend` as a workaround:

```
from plotnine.data import mpg
(
    ggplot(mpg, aes(x='displ', y='hwy', color='factor(drv)'))
    + geom_point()
    + scale_color_cmap_d('viridis')
    + guides(color=guide_legend(title='drive train type'))
)
```

Thanks for the great library!

**Comment by has2k1** [comment]
A simpler alternative is `+ labs(color="drive train hype")`.
