### ISSUE TITLE
importing ggplot from plotnine

### ISSUE THREAD

**Issue by sarakolding** [has2k1/plotnine#705]
Since updating plotnine, when importing ggplot as 
`from plotnine import ggplot`

I get the following pyright error, although the code functions as expected:

`error: "ggplot" is not exported from module "plotnine"
    Import from "plotnine.ggplot" instead (reportPrivateImportUsage)`

seems to be related to this issue in torch: https://github.com/microsoft/pylance-release/issues/2953 

python 3.10.4
plotnine 0.12.2
pyright 1.1.320

**Comment by has2k1** [comment]
This is the same as https://github.com/has2k1/plotnine/issues/685 which was fixed but has not shipped.

**Comment by sarakolding** [comment]
Great, thanks!
