### ISSUE TITLE
Unrecognised timezone class <class 'datetime.timezone'>

### ISSUE THREAD

**Issue by jrr96** [has2k1/plotnine#707]
The code below (copy pasted from https://plotnine.readthedocs.io/en/stable/tutorials/miscellaneous-manipulating-date-breaks-and-date-labels.html):

```
from plotnine.data import economics
(ggplot(economics)
 + geom_point(aes('date', 'psavert'))
 + labs(y='personal saving rate')
)
```

Produces the error:

Unrecognised timezone class <class 'datetime.timezone'>

**Comment by has2k1** [comment]
Make sure you have the latest version of plotnine and mizani=0.9.2.
