### ISSUE TITLE
Add specific gene labels to geom_point volcanoplot

### ISSUE THREAD

**Issue by jesswhitts** [has2k1/plotnine#722]
Hi, 

I have a volcano plot which I made using this code:

(
    p9.ggplot(de_comp, p9.aes("lfc_mean", "-log10_pscore", color="significance"))
    + p9.geom_point(
        de_comp.query("gene_type == 'Other'"), alpha=0.5
    ) 
    + p9.geom_point(de_comp.query("gene_type != 'Other'"))
    + p9.labs(x="LFC mean", y="Significance score (higher is more significant)")
)

I want to add gene name labels for a few pre-defined genes (which I currently have as a list)
How do I do this? I have tried geom_text but can't get it to work

Best,
Jess

**Comment by has2k1** [comment]
Please create a small example that can run.

**Comment by jesswhitts** [comment]
I solved this, I wanted geom_labels not geom_text
