### ISSUE TITLE
pandas-0.21 deprecaption warnings

### ISSUE THREAD

**Issue by stonebig** [has2k1/plotnine#73]
Trying this:
`````
# plotnine: giving a taste of ggplot of R langage (formerly we were using ggpy)
from plotnine import ggplot, aes, geom_blank, geom_point, stat_smooth, facet_wrap, theme_bw
from plotnine.data import mtcars
ggplot(mtcars, aes(x='hp', y='wt', color='mpg')) + geom_point() +\
facet_wrap("~cyl") + theme_bw()
`````
I get that:

![plotnine](https://user-images.githubusercontent.com/4312421/32159614-7e8ebe4e-bd4e-11e7-98f1-6802c6217b51.PNG)

**Comment by has2k1** [comment]
Thanks for the heads up.

**Comment by stonebig** [comment]
lost in versionneer ... would you mind releasing a dev version for this ?

**Comment by has2k1** [comment]
> lost in versionneer 

What do you mean? 

> would you mind releasing a dev version for this 

As in a dev version on pypi?

Does `pip install git+https://github.com/has2k1/plotnine.git` not work?

**Comment by stonebig** [comment]
ah, I don't know, after a long fight I just succeeded to remove versioneer code for my purpose.

**Comment by has2k1** [comment]
How was it interfering? Versioneer has been pain free for me.

**Comment by stonebig** [comment]
i download from github the .zip, then unzio, then "python setup.py sdist bdist_wheel" , as my goal is to make a wheel for later re-use

**Comment by has2k1** [comment]
That makes sense. I have seen the zip issue [else where](https://github.com/matplotlib/matplotlib/issues/8443).

In that case, the work flow would be

```bash
git clone https://github.com/has2k1/plotnine.git --depth=1
cd plotnine
python setup.py sdist bdist_wheel
```

**Comment by stonebig** [comment]
noted for next time. thanks a lot for plotnine package.
