### ISSUE TITLE
Can the plotnine module draw significance markers？

### ISSUE THREAD

**Issue by hxpGit512** [has2k1/plotnine#731]
Dear plotnine development team，

Can the plotnine module draw significance markers like ggsignif or ggpubr derived from the ggplot2 package, by calculating the significance and describing the p-value or * in the plot?

I look forward to your reply. This functionality is very important for scientific researchers.

**Comment by has2k1** [comment]
Plotnine cannot draw significance markers. This is outside the scope of the project and it is better implemented in an extension.

**Comment by hxpGit512** [comment]
已收件
