### ISSUE TITLE
In-place string scalars in `aes`

### ISSUE THREAD

**Issue by julian-urbano** [has2k1/plotnine#733]
In-place use of scalars in `aes` is very handy, for instance to use constants or to easily differentiate groups:
```python
import pandas as pd
from plotnine import *

# sample data
df = pd.DataFrame({'x': [1, 2, 3],
                   'y': [4, 5, 6],
                   'z': [14, 15, 16]})

# in-place mapping to numeric scalars works just fine,
# using both a constant or a list
ggplot(df, aes(x='x')) +\
    geom_point(aes(y=3)) +\
    geom_point(aes(y=[7,8,9]))
```

<img src="https://github.com/has2k1/plotnine/assets/6097978/1e39e5d6-bd2e-4994-a9b0-4c45d048aefb" width="400">

In the past (at least 0.10.1), we could also use string scalars, for example to use different colors for different datasets and have plotnine generate the mapping and scale for us:

```python
ggplot(df, aes(x='x')) +\
    geom_point(aes(y='y', color=['Treatment'])) +\
    geom_point(aes(y='z', color=['Control']))
```

<img src="https://github.com/has2k1/plotnine/assets/6097978/b77a1218-cdee-497f-9267-259b133272ff" width="400">

But I'm afraid that this doesn't work anymore (0.12.4), nor does it work when giving a full list of values, as big as the dataframe (ie. `color=np.repeat('Treatment',3)`:

```
C:\ProgramData\anaconda3\Lib\site-packages\plotnine\guides\guides.py:197: PlotnineWarning: Cannot generate legend for the 'color' aesthetic. Make sure you have mapped a variable to it
```

**Comment by has2k1** [comment]
This is a bug. Using a list with a single string should be just about equivalent to using `repr` string expressions. e.g.

```python
(ggplot(df, aes(x='x'))
 +  geom_point(aes(y='y', color='"Treatment"'))
 +  geom_point(aes(y='z', color='"Control"'))
)
```
