### ISSUE TITLE
Overlapping labels and wrong direction of cols in geom_col

### ISSUE THREAD

**Issue by luifrancgom** [has2k1/plotnine#741]
## Description

There is a problem in relation to the labels and the direction of the columns when using `geom_col` 

## Steps to reproduce and actual behavior

```python
import pandas as pd
from plotnine import (
      ggplot, aes, 
      geom_col
)
from plotnine.data import mtcars


df = (mtcars.
      loc[:, ["name", "disp"]])

(ggplot(data=df,
        mapping=aes(x="disp", y="name")) +
 geom_col())
#> <Figure Size: (640 x 480)>
```

![](https://i.imgur.com/BHVyFk6.png)

## Expected behavior

I was expecting  a similar result as in the case of R:

``` r
library(ggplot2)
library(tibble)

tbl <- mtcars |> 
  rownames_to_column(var = "name") |>
  _[c("disp", "name")]

ggplot(data=tbl,
       mapping=aes(x=disp, y=name)) +
    geom_col()
```

![](https://i.imgur.com/7ncpv7n.png)

<sup>Created on 2024-01-12 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

## Session information

```
Session info --------------------------------------------------------------------
Platform: Windows-10-10.0.22621-SP0 (64-bit)
Python: 3.11
Date: 2024-01-12
Packages ------------------------------------------------------------------------
plotnine==0.12.4
reprexpy==0.3.3
```

**Comment by has2k1** [comment]
Plotnine does not yet automatically detect the orientation of the plot based on the mappings. For now you have to map the discrete variable to the `x` aesthetic and then use `coord_flip`.

```python
(ggplot(data=df, mapping=aes(x="name", y="disp"))
 + geom_col()
 + coord_flip()
)
```

**Comment by luifrancgom** [comment]
Thank you @has2k1. In this case what you recommend in relation to this issue. Should I close it or you will label as a possible enhancement in a distant future in relation to detecting the orientation? Please let me know.
