### ISSUE TITLE
How to show and wait for chart when using plotline in console program?

### ISSUE THREAD

**Issue by fhg-isi** [has2k1/plotnine#746]
When createing a chart with plotnine, I would expect following code to work. 

```
chart = (ggplot(df, ...))
chart.show()
```

However, chart does not have a show method. 

If I use

```
fig = chart.draw()
fig.show()
```
A plot window is created but different to matplotlib, the application does not wait until I closed the window. 

I also tried

```
chart.draw()
plt.show()
```

=> What is the recommended way to display plotnine charts outside notebook environments?

**Comment by fhg-isi** [comment]
Its `chart.draw(True)` Maybe you want to include this in the getting started documentation.

**Comment by fhg-isi** [comment]
`print(chart) `
also works. However, I would expect print to show something in the console, not to open  a plot window.

**Comment by has2k1** [comment]
There is an API change and the recommended method will be `chart.show()`. And `print` is being deprecated.
