### ISSUE TITLE
geom_smooth not showing error bars in example

### ISSUE THREAD

**Issue by fkgruber** [has2k1/plotnine#748]
The example plot for geom_smooth is not showing the error bars (https://www.plotnine.org/generated/plotnine.geoms.geom_smooth.html#plotnine.geoms.geom_smooth)
```

from plotnine import (
    ggplot,
    aes,
    geom_point,
    geom_smooth,
    labs
)
from plotnine.data import mpg
(
    ggplot(mpg, aes(x='displ', y='hwy'))
    + geom_point()
    + geom_smooth(span=.3)
    + labs(x='displacement', y='horsepower')
)
```
I also get the message:

> /Users/me/miniconda3/envs/mhcflurry/lib/python3.10/site-packages/plotnine/stats/smoothers.py:330: PlotnineWarning: Confidence intervals are not yet implemented for lowess smoothings.

<img width="637" alt="image" src="https://github.com/has2k1/plotnine/assets/4311763/320c5002-fd8f-49af-9830-e0c116cb0132">

**Comment by has2k1** [comment]
You need to install [scikit-misc](https://github.com/has2k1/scikit-misc) which provides loess smoothing which has intervals implemented.

**Comment by fkgruber** [comment]
thanks
