### ISSUE TITLE
Can't edit text when saving a plotnine figure to an svg file

### ISSUE THREAD

**Issue by nettanetta** [has2k1/plotnine#756]
Hi,
First I want to thank you for helping me avoid writing code in R, Plotnine is a lifesaver package!
Lately, I noticed that when I save a plot made with R's ggplot2 as an SVG or PDF file, I can upload it to illustrator and edit the figure text. However, when I do the same with a plot generated using plotnine, illustrator does not recognize the text as text and therefore makes editing my figures a bit tricky. 

As an example I created the same figure using ggplot and plotnine (based on [this](https://blog.tidy-intelligence.com/posts/ggplot2-vs-plotnine/) tutorial).

Is it possible to fix it?
thanks!
Netta

python code:
```
from plotnine import *
from palmerpenguins import load_penguins

penguins = load_penguins().dropna()
p = ggplot(penguins, aes(x = "island")) + geom_bar()
ggsave(p, filename = "penguins_python.svg")
```

R code:
```
library(ggplot2)
library(palmerpenguins)

penguins <- na.omit(palmerpenguins::penguins)
penguins_figure <- ggplot(penguins, aes(x = island)) + geom_bar()
ggsave(penguins_figure, filename = "penguins-figure.svg")


```
![penguins_python](https://github.com/has2k1/plotnine/assets/29280770/4420e54c-24a0-4108-a1d1-12eaba8bec7c)
![penguins_r](https://github.com/has2k1/plotnine/assets/29280770/a16b8732-b24e-4443-a785-99c19e754dd0)

**Comment by TyberiusPrime** [comment]
That's a matplot lib trap / ooptimization to have the SVG look identical even if the fonts are not on the target machine.:

Use 
```
import matplotlib.pyplot as plt
plt.rcParams['svg.fonttype'] = 'none'
```

to turn this off.

See https://matplotlib.org/stable/users/explain/customizing.html

**Comment by has2k1** [comment]
With the next release you will be able to use `theme(svg_usefonts=True)`.
