### ISSUE TITLE
abnormal legend

### ISSUE THREAD

**Issue by wangjiawen2013** [has2k1/plotnine#757]
Hi,
I made a figure using:
```
ggplot(obs,aes(x='library_id',y='percentage',fill='leiden')) + geom_bar(stat='identity') + scale_fill_manual(values=adata.uns['leiden_colors']) + theme(axis_text_x=element_text(angle=45))
```
The legend is weired, some items were lost (1, 19, 20, and so on):
![image](https://github.com/has2k1/plotnine/assets/29703450/941aa9a8-53d2-4045-a19f-e2524fa46fc4)

When using plotnine_prism() with the same data, it looks well:
![image](https://github.com/has2k1/plotnine/assets/29703450/9a83953c-e621-48ee-9f59-f7c6b74e555d)

I don't want to use plotnine_prism() theme, so how to adjust the legend ?

**Comment by has2k1** [comment]
You can set the number of columns that works for you 
```python
+ guides(fill=guide_legend(ncol=2))
```

and/or adjust the height of the keys

```python
+ theme(legend_key_height=10)
```

**Comment by wangjiawen2013** [comment]
Thanks, I'll try it.
And can plotnine adjust the columns automatically according to the number the keys ?  When there are less keys, the legend is one column, while it's two columns when there are lots keys ?

**Comment by has2k1** [comment]
> Thanks, I'll try it. And can plotnine adjust the columns automatically according to the number the keys ? When there are less keys, the legend is one column, while it's two columns when there are lots keys ?

No it does not, but it is something we could look into. While I don't think the problem of the overflowing legend can go away entirely, it could become an even rarer edge-case.
