### ISSUE TITLE
For barplot and histplot (start from where right the x axis is instead of some space above x)

### ISSUE THREAD

**Issue by EnvGenomics** [has2k1/plotnine#76]
I have to say that the author of ggplot2, you know who I am talking about, is a stubborn person and sticks to his own opinion that some space should exist between x axis and start of the bar or other figure elements that start from x axis, which I think is ugly and strange. Since you rewrite the package, is that possible that you make some improvement or at least, give us a choice, just like the option of inward and outward ticks in the early version of ggplot2?
Also, how to change the location of a legend to wherever I want to put in the plotting area?

**Comment by EnvGenomics** [comment]
[diamonds_bar123411.pdf](https://github.com/has2k1/plotnine/files/1443873/diamonds_bar123411.pdf)
[diamonds_bar12341111.pdf](https://github.com/has2k1/plotnine/files/1443874/diamonds_bar12341111.pdf)

**Comment by has2k1** [comment]
You can do both.

```python
 + scale_y_continuous(expand=(0, 0, .1, 0))  # Available in the next release
 + theme(legend_position=(0.2, 0.6))
```

**Comment by EnvGenomics** [comment]
Dear Hassan,

This is Jayson. I am writing to you to discuss the possibility of writing a book introducing your package plotnine in Chinese. ggplot2 has receive great popularity in China and all over the world and I believe plotnine will also be welcomed by the science community all over the world. I am going to work with Jie Zhang, who is very familiar with publication of books and both he and I have lots of experience in visualization of data using different packages. We will ask you to write a preface for the new book. We are just start to write the book and wondering whether you can authorize the book introducing your package.

Looking forward to your reply.


Best,


Jianshu (Jayson) Chao
