### ISSUE TITLE
theme_minimal crops out facet labels (not happening with other themes)

### ISSUE THREAD

**Issue by jwhendy** [has2k1/plotnine#760]
Hello, I've never run into this before so I'm suspecting it's some kind of regression. Here's a repro:
```
import pandas as pd
from plotnine import * 

foo = pd.DataFrame({'label': ['a', 'a', 'b', 'b'],
                    'x': [0, 1, 2, 3],
                    'y': [4, 5, 6, 7]})
```

By default we get:

```
p = ggplot(foo, aes(x='x', y='y', group=1)) + geom_line()
p = p + facet_wrap('~label')
p
```
<img width="638" alt="image" src="https://github.com/has2k1/plotnine/assets/379357/080752fb-4a3b-40fc-b762-6f1f9a5e7abd">

And trying a few others:
```
p + theme_bw()
```
<img width="637" alt="image" src="https://github.com/has2k1/plotnine/assets/379357/711fe659-3bc4-431a-948a-189f131cd5ee">

```
p + theme_dark()
```
<img width="638" alt="image" src="https://github.com/has2k1/plotnine/assets/379357/82871afd-284c-4f1d-a31c-c193ea783749">

However with `theme_minimal()` the facet labels are removed. You can try this without the additional plot background arguments to `theme()`, but the result is the same. I'm including it so it's white and easily seen vs. the default transparent bg:
```
p + theme_minimal() + theme(plot_background=element_rect(fill='white'))
```
<img width="636" alt="image" src="https://github.com/has2k1/plotnine/assets/379357/cace0418-4615-4626-8010-c62496b04f3c">

**Comment by has2k1** [comment]
The problem is

```python
theme(strip_background=element_blank())
```

removes the box around the facet labels. The layout manager uses box when accounting for space taken by the labels.

**Comment by jwhendy** [comment]
Is it a dumb/hacky fix to adjust [L28](https://github.com/has2k1/plotnine/blob/main/plotnine/themes/theme_minimal.py#L28) to specify a transparent strip_background vs. fixing via the layout manager (which to my unfamiliar ear, sounds much more involved)?

Googling around, it seems transparency can be specified in RGB codes like `#AARRGGBB`, as long as the backend will accept the additional alpha parameter. Having found that, I tried this and it works:

```
p = ggplot(foo, aes(x='x', y='y', group=1)) + geom_line()
p = p + facet_wrap('~label')
p = p + theme_minimal()
p = p + theme(strip_background=element_rect(fill="#00000000", color="#00000000"))
p
```
<img width="648" alt="image" src="https://github.com/has2k1/plotnine/assets/379357/6a423939-df44-4f1b-8159-c4a6fb00741e">

Showing here with an additional theme arg so things are not transparent:
```
p = p + theme(plot_background=element_rect(fill="white"))
p
```

<img width="637" alt="image" src="https://github.com/has2k1/plotnine/assets/379357/76e90c45-cead-479d-8b9c-2377720598bd">

Not sure if there are other byproducts of setting `strip_background` to an `element_rect` vs. `element_blank`...

**Comment by has2k1** [comment]
> Is it a dumb/hacky fix to adjust [L28](https://github.com/has2k1/plotnine/blob/main/plotnine/themes/theme_minimal.py#L28) to specify a transparent strip_background vs. fixing via the layout manager (which to my unfamiliar ear, sounds much more involved)?

This is a real bug based on a wrong assumption, and requires fixing it in the layout manager has to be fixed. I have working solution and I'll make a release on Friday.

In the meantime, you should be able to use `theme(strip_background=element_rect(fill="none", color="none"))`
