### ISSUE TITLE
dynamic labels i.e. labs(fill=lambda x: x['example_col'].iloc[0])

### ISSUE THREAD

**Issue by Nephdz** [has2k1/plotnine#765]
Is there a way to use a lambda function or something else to dynamically change the labels for all parts of the plot to be a value in the dataframe? I'm thinking something like this:

```python
(
    df
        .loc[lambda x: x['filter_col']==999]
        .pipe(ggplot)
            + geom_map(aes(fill='bins'))
            + scale_fill_manual(labels=lambda y: [np.log(x) for x in y],values=[to_hex(c) for c in colors])
            + labs(fill=lambda x: f'legend label string: {x['example_col'].iloc[0]}',title=lambda x: '{} | {} | {}'.format(x['A'].iloc[0],x['B'].iloc[0],"C"))
)
```

I'm no expert in R but I think ggplot lets you do something where you create an entire column of strings of `f'legend label string: {x['example_col'].iloc[0]}'` and call it fill_column then do  `+ labs(fill=.$fill_column )`

**Comment by has2k1** [comment]
I am not sure of what you are trying to do, but the values to any parameter in the `labs()` call has to be a string. It does not make sense to have anything else, I'm don't know about R.

**Comment by has2k1** [comment]
Okay I get it. It is not possible.

**Comment by TyberiusPrime** [comment]
Using my libraries [dppd](https://github.com/tyberiusPrime/dppd)/[dppd_plotnine](https://github.com/tyberiusPrime/dppd_plotnine) you can probably achieve something similar.

It's not gonna be a literal R translation though.

I think it would read like this

```python 
(
import dppd, dppd_plotnine
dp, X = dppd.dppd()

dp(df)
        .filter_by(X['filter_col'] == 999)
        .p9()
        .add_map(x='x', y='y', fill='bins') # aes = name, non_aes = _name
        # I think labs is not wrapped in dppd_plotnine
        # (would be trivial to add though).
        # but putting the name on the scale will work.
        .scale_fill_manual(
              #I'm just assuming that y & colors are from the df
              # after .p9(), the dataframe is in X.data
              labels=lambda y: [np.log(x) for x in X.data['y']],
              values=[to_hex(c) for c in X.data['colors'],
              name=f'legend label string: X.data['example_col'].iloc[0]}',)
             )
       .title( '{} | {} | {}'.format(X.data['A'].iloc[0],X.data['B'].iloc[0],"C"))
).pd
```
