### ISSUE TITLE
AttributeError: 'YAxis' object has no attribute 'get_tick_params'  on example plot

### ISSUE THREAD

**Issue by jfhawkin** [has2k1/plotnine#767]
I ran plotnine 0.13.4 and received the below error message. Downgrading to 0.13.3 solved the issue. It seems to be an error in the most recent release.

from plotnine import ggplot, geom_point, aes, stat_smooth, facet_wrap
from plotnine.data import mtcars

(
    ggplot(mtcars, aes("wt", "mpg", color="factor(gear)"))
    + geom_point()
    + stat_smooth(method="lm")
    + facet_wrap("gear")
)

**Comment by has2k1** [comment]
This is an installation dependency issue, you need matplotlib >= 3.7.0.

**Comment by jfhawkin** [comment]
Thanks! That was the issue. My environment was using matplotlib 3.6.3.
