### ISSUE TITLE
Please loosen the restrictions on theme(figure_size=( , ))

### ISSUE THREAD

**Issue by jnhyeon** [has2k1/plotnine#783]
Thank you for creating a good package.

I set the height of figure_size to 30, so the chart needs to be viewed vertically.
However, the height of figure_size is currently limited to 25.
Please loosen the restrictions on theme(figure_size=( , )).

Thank you

**Comment by has2k1** [comment]
If you are setting height of 25 inches, and assuming the default dpi=100 that gives height=2500px. The retina version has height=5000px. So any height above 25 inches is probably not for an inline image. Is this a wrong assumption?

If it isn't and you intend to save a large image, you can override the restriction with `p.save("plot.png", limitsize=False)`. Does this work for you?

**Comment by jnhyeon** [comment]
Thank you for your quick reply.

I am performing data analysis using a notebook in VSCode.
As shown in the attached image, there are many items, so a long vertical bar chart must be drawn.
Since it is not saved as an image, the p.save() function cannot be used.
I would like to display a bar chart on the output screen of the notebook.
Is there any way?

Thank you

![image](https://github.com/has2k1/plotnine/assets/3360511/9fc576b2-f082-4b80-a9e7-e88fb3a315be)
![image](https://github.com/has2k1/plotnine/assets/3360511/49fe6b42-95fb-4721-8f2f-b890091b5191)
