### ISSUE TITLE
Change color of only one x axis label - plotnine

### ISSUE THREAD

**Issue by pyvid** [has2k1/plotnine#787]
Is there a way to only change the color of one specific x/y axis label with the use of plotnine only? I only get as far as colorizing all x or y axis labels in one color.

**Comment by has2k1** [comment]
Yes you can. You should pass a list of colors. There should be as many colors as there are labels.

**Comment by pyvid** [comment]
> Yes you can. You should pass a list of colors. There should be as many colors as there are labels.

Thanks for your reply. Unfortunately this is not working for me, I'm not sure what im missing.
With this line of code I'm able to change the color of all x axis labels:

`theme(axis_text_x=element_text(color="red")) +`

When I'm passing a list of colors like this:

`theme(axis_text_x=element_text(color=["black", "black", "black", "red", "black"])) +`

I'm getting a ValueError (ValueError: ['black', 'black', 'black', 'red', 'black'] is not a valid value for color)

**Comment by has2k1** [comment]
Download the latest version of plotnine.
