### ISSUE TITLE
Error importing plotnine with Python 3.6.1

### ISSUE THREAD

**Issue by ndeku** [has2k1/plotnine#79]
Error importing plotnine on OSX 10.12.6 Python 3.6.1 (Anaconda distribution 4.3.27).

Any help would be appreciated

`from plotnine import *`
`from plotnine.layer import Layers`

---------------------------------------------------------------------------
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-16-9639a44efb55> in <module>()
----> 1 from plotnine import *
      2 from plotnine.layer import Layers

/Users/myusername/anaconda/lib/python3.6/site-packages/plotnine/__init__.py in <module>()
      1 from __future__ import absolute_import
      2 
----> 3 from .qplot import qplot            # noqa: F401
      4 from .ggplot import ggplot, ggsave  # noqa: F401
      5 from .watermark import watermark    # noqa: F401

/Users/myusername/anaconda/lib/python3.6/site-packages/plotnine/qplot.py in <module>()
      9 import six
     10 
---> 11 from .ggplot import ggplot
     12 from .aes import aes, all_aesthetics, scaled_aesthetics
     13 from .labels import ggtitle, labs

/Users/myusername/anaconda/lib/python3.6/site-packages/plotnine/ggplot.py in <module>()
      8 import pandas as pd
      9 import matplotlib as mpl
---> 10 import matplotlib.pyplot as plt
     11 from matplotlib.offsetbox import AnchoredOffsetbox
     12 import matplotlib.transforms as mtransforms

/Users/myusername/anaconda/lib/python3.6/site-packages/matplotlib/pyplot.py in <module>()
     27 from cycler import cycler
     28 import matplotlib
---> 29 import matplotlib.colorbar
     30 from matplotlib import style
     31 from matplotlib import _pylab_helpers, interactive

/Users/myusername/anaconda/lib/python3.6/site-packages/matplotlib/colorbar.py in <module>()
     30 
     31 import matplotlib as mpl
---> 32 import matplotlib.artist as martist
     33 import matplotlib.cbook as cbook
     34 import matplotlib.collections as collections

/Users/myusername/anaconda/lib/python3.6/site-packages/matplotlib/artist.py in <module>()
     15 from . import cbook, docstring, rcParams
     16 from .path import Path
---> 17 from .transforms import (Bbox, IdentityTransform, Transform, TransformedBbox,
     18                          TransformedPatchPath, TransformedPath)
     19 # Note, matplotlib artists use the doc strings for set and get

ImportError: cannot import name 'TransformedPatchPath'

**Comment by has2k1** [comment]
I think you have an issue with your Matplotlib installation.

This line is failing:

```python
 import matplotlib.pyplot as plt
```

Maybe it is a corrupt environment.
