### ISSUE TITLE
geom_text: family aesthetic does not seem to use mappings

### ISSUE THREAD

**Issue by machow** [has2k1/plotnine#790]
Manually specifying sans-serif or serif seems to work. But using those in a mapping to family doesn't seem to work (at least on my Mac). (I also noticed that there doesn't seem to be support for `"mono"`, but that might be worth a separate issue?)

```python
from plotnine import *
import pandas as pd

df = pd.DataFrame({"x": 1, "y": [2, 1], "family": ["sans-serif", "serif"]})

# doesn't seem to be used, everything is sans-serif
(
  ggplot(df, aes("x", "y")) + 
  geom_text(aes(label = "family", family="family"), size=20)
)
```

<img width="651" alt="image" src="https://github.com/has2k1/plotnine/assets/2574498/0644744d-4136-4c82-b555-badbe0933d32">

```python
# works (all sans-serif)
(
  ggplot(df, aes("x", "y")) + 
  geom_text(aes(label = "family"), family = "sans-serif", size=20)
)
```

<img width="660" alt="image" src="https://github.com/has2k1/plotnine/assets/2574498/145c2c03-e0fb-4622-8c44-2fd5a9252c50">

```python
# also works (all serif)
(
  ggplot(df, aes("x", "y")) + 
  geom_text(aes(label = "family"), family = "serif", size=20)
)
```

<img width="649" alt="image" src="https://github.com/has2k1/plotnine/assets/2574498/d41912e9-6c90-4674-87f4-ffdd0682786c">

**Comment by has2k1** [comment]
Currently font family is a parameter and not an aesthetic but we can turn it into an aesthetic.
