### ISSUE TITLE
(dodged) Bars overlap axis when using 2x`geom_bar()` and `geom_text`

### ISSUE THREAD

**Issue by mcanouil** [has2k1/plotnine#798]
Take the code below:

```python
from plotnine import *
import polars as pl

(
    ggplot(
        data=pl.DataFrame(
            {
                "X": ["x", "x", "y", "y"],
                "GROUP": ["A", "B", "A", "B"],
                "COUNT": [42, 24, 32, 18],
                "TOTAL": [74, 74, 50, 50],
            }
        )
    ) +
        aes(x="X", y="COUNT") +
        scale_y_continuous(expand=(0, 0, 0.05, 0)) +
        scale_x_discrete(expand=(0, 0, 0.05, 0)) +
        theme(axis_line=element_line()) +
        geom_bar(stat="identity") +
        geom_text(mapping=aes(label="TOTAL", y="TOTAL+1")) +
        geom_bar(mapping=aes(fill="GROUP"), position="dodge", stat="identity")
)
```

See how the dodged bars from the last `geom` overlaps both x/y-axis?

![image](https://github.com/has2k1/plotnine/assets/8896044/4dd0cfe1-500b-4a66-9ea6-c522796ca8b5)

Now, if you remove one of the `geom_` (any), there are no issues, *e.g.*, removing `geom_text`:

![image](https://github.com/has2k1/plotnine/assets/8896044/d273e974-517c-4cae-b39d-1b3e19e69fb5)

**Comment by has2k1** [comment]
matplotlib sets a very low [`zorder=2.5`](https://github.com/matplotlib/matplotlib/blob/54729dbcb59c6f46c44241fc3193a2e67d5983e8/lib/matplotlib/spines.py#L64) for the axis line (spline). We need to override it.

Actually, this `theme(axis_line=element_line(zorder=100))` works, but we will set our own default.
