### ISSUE TITLE
Need example for multiline graph

### ISSUE THREAD

**Issue by jrbrearley** [has2k1/plotnine#80]
Any chance of an working python 3.6.3 example of how to make a multiline graph, like gnuplot can easily do?

Sample data file is:
`category "series 1" "series 2" "series 3" "series 4" "series 5"`
`QTR1      1          2          3          4          5`
`QTR2      7          8          9          10         11`
`QTR3      12         13         14         15         16`
`QTR4      17         18         19         20         21`

Gnuplot output graph:
![lines_multi_column_data_file](https://user-images.githubusercontent.com/32575796/32701753-1bdd7c30-c7a9-11e7-81f5-f469ad84ed4b.png)

**Comment by has2k1** [comment]
If you are coming from gnuplot, you have to get used to thinking about the data in a different way. It should be [tidy data](https://en.wikipedia.org/wiki/Tidy_data).

This is what the tidy data version looks like:

```
   category    series  count
0      QTR1  series 1      1
1      QTR2  series 1      7
2      QTR3  series 1     12
3      QTR4  series 1     17
4      QTR1  series 2      2
5      QTR2  series 2      8
6      QTR3  series 2     13
7      QTR4  series 2     18
8      QTR1  series 3      3
9      QTR2  series 3      9
10     QTR3  series 3     14
11     QTR4  series 3     19
12     QTR1  series 4      4
13     QTR2  series 4     10
14     QTR3  series 4     15
15     QTR4  series 4     20
16     QTR1  series 5      5
17     QTR2  series 5     11
18     QTR3  series 5     16
19     QTR4  series 5     21
```
 
**code**
```python
from io import StringIO
import pandas as pd
from plotnine import *

# Read data into dataframe
io = StringIO(
"""category "series 1" "series 2" "series 3" "series 4" "series 5"
QTR1 1 2 3 4 5
QTR2 7 8 9 10 11
QTR3 12 13 14 15 16
QTR4 17 18 19 20 21
""")
data = pd.read_csv(io, sep=' ')

# Covert to tidy data
series = ['series {}'.format(i) for i in range(1, 6)]
df = data.melt(id_vars=['category'], value_vars=series, var_name='series', value_name='count')

# Plot
(ggplot(df)
 + aes('category', 'count', color='series', group='series')
 + geom_point()
 + geom_line())
```
![gnuplot-question](https://user-images.githubusercontent.com/780341/32762768-f470461e-c8c0-11e7-8061-a60a97f2438f.png)

**Comment by jrbrearley** [comment]
Thanks, that works very nicely!
