### ISSUE TITLE
Feature Request: Plot horizontal column chart

### ISSUE THREAD

**Issue by jrbrearley** [has2k1/plotnine#81]
geom_col happily plots vertical dodge columns and vertical stack columns. On occasion, some people want the columns to go horizontally, not vertically. It would be nice to be able to do this in plotnine.

gnuplot can do horizontal histograms, but the formula needed is kind of messy and not well understood or documented.

**Comment by has2k1** [comment]
That is already possible, use `coord_flip`.

**Comment by jrbrearley** [comment]
Thanks Hassan, it works great!

p + plotnine.coord_flip()
