### ISSUE TITLE
when import plotnine there are some warning

### ISSUE THREAD

**Issue by gaorongchao** [has2k1/plotnine#83]
D:\Anaconda3\lib\site-packages\statsmodels\compat\pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

**Comment by has2k1** [comment]
Yeah it is annoying but it is a [statsmodels](https://github.com/statsmodels/statsmodels) [issue](https://github.com/statsmodels/statsmodels/issues/3814).

**Comment by gaorongchao** [comment]
I think you can update to use pandas.tseries module instead

**Comment by has2k1** [comment]
The offending line is not in plotnine.
