### ISSUE TITLE
xlab,ylab,ggtitle cannot use Chinese character

### ISSUE THREAD

**Issue by gaorongchao** [has2k1/plotnine#84]
when use chinese in figure,it show Square only。
I know this is caused by matplotlib，but when I use matplotlib，I can set 

```
from pylab import mpl
mpl.rcParams['font.sans-serif'] = ['SimHei'] 
```

to show chinese.

but it does not work, when use plotnine?

**Comment by gaorongchao** [comment]
I think there need some option to special the font

**Comment by has2k1** [comment]
Try

```python
(ggplot()
 ...
 + theme(text=element_text(family='SimHei'))
)
```

**Comment by gaorongchao** [comment]
Great!!!
It work
