### ISSUE TITLE
shape in ggplot2

### ISSUE THREAD

**Issue by gaorongchao** [has2k1/plotnine#85]
in ggplot2:
![image](https://user-images.githubusercontent.com/3361790/33010310-03b4248e-ce15-11e7-8a04-ec4e814ee50a.png)

in plotnine:
![default](https://user-images.githubusercontent.com/3361790/33106852-538f3ed4-cf6f-11e7-9098-146c13be8e2f.png)

some of them are too similar in plotnine;
```r
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, shape = class))
```
```python
(ggplot(mpg,aes('displ','hwy',shape='class'))+geom_point())
```

**Comment by has2k1** [comment]
There are a couple of issues here.

1. ggplot2 shapes are drawn from R which has variations of the same shape one with are fillable and others are unfillable shapes. Plus, the variety makes it easier together shapes there are more visually distinct.

2. The agg/png backend for matplotlib is not very good are drawing small shapes.

3. The comparison images (above) are not of the same size.

The way to address this is to give the user an option of mixing shapes. Currently, you can either have unfilled shapes, or filled shapes. Maybe we can create a list of mixed (filled & unfilled) shapes.

```python
mixed_shapes = (
    'o',  # circle      (filled)
    '^',  # triangle up (filled)
    's',  # square      (filled)
    'x',  # x           (unfilled)
    '1',  # tri_down    (unfilled)
    '+',  # plus        (unfilled)
    '*'   # star        (filled)
)


(ggplot(mpg, aes('displ', 'hwy', shape='class'))
 + geom_point(size=3)
 + scale_shape_manual(values=mixed_shapes)
)
```
@gaorongchao are these distinct enough? If not, the options are at https://matplotlib.org/api/markers_api.html. I think we an come up with a decent list. Thanks.

**Comment by gaorongchao** [comment]
I think it's much better than before,I can adjust by myself，Thank you very much.
