### ISSUE TITLE
geom_col: overlapping x-axis labels when using `element_text(angle=45)`

### ISSUE THREAD

**Issue by nick-youngblut** [has2k1/plotnine#863]
reprex:

```python
import plotnine as pn
from plotnine.data import mtcars

pn.ggplot(mtcars, pn.aes("name", "mpg")) \
    + pn.geom_col() \
    + pn.theme(
        figure_size=(10,3),
        axis_text_x=pn.element_text(angle=45)
    ) 
```

The resulting x-axis labels are not correctly positioned:

![Screenshot 2024-08-05 at 10 47 12 AM](https://github.com/user-attachments/assets/9670b60b-e72c-436d-89f7-d679c80c931f)

Using `pn.element_text(angle=45, hjust=1)` helps, but then the labels are too far to the left of each x-axis tick.

Another example from my own data: 

![Screenshot 2024-08-05 at 10 44 41 AM](https://github.com/user-attachments/assets/36a292a5-eb72-46b2-9556-afcbd78b544e)

The most relevant sections of my very long conda env:

```
# Name                    Version                   Build  Channel
python                    3.10.14         hd12c33a_0_cpython    conda-forge
plotnine                  0.13.6             pyhd8ed1ab_0    conda-forge
```

**Comment by has2k1** [comment]
The text is rotated around the point at which it is aligned. By default that is the baseline/center. You need to change the alignment (`va` & `ha`), and also the `rotation_mode` which affects the order of rotation and alignment.

```python
theme(
    axis_text_x=element_text(angle=45, va="top", ha="right", rotation_mode="anchor")
)
```

**Comment by nick-youngblut** [comment]
Thanks @has2k1  for the info! I didn't know that plotnine differed from the ggplot2 API in this regard. I'll keep that in mind.

**Comment by has2k1** [comment]
Reopened so that it is documented.
