### ISSUE TITLE
date in scale_x is not show acceptable 

### ISSUE THREAD

**Issue by gaorongchao** [has2k1/plotnine#87]
This is my code 
```python
from plotnine import * 
from plotnine.data import *

p = ggplot(economics,aes(x='date',y='pce'))
p + geom_line()
````
![image](https://user-images.githubusercontent.com/3361790/33160611-bc579a9e-d058-11e7-8e19-756dcaabb94a.png)

The default of scale of x is does not normal.

I konw we can use date_break to reset the default x scale.
```python
from mizani.breaks import date_breaks
from mizani.formatters import date_format

p = ggplot(economics,aes(x='date',y='pce'))
(p + geom_line()
  + scale_x_datetime(breaks=date_breaks('10 years'),labels=date_format('%Y')))
```
![image](https://user-images.githubusercontent.com/3361790/33161144-85e795b4-d05c-11e7-92b7-530505e667ab.png)

But I still hope the default will show better than now!

This is default drawn in R ggplot2
```R
library(ggplot2)
ggplot(data = economics) + 
  geom_line(mapping = aes(x = date, y = pce))
```
![image](https://user-images.githubusercontent.com/3361790/33160992-9e7efe2e-d05b-11e7-97a2-f1d9eba866c1.png)

**Comment by has2k1** [comment]
This is a mizani & matplotlib issue.
