### ISSUE TITLE
Equivalent of ggplot's interaction?

### ISSUE THREAD

**Issue by kiwidamien** [has2k1/plotnine#872]
I cannot find how to do the equivalent of ggplot's `interaction` feature.

## What I'd like to do
This site has an [example](https://www.statology.org/ggplot-group-by-two-columns/) that has the sort of thing I am looking to reproduce: I have two discrete factors (in the example, store and promotion), and I would like to produce a line plot with each unique combination making a "group" to connect the lines with.

## Example in ggplot

Taking it from the example above:
```r
#create line plot with values grouped by store and promo
ggplot(df, aes(x=week, y=sales, color=store, shape=promo,
               group=interaction(store, promo))) + 
  geom_point(size=3) +
  geom_line()
```

## What I'd expect to work in `plotnine`

```python
import plotnine as p9
import pandas as pd

df = pd.DataFrame({
    'week': [1,2,3,4]*4,
    'store': (["A"]*8 + ["B"]*8),
    'promo': (["promo1"]*4 + ["promo2"]*4)*2,
    'sales': [1, 2, 6, 7, 2, 3, 5, 6, 3, 4, 7, 8, 3, 5, 8, 9]
})

#create line plot with values grouped by store and promo
(
  p9.ggplot(df, p9.aes(x="week", y="sales", color="store", shape="promo",
               group="interaction(store, promo)")) + 
  p9.geom_point(size=3) +
  p9.geom_line()
)
```

This breaks because it doesn't know what interaction is. If I want the plot, I have to create a column in the data solely for defininte groups:
```python
# ... as before

df['group_col'] = df.apply(lambda row: (row.store, row.promo), axis=1)
(
  p9.ggplot(df, p9.aes(x="week", y="sales", color="store", shape="promo",
               group="group_col")) + 
  p9.geom_point(size=3) +
  p9.geom_line()
)
```

This isn't great, because it means I am manually creating (and the tidying columns) for every plot grouping that makes sense, rather than the R-style approach where the interaction happens inside p9 but doesn't alter the actual data frame.

**Comment by has2k1** [comment]
This is not exactly a plotnine issue, it is a function issue. R has an `interaction` function and there is none in python.

For your case you can define a basic `interaction` function and everything will work.

```python
def interaction(*cats, sep="."):
    cats = [c.astype(str) for c in cats]
    return [sep.join(items) for items in zip(*cats)]
```
