### ISSUE TITLE
use geom_segment when scale x is datetime

### ISSUE THREAD

**Issue by gaorongchao** [has2k1/plotnine#88]
if the scale x is not datetime,it work
```python
from plotnine import * 
from plotnine.data import *
import datetime

p = ggplot(economics,aes(x='pop',y='pce'))
(p + geom_line()
  + geom_segment(aes(x=240000,xend=240000,y=0,yend=12500)))
```
The flow doesnot work
```python
from mizani.breaks import date_breaks
from mizani.formatters import date_format

p = ggplot(economics,aes(x='date',y='pce'))
(p + geom_line()
   + geom_segment(aes(x=datetime.datetime.strptime('1970-01-01','%Y-%m-%d'),xend=datetime.datetime.strptime('1970-01-01','%Y-%m-%d'),y=0,yend=12500)) 
   + scale_x_datetime(breaks=date_breaks('10 years'),labels=date_format('%Y')))
```

**Comment by has2k1** [comment]
Yes, that is a bug. For a work around, enclose `x` and `xend` in `pd.Series`

i.e

```python
geom_segment(aes(x=pd.Series([datetime.datetime.strptime('1970-01-01','%Y-%m-%d')]), xend=pd.Series([datetime.datetime.strptime('1970-01-01','%Y-%m-%d')]), y=0, yend=12500))
```

Sorry to ask, but what are you doing to run into all these edge cases?

**Comment by gaorongchao** [comment]
I don't think this is an edage cases,when I use this in my work, something like financial，Time Series is the most common thing. And always need to drawn the average rate,income in the pic. So if other people know and want use plotnine I think they will encounter these case. now I think plotnine is not as famous as seaborn or matplotlib. I hope plotnine will be better than ggplot in R, come on !
