### ISSUE TITLE
Performing Calculation on Axis Coordinate

### ISSUE THREAD

**Issue by nanobe-ai** [has2k1/plotnine#883]
`
p2 = (
    p9.ggplot(df, aes(x = "date")) +
    p9.geom_segment(aes(y = "low", yend = "high", xend = "date"), color = "black") +
    p9.geom_segment(aes(y = "open", yend = "open", xend = "date - 0.1"), color = "black") +
    p9.geom_segment(aes(y = "close", yend = "close", xend = "date + 0.1"), color = "black") +
    p9.labs(title = "OHLC Chart", x = "Date", y = "Price") +
    p9.theme_minimal()
)

p2.show()

`

When given a DataTimeArray as "date", and needing to compute an offset from the axis coordinate, i.e. "date - 0.1", the following error occurs:: 'DatetimeArray' and 'float'

Can you please assist with the proper formatting for xend in this case.

Thanks!

**Comment by TerryGamon** [comment]
Always difficult without sample data, but I suppose that is what you are looking for?

import plotnine as p9
import pandas as pd

# Sample DataFrame with multiple dates and OHLC values
data = {
    'date': pd.to_datetime([
        '2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04', '2023-01-05',
        '2023-01-06', '2023-01-07', '2023-01-08', '2023-01-09', '2023-01-10'
    ]),
    'open':  [106, 102, 107, 104, 106, 100, 107, 105, 104, 103],
    'high':  [110, 112, 113, 114, 115, 118, 116, 117, 116, 114],
    'low':    [95, 97,   96,  98,  99,  96, 101, 99, 98, 96],
    'close': [100, 110, 104, 112, 114,  96, 113, 111, 110, 107]
}
df = pd.DataFrame(data)

df['date_num'] = df['date'].map(pd.Timestamp.toordinal)
df['datum'] = df['date'].dt.strftime('%m-%d')

xbreaks = df['date_num'].to_list()
xdate = df['datum'].to_list()

# Plot
p = (
    p9.ggplot(df, p9.aes(x="date_num")) +
    p9.geom_segment(p9.aes(y="low", yend="high", xend="date_num"), color="black") +
    p9.geom_segment(p9.aes(y="open", yend="open", x="date_num", xend="date_num - 0.2"), color="black") +
    p9.geom_segment(p9.aes(y="close", yend="close", xend="date_num + 0.2"), color="black") +
    p9.scale_x_continuous(
         breaks=xbreaks,
         labels = xdate
    ) +
    p9.labs(x='',y='')+
    p9.theme_bw() 
)

p

![image](https://github.com/user-attachments/assets/707d22dc-e190-4420-856f-6fa75eca684d)

**Comment by nanobe-ai** [comment]
Absolutely perfect.  Thank you very much for your time and effort.
