### ISSUE TITLE
custom linetype fails in`geom_hline

### ISSUE THREAD

**Issue by ilia-kats** [has2k1/plotnine#886]
Consider this example:
```
ggplot(data.mtcars, aes("mpg", "cyl")) + geom_hline(yintercept=0, linetype=(0, 5, 10))
```

This throws a `TypeError: object of type 'int' has no len()`. On the other hand,

```
ggplot(data.mtcars, aes("mpg", "cyl")) + geom_line(linetype=(0,(5, 10)))
```

works fine. This is on plotnine 0.14.0.

**Comment by has2k1** [comment]
You are missing some parenthesis in the first snippet, ~`linetype=(0, 5, 10)`~, `linetype=(0, (5, 10))`.
