### ISSUE TITLE
how use pandas multiindex dataframe to plot 

### ISSUE THREAD

**Issue by gaorongchao** [has2k1/plotnine#90]
```python
from plotnine import * 
from plotnine.data import *
import datetime
df = pd.pivot_table(diamonds,index=['cut','clarity'],columns=['color'],values=['price'])
```

how to draw picture with the df.

**Comment by has2k1** [comment]
Multi-index dataframe are not tidy data. The ggplot2 way is all about plotting [tidy data](http://vita.had.co.nz/papers/tidy-data.pdf).

**Comment by gaorongchao** [comment]
Is There anyway transform Multi-index dataframe to tidy data?

**Comment by has2k1** [comment]
You have to look into collapsing/resetting the index and may be even some other operations.
