### ISSUE TITLE
Figure cropped in external window from spyder

### ISSUE THREAD

**Issue by egayer** [has2k1/plotnine#91]
Hi, 
When using plotnine from spyder with an "automatic" backend for graphics, legends are cropped not only in the pop up window but also when saving figures. I tried changing figure_size with no effect.

![test](https://user-images.githubusercontent.com/14859142/33222642-0de73274-d159-11e7-9811-848955f7b46a.png)

thanks for your help and for plotnine

PS: any plan on making a raster geom ? (geo_raster)

**Comment by has2k1** [comment]
This is due to a limitation in Matplotlib's current layout system. The work around is to manually make room for the legend. e.g.

```python
theme(subplots_adjust={'right': 0.85})
```

No plans for `geom_raster`. Is `geom_tile` not sufficient? Are you looking for something that only [imshow](http://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.imshow.html#matplotlib.axes.Axes.imshow) can do?

**Comment by egayer** [comment]
Thanks for the workaround,

however, is subplots_adjust only working on plotnine 0.3.0 ? because conda-forge only allows me to install version 0.2.1, and running your line I get this :

> u'No such theme able element subplots_adjust'

I am super new in ggplot world, and extra super new in plotnine. I did not try geom_tile because I understand it needs X,Y and Z, while by raster I meant a 2D array of Z. As you mentioned I was talking of geom_raster as the equivalent of imshow.

**Comment by has2k1** [comment]
You can find v0.3.0 on conda-forge.

`geom_tile` does not need `z`, you can map to the `fill` aesthetic, but even that is optional. `geom_raster` would for all intents be similar to `geom_tile` except for the ability to do interpolation on the fill colors.

**Comment by egayer** [comment]
Hi Hassan, 

answering this way to not bother the online discussion with my stupid questions
> You can find v0.3.0 on conda-forge.
> 
You are right it is on conda-forge,but unfortunately conda does not allow me to install it. I am on py2.7 and here is what I get from conda-forge when searching for plot nine :

conda search -c conda-forge plotnine
Fetching package metadata ...........
plotnine                     0.3.0                      py_0  conda-forge
                             0.2.0                    py36_0  conda-forge
                             0.2.0                    py35_0  conda-forge
                             0.2.0                    py27_0  conda-forge
                             0.2.1                    py36_0  conda-forge
                             0.2.1                    py35_0  conda-forge
                          *  0.2.1                    py27_0  conda-forge

version 0.3.0 does have the same flag as the others. When trying to force install version 0.3.0, or trying an update, nothing happens (before to install 0.2.1 which the one with the star)


> geom_tile does not need z, you can map to the fill aesthetic, but even that is optional. geom_raster would for all intents be similar to geom_tile except for the ability to do interpolation on the fill colors.
> 
Sorry I am confused, what do you mean by geom_tile does not need z ? let’s say I have a 2D numpy array named A.
plt.imshow(A) would give the image of the matrix A. How can I do this with geom_tile ? (I get the fact that geom_tile won’t do any interpolation).

thanks again
Eric

**Comment by has2k1** [comment]
1. You need to update conda >=4.3.

2. Put the two columns/rows in separate columns of a dataframe or even use `qplot`.

```python
A = np.array([[1,2,3], [1,2,3]])
df = pd.DataFrame({'col1': A[0, :], 'col2': A[1, :]})
ggplot(df, aes('col1', 'col2')) + geom_tile()

# OR
qplot(x=A[0, :], y=A[1, :], geom='tile') + labs(x='col1', y='col2')
```

**Comment by egayer** [comment]
many thanks !
