### ISSUE TITLE
plotnine: How to plot multiple variables on X-Axis?

### ISSUE THREAD

**Issue by jrbrearley** [has2k1/plotnine#98]
When plotting the diamonds.csv data, I recalled that the price of a diamond is really dependent on 4 variables, the carat size, clarity, cut and color. Using your previous suggestions on plydata.summarize, I created a modified X-Axis composite variable based on carat size & clarity.

I tried specifying a list of column names for the graph aes, but didnt get anywhere.

To create the composite variable, first I pandas.cut to map the various sizes into 4 bins, then pandas.assign to create a new column.
 `carat_sizes = pandas.cut(diamonds['carat'], [0, 1, 2, 3, 100], labels=["0-1", "1-2", "2-3", "3+"])`
`df2 = diamonds.assign(size = carat_sizes)`

Next step was to merge the clarity column with the newly added carat_size column. I didnt find any suitable functions to do this, so I coded the following:
`combo = []`
`for i in range(len(df2.values)):`
`   c = df2.loc[i,'clarity']`
`   s = df2.loc[i,'size']`
`   cs = c+" "+s`
`   # print("i:", i, "c:", c, "s:", s, "cs:", cs)`
`   combo.append(cs)`
`df3 = df2.assign(clarity_size = combo)`

Anyway, by plotting the 'clarity_size' combo index on the X-Axis, I was able to get the following graph:
![plotnine_plydata](https://user-images.githubusercontent.com/32575796/33730281-7d996512-db4d-11e7-88ca-bccfdf3966af.png)

Using the geom_text(angle=90), I was able to add labels rotated vertically. However the default text on the X-axis is still horizontal and cut off.

So my questions are:
1) Is there a more graceful way to plot multiple variables on the X-axis? Creating a composite single variable seems to go against the grain of the tidy data principles.
2) How to get the default text on the X-Axis rotated vertically? Playing with plotnine.scales.scale_x_continuous(angle=90) & plotnine.scales.scale_x_continuous(labels='') didn't work.

Here is the full script: 
[plotnine_plydata.zip](https://github.com/has2k1/plotnine/files/1540108/plotnine_plydata.zip)

**Comment by has2k1** [comment]
> 1. Is there a more graceful way to plot multiple variables on the X-axis? Creating a composite single variable seems to go against the grain of the tidy data principles.

You can create a nice plot, if you are comfortable manipulating data and doing good layering. The simpler solution is to use facetting. Add a cut variable to the dataframe and facet by it.

> How to get the default text on the X-Axis rotated vertically? ...

`+ theme(axis_text_x=element_text(rotation=90))`
