### ISSUE TITLE
facet_grid & facet_wrap documentation examples

### ISSUE THREAD

**Issue by jrbrearley** [has2k1/plotnine#99]
I found some interesting documentation examples for ggplot2 facet_grid & facet_wrap using restaurant tips data set at http://www.cookbook-r.com/Graphs/Facets_(ggplot2)/

I created the following facet_grid & facet_wrap examples using diamonds.csv. WBN if you could add these to the docs at https://plotnine.readthedocs.io/en/stable/generated/plotnine.facets.facet_grid.html#plotnine.facets.facet_grid

![plotnine_facet1](https://user-images.githubusercontent.com/32575796/33949734-7e198dc8-dff8-11e7-9086-5a86dddbedee.png)

![plotnine_facet2](https://user-images.githubusercontent.com/32575796/33949765-952a4caa-dff8-11e7-83f0-06b6df00879e.png)

![plotnine_facet3](https://user-images.githubusercontent.com/32575796/33949811-b1865b14-dff8-11e7-9a28-403348507f76.png)

Here is the script: 
[plotnine_facets.zip](https://github.com/has2k1/plotnine/files/1556241/plotnine_facets.zip)

Minor issue: I noticed that all these graphs show black dots, not colored dots in the legends. Am I missing an option for the legends? Or is this a bug?

**Comment by has2k1** [comment]
Thank you for the offer, but it does not meet the [criteria](https://github.com/has2k1/plotnine#contributing) (subjective) that I am looking for.

> Minor issue: ...

I do not think there is a bug. You must using a non-fillable shape without mapping to the colour. It would be more helpful if you post the short easily reproducible code samples, dealing with archives does not scale.
